### ISSUE TITLE
Garmin Communicator: create/send training

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#100]
**Reported by laufhannes on 16 Aug 41532422 14:13 UTC**
Fr viele ist der einzige Grund, das Garmin Training Center zu nutzen, die Programmierung der Trainings.

----

Siehe http://developer.garmin.com/web/communicator-api/documentation/symbols/Garmin.DeviceControl.html#writeWorkoutsToFitnessDevice

und https://forums.garmin.com/archive/index.php/t-10579.html - von dort beispielhaftes XML.

Siehe http://www8.garmin.com/xmlschemas/TrainingCenterDatabasev2.xsd fr die genauen Vorgaben (Suche nach "Workout_t").
```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<TrainingCenterDatabase xmlns="http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2 http://www.garmin.com/xmlschemas/TrainingCenterDatabasev2.xsd">
 <Workouts>
  <Workout Sport="Running">
   <Name>Testname</Name>
   <Step xsi:type="Step_t">
    <StepId>1</StepId>
    <Duration xsi:type="Time_t">
     <Seconds>300</Seconds>
    </Duration>
    <Intensity>Active</Intensity>
    <Target xsi:type="None_t" />
   </Step>
   <ScheduledOn>2010-07-31</ScheduledOn>
   <Notes>Notes ...</Notes>
  </Workout>
 </Workouts>
</TrainingCenterDatabase>
```

Sport, Name und Step sind Pflicht.

Sport-Typen: "Running", "Biking", "Other"
Name: 1 bis 15 Zeichen
!ScheduledOn: xsd:date
Notes: xsd:string
Creator, Extension weglassen?

!StepId: 1 bis 20
Intensity: Active / Resting

Duration:
 * Time_t(Seconds)
 * Distance_t(Meters)
 * HeartRateAbove_t(!HeartRate)
 * HeartRateBelow_t(!HeartRate)
 * CaloriesBurned_t(Calories)
 * UserInitiated_t()

Target:
 * Speed_t(!SpeedZone)
 * HeartRate_t(!HeartRateZone)
 * None_t()

!SpeedZone:
 * Typ: CustomSpeedZone_t

```
<...>
   <ViewAs> SpeedType_t </ViewAs>
   <LowInMetersPerSecond> SpeedInMetersPerSecond_t </LowInMetersPerSecond>
   <HighInMetersPerSecond> SpeedInMetersPerSecond_t </HighInMetersPerSecond>
</...>
```

SpeedType_t: Pace / Speed
SpeedInMetersPerSecond_t: einfacher Wert (xsd:double)

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/100

**Comment by mipapo** [comment]
Implementation not possible.

**Comment by laufhannes** [comment]
Creation of tcx/fit files would be possible.
