### ISSUE TITLE
PHP-Exceptions verwenden

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1002]
**Reported by laufhannes on 17 Nov 44077915 11:02 UTC**
Vernnftiges Error-Handling, damit die entschiedenen Fehlermeldungen dem User direkt angezeigt werden. Derzeit landen zu viele "wichtige" Fehlermeldungen in der Error-Toolbar, die die meisten User bersehen.

Daher: Exceptions verwenden -> diese im Frontend anzeigen
Debug-Infos: wie gehabt ber die Error-Toolbar bzw. Log-Dateien

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1716

**Comment by laufhannes** [comment]
This is done step by step. A remark is placed into #1695.
