### ISSUE TITLE
Refactor Diagramme (JS-Part)

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1003]
**Reported by laufhannes on 27 Nov 44077927 21:10 UTC**
Fr alle Diagramme:
 - in Toolbar: Legende an/aus
 - in Legende: einzelne Datenreihen an/aus

Hover-Effekte/-Daten in eigene Library

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1717

**Comment by laufhannes** [comment]
JS parts already fixed.

A complete refactoring, e.g. using d3.js, will be done later.
