### ISSUE TITLE
Multi-Importer: set 'creator'

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1010]
**Reported by laufhannes on 17 Oct 44086025 10:13 UTC**
Die Felder 'creator' und 'creator_details' bleiben derzeit leider leer. Wre gut, wenn die beim Multi-Import gefllt werden. Dann knnte man in der Datenbank nach fehlerhaftem Import (wie gerade bei einem user) bequem alle Trainings dieser einen Datei löschen.

**Comment by laufhannes** [comment]
See related #911. `creator` / `creator_details` should be transformed in some `device` or similar. The file name or further details of the upload are not relevant.
