### ISSUE TITLE
Multi-Importer: identify duplicate activities

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1011]
**Reported by laufhannes on 25 Jun 44086052 23:56 UTC**
"Irgendwie" doppelte Trainings erkennen, zum Beispiel durch Vergleich von Zeitstempel & Dauer. Diese sollen in der Auswahlliste dann zwar auch aufgefhrt sein, aber standardmig nicht ausgewhlt sein.

Dadurch verhindert man einen ungewollten doppelten Import und kann eventuell eine sehr groe Datei "nach und nach" importieren, wenn nach einer bestimmten Anzahl von Trainings der Vorgang abgebrochen wird. (Das wre evtl. eine Idee fr ein weiteres Ticket: Import auf max. 200 Trainings oder so beschrnken)

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1725

**Comment by laufhannes** [comment]
Duplicate of #1168, fixed since 523fa37 in v2.4.
