### ISSUE TITLE
Calculations: track changes of values

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1027]
**Reported by laufhannes on 5 Mar 44160344 20:49 UTC**
Idee:
Im Rechenspiele-Panel anzeigen, wie sich die Werte gendert haben. (Ob nun zum Vortag, zur Vorwoche oder wie auch immer ...)

Eventuell unabhngig vom Plugin die ATL/CTL/GA/VDOT-Daten wochenweise als eigene Tabelle mitspeichern. Dadurch mssten z.B. das Form-Diagramm und hnliches nicht immer alle Daten neu berechnen. Allerdings wrden viele Daten in die Datenbank wandern.

Alternativ:
Nur den letzten Wert (und den aktuellen) in den Plugin-Daten speichern. Das msste dann jeweils aktualisiert werden, wenn die Daten nicht mehr mit den aktuellen bereinstimmen.

--
Michael: Vorschlag, welche von beiden Varianten?

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1745

**Comment by laufhannes** [comment]
@mipapo: I think we discussed this once. It's probably a "wontfix", right?

**Comment by mipapo** [comment]
> @mipapo: I think we discussed this once. It's probably a "wontfix", right?
Yep - "wontfix"
