### ISSUE TITLE
Weather: reload when changing date

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1029]
Wenn ein Nutzer Daten manuell eintrgt und das Formular aufruft sind die aktuellen Wetterdaten eingetragen. 
Wenn er dann das Datum ndert wird das Wetter nicht entfernt. 
Zu beachten ist, dass die Wetterdaten nur beim ersten Anlegen einer manuellen Trainingseinheit entfernt werden darf.

(via Forum: http://forum.runalyze.de/viewtopic.php?f=20&t=114)

**Comment by laufhannes** [comment]
Just a note: historical weather data is not available anymore. Openweathermap.org requires a paid account for historical data.

**Comment by mipapo** [comment]
Needs an ajax resource to request the weather. 
Request needs to contain Date + Time + Timezone (from activity or user account settings) + Startpoint
