### ISSUE TITLE
Übersetzung für JavaScript

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1039]
**Reported by laufhannes on 24 Oct 44190192 03:28 UTC**
Siehe auch #1756: JS fr Build komprimieren

Zustzlich sollte es dann noch eine js.locale.php oder so geben, die die bersetzungen der bentigten Strings liefert.

Frage dafr: Inwiefern sind die notwendig? Knnen nicht z.B. die !Monate/Wochentage beim Datepicker immer auf englisch ausgeliefert werden?

 - /lib/jquery.datepicker.js (defaults.locale: !Monate/Wochentage)
 - /lib/fineuploader-3.5.0.min.js (messages)
 - /lib/runalyze.lib.js
   - setupAjax(): Fehlermeldungen
   - initFormulars(): Fehlermeldung
   - loadOverlay(): Fehlermeldung
   - $.loadDiv(): Fehlermeldung
 - /lib/runalyze.lib.gmap.js
   - init(): Fehlermeldung
 - /lib/runalyze.lib.plot.js
   - save(): Fehlermeldung

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1758

**Comment by laufhannes** [comment]
Week and month names are most important and they are already translated.
