### ISSUE TITLE
Sportart ändern: VDOT bleibt bestehen

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1041]
**Reported by laufhannes on 20 Jun 44201062 02:32 UTC**
Trainings als Laufen eintragen, speichern
-> auf Radfahren ndern, speichern
-> VDOT bleibt bestehen, Form berechnet sich nicht neu

Problem ist, dass im !TrainingObject nach dem Update nur den VDOT ndert, wenn das Training auf "Laufen" steht. Es wird aber nicht erkannt, wenn es von Laufen auf eine andere Sportart gestellt wird.

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1760

**Comment by laufhannes** [comment]
Fixed in 95b031b2420c60abc1452799bc7fc8d9b555ca1d.
