### ISSUE TITLE
Tag-Function

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1048]
**Reported by laufhannes on 23 Mar 44231088 00:45 UTC**
Haken hnlich wie "bahn" und "abc"

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1768

**Comment by mipapo** [comment]
+1 durch die Umfrage 2015 
Meiner Meinung nach sollten wir hier achten wie wir bahn, abc und Laufbandtraining besser integrieren können. Nutzer werden nach und nach mit ähnlichen Wünschen kommen und dies nicht nur beim Laufen, sondern auch bei anderen Sportarten.
Es sollte sich Gedanken darüber gemacht werden eine Taggingfunktion für Aktivitäten einzuführen, die dann auch eine flexible Auswertung ermöglicht.

**Comment by laufhannes** [comment]
+1 for tags

**Comment by mipapo** [comment]
````
--
-- Tabellenstruktur für Tabelle `runalyze_tag`
--

CREATE TABLE IF NOT EXISTS `runalyze_tag` (
`id` int(11) NOT NULL,
  `tag` varchar(50) NOT NULL,
  `accountid` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Tabellenstruktur für Tabelle `runalyze_tag_activity`
--

CREATE TABLE IF NOT EXISTS `runalyze_tag_activity` (
`activityid` int(11) NOT NULL,
  `tagid` int(11) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Indizes für die Tabelle `runalyze_tag`
--
ALTER TABLE `runalyze_tag`
 ADD PRIMARY KEY (`id`), ADD KEY `accountid` (`accountid`);
````

Maybe tag-groups for running partners etc?

**Comment by laufhannes** [comment]
I guess it's easier to keep tags as simple as possible so far, i.e. no groups and only running drills ('lauf abc') will be converted.

**Comment by laufhannes** [comment]
- `runalyze_tag_activity.tagid` should not have a default value
 - a unique key for `(activityid, tagid)` could be useful?
 - an index for `tagid` could be useful?

**Comment by mipapo** [comment]
@laufhannes My SQL statement was just a draft and was not ready for production  ;)
Of course your mentioned points have to be considered

**Comment by mipapo** [comment]
@laufhannes Please have a look at the updated table structure

**Comment by laufhannes** [comment]
Is that an export from phpMyAdmin? The `CONSTRAINT` definitions seem odd to me, I guess you mean just a normal `KEY`?

**Comment by mipapo** [comment]
@laufhannes There is no difference. But I updated the table structure with the original mysql "show create table" output

**Comment by laufhannes** [comment]
Is there a difference for `tagActivity (activityid, tagid)` if it is a unique key or the primary key?

And still: `runalyze_tag_activity.tagid` must not have a default value (same for `runalyze_tag_activity.activityid`). I'm not even sure if something like `DEFAULT '0'` is allowed if we add foreign keys. (I guess it's good to use them for all upcoming tables)

**Comment by mipapo** [comment]
- Currently just have to check the database export/import with the tag function

Need help for the chosen field during adding an activity. The field is just 1px wide - Don't know why
