### ISSUE TITLE
kein editieren von strecken über 100 km?

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1058]
**Reported by moritzkufferath@gmx.de on 26 Jan 44281346 13:17 UTC**
Hallo runalyze-Team,

teste gerade euer tool. User: Moritz79. Bis jetzt alles gut, aber ich hab einen 100 km lauf eingetragen und wollte danach nachtrglich noch etwas nachtragen/ndern. Allerdings komme ich nicht mehr in den edit modus. Immer Fehler-Meldung. Bei den anderen kurzen Trainingslufen ist das editieren kein Problem. 

Gru,

Moritz

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1793

**Comment by grzeg1** [comment]
Unconfirmed.
