### ISSUE TITLE
Several improvements (code included)

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1063]
**Reported by grzeg1 on 3 Jun 44330102 12:39 UTC**
First of all I want to say: good work! I can't wait for full translation to english (especially the parts regarding vdot and prognosis descriptions).

I added some improvements to my local runalyze installation and would like to share them (diff to v764 included):

- mini bar charts for pulse and pace zones
- pulse zones for workout displayed as karvonen percentage plus name of the zone
- pace zones displayed as low-high value
- times of best segments of the workout:  1,5,21.1,42km and 12min(cooper - distance)
- GpsData getBestSegments funcion - in the future the values could be saved to database for reporting
- split km pace chart - bars height adjusted, average fixed, improved readability
- form chart includes TSB and TRIMP values and extends to the future
- some corrections in average pace functions - to get average pace you divide total time by total distance, you can't just get individual paces for parts of the distance and average them (when the parts of the distance don't have even times and distances)
- some methods for Plot object

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1802

**Comment by grzeg1** [comment]
Most changes were ported to 2.0. If there is anything else I'll make a new ticket.
