### ISSUE TITLE
Km Differenz zwischen Polar RC3 GPS und Runalyze

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1065]
**Reported by Kristian-Goossen@gmx.de on 28 Feb 44343138 07:05 UTC**
Guten Morgen,

ich habe folgendes Problem:

Nach meinem Lauf zeigt meine Uhr (Polar RC3 GPS) bespielsweise 15 km an. Die Uhr syncronisiere ich mit dem PC und erstelle eine hrm und gpx Datei. Diese Datei importiere ich bei Runalyze (Onlineversion). Nun wird nicht mehr 15 km sondern nur noch etwa 14,3 km angezeigt. Woran kann diese Differenz liegen?

Vielen Dank fr eure Hilfe

Mit freundlichen Gren
Kristian Gooen

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1805

**Comment by grzeg1** [comment]
Probably related to #1189. If there's still problem somebody will report it again.
