### ISSUE TITLE
Die Fenster sind leider komplett durchsichtig

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1066]
**Reported by tesche-vagt@gmx.net on 3 Feb 44349639 22:32 UTC**
Hallo,
ich bin total begeistert von dem Programm Runalyze. Vielen Dank dafr!!! Erst habe ich es online genutzt, aber um traffic von Deinem Server zu nehmen, habe ich jetzt einen kostenfreien Webspace genommen und das Programm dort installiert. Es hat alles super geklappt. Nur leider sind die Fenster durchsichtig und ich bekomme die Transparenz nicht abgeschaltet. Ich habe die FAQ schon durch und auch ReWriteBase in /lib/min entsprechend angepasst. leider ohne Ergebnis. Woran kann es noch liegen. Anbei einige Screenshots, damit Du weit was ich meine!
Danke im Voraus fr die Hilfe.
Alex

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1811

**Comment by grzeg1** [comment]
minifier not used any more
