### ISSUE TITLE
Mehrere Trainings "gruppieren"

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1068]
**Reported by laufhannes on 15 Jun 44425636 21:42 UTC**
Beispiele:
 * Triathlon = Schwimmen + Radfahren + Laufen
 * Wettkampf = Warmlaufen + Rennen + Auslaufen
 * Koppeltraining = Radfahren + Laufen
 * Gemischtes Training = Hinlaufen + Krafttraining + Spinning + Zurcklaufen

Problem:
Jedes Training hat eine eindeutige ID. Wie soll bei solchen Trainings verfahren werden? Alle bleiben einzelne Trainings, die lediglich fr die Kalenderansicht und Trainingsansicht zusammengefhrt werden? Oder ein ganz neues Konzept?

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1821

**Comment by laufhannes** [comment]
Duplicate of #1398.
