### ISSUE TITLE
SectionView: konfigurierbar machen

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1070]
**Reported by laufhannes on 22 Feb 44431207 19:26 UTC**
 - Sichtbarkeit der einzelnen Abschnitte (sichtbar/eingeklappt/unsichtbar)
 - Reihenfolge der einzelnen Abschnitte

Was ist mit dem kombinierten Diagramm fr Pace/Herzfrequenz?
 - Neue Section anlegen, default unsichtbar

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1823

**Comment by laufhannes** [comment]
Duplicate of #1548.
