### ISSUE TITLE
TSB in percent

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1074]
**Reported by laufhannes on 31 Dec 44493593 11:14 UTC**
"ATL/CTL habe ich dann dementsprechend als Zahlenwerte genommen, TSB als Prozentwert (100*(CTL-ATL)/CTL), da der CTL ja theoretisch immer weiter ansteigen sollte und ein TSB von z.B. 10 prozentuell immer weniger ausmacht."

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1827

**Comment by laufhannes** [comment]
I think the idea of displaying tsb in percent is quite interesting if the user wants it to.

My suggestion is to scale it as `TSB / max(ATL, CTL)` thus it's '+100%' for ATL = 0 and '-100%' for CTL = 0. Of course this will use current ATL / CTL, not maximal values.
