### ISSUE TITLE
Additions to Runalyze

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1080]
**Reported by grzeg1 on 13 Aug 44573995 09:22 UTC**
Dear all,
I made some additions/changes to Runalyze (thank you guys for developing such a great app).
I'm putting my changes on GitHub so you can play with new features and take the ones you like.
Some of the code will be just a hack good enough for me to play with and needing more work
before integrating. Nevertheless you can see what the feature is worth - like let's say map cursor following chart I missed so much.

The project URL is:
https://github.com/grzeg1/runalyze-test

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1833

**Comment by grzeg1** [comment]
Most changes were ported to 2.0. If there is anything else I'll make a new ticket.
