### ISSUE TITLE
Flot: use downsample-plugin

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1085]
**Reported by laufhannes on 18 Jun 44607292 05:43 UTC**
With button in config toolbar to dynamically vary the downsample-rate, e.g. in "pixel per point" (from 1 to 10).

See: http://flot.base.is/

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1838

**Comment by laufhannes** [comment]
Flot will be replaced by d3js.
