### ISSUE TITLE
Swimming: enhanced activity data

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1103]
**Current status**: Swimming has no special values. Only distance/time are saved.

**Wished**: Complete analysis of swimming data. This includes:
 - mode (indoor / outdoor)
 - pool length
 - laps (distance, time, swim style)

**Testdata**:
 - http://trac.runalyze.de/cgi-bin/trac.fcgi/attachment/ticket/595/schwimmen.tar.bz2
 - https://dl.dropboxusercontent.com/u/2507983/B70BC0501D001F00-2014-08-27T10_51_53-0.sml

**Related**:
 - #672 (pool length as new column)
 - #595 (tcx-file with swim data)

**Comment by mipapo** [comment]
http://steelcityendurance.com/swimming/what-can-swolf-tell-us-interpreting-swim-data-from-your-gps-watch/

**Comment by laufhannes** [comment]
Mode could be realized as training type or whether a pool length is specified or not. Strokes and stroketype are currently implemented in our `feature/swim`-branch.

**Comment by mipapo** [comment]
![auswahl_032](https://cloud.githubusercontent.com/assets/2135076/8496257/0562864a-2174-11e5-968c-58a838955c26.png)
![auswahl_031](https://cloud.githubusercontent.com/assets/2135076/8496258/0566be7c-2174-11e5-859d-99f66c925cfa.png)
![auswahl_030](https://cloud.githubusercontent.com/assets/2135076/8496259/057545f0-2174-11e5-81b8-299bee543d5c.png)
![auswahl_029](https://cloud.githubusercontent.com/assets/2135076/8496260/057b2f92-2174-11e5-8b64-3c35859061b9.png)
