### ISSUE TITLE
Add service to tapiriik

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1114]
Tip by @grzeg1 from Issue #980

**Comment by grzeg1** [comment]
There are 2 things to do:
- create api on Runalyze side (OAuth authorization probably) that would allow adding training remotely
- create service on tapiriik side to use the api

**Comment by mipapo** [comment]
I have and API in my mind, although i would like to create it with an framework like symphony. (Would like to see runalyze with a framework in the background. First step would produce a lot of work, but afterwards it would be easier to add things like an API...

**Comment by mipapo** [comment]
added to #1648
