### ISSUE TITLE
Calendar: quick jump

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1137]
via Thomas: "ich vermisse eine Möglichkeit, schnell zu einem bestimmten Datum zu kommen. Die schnellste Möglichkeit ist, auf das Jahr zu klicken und dann über die Pfeiltasten Jahr für Jahr zu springen. Wollte vorhin auf 1989 springen um alte Wettkämpfe zu editieren und das dauert dann schon mal..."

**Comment by laufhannes** [comment]
Another request from a user: a quick link to 'Today'.

**Comment by mipapo** [comment]
https://github.com/FortAwesome/Font-Awesome/issues/3609 
Added a "+1" there. Haven't found a nice icon for "today" in font awesome..

**Comment by mipapo** [comment]
Quick jump to "today" handled in #1672

**Comment by mipapo** [comment]
@laufhannes When you click on the calendar icon and click e.g. on "January, 2016 you will get a month choice. In the headline you can click again on the "year" and can easily jump to historical years. 
Think it's no problem to handle it that way?

**Comment by laufhannes** [comment]
@mipapo Agree!
