### ISSUE TITLE
E-Mail Templates

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1150]
Für Registrierung, Passwort vergessen etc. Mails anstatt diese direkt im Code zu haben Templates verwenden.

**Comment by mipapo** [comment]
c7a761be94c618d84185a1bde9b8b74884700b32 (recoverPassword)
one left: Delete Account

**Comment by laufhannes** [comment]
Please, please, pleeeaaaaaaseeeee use a base template for all recurring stuff ;)

\+ phpStorm shows some issues (`itemscope` etc. not allowed, `style` on `<html>` not allowed, ... and what's that complete html block inside the table at [recoverPassword.html.twig#L70-L81](https://github.com/Runalyze/Runalyze/blob/c7a761be94c618d84185a1bde9b8b74884700b32/app/Resources/views/mail/account/recoverPassword.html.twig#L70-L81)?)

**Comment by mipapo** [comment]
> Please, please, pleeeaaaaaaseeeee use a base template for all recurring stuff ;)
It's planned - Will do this in another commit 

> + phpStorm shows some issues
Have to check the original template - I was irritated by that too

**Comment by mipapo** [comment]
fixed in d140112d1044e7c6203024e3535273c898ce3cda
