### ISSUE TITLE
Training Monotony calculation error

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1165]
It only takes into account training days TRIMPS. Should also take into account 0 TRIMP days.

**Comment by laufhannes** [comment]
You're right!

Currently not at home to fix it. The solution should be to add at https://github.com/Runalyze/Runalyze/blob/master/inc/core/Calculation/Monotony.php#L91 the following:
```php
$var += (count($this->TRIMP) - $this->Count) * $this->Avg * $this->Avg;
```

(And a unit test is required.)

**Comment by grzeg1** [comment]
Hmmm. I think we should start more like:
const COUNT = 7;

and in calculate:
$this->Avg = array_sum($this->TRIMP) / COUNT;
(and get rid of all other counts)

and when generating array:
$MonotonyQuery->setRange(time() - Monotony::COUNT*DAY_IN_S, time());

**Comment by laufhannes** [comment]
But then the period is fixed to one week? I could agree on making the $count-parameter mandatory for the Monotony class.

**Comment by grzeg1** [comment]
Everywhere I look a week is used.
Also if we use a different number of days we're probably going to also use different warning and critical thresholds.
So it's probably best to use the simplest version with everything const (use strictly fellrnr's method).
