### ISSUE TITLE
Better Maintenance Mode

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1167]
- [x] Configureable message for maintenance mode. (File! ->config.php or whatever)
- [ ] Offline site should work without database connection (When working on database) (Cached or I will think of an better caching in front (fcgi_cache or varnish)
- [x] Users should be logged out immediately (c4fa4c130202c3d8abfbf848170dbb8f29aaa8c7)

**Comment by mipapo** [comment]
Users should be logged out immediately

**Comment by mipapo** [comment]
#1620

**Comment by laufhannes** [comment]
@mipapo Any chances that the remaining todo can be fixed for v3.0?

**Comment by mipapo** [comment]
Caching is not yet possible due migration. We will think again about this later.

**Comment by mipapo** [comment]
Hint: Cache must be deleted after updating the config settings
