### ISSUE TITLE
Performance: use InnoDB tables or switch to PostgreSQL

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1170]
Currently Runalyze uses MyISAM table engine. Historically they were faster for almost-read-only scenarios (like web portal with thousands of visits but few updates daily).

Latest tests, Oracle's own included, show it's not the case any more. 

Moreover: MyISAM tables only support table locks, so every time a record is updated, whole table is locked. So they're very inefficient in multi-user scanarios.

Engine type can be changed with simple ALTER TABLE.

Disclaimer: as I generally work with PostgreSQL I may be wrong in some parts.

**Comment by laufhannes** [comment]
@mipapo and me already discussed it - without a final decision so far. I often read your first point, that MyISAM is better for reading. But if it's right that that's not the case anymore, we definitely should switch.

I'd love to have a runalyze-specific benchmark for this, but I guess that's a lot of work.

**Comment by grzeg1** [comment]
It may be best just to switch and observe server load and service responsiveness for a few days (a bit of tuning may be applied too). And it's always possible to switch back.
What's probably most interesting is not locking whole tables for database-intensive tasks (cleanup). You're right that building a specific benchmark will involve a lot of work.

**Comment by mipapo** [comment]
@grzeg1 @laufhannes I think moving to InnoDB is the right way. Switching to InnoDB will cause a relativ long downtime (will do it in the night).
PostgreSQL is great too, but currently no choice.

**Comment by mipapo** [comment]
@grzeg1 All tables except _training are now InnoDB on our onlineversion. The training table will I switch at 12pm (german time)

**Comment by grzeg1** [comment]
Is it so much better you've already closed the issue?

**Comment by laufhannes** [comment]
Mainly because Michael agreed and convinced me that we should go with InnoDB and so far it's definitely not worse.

I guess a verifiable result will only be possible with complete benchmarks but that needs to much work. Then one could compare the engine for each table. I think it could be possible that MyISAM is a little bit better for e.g. _account, _sport, _type, _plugin, _dataset, _clothes.

**Comment by mipapo** [comment]
Just another comment: Because of the database design in version 1.5 it's not possible to convert _training to InnoDB, because the maximum row size is too big. 
I'm not sure, but I hope it will work after the redesign.

**Comment by grzeg1** [comment]
This has to be something else. My 1.5 database converted perfectly. Counting column sizes does not give a value that would be bigger than described limit: http://dev.mysql.com/doc/refman/5.5/en/innodb-restrictions.html. 
Is it possible you have a different structure? Like varchar columns instead of text for arrays?

**Comment by laufhannes** [comment]
Problem is the following.
```
ALTER TABLE `runalyze_training` ENGINE=InnoDB;
ERROR 1118 (42000): Row size too large (> 8126). Changing some columns to TEXT or BLOB or using ROW_FORMAT=DYNAMIC or ROW_FORMAT=COMPRESSED may help. In current row format, BLOB prefix of 768 bytes is stored inline.
```

Maybe it does only occur if there are too large rows (and not the theoretical column size)? Another user reported the problem on Facebook as well. He was able to solve it with `ROW_FORMAT=DYNAMIC`.

**Comment by grzeg1** [comment]
OK it seems it uses 768 bytes for every blob (text) field. So the arrays get a lot of it. DYNAMIC format lets even the 768 bytes be pushed out so it should work.
Also innodb_log_file_size should be increased.
http://dev.mysql.com/doc/refman/5.6/en/innodb-parameters.html#sysvar_innodb_log_file_size
http://stackoverflow.com/questions/15585602/change-limit-for-mysql-row-size-too-large

**Comment by mipapo** [comment]
innodb_log_file_size is already set to 256MB. I will try some things locally.

Just for documentary reasons:
http://serverfault.com/questions/236630/do-innodb-or-myisam-tables-offer-better-insert-performance-in-mysql-5-1
http://stackoverflow.com/questions/18806377/setting-the-right-mysql-innodb-log-file-size

**Comment by grzeg1** [comment]
Verified locally as follows:
- inserted training with gps path, hr, elevation, cadence and power
- opened training view
- got 500 internal server error - row size too large - as Runalyze was trying to add gps_cache_object to DB
- altered row format to dynamic
- still error

After some digging:
- `show table status like 'runalyze_training'\G;`
- got `Row_format: Compact`
- `SHOW VARIABLES LIKE 'innodb_file%';`
- `SET GLOBAL innodb_file_format=barracuda; SET GLOBAL innodb_file_per_table=ON;`
- `alter table runalyze_training row_format=dynamic;`
- `show table status like 'runalyze_training'\G;`
- now got: `Row_format: Dynamic`
- **now no error when opening trainng view - correct setup for large BLOBs**
- put in my.cnf:
```
innodb_file_per_table   = 1
innodb_file_format      = Barracuda
```

**Comment by grzeg1** [comment]
Variables set in #1216. This allows to install Runalyze and work properly.
In fact every sysadmin can choose a different engine for install, e.g. TokuDB (this is something worth trying too). So I suggest we move this issue out of Milestone 2.0 to Speed Optimizations.

**Comment by laufhannes** [comment]
That will probably cause troubles again if one has no rights to use `SET GLOBAL ...` and thus break more updates than it fixes. Git-Users may be considered as hackers but there are (sadly) a lot of people installing a webserver for their first time just to use an own installation of Runalyze.

I needed to increase `max_allowed_packet` and `key_buffer_size` some time ago and hat to remove that setting from the repository due to these problems. Maybe it's better to collect these settings in ini files that users need to apply themselves whenever required.

**Comment by grzeg1** [comment]
Then I suggest we go back to MyISAM not to block release. Transactions and foreign keys are not required now. I can feel the need to apply transactions though as e.g. training data is now in 3 different tables.
Of course this has nothing to do with what engine is used for runalyze.de. There, Innodb should have great benefit as row-level locks will improve concurrency of updates (especially long time tasks)

**Comment by laufhannes** [comment]
@mipapo Do you agree with keeping MyISAM as "official" engine for Runalyze in the repository? I agree that performance is not a big problem for small installations and for low concurrency MyISAM is pretty good.

We could just add some `/inc/install/innodb.sql` (including the stated `SET GLOBAL` statements) that users can apply if they wish to.

**Comment by mipapo** [comment]
I think it's okay. I don't know anyone who uses a big installation.

**Comment by laufhannes** [comment]
I added the `innodb.sql` in 88c3bcfe9e522f96ac17ecaed860bd25486e83f4 and switched our structures back to MyISAM.

**Comment by grzeg1** [comment]
So I'm closing this for now. Nothing more to be done.
