### ISSUE TITLE
Defect activities with data size mismatches

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1172]
This may occur for existing activities:

    Fatal error: Uncaught exception 'RuntimeException' with message 'Data arrays must be of the same size. (3360 != 3348) (for elevations_corrected)' in /runalyze/inc/core/Model/Object.php:69

In my opinion it's good to guarantee equally sized arrays. A solution could be to add a tool for correcting "defect" activities:
 - find defect activities
 - multiple options to "solive" it

And: Find out which importer creates these mismatches.

**Comment by laufhannes** [comment]
It seems that this does only occur for 'elevations_corrected'.

**Comment by grzeg1** [comment]
There's a bug with elevation recalculation. I spotted it by extremely high vdot values calculated. As far as I can see there is now route which is different than training id, but cleanup calculator is mistaking training id for route id.
Question: what is route id and why does training have route id? Is it one-to-many relationship?

**Comment by laufhannes** [comment]
At the moment it's a 1 to 0..1 relation and so the route table could have activityid as primary key, but it was thought that in the future that users without gps device could insert one route and use it for multiple activities. I don't know how many people would use that and if it is our job to care for non-gps-runners.

Concerning the bug: It seems that you are right - even though the results looked good for me.
In https://github.com/Runalyze/Runalyze/blob/master/plugin/RunalyzePluginTool_DatenbankCleanup/JobLoop.php#L156-L157 it must be `$Data['routeid']` (and `routeid` must be fetched in the query). The unit test does not cover that.

**Comment by laufhannes** [comment]
Did not see your pull request ;)

**Comment by laufhannes** [comment]
Another bug for mismatching sizes:
GPX-Importer seems to ignore the first trackpoint and therefore HRM+GPX-Importer produces a heart rate array with one point more than lat/lng-points.

Reference: [Markus post on Google+](https://plus.google.com/u/0/104994890445843557698/posts/ZqPmPF47bZE)

**Comment by grzeg1** [comment]
Gpx+hrm seems to be the only importer that gets data from 2 files. I guess we can assume no other one will be doing it and close the issue?
