### ISSUE TITLE
Catch exceptions

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1174]
There are some exceptions that should be catched, especially for failing constructors, e.g. if no id is given.

Display plugin
```
Uncaught exception 'RuntimeException' with message 'Invalid id "" given to create a plugin.' in
\runalyze\inc\plugin\class.Plugin.php:124 Stack trace: #528
\runalyze\inc\plugin\class.PluginFactory.php(60): Plugin->__construct(NULL) #1
```

tbc

**Comment by mipapo** [comment]
Invalid activities
https://support.runalyze.com/scp/tickets.php?id=443

**Comment by laufhannes** [comment]
Closed as rather unspecific issue. A lot of work will be done when switching to symfony and controllers.
