### ISSUE TITLE
Compiling language files

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1175]
Code below. Not sure where to put it. Admin screen? Installer?

```php
<?php

$supportedLanguages=array();

require ('config_lang.php');

$LOCALE_DIR=__DIR__.'/inc/locale';

foreach ($supportedLanguages as $lang => $larr){
    $lang_dir=$LOCALE_DIR.'/'.$lang.'/LC_MESSAGES/';
    if (is_file($lang_dir.'runalyze.po')){
        echo $lang.' ';
        system ('msgfmt -v '.$lang_dir.'runalyze.po -o '.$lang_dir.'runalyze.mo');
    }
}

?>
```

**Comment by laufhannes** [comment]
I'd prefer the /build/ directory.

And: Is there any reason not to include the mo-files in the repository?

**Comment by grzeg1** [comment]
Only that these are binary files about 200K each that can be generated  in seconds.
I thought you did not include them because of it ;)

**Comment by laufhannes** [comment]
I did not realize that they are not there until yesterday.

Is the above system call the same for Windows/OS X/Linux? If we provide a final build script that calls all the single ones, that should be enough for git-user. I only have to remind myself to include these files in our final zip-archive. (At least the major releases should be served as ready-to-go archives.)

**Comment by grzeg1** [comment]
I'm afraid the whole locale thing will not work under Windows. Windows has different locale names. But hopefully just configuration file would suffice. May work under OS X though.
I've never used gettext in Windows either so don't know what tools are available.
However translating texts like 'chmod 644' I thought you were mainly focusing on Linux/Unix ;)

**Comment by grzeg1** [comment]
script integrated in #1211
