### ISSUE TITLE
[2.0alpha] Training at Temperature 0° => ?°

### ISSUE THREAD

**Issue by sportsaddict** [Runalyze/Runalyze#1179]
I just wondered why my yesterday's training has a questionmark displayed instead of 0°. It seems to me, that the temperature value is left to the default value NULL within runalyze_training. Setting the Temperature to any other values than 0 via the edit form works just fine, but resetting it then to 0 neither works. It is left at the previously value <>0. This behaviour is new since 2.0alpha.

**Comment by laufhannes** [comment]
Changing value from "NULL" to "0" is still not possible.

**Comment by grzeg1** [comment]
Fixed in pull request.

**Comment by laufhannes** [comment]
Your fix is only for the boxed value, not for the updater. I'll commit a complete fix. 
And I'll try to get rid of `Helper::`

**Comment by grzeg1** [comment]
Strange. In my local install everything else is working, so just needed to fix boxed value display.

**Comment by grzeg1** [comment]
Ok, now I can see. Update from null to 0 is not working.
