### ISSUE TITLE
Public view broken when having public trainings

### ISSUE THREAD

**Issue by sportsaddict** [Runalyze/Runalyze#1180]
When calling the public training link the following error occurs. It seems as it is ocurring only when trying to draw the green "+" in front of a public training. Sorry, my php skills are not sufficient to provide a solution...

Fatal error: Access to undeclared static property: Runalyze\View\Icon::$ADD_SMALL_GREEN in ...../Runalyze/inc/class.Dataset.php on line 381

**Comment by laufhannes** [comment]
Reminder: I should commit the fixes that I apply to our online test version ;)
