### ISSUE TITLE
route network filtered by sports type

### ISSUE THREAD

**Issue by sportsaddict** [Runalyze/Runalyze#1181]
Would be nice to filter the route network by sports thus having something like a personal heatmap for either biking or running (or whatever there is...).

Regards, Bjoern

Just to say it once more: Nice work that you are doing there :)

**Comment by sportsaddict** [comment]
Filtering the most recent routes/places was just a one line change but unfortunately the route network is using a completely different and imho static query.

Here is the diff for the routes/places view:

66a67
> 		$this->setSportsNavigation();

**Comment by laufhannes** [comment]
Seems there have been some problems with your link?
