### ISSUE TITLE
Support imperial units

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1182]
For american users

**Comment by laufhannes** [comment]
Theoretically this is prepared in https://github.com/Runalyze/Runalyze/blob/master/inc/core/Data/Weather/Temperature.php. After adding a new configuration value one has to look at the following:
 - display the correct unit for the input field
 - read the value as fahrenheit but save it in the database as celsius
 - display it as fahrenheit whereever needed

**Comment by grzeg1** [comment]
Distances need to be taken care of too.

**Comment by mipapo** [comment]
+weight

**Comment by laufhannes** [comment]
+1 via mail from Jeremy

**Comment by aoleinik22** [comment]
I would really appreciate this too. Although I love metric units, in the states there's no way to avoid talking in terms of min/mile. A marathon is 26 miles here not 42km. I am sure many users would really appreciate implementation of imperial units.

**Comment by laufhannes** [comment]
Missing features:
 - [ ] plots: x-axis labels at even miles
 - [ ] activity form: accept other units for input
 - [ ] activity form: correctly calculate pace in case of other unit

Missing 'nice-to-have's
 - [ ] laps window: accept other units for input
 - [ ] prognosis panel: accept other units for input in configuration & calculator window
 - [ ] races plugin: accept other units for input in configuration

**Comment by laufhannes** [comment]
Missing 'nice-to-have's should be moved into a new issue, so that this one is done and can be merged into master.
