### ISSUE TITLE
Compiled files (class maps, plugin maps, js) in repository

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1186]
There is a trouble with compiled files in the repository. Having them means only one person can work with these files or we get lots of unnecessary diffs. Also comitting requires building before which can be easily forgotten.
Mybe it's better to remove them from repository and require build for git users. They can be included in release zips.

**Comment by laufhannes** [comment]
I think git does a good job with merging so that there shouldn't be any problems with different people working at the same time at these files?

If we remove these files from our repository every git user has to download the YUI compressor (for *.js) and LESS (for *.css) himself. That may be easier with Composer but that's too much for v2.0 in my opinion.

And at least the class map will not be required anymore as soon as all classes are transformed to the new namespace system.

**Comment by grzeg1** [comment]
Whenever I build classmap it's in totally different order than the one in repository. So there is a diff for almost a whole file. Same thing with minified one-line js ;)
It's mainly for your convenience with pull requests - you will not be able to verify what changed in compiled files.

Git users need to be treated more like hackers - not scared of a dependency install. Anyway they need to configure and install mysql, apache etc. Believe me, the biggest challenge for me was installing mysql, creating  database and granting rights (I'm PostgreSQL user).
YUI is getting one file - did it yesterday in 2 minutes. Ok, 3 - had to copy it into different directory.
Less was more ;) of a problem. It took 15 minutes for the newest version. For distribution version it took 1 minute. :)

**Comment by grzeg1** [comment]
You're absolutely right with one thing though: it's not important enough to postpone 2.0 release.

**Comment by grzeg1** [comment]
I think I found a solution - Nightly builds. Keeping just the last one is enough.
People who want to try 'latest and greatest' ;) just get the nightly build.
People who want to use git need to install less.js, YUI, msgfmt. To hack they need it anyway.
No generated files in repo.
Build only needs to be updated when something was changed.

**Comment by grzeg1** [comment]
After latest changes to .js files, can we finally get rid of everything that is compiled/generated from the repo?

**Comment by mipapo** [comment]
This will be "fixed" when we merge the micro symfony branch

**Comment by mipapo** [comment]
@laufhannes Is everything done for this ticket?

**Comment by laufhannes** [comment]
Yes, but respective issues are closed as soon as the branch is merged.
