### ISSUE TITLE
Plugin 'Races': reduce number of queries

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1187]

**Comment by grzeg1** [comment]
With regards to #1193 performance gain may be negligible.... or not ;)

**Comment by grzeg1** [comment]
Single query would be a bit complicated for planner. Simplest probably something like:

```SELECT * FROM (SELECT id, distance, s, (select count(*) from runalyze_training rt1 where rt1.distance=rt.distance and (rt1.s<rt.s or (rt1.s=rt.s and rt1.time<rt.time)) and `accountid`=0 and typeid=5 ) num from runalyze_training rt WHERE `accountid`=0 and typeid=5 and distance in (1,5,10,21.1,42.2) ) AS tt WHERE num=0 ORDER BY distance;```

**Comment by laufhannes** [comment]
I more thought about just fetching all rows with `typeid=5`.

Your query seems like a one-query-solution to fetch all personal bests (with the possibility to fetch any column in contrast to [PersonalBest::lookupDistances](https://github.com/Runalyze/Runalyze/blob/master/inc/core/Activity/PersonalBest.php#L97-L101)) at once, right?

**Comment by grzeg1** [comment]
Yes, that's what it does. If there are identical times it takes the first PB, can be changed to show last.
Alternative would be to add LIMIT 1 to existing queries.

**Comment by laufhannes** [comment]
I added this query in a9104d55d0ee2496f6f0d18ff8188da7653c48a2 for completeness, but currently it's much slower than repeating simple queries.

Nevertheless, this ticket was for the 'Races' statistics not for prognosis window.
