### ISSUE TITLE
Performance: queries, indexes

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1193]
There are some general issues with current database stuff:

1) Almost every query gets data for a given account id. Then it's narrowed by time, sport etc. But indexes are just made on a single column.
e.g: we want last week of data for accountid=5, so either we use accountid index and filter all the records for last week or we take last week's records from all accounts and filter only accountid=5

```CREATE INDEX act_time ON runalyze_training (accountid, time);```

will let the planner find all the necessary records using only index search.

2) There are queries in which WHERE clauses are like

```WHERE YEAR(FROM_UNIXTIME(time))='2015'```

This forces the DB engine to get all records (maybe for a single accountid) and perform some calculations to filter them. The desired form would be:

```WHERE time BETWEEN UNIX_TIMESTAMP('2015-01-01') AND UNIX_TIMESTAMP('2015-01-01')```

This way DB engine can effectively use index on time column.

Unfortunately MySQL EXPLAIN is not as good as PostgreSQL's, but it's usable to some extent and can help with debugging.

**Comment by laufhannes** [comment]
Just tested an additional index `(accountid, time)` for `runalyze_user` with `mysqlslap` using the following queries:
```sql
SELECT * FROM `runalyze_user` WHERE `accountid`=0 ORDER BY `time` DESC LIMIT 1;
SELECT `weight`, `pulse_rest`, `time` FROM `runalyze_user` WHERE `accountid`=0 ORDER BY `time` DESC LIMIT 10;
SELECT `fat`, `water`, `muscles`, `time` FROM `runalyze_user` WHERE `accountid`=0 ORDER BY `time` DESC LIMIT 10;
SELECT * FROM `runalyze_user` WHERE `accountid`=0 ORDER BY `time` ASC;
```

For my single-user installation: (150 MB in total, ~250 rows in `runalyze_user`): 
`0.075s vs 0.048s` (with vs without)

For an older dump of our online version (12 GB in total, ~22.000 rows in `runalyze_user`): 
`0.058s vs 0.072s` (with vs without, MyISAM) 
`0.226s vs 0.101s` (with vs without, InnoDB)

All tests with `--iterations=200 --concurrency=20`. And of course only reads and no writes are not fair for MyISAM vs InnoDB and all clients requesting the same accountid is not realistic either. Still, a first impression.

**Comment by grzeg1** [comment]
In general database engine should be 'smart' when choosing execution plan, so in no way additional index should slow down the query. DB would just consider it suboptimal and use some other index.
Reading an index also has a cost. So sometimes if there is not much data and you fetch all the records (like last query) it's cheaper to read them all and then sort.
Using `explain extended select ...` you can check which index is used. Also running `ANALYZE TABLE` is needed to confirm that statistics were updated (especially when we have a new database or recreated table).
An example of a query with big speedup would be (off the top of my head - only checked with explain)
```
SELECT accountid, max(time) FROM runalyze_user GROUP BY accountid;
```
Anyway, for optimizations I thought more about `runalyze_training` table and the way queries (e.g shape plot) are done. The bigger the table, the more records for a given accountid, the better is to use additional index. But almost every time we get all or most of the records for a given accountid, DB is going to fall back to just accountid index. And every time we get all/most of the records for all users DB will just forget indexes and do a full table scan.

**Comment by grzeg1** [comment]
I just noticed one thing in what you wrote. There were lots of changes in MySQL between 5.1 and 5.5 especially regarding InnoDB. So you may want to upgrade ;)
