### ISSUE TITLE
New translation strings not being picked up from github by Weblate.

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1197]
I don't know how it's supposed to work either :( 
I mean when translations are picked up from github and when they're commited back.

**Comment by grzeg1** [comment]
Any progress on this?

**Comment by laufhannes** [comment]
I'm really not into weblate. @mipapo?

**Comment by mipapo** [comment]
I have manually update the base translation. In the moment there is no script for this, but i will create one.
In the moment translate.runalyze.de is down for maintenance of weblate. I'm trying to update the software. 
I will have a look into the singular/plural problem too.

**Comment by mipapo** [comment]
Dammit! Sometimes the dependencies with python django and weblate are terrible. Database backup went wrong so i have to setup a new weblate instance...

**Comment by grzeg1** [comment]
It's not working yet, is it?

**Comment by grzeg1** [comment]
We have a saying here:
There are 2 kinds of IT guys: those who are doing backups, and those who will do backups ;)

**Comment by mipapo** [comment]
Well i do a lot of backups ;) But the backup restore of the weblate files didn't worked. (Or wasn't running)
I will have a look in the evening into the problem. Currently at work and a bit under pressure because of moving in to a new apartment.

**Comment by grzeg1** [comment]
I read some of the Weblate docs and it seems you have to do the update from code manually.
Below are commands I used for one of the projects. I remember that it took me some time go get things right (so that nothing gets lost or overwritten). 
```
xgettext --from-code=utf-8 -o template.pot -n file1.php
xgettext --from-code=utf-8 -j -F -o template.pot -n other_files/*.php
xgettext --from-code=utf-8 -j -F -o template.pot -n more_files/*.php

cp locale/de_DE/LC_MESSAGES/translation.po /tmp/translation.po
msgmerge /tmp/translation.po template.pot > locale/de_DE/LC_MESSAGES/translation.po

echo >> /tmp/translation.po
cp locale/pl_PL/LC_MESSAGES/translation.po /tmp/translation.po
msgmerge /tmp/translation.po template.pot > locale/pl_PL/LC_MESSAGES/translation.po
```
Anyway it would be godd to manually check first few merges. Or does Weblate do the merging automatically?

**Comment by mipapo** [comment]
I know that this have to be done manually, but i will create a tiny script for that. 
I could deactive the weblate git push and check/do this manually.

**Comment by grzeg1** [comment]
There is also this thing with github and `Merge branch 'master' of https://github.com/Runalyze/Runalyze` commits weblate does (they're in my pull requests too). I have still to verify it but it seems that when you pull with `--rebase` option there will be no such entries in log. This is not on by default because it may be important if someone else is pulling directly from you - then they want to see that you merged with upstream.

**Comment by mipapo** [comment]
Bizarrely it worked with weblate. Problem was that i did it the last time manually to have the latest pot files in the git repo. So just a mistake. (And i had no time to redo the commit). I will test the new weblate instance before I go on.

**Comment by mipapo** [comment]
So - Weblate 2.1 had some bugs (which were fixed in the github repo but not in the package).
Finally i could add Runalyze again to weblate. 
It will pull now with the rebase option.
Anything else i will test. New base file or rather the check for new translation strings will come in the next days.

**Comment by grzeg1** [comment]
Main page is always in German - are other languages available?
Also are user accounts lost?

**Comment by mipapo** [comment]
Like i sad i had to make a new installation of weblate and did not a restore of the old database. Will be the last time. Since weblate is now in a "nice version" available i won't update it for a longer time (except there are secure bug fixs)
After the registration there should be the the possibility to change the interface language. Currently i don't know why weblate doesn't recognize the browser language. I will try to set the standard language to english.

**Comment by grzeg1** [comment]
As for languages: I don't know the details of your install but for gettext you have to install given locale to set it (i.e. it needs to be in `locale -a` output)

**Comment by mipapo** [comment]
Every possible locale is activated/installed ;)

**Comment by grzeg1** [comment]
Languages: sorry, it was me messing with browser accept-language ;)
Weblate: is it ready yet? I mean can I register again? I guess all the suggestions were lost...

**Comment by mipapo** [comment]
You can register again. Weblate has some ugly bugs i had to correct first.
Currently the connection between github and weblate is no possible. I will have a look in the next days at this problem, but can't promise that I have any time.

Suggestion are lost.

**Comment by grzeg1** [comment]
I updated the template but weblate does not update word list for translations. Can you please check and maybe manually update so translations for 2.0 can be finished?

**Comment by mipapo** [comment]
Had no time (and no internet at home). Will do it through the day

**Comment by mipapo** [comment]
@grzeg1 All language files are updated. 
In the moment i can update all po files against the default.pot automatically. 
I will setup a hook to update the git repo on weblate automatically. For the beginning the default.pot have to be updated manully. Will change it in the next time. 
Would be great @grzeg1 if you update file from time to time for the beginning

**Comment by grzeg1** [comment]
I will update. Now I just need to know how to trigger update both ways. I mean pull and push to github.

**Comment by mipapo** [comment]
I will give you the rights on translate.runalyze.de to work with github

**Comment by mipapo** [comment]
@grzeg1 
In the moment the plural strings are not picked up.
I think "_e:1,2" "_ne:1,2" hast to be added to the keywords. I tried it with PoEdit but they were not picked up. 
If i do it with xgettext they are found. But 
>    xgettext -o default.pot -p . --force-po --from-code=UTF-8 --keyword --keyword=__ --keyword=_n:1,2 -L PHP *.php
```
#: tpl.loginWindow.php:191
#, php-format
msgid "has logged <strong>%s</strong>."
msgid_plural "have logged <strong>%s</strong>."
msgstr[0] ""
msgstr[1] ""
```
    xgettext -o default.pot -p . --force-po --from-code=UTF-8 --keyword --keyword=__ --keyword=_e --keyword=_n:1,2 --keyword=_ne:1,2 $(find . -name "*.php")
So i think this would be the right way to create the default.pot? 
How has looked your command to create the pot file? :)

**Comment by grzeg1** [comment]
`xgettext -LPHP -F -k__ -k_e -k_n -o template.pot -f filelist --omit-header`
yours is better ;)

**Comment by mipapo** [comment]
@grzeg1 Okay ;) I will check my pot file against the current and try to update just the german po-file for a function test  :)

**Comment by grzeg1** [comment]
It's ok, I checked it.

**Comment by mipapo** [comment]
@grzeg1 When you already checked it you could update the default.pot. Afterwards i will start the script which updates all the po files

**Comment by grzeg1** [comment]
It's updated in pull request with some other stuff and waiting for @laufhannes to merge. A few updates to source strings are also included.

**Comment by grzeg1** [comment]
There is a new template present. I clicked "Pull" in Weblate ad it shows last commit id pulled as the latest from github. But new strings did not appear - translation is still 100%.

**Comment by mipapo** [comment]
@grzeg1 Just like i sad: There is currently no connection between pulling and my script. I updated them now.

**Comment by grzeg1** [comment]
Ok, there's pulling, pushing, updating source strings, updating po files from pot and updating po files from weblate. So I got confused about what was working and what was not ;)

**Comment by grzeg1** [comment]
All the translations I did yesterday in Weblate were lost :( There must be something wrong with update scripts.

**Comment by grzeg1** [comment]
@mipapo You don't have yesterday's file, do you?

**Comment by mipapo** [comment]
@grzeg1  I will update the script: Before the script merge the changes the local git repo will be pushed. This should work.

(and to your question in weblate: l-sleeve is in german "Langarmshirt" which means: a shirt with long  sleeves. Maybe the english translation is not correct)

**Comment by grzeg1** [comment]
@mipapo there are still a few source strings changed in  7791e1e140bff7ab86b428d6bb389f893c60c799 and not updated.

**Comment by mipapo** [comment]
@grzeg1 @laufhannes Updated source pot template and updated translatios in weblate

**Comment by grzeg1** [comment]
Thanks. Could you add a manual button to repository maintenance for updating source and for forcing a full commit with add until the automatic stuff is resolved? Now in Repository Maintenance there is:
```
# On branch master
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	modified:   inc/locale/bg/LC_MESSAGES/runalyze.po
#	modified:   inc/locale/da/LC_MESSAGES/runalyze.po
#	modified:   inc/locale/default.pot
#	modified:   inc/locale/es/LC_MESSAGES/runalyze.po
#	modified:   inc/locale/fr/LC_MESSAGES/runalyze.po
#	modified:   inc/locale/it/LC_MESSAGES/runalyze.po
#	modified:   inc/locale/li/LC_MESSAGES/runalyze.po
#	modified:   inc/locale/nl/LC_MESSAGES/runalyze.po
#	modified:   inc/locale/pt/LC_MESSAGES/runalyze.po
#	modified:   inc/locale/ru/LC_MESSAGES/runalyze.po
#	modified:   inc/locale/sl/LC_MESSAGES/runalyze.po
#	modified:   inc/locale/sr/LC_MESSAGES/runalyze.po
#	modified:   inc/locale/sv/LC_MESSAGES/runalyze.po
#	modified:   inc/locale/tr/LC_MESSAGES/runalyze.po
#	modified:   inc/locale/zh/LC_MESSAGES/runalyze.po
#
no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by mipapo** [comment]
@grzeg1 Currently i think it's better if i do it manually. By the end of the next week i have internet at home again and can do more for Runalyze.

**Comment by grzeg1** [comment]
This can be finished in 2.0 milestone.

**Comment by grzeg1** [comment]
@mipapo ? Once we get this going I promise not to bother you again ;) ;)

**Comment by mipapo** [comment]
@grzeg1 
1. Well currently is the status that every commit  automatically updates the repo on translate.runalyze.de
Seems that "Push" work definitly fine since that ;)

2.Supporting multiple branches is a bit tricky - or in other words: I don't like the idea to have several "Projects" on weblate. Every user would have to look in every Projectbranch for left messages.

3. And yeah automatic update source strings is in work. Try to do this at the weekend. Have some appointments during this week. But - thanks for constantly reminding me on this topic ;)

**Comment by grzeg1** [comment]
Every time I see untranslated messages, go to translate them and find out they're not updated I just leave you a note ;)

**Comment by mipapo** [comment]
Currently i don't know where to put my script, which first commit and pushes all changes on weblate to github. Afterwards it updates the default.pot and updates all the po-files. 
Then it commit and push the changes again to git.
I wanted to put this script after weblate get a hook from github (when there are new changes).
So ... still under work

**Comment by grzeg1** [comment]
hook seems ok, just needs a few ifs:
- if only po/pot files were committed - do nothing
- if script is still running when hook triggered - leave a mark to re-run it when finished
something like (meta-language):
```
if (is_file(/tmp/running)){
  touch /tmp/rerun;
  exit;
}
touch /tmp/running;
do{
  rm /tmp/rerun;
  if (not_only(po+pot)){
      run_script;
  }
} while (is_file (/tmp/rerun));
rm /tmp/running;
```

not entirely bulletproof, but should do and in corner cases of concurrency problems it will self-fix with another commit

**Comment by mipapo** [comment]
Yeah, this case is important too.
My question is currently where i can put this script in weblate so that it's executed after receiving the information about the update repo from github. 
There is an option before commiting things, but not for "after receiving hook".
Git comes with several hook examples  (e.g. post-update.sample, pre-commit.sample, pre-rebase.sample, commit-msg.sample, pre-applypatch.sample, prepare-commit-msg.sample , and update.sample).
First thought "post-update" would be right, but currently it doesn't work

**Comment by grzeg1** [comment]
For github I think you need to look here: https://developer.github.com/v3/repos/hooks/#create-a-hook

**Comment by grzeg1** [comment]
And in classic git it would be post-receive I guess?
http://git-scm.com/book/es/v2/Customizing-Git-Git-Hooks#Server-Side-Hooks

**Comment by grzeg1** [comment]
Of course I mean a set-up where server triggers the hook after succesful push, hook calls an URL on weblate server which contains script that does `git pull` and then updates translations.

**Comment by mipapo** [comment]
Thanks for the links. The second sounds good. Currently i don't have anything to change so we'll see whether this works. 

To your last comment: That is the current set-up (or it should be). Github calls an URL on weblate which calls "git pull". Then it should just update the translations. (Via git post-receive hook?).
Or am I completely wrong?

**Comment by grzeg1** [comment]
When it already calls `git pull` why not call the update script in the next line?

**Comment by mipapo** [comment]
I don't know where "git pull" is called in weblate, when the hook url is called.. Weblate had this hookfeature inherently.

**Comment by grzeg1** [comment]
The nice guy from Weblate implemented a post-update user script:
https://github.com/nijel/weblate/issues/687
Can you verify if it would help? I will try it too, but first I will have to set up whole Weblate so it'll take time.

**Comment by mipapo** [comment]
Arr - One thing i hate updating weblate ;) But i will do it

**Comment by mipapo** [comment]
@grzeg1 Okay updated weblate to weblate-2.3dev (git clone) 
Seems to work. I will now look to add the script

**Comment by grzeg1** [comment]
Is it working now? Seems to me something is auto-updating? Did you use the new weblate feature?

**Comment by mipapo** [comment]
@grzeg1 Yip. Seems to work with the new weblate feature.

**Comment by grzeg1** [comment]
Translation strings do not seem to be updated for equipment...

**Comment by mipapo** [comment]
Done

**Comment by grzeg1** [comment]
Time to update again ;)

**Comment by mipapo** [comment]
I will do it during this week. You don't have to remind me

**Comment by mipapo** [comment]
I do it always at regular intervals. At the moment I don't wanna further automate this.
