### ISSUE TITLE
Fit-Import fails with newest perl version

### ISSUE THREAD

**Issue by guotsuan** [Runalyze/Runalyze#1198]
When I tried to upload the fit file to the database. I got the error:

[Sun Jan 25 23:56:40.625483 2015] [:error] [pid 27054] [client ::1:41747] PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Reading *.fit-file failed. First line was "UNIVERSAL->import is deprecated and will be removed in a future perl at /srv/http/runalyze/inc/../call/perl/Garmin/FIT.pm line 6.".' in /srv/http/runalyze/inc/import/filetypes/class.ImporterFiletypeFIT.php:100\nStack trace:\n#0 /srv/http/runalyze/inc/import/filetypes/class.ImporterFiletypeFIT.php(76): ImporterFiletypeFIT->readFirstLine()\n#1 /srv/http/runalyze/inc/import/filetypes/class.ImporterFiletypeFIT.php(47): ImporterFiletypeFIT->readFile()\n#2 /srv/http/runalyze/inc/import/class.ImporterFactory.php(288): ImporterFiletypeFIT->parseFile('import/files/Fe...')\n#3 /srv/http/runalyze/inc/import/class.ImporterFactory.php(277): ImporterFactory->importWithClass('ImporterFiletyp...')\n#4 /srv/http/runalyze/inc/import/class.ImporterFactory.php(70): ImporterFactory->constructForFilename('Fenix-2.fit')\n#5 /srv/http/runalyze/inc/import/class.ImporterWindow.php(98): ImporterFactory->__construct('Fenix-2.fit')\n#6 /srv/http/runaly in /srv/http/runalyze/inc/import/filetypes/class.ImporterFiletypeFIT.php on line 100, referer: http://localhost/runalyze/
 
I think it is caused by the deprecation warnings about "use UNIVERSAL" cause function, 
 ImporterFiletypeFIT->readFirstLine() failed.  Add 'no warnings 'deprecated';' to the call/perl/Garmin/fit.pm 
can suppress the problem for now before updating the readFistline() function or fit.pm. 

My perl version: v5.20.1

Cheers,

Quan

**Comment by grzeg1** [comment]
There's a new version of the library. Changelog says fix for UNIVERSAL is included.

**Comment by laufhannes** [comment]
I was not able to update perl and check the importer within a few minutes this morning. I'll have a closer look this evening. But as @grzeg1 mentions a simple update of the perl module `call/perl/Garmin/Fit.pm` from http://pub.ks-and-ks.ne.jp/cycling/GarminFIT.shtml#description to version 0.12 should fix the issue.
