### ISSUE TITLE
Fatal error, undefined method

### ISSUE THREAD

**Issue by KlausiHH** [Runalyze/Runalyze#1199]
I did a git pull in the morning, very much updated files since the last on Thursday.
But now, the hole installation doesn't work anymore.

Fatal error: Call to undefined method PluginFactory::dataFor() in /home/httpd/docs/.../public/runalyze/inc/plugin/class.Plugin.php on line 316

The pull:
-----------------------------------------
C:\Users\jpm\workspace\Runalyze>git pull
remote: Counting objects: 236, done.
remote: Compressing objects: 100% (235/235), done.
Receiving objects:  63% (149/236), 212.00 KiB | 3
Receiving objects: 100% (236/236), 438.14 KiB | 371.00 KiB/s, done.
Resolving deltas: 100% (98/98), done.
From https://github.com/Runalyze/Runalyze
   78a1649..1a3025d  master     -> origin/master
   ff9193a..cdcb923  feature/misc -> origin/feature/misc
Updating 78a1649..1a3025d
Fast-forward
 build/scripts.js                                   | 207 ++------------
 build/scripts.min.js                               |   2 +-
 call/call.Plugin.display.php                       |  16 +-
 call/call.Plugin.install.php                       |   3 +
 call/call.Plugin.uninstall.php                     |   4 +
 inc/core/Activity/Duration.php                     |  12 +-
 inc/core/Activity/PersonalBest.php                 |   4 +
 inc/core/Configuration/Category/ActivityView.php   |   4 +-
 inc/core/Data/Laps/Laps.php                        |   7 +
 inc/core/Model/Activity/Updater.php                |   2 +-
 inc/core/Model/Factory.php                         |   8 +-
 inc/core/Parameter/Set.php                         |  15 +
 inc/core/View/Window/Laps/Window.php               |   1 +
 inc/data/class.Sport.php                           |   2 +-
 inc/draw/class.Plot.php                            |  36 ++-
 inc/html/class.Icon.php                            |  11 +-
 inc/plugin/class.Plugin.php                        |  35 +--
 inc/plugin/class.PluginFactory.php                 | 157 +++++++----
 inc/plugin/class.PluginInstaller.php               |   5 +-
 inc/plugin/class.PluginTool.php                    |   5 +-
 inc/plugin/config/class.PluginConfiguration.php    |  42 ++-
 inc/system/config/class.ConfigTab.php              |   2 +-
 inc/system/config/class.ConfigTabPlugins.php       |  39 ++-
 inc/system/define.files.php                        |  28 +-
 inc/tpl/tpl.DataBrowser.php                        |  17 +-
 .../search/class.FormularSelectSearchSort.php      |   5 +-
 inc/training/search/class.SearchFormular.php       |  32 ++-
 inc/training/search/class.SearchResults.php        |  78 ++++--
 .../view/section/table/class.TableLapsAbstract.php |   5 +
 .../view/section/table/class.TableLapsComputed.php |  32 ++-
 lib/flot-0.8.1/jquery.colorhelpers.min.js          |  21 --
 lib/flot-0.8.1/jquery.flot.canvas.min.js           |  28 --
 lib/flot-0.8.1/jquery.flot.min.js                  |  29 --
 lib/flot-0.8.1/jquery.flot.navigate.min.js         |  86 ------
 lib/flot-0.8.1/jquery.flot.pie.min.js              |  56 ----
 lib/flot-0.8.1/jquery.flot.resize.js               |  60 ----
 lib/flot-0.8.1/jquery.flot.resize.min.js           |  19 --
 lib/flot-0.8.1/jquery.flot.selection.min.js        |  79 ------
 lib/flot-0.8.1/jquery.flot.stack.min.js            |  36 ---
 lib/flot-0.8.1/jquery.flot.time.min.js             |   9 -
 lib/flot-0.8.3/LICENSE.txt                         |  22 ++
 lib/{flot-0.8.1 => flot-0.8.3}/base64.js           |   0
 lib/{flot-0.8.1 => flot-0.8.3}/excanvas.min.js     |   0
 .../jquery.colorhelpers.js                         |   5 +-
 lib/flot-0.8.3/jquery.colorhelpers.min.js          |   1 +
 .../jquery.flot.canvas.js                          |   2 +-
 lib/flot-0.8.3/jquery.flot.canvas.min.js           |   7 +
 .../jquery.flot.crosshair.js                       |   8 +-
 .../jquery.flot.curvedLines.js                     |   0
 .../jquery.flot.hiddengraphs.js                    |   0
 lib/{flot-0.8.1 => flot-0.8.3}/jquery.flot.js      | 307 ++++++++++++++-------
 lib/flot-0.8.3/jquery.flot.min.js                  |   8 +
 .../jquery.flot.navigate.js                        |   6 +-
 lib/flot-0.8.3/jquery.flot.navigate.min.js         |   7 +
 .../jquery.flot.orderBars.js                       |   0
 lib/{flot-0.8.1 => flot-0.8.3}/jquery.flot.pie.js  |  31 ++-
 lib/flot-0.8.3/jquery.flot.pie.min.js              |   7 +
 lib/flot-0.8.3/jquery.flot.resize.js               |  59 ++++
 lib/flot-0.8.3/jquery.flot.resize.min.js           |   7 +
 .../jquery.flot.selection.js                       |  10 +-
 lib/flot-0.8.3/jquery.flot.selection.min.js        |   7 +
 .../jquery.flot.stack.js                           |   2 +-
 lib/flot-0.8.3/jquery.flot.stack.min.js            |   7 +
 lib/{flot-0.8.1 => flot-0.8.3}/jquery.flot.text.js |   0
 .../jquery.flot.textLegend.js                      |   0
 lib/{flot-0.8.1 => flot-0.8.3}/jquery.flot.time.js |   3 +-
 lib/flot-0.8.3/jquery.flot.time.min.js             |   7 +
 lib/runalyze.lib.feature.js                        |   6 +-
 plugin/RunalyzePluginPanel_Prognose/Plot.Form.php  |   2 +-
 .../class.RunalyzePluginPanel_Prognose.php         |   4 +-
 .../RunalyzePluginPanel_Rechenspiele/Plot.Form.php |  55 ++--
 .../window.plot.php                                |   8 +-
 .../class.RunalyzePluginStat_Rekorde.php           |   4 +-
 .../class.RunalyzePluginStat_Statistiken.php       |   7 +-
 .../class.RunalyzePluginStat_Trainingspartner.php  |   2 +-
 .../Plot.Daytime.php                               |  33 ++-
 .../Plot.Weekday.php                               |  29 +-
 .../class.RunalyzePluginStat_Wetter.php            | 104 ++++---
 .../class.RunalyzePluginStat_Wettkampf.php         |  25 +-
 .../JobLoop.php                                    |  11 +-
 tests/bootstrap.php                                |   1 +
 tests/inc/core/Activity/DurationTest.php           |   7 +
 tests/inc/core/Model/Activity/InserterTest.php     |  11 +-
 .../JobLoopTest.php                                |  44 ++-
 84 files changed, 1080 insertions(+), 1025 deletions(-)
 delete mode 100755 lib/flot-0.8.1/jquery.colorhelpers.min.js
 delete mode 100755 lib/flot-0.8.1/jquery.flot.canvas.min.js
 delete mode 100755 lib/flot-0.8.1/jquery.flot.min.js
 delete mode 100755 lib/flot-0.8.1/jquery.flot.navigate.min.js
 delete mode 100755 lib/flot-0.8.1/jquery.flot.pie.min.js
 delete mode 100755 lib/flot-0.8.1/jquery.flot.resize.js
 delete mode 100755 lib/flot-0.8.1/jquery.flot.resize.min.js
 delete mode 100755 lib/flot-0.8.1/jquery.flot.selection.min.js
 delete mode 100755 lib/flot-0.8.1/jquery.flot.stack.min.js
 delete mode 100755 lib/flot-0.8.1/jquery.flot.time.min.js
 create mode 100644 lib/flot-0.8.3/LICENSE.txt
 rename lib/{flot-0.8.1 => flot-0.8.3}/base64.js (100%)
 rename lib/{flot-0.8.1 => flot-0.8.3}/excanvas.min.js (100%)
 mode change 100755 => 100644
 rename lib/{flot-0.8.1 => flot-0.8.3}/jquery.colorhelpers.js (97%)
 mode change 100755 => 100644
 create mode 100644 lib/flot-0.8.3/jquery.colorhelpers.min.js
 rename lib/{flot-0.8.1 => flot-0.8.3}/jquery.flot.canvas.js (99%)
 mode change 100755 => 100644
 create mode 100644 lib/flot-0.8.3/jquery.flot.canvas.min.js
 rename lib/{flot-0.8.1 => flot-0.8.3}/jquery.flot.crosshair.js (96%)
 mode change 100755 => 100644
 rename lib/{flot-0.8.1 => flot-0.8.3}/jquery.flot.curvedLines.js (100%)
 rename lib/{flot-0.8.1 => flot-0.8.3}/jquery.flot.hiddengraphs.js (100%)
 rename lib/{flot-0.8.1 => flot-0.8.3}/jquery.flot.js (90%)
 mode change 100755 => 100644
 create mode 100644 lib/flot-0.8.3/jquery.flot.min.js
 rename lib/{flot-0.8.1 => flot-0.8.3}/jquery.flot.navigate.js (98%)
 mode change 100755 => 100644
 create mode 100644 lib/flot-0.8.3/jquery.flot.navigate.min.js
 rename lib/{flot-0.8.1 => flot-0.8.3}/jquery.flot.orderBars.js (100%)
 rename lib/{flot-0.8.1 => flot-0.8.3}/jquery.flot.pie.js (97%)
 mode change 100755 => 100644
 create mode 100644 lib/flot-0.8.3/jquery.flot.pie.min.js
 create mode 100644 lib/flot-0.8.3/jquery.flot.resize.js
 create mode 100644 lib/flot-0.8.3/jquery.flot.resize.min.js
 rename lib/{flot-0.8.1 => flot-0.8.3}/jquery.flot.selection.js (97%)
 mode change 100755 => 100644
 create mode 100644 lib/flot-0.8.3/jquery.flot.selection.min.js
 rename lib/{flot-0.8.1 => flot-0.8.3}/jquery.flot.stack.js (99%)
 mode change 100755 => 100644
 create mode 100644 lib/flot-0.8.3/jquery.flot.stack.min.js
 rename lib/{flot-0.8.1 => flot-0.8.3}/jquery.flot.text.js (100%)
 rename lib/{flot-0.8.1 => flot-0.8.3}/jquery.flot.textLegend.js (100%)
 rename lib/{flot-0.8.1 => flot-0.8.3}/jquery.flot.time.js (99%)
 mode change 100755 => 100644
 create mode 100644 lib/flot-0.8.3/jquery.flot.time.min.js

**Comment by laufhannes** [comment]
Can you compare your `inc/plugin/class.PluginFactory.php` with https://github.com/Runalyze/Runalyze/blob/master/inc/plugin/class.PluginFactory.php#L71-L83?

**Comment by grzeg1** [comment]
Maybe clone clean repo again and copy your config.php there. It seems to be something you did locally. And if you still have this bug tell how to reproduce.

**Comment by KlausiHH** [comment]
OK, sorry, the problem is on my site. I don't have git on my webspace. So use it locally on Wintendo and with Netbeans, wich should sync all files by FTP with the webspace. This was not working at all.
