### ISSUE TITLE
New registration: Default configuration setting does not work (sport-/typeid)

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1200]
Register a new user and have a look at the configuration. `MAINSPORT`, `RUNNINGSPORT`, `TYPE_ID_RACE` and `TYPE_ID_LONGRUN` are not set properly.

In addition, default sport types / activity types / clothes need translations.

**Comment by grzeg1** [comment]
in #1212

**Comment by grzeg1** [comment]
`runalyze_empty.sql` - does this just go away or we need to call `createNewUserFromPost()` for user with accountid 0

**Comment by laufhannes** [comment]
Currently there's still the option `USER_MUST_LOGIN`, so that users may use Runalyze without creating an account, yes.

**Comment by grzeg1** [comment]
I guess we can close it?

**Comment by laufhannes** [comment]
Still wanted to test it, but I only found some other bugs ;)
