### ISSUE TITLE
Fix cache clean

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1202]
Currently a `Cache::clean()` will remove everything from cache. Since this method is available from our cacheclean tool a single user can clean the cache of everyone.

I'd like to have two different Cache classes, implementing both a predefined interface
 - `UserCache`
 - `GlobalCache`

I not sure if we can configure phpFastCache to use different places* for both caches or if we have to somehow remember all keys that belong to a single user. Speaking of general data as configuration, sport types, activity types, clothes and plugins it should be easy to keep these keys as array, but activities, trackdata and routes are indexed by their id**.

\* *As phpFastCache provides several drivers, there's probably not for everyone a single "pace" where the cache is saved.*

\*\*  *Another question is if it's really of any advantage to cache single id-based rows.*

**Comment by grzeg1** [comment]
Other question related to database performance: how much caching wil actually be needed when database is tuned (innodb, indexes, queries). Writing and reading cache files has a cost too.

**Comment by laufhannes** [comment]
Another question that should be benchmarked properly ;-)

**Comment by mipapo** [comment]
In the future i will use memcache for the online runalyze instance. But in the moment the performance seems to be good. 
The next change will be a new virtual server with an seperated ssd. 
Runalyze is gettin fast *yey*

**Comment by grzeg1** [comment]
Workaround proposed that should be enough to close this for 2.0.
In final version cache handling needs to be invisible to user. Objects need to be removed from cache when we know that they're no longer valid. But this is too much for now I think.

**Comment by laufhannes** [comment]
I like the solution. Much better than tracking all keys for every user.
