### ISSUE TITLE
Prognose shape: Range Date issue

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1204]
When there are no entries for the prognose the shown timestamp is 0 ;)
![agcfbjic](https://cloud.githubusercontent.com/assets/2135076/5936170/3f8b0fac-a6e2-11e4-8ffc-42dc4aeec9a4.png)

**Comment by grzeg1** [comment]
I guess selection should be off here? Not much sense in displaying average prognose if there is just one value per month.

**Comment by grzeg1** [comment]
Now after #1203 fix it should work.
But still selection does not seem to show anything valuable. Maybe for someone who competes regularly on the same distance - like 10K once a month. Then it might be interesting to see averages.

**Comment by laufhannes** [comment]
It does.

And I think there is no need to disable the selection. Last year I had eight 10k races and my graph does now cover eight years in total. So there is something to average.
