### ISSUE TITLE
Directory for all local files/directories

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1213]
I'd like to add a new directory (e.g. `/local/`) that holds the following directories:
 - `/log/`
 - `/srtm/`
 - `/files/import/`
 - `/files/export/`

Directories that need write permissions will be all together and it will be easier to ensure that the update progress will not delete installation-specific files.

Further directories may follow in the future:
 - `/tpl/`
 - `/cache/`

Open for discussion: Should this be added for v2.0? And will we put configuration files (`config.php`, `config_lang.php`) in this directory as well?

**Comment by grzeg1** [comment]
I'd push 2.0 asap and immediately start work on 2.1 - release early, release often ;-) There will always be something to improve ;-)

**Comment by laufhannes** [comment]
And such a directory restructuring does not require a 3.0, speaking of semantic versioning?

**Comment by grzeg1** [comment]
Versioning is what you want it to be. Like Java 1.5, then 1.6 with lots of changes, then Java 7.
Or MySQL with 5.x versioning for ages. Or even better Linux 3.0 which was really 2.6.something and Linus was explaining that no, there were no significat changes inside ;). 
It's always more of a marketing thing, letting users know that something really big (or small) is coming.
If I were to choose, I'd choose 2.1 ;)

**Comment by laufhannes** [comment]
Sure, a lot of companies do not follow semantic versioning and so far we did not either. (And as we do not have a public API so far that's maybe not even against it. Was only a though.)

**Comment by mipapo** [comment]
"tpl" directory can be omitted due future changes

**Comment by laufhannes** [comment]
Config files (`config.php` and `config_lang.php`) are still missing.

**Comment by mipapo** [comment]
config.php must be moved to data -> add it to the documentation and to the update blog post (with a biiiiiiiggggg "Attention" icon) #1661
