### ISSUE TITLE
Refactor account classes

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1214]
We'll use doctrine entities together with symfony's authentication.

---

Old content:

 - [ ] Add `Model/Account`
   - [ ] Add `Inserter`
   - [ ] Add `Updater`
   - [ ] Add `Deleter`
     - Do we still need the trigger for the database or will the Deleter class do that stuff?

Shall this go into v2.0 or is it too much/too critical?

**Comment by grzeg1** [comment]
2.1 ;-)

**Comment by mipapo** [comment]
Work done in b43bfb6ad2622ee59d82e113d3df9c7876700069 517dd45083c63ed9b7ea254e318d83173b4c8e61  d4e4688e89a795cf01e7071c7c668d2922e39d87 
Using Doctrine Entity
