### ISSUE TITLE
Database structure: columns with latin1 character set.

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1217]
Is it needed for anything or can be changed to utf-8?
Now that we have translations latin1 is not enough - translated sport names are already messed-up.

**Comment by laufhannes** [comment]
Default charset should already be utf-8. I hope MySQL handles it correctly if there are special characters in latin1 and we alter the column to utf-8?

**Comment by grzeg1** [comment]
I guess you need to verify it for German. For Polish I had to alter it before I was able to enter national characters.
