### ISSUE TITLE
Problems with 'route' data for activities

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1220]
I'm not sure if Marko discovered these bugs before we fixed them or if they are still present:
 - [x] 'route' field in editor is empty after creation
 - [x] changes in editor will cause 'route' field to be empty
 - [x] label for route in elevation plugin has some strange behavior
 - [x] Unknown index 'routeid' for some form
 - [x] `route` as dataset

**Comment by grzeg1** [comment]
current version:
- route ok after creation
- route field empty when edit started
- route field not updated after editing

**Comment by laufhannes** [comment]
`route` has currently the problem of being redundant in database:
  - `runalyze_training.route`
  - `runalyze_route.name`
  - `runalyze_route.cities`

The first one is meant to be deprecated as its name belongs to the 
route, not to the activity. In terms of editing activities and viewing 
activity data this requires a second lookup.

(The last one is a preparation to track all visited cities which is 
currently done by using 'City A - City B' as route.)

Your fix forces the edit form to display `runalyze_training.route` which 
is empty for all created activities since v2.0alpha.

**Comment by grzeg1** [comment]
It does, but then `runalyze_route` seems correctly updated and all other places where searching is done by `runalyze_training.route` work.
So the only bad thing is just a bit of data redundancy here and it can be fixed in next release. Am I rigt?

**Comment by laufhannes** [comment]
Yes. I included fixes for both in 95e6979752b992ee12f6ba7c2176165946f37fb8 and bf749d5bbe7ce0e5890f4954de265e95a6c02233. In addition, labels in elevation plugin are fixed by 740b48ff334e8efc5b6568284951efef1956cb81.

I need to have a look again at the dataset.

**Comment by laufhannes** [comment]
Fixed with 550ac56554341044cc4f7f7a23b4efee2a3923fe.
