### ISSUE TITLE
Bugs in configuration

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1230]
- [x] `TRAINING_MAP_PUBLIC_MODE` is not respected
 - [x] `PACE_Y_LIMIT_MIN` (and `_MAX`) is confusing/not respected
     - probably just drop `... && $min < 1000*$LimitMin->value()`
 - [x] `TRAINING_ELEVATION_SERVER` can be removed
     - current order: srtm > geonames > datasciencetoolkit > googleapis (see [Corrector.php](https://github.com/Runalyze/Runalyze/blob/master/inc/core/Data/Elevation/Correction/Corrector.php#L58-L72))
 - [x] New ordering (sport types, activity types, shoes) currently requires a cacheclean to work
     - ordering should be done dynamically, regardless of the ordering of cached array
 - [x] Changing `DB_DISPLAY_MODE` needs an onchange event
     - moved to product backlog: #1235

**Comment by laufhannes** [comment]
Just added some more bugs.

**Comment by grzeg1** [comment]
Ordering: user has absolutely no control over id-s assigned. Useful only in some special use cases.
I'd suggest only alphabetical sorting for now. Intuitive and easy to find what you're looking for.
For convenience later we could automatically fill up values based on most frequent ones used.

**Comment by laufhannes** [comment]
As ids are on auto increment ordering by id is nearly the same as ordering by creation/insertion time. At least for equipment I definitely do need that - and I don't see any drawbacks by keeping that option.

**Comment by laufhannes** [comment]
Ordering fixed with bfb75993946e36532bfd9c1211abfce27d757c2b.
