### ISSUE TITLE
Remove invalid values from elevation correction

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1234]
For empty gps data (e.g. if signal is lost for a short time period) elevation correction gives invalid values (-32.768). These should be removed.

There was a solution in v1.5 to fill these values with the next valid ones. (see [class.GpsData.php#L1159-L1186](https://github.com/Runalyze/Runalyze/blob/support/1.5/inc/data/gps/class.GpsData.php#L1159-L1186)) But that solution changed latitude/longitude as well and does not work if gps signal is lost at the beginning.

**Comment by grzeg1** [comment]
Suggestion: invalid values for gps data are going to produce invalid pace/speed as well. So the better option would be to interpolate invalid GPS data and then elevation correction wouldn't need bad data handling. What do you think?

Also this may be a regression but it's not technically a bug (garbage in -> garbage out ;))

**Comment by laufhannes** [comment]
There are devices as my Garmin Fenix 2 out there that record distance/pace via acceleration sensor with acceptable accuracy if gps signal is lost. So there is no need to interpolate.

I agree for your last point (garbage in -> garbage out) and think that we should not change data in that case if we don't have to. That means, for distance/pace we take whatever comes in. But as soon as the user requests elevation correction it's our responsibility to give not completely wrong data.

Keeping `-32.768` as 'invalid' altitude value and excluding it from all calculations seems okay for me, but I guess it's much more work.

**Comment by grzeg1** [comment]
I tried to take a look from a broader point of view. Meaning if interpolation needs to be done anyway it could spare some work on elevation.
As far as elevation is concerned: do you just mean SRTM files? It seemed to me from code reading that it was being changed to `0` (which is still not right for further processing) before being returned?

**Comment by grzeg1** [comment]
Off topic: does this gitter thing work for you?

**Comment by laufhannes** [comment]
SRTM files may have gaps/empty points but as long as that are no large gaps values are already interpolated within the reader. I did not see any problems with SRTM files so far.

But for "empty" points, i.e. 0.0°/0.0° they are never used (unless one has a srtm-file including that point). For Geonames.org I found:
 > a single number giving the elevation in meters according to srtm3, ocean areas have been masked as "no data" and have been assigned a value of -32768
