### ISSUE TITLE
Allow login via email instead of username

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1236]
Suggestion to avoid two database lookups:
 - do not allow usernames to contain `@`
 - if login value contains `@` look for email otherwise for username

**Comment by grzeg1** [comment]
How about completely ditching usernames and staying with emails as usernames?

**Comment by mipapo** [comment]
Well for sharing it would be a problem, because of the site shared/<username> 
And personally I like usernames for login, because my problem is that i often forget with which emailaddress I'm registered anywhere.

**Comment by grzeg1** [comment]
Isn't it as easy to forget username as it is with email address?. And if you want to reset password you need email anyway?

"Well for sharing it would be a problem..." - this one I don't understand - could you elaborate?

Everywhere I look (Garmin Connect, Polar Flow, Tapiriik, Dropbox, Facebook etc.) they just use emails. And they do it for users' convenience.

**Comment by laufhannes** [comment]
Users don't want to share their real name or their email but we need a unique identifier to display on public sites (shared views and lists so far). I prefer an immutable username for that and not an input field for "Displayed name".

**Comment by mipapo** [comment]
@grzeg1 I have with some expections everywhere the same username  - so i won't forget. And the emailproblem is a little luxusproblem (Some aliases for my majormailaddress)

@laufhannes +1  - Is there a reason why we have the real name in the database? I think it's unimportant or am I wrong?

**Comment by laufhannes** [comment]
@mipapo I think that was meant as "Displayed name" and is not used anywhere.

**Comment by mipapo** [comment]
@laufhannes Sorry - Then i got it wrong ;)

**Comment by grzeg1** [comment]
Every new platform uses just Last name for sharing. People who don't want to share (If they share via FB they don't care anyway) just use an alias. Few old platforms that still use usernames, end up with usernames like hannes008 anyway ;)

Alternatively if you can't live with that we could label it as 'Alias for public pages' and not use it for logging-in?

**Comment by grzeg1** [comment]
Hmm. I can see now that GC still lets you log in with username.

**Comment by laufhannes** [comment]
GitHub and Twitter are just two prominent examples of username-based platforms.

Labeling it as 'alias' seems correct (that's what it is used for so far). But I'd prefer labeling login via username as deprecated for e.g. one year instead of dropping it directly.

**Comment by grzeg1** [comment]
One year's a lot in OS world ;) But it's you call of course.

**Comment by mipapo** [comment]
@grzeg1 @laufhannes Stop! ;) Currently there is only the possibility to login via username - right?
We should add allow the login via mail and then track (i think we have enough user to see what they are using) which kind of login they are using. I don't like the idea to stop the login via username. I think the most users will login via username.

**Comment by grzeg1** [comment]
@mipapo I bet most will log in by username as probably most of them have login credentials saved in their browsers just like me ;)

anyway, I'm fine with whatever you choose

remaining question is: should user creation require username?

**Comment by mipapo** [comment]
@grzeg1 Well, when there is no choice it's hard to login in another way (although there are some few experts how added their mail address also to username.

But you're meaning currently name or username. 
If you mean username. In my opinion it should be required.

**Comment by mipapo** [comment]
Working in micro-symfony branch which will be merged soon
