### ISSUE TITLE
Uploads: problems with spaces / umlauts

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1246]
Following file names do not work:
 - `Test ä.tcx`
 - `Test ae.fit`

**Comment by grzeg1** [comment]
First one works for me. Maybe filesystem/locale configuration?

**Comment by laufhannes** [comment]
The first one does work for me as well but not on svn.runalyze.de.

**Comment by grzeg1** [comment]
Actually it seems that if two users try to upload file with the same name at the same time they will be mixed-up. Lately seems less likely as most platforms name files by dates, but still may be probable in multi-user environments.
Proposed solution to both: make a hash (e.g, MD5) of user id and file name and use it where just file name is used.

**Comment by laufhannes** [comment]
Umlauts still fail on svn.runalyze.de (Debian). Files are uploaded correctly (at least umlauts are shown via console) but they are not found for parsing.

I don't know if @mipapo has time for a short look the next days?

**Comment by laufhannes** [comment]
There are two different ways to represent an `ä` if encoded with `encodeURIComponent()` (which is done in our uploader): `%C3%A4` and `a%CC%88` - depending on whatever. It seems to me that while uploading and moving the uploaded file with php the first one occurs and while requesting `call.Training.create.php?file=...` the second one occurs. Probably some OS find the file in both cases, some do not.

[`Normalizer::normalize($string)`](http://us2.php.net/manual/en/normalizer.normalize.php) seems to fix the problem (but requires the intl extension). We can try to find a better solution in a later version (e.g. as soon as we use something else than Fineuploader). For v2.0 that should be enough. If people have this problem and can't use intl they just can't upload files with umlauts or similar. That's it.
