### ISSUE TITLE
VDOT correction by elevation: Which value to choose?

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1249]
Elevation data is available as total/up/down from `route` and as value from `training`. As the distance correction favors up/down route's value is currently used. But as route's values are always calculated the user can't actually change elevation value to correct vdot estimation.

**Comment by grzeg1** [comment]
VDOT correction needs gradient analysis. Current state is useful only for street running. This way correction from track should be always more important.
We can make a selection: use manual data/use track data for VDOT correction and unlock separate up and down values for training.
We should also get rid of 'total' elevation. Just use up and down, and when going back to starting point up=down. For user's comfort when only up is entered, down can be duplicated as up.

Somehow related to: #1297

**Comment by laufhannes** [comment]
There's a ticket for using grade adjusted pace: #1573.
