### ISSUE TITLE
Script for global cleanup

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1252]
As with v2.0 some formulas for vdot / trimp / jd points changed every user has to cleanup all of his activities to get consistent values. This should be done by the administrator - otherwise user will forget about it and complain.

**Comment by grzeg1** [comment]
You mean should be a part of migration?

**Comment by laufhannes** [comment]
Yes. Otherwise there are no 'training points' for old activities and vdot/trimp values for new activities will differ from old ones.

And I think that it's a good idea to just tell everyone: You have to do a cleanup yourself.

**Comment by laufhannes** [comment]
I'd try to change classes used by the plugin such that it can be used in a new script, similar to db-refactor.php, that loops through all accounts.

**Comment by laufhannes** [comment]
Or one could try to change the db-refactor.php itself to do these calculations as well.

**Comment by laufhannes** [comment]
Should be done with 76bdd0d66313c3e095439b940a37aa11f3f5d755.
