### ISSUE TITLE
Login window not shown on 1024px width

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1253]

**Comment by grzeg1** [comment]
[inc/tpl/tpl.installerHeader.php#L23-L28](https://github.com/Runalyze/Runalyze/blob/master/inc/tpl/tpl.installerHeader.php#L23-L28)
Sems `Ajax::wrapJSforDocumentReady('Runalyze.init();');` generates `div id="ajax"`, but in lines 26-27 another `div id='ajax'` is defined. This ruins css. 
Gets better after removing lines 26-27. But I'm not sure how it's all supposed to work.
