### ISSUE TITLE
Singular/Plural problem

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1256]
Plural is not displayed (e.g. on the login page). Instead it remains singular.

**Comment by grzeg1** [comment]
@mipapo can you give an example: what is displayed and what should be?
Also how are things going with automatic translations update? There are probably a few not updated. Maybe this is the issue here?

**Comment by mipapo** [comment]
Can be closed. The mo files were not recreated after the update of the installation at svn.runalyze.de. So it works. Everythin is fine.
I won't finish the automatic translation update in the moment. I don't trust weblate ;) 
I have a deeper look into this when i have finally internet at home....(german providers are soo slow when it has to do with a new connection).
It's also not import for the final version of Runalyze v2.0. I will update the base translation tomorrow.
