### ISSUE TITLE
Prognosis calculator (CPP): warning for invalid input

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1258]
Nothing will be computed if both results have same distance. An error message should be displayed.

In addition, strange values occur for unbalanced results. `K` must not be less than 132 (which is the world record for 1.000m) and `e` should probably be bounded as well.

**Comment by laufhannes** [comment]
+1 via Twitter. 

Example input: 10.54k in 58:59 and 10.50k in 59:34. 
Result: K = 1571209, e = -2.588

**Comment by laufhannes** [comment]
+1 via Mail.
For `e < 1` times get better for shorter distances.

**Comment by laufhannes** [comment]
Not sure if it's easy to realize, but both results should not be too similar. If the best result is for 10k, the second one should not be between something like 8k and 12k.

**Comment by jjqoie** [comment]
The Bock (CPP) prognosis use a short and long result. Additionally the recommended distances of the best short / long run depends on the target distance the prognosis is calculated.
The prognosis fails if the pace of the long run is faster than the pace of the short run - see condition at the end of the screenshot

I added as a test an query for the top result 10km and use it as default value in the class.Prognose_PrognosisWindow.php
But I have problem to find where I can change the Input form text for Bock CPP
and where the calculation for the different distance is done

<img width="692" alt="screen shot 2016-02-24 at 22 46 04" src="https://cloud.githubusercontent.com/assets/17315965/13302110/77c681bc-db48-11e5-844f-2c80e5b57fb4.png">


plugin/RunalyzePluginPanel_Prognose/class.Prognose_PrognosisWindow.php

	protected function setDefaultValues() {
		$Strategy = new Prognosis\Bock();
		$TopResults = $Strategy->getTopResults(2);
		$TopResults10km = $Strategy->getTopResults(1,10);

		$CurrentShape = Configuration::Data()->vdotShape();

		if (empty($_POST)) {
			$Factory = new PluginFactory();
			$Plugin = $Factory->newInstance('RunalyzePluginPanel_Prognose');

			$_POST['model'] = 'jack-daniels';
			$_POST['distances'] = implode(', ', $Plugin->getDistances());

			$_POST['vdot'] = $CurrentShape;
			$_POST['endurance'] = true;
			$_POST['endurance-value'] = BasicEndurance::getConst();

			$_POST['best-result-km'] = !empty($TopResults) ? $TopResults[0]['distance'] : '5.0';
			$_POST['best-result-time'] = !empty($TopResults) ? Duration::format($TopResults[0]['s']) : '0:26:00';
			$_POST['second-best-result-km'] = !empty($TopResults10km) ? $TopResults10km['distance'] : '10.0';
			$_POST['second-best-result-time'] = !empty($TopResults10km) ? Duration::format($TopResults10km['s']) : '1:00:00';
		}

**Comment by laufhannes** [comment]
But that solution will fail if there's no result for 10k or more? And it will fail as well if there's only a bad 10k result (e.g. because that person does only good 3k and 5k races). And even if there's a valid 10k result there may be a better 9.5k result that should be used instead. And what's with the case that the best result returned by `$Strategy->getTopResults(2)` is equal to the result returned by `$Strategy->getTopResults(1,10)`?

Bock's suggestions to use 3k/5k/10k/hm as test results is a very general suggestion. I don't think it's a good solution to force the calculator to use 10k or more as second result.

I'd prefer a solution that checks that there's a factor of at least `1.5` or something like that between both distances.

---

> But I have problem to find where I can change the Input form text for Bock CPP
and where the calculation for the different distance is done

Which text do you mean? All prognosis strategies use the same form and inputs. Hiding some fields for specific strategies is done via js, see [class.Prognose_PrognosisWindow.php#L456](https://github.com/Runalyze/Runalyze/blob/support/2.4.x/plugin/RunalyzePluginPanel_Prognose/class.Prognose_PrognosisWindow.php#L456).

The strategy is setup in [class.Prognose_PrognosisWindow.php#L155-L168](https://github.com/Runalyze/Runalyze/blob/support/2.4.x/plugin/RunalyzePluginPanel_Prognose/class.Prognose_PrognosisWindow.php#L155-L168) and [class.Prognose_PrognosisWindow.php#L137](https://github.com/Runalyze/Runalyze/blob/support/2.4.x/plugin/RunalyzePluginPanel_Prognose/class.Prognose_PrognosisWindow.php#L137) just chooses the requested strategy.
