### ISSUE TITLE
Configuration: avoid scrolling in activity view

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1259]
As a simple workaround for people complaining about scrolling for lap data etc.

**Comment by grzeg1** [comment]
IMO everything that is 'enhancement' should go into 2.1 and only bugs into 2.0.x.
Also there is going to be more feedback regarding new layout, so I'd wait until we get it all before implementing a solution.

**Comment by laufhannes** [comment]
Valid point.

**Comment by grzeg1** [comment]
Requires a few answers from #1295
