### ISSUE TITLE
Prognosis panel: Trailing comma breaks query

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1260]
At least two users report problems with ajax requests (they always open in a new window ...).
They are both on latest Chrome but it seems that other browsers may have the same issue. - And for me latest Chrome is working well.

(And as they reported it today I guess v1.5 worked for them.)

**Comment by grzeg1** [comment]
Can you write how to reproduce so I can check with my browser? Desired vs obtained result?

**Comment by laufhannes** [comment]
Click on one of the arrows above the calendar. The next or previous week should load within that container, but for them the requested page will open in a new tab.

**Comment by grzeg1** [comment]
I had a problem back in 1.5 - every ajax call would open in new window/top of page. If I remember well it was somehow related to Apache configuration and missing php module. I guess we're talking local installs here? Maybe they copied new files over the old directory structure and there are some leftovers?

**Comment by laufhannes** [comment]
No, both on our online version, and both on Windows, once 8.1, once tried on both 7 and 8.1.

**Comment by laufhannes** [comment]
Okay, it has nothing to do with ajax/JS. It depends on their account: prognosis display "crashes".

**Comment by laufhannes** [comment]
If a user sets `1, 3, 5, 10, ` as distances the query to lookup will break.

**Comment by laufhannes** [comment]
A short fix is to wrap `$this->getDistances()` with `array_filter()`, but probably the complete query `'AND `distance` IN('.implode(',', $distances).') GROUP BY `distance`'` in [PersonalBest](https://github.com/Runalyze/Runalyze/blob/master/inc/core/Activity/PersonalBest.php) is insecure.
