### ISSUE TITLE
Minor bugs in v2.0

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1263]
We don't need an issue for every small bug:
 - [x] Laps window: distances with comma (`0,4`) do not work
 - [x] Laps window: "Every ... km" does not work if splits are empty
 - [x] Global cleanup: flag `cleanup` for accounts is not updated
 - [x] Json importer: no loading effect while uploading
 - [x] Cadence can have wrong array size as well
 - [x] Gpx parser: one hr-value is missing for spoq-extension
 - [x] Plot precision by distance (e.g. every 50m) fails
 - [x] Clothes configuration: cache clean does not work
 - [x] Safari: mark splits 'all active' does not work

**Comment by grzeg1** [comment]
better to have an issue for every small bug (which may be not so small)  (maybe just group related ones)

**Comment by grzeg1** [comment]
Passwort vergessen? Hannes? just need translation update I guess

**Comment by laufhannes** [comment]
`sprintf()` should be used instead of `__('Did you forgot your password').' '.$account['name']."?`

**Comment by laufhannes** [comment]
`sprintf()` is moved to master / v2.1.
