### ISSUE TITLE
Record shoe size

### ISSUE THREAD

**Issue by Optophonic** [Runalyze/Runalyze#1267]
In the table of shoes it would be helpful to record the size of the shoes

If you are using different shoe brands it could help you to find the right size for a brand especially if you order online.

**Comment by mipapo** [comment]
Great idea!

**Comment by grzeg1** [comment]
Seems short notes for each shoe would be optimal. Everybody can then put whatever they want there - size, drop, whether they liked it etc.

**Comment by laufhannes** [comment]
+1 for short notes

**Comment by mipapo** [comment]
+1 short notes - I will add this :)

**Comment by mipapo** [comment]
Lohnt sich nicht mehr. Wird in #581 vorhanden sein
