### ISSUE TITLE
TRIMP: estimate if hr is missing

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1268]
Currently trimp is only a function of time if hr data is missing. Can we somehow estimate hr for trimp calculation if hr data is missing?

Other possibility: Get `RPE` for activity types back and use that as fallback.

**Comment by grzeg1** [comment]
I always estimate average HR for my trainings without HR meter, enter it and then get TRIMP. This can be done even now.
RPE gives different range of values so it won't be comparable and thus is not a good solution.
What could be done though is a quick calculator where user would enter perceived % of effort (e.g. I was running at my 80% effort) and it would calculate average HR based on % of HR reserve. This should give a good estimation and same value range, comparable with HR-based TRIMP.

**Comment by laufhannes** [comment]
Yeah, I told him to enter them by hand if he really wants to rely on TRIMP in that case - but he does not want to that for the last two years.

Another idea: add `avg. hr` as field for activity types (as it's there for sport types).

**Comment by laufhannes** [comment]
Just as a note: I just saw that `RPE` is still there. But I agree that they give another range (although one could just define a mapping, e.g. RPE 1 = 50 %HRmax, RPE 10 = 95 %HRmax).

**Comment by grzeg1** [comment]
We could change RPE to '%effort' and migrate 1-10 values to 10-100% values. Then calculate. I thought HR reserve, not HR Max as the reserve is proportional to effort.

**Comment by grzeg1** [comment]
Of course the only case it's valid is when different training types correspond to different effort levels and user carefully chooses appropriate training type matching his effort. Otherwise it's of no use.

**Comment by laufhannes** [comment]
Another note: sport types have currently `RPE` and `avg HR`. Average heart rate is currently used as fallback and rpe is not used anywhere.

My guess is that normal users will understand an average heart rate easier than rpe / effort.
