### ISSUE TITLE
Unwanted autopause in TCX importer (maybe others too)

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1269]
I just realized I removed this in my modified 1.5 version.
Especially for ABC/Intervals, also for swimming it cuts time and TRIMP is then all wrong.
Desired result: full time of training registered.
It would easy to make it configurable. Question is: what should the default option be. Ideally target version would be to let user change this for a single import.

**Comment by laufhannes** [comment]
This problem exists in Runalyze for a long time.

#913 was about our current auto-detection of pauses as well. My idea there was:
 - config: limit for auto pause (can be 'none')
 - config: 'trust auto-detection' or 'always check'
 - for a check: show which pauses are detected and add checkboxes to (un)check them

But I guess that's too much for any v2.0.x

**Comment by grzeg1** [comment]
How about config value: detect autopause, default true (match current behavior). For TCX it's 1-line change. Without it I'm not able to use 2.0 for my swimming ;)
I'll make a PR anyway, you'll decide which ver. to put it.

**Comment by laufhannes** [comment]
This solution is now integrated in v2.1 and v2.0.x.
