### ISSUE TITLE
TRIMP calculation possibly wrong - based on time instead of elapsed time

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1270]
It should be based on elapsed time. Average HR needs checking (if it's calculated for the whole activity).

**Comment by laufhannes** [comment]
Elapsed time is only the difference between beginning and end. This value is larger than the 'active' time if there are pauses: E.g. if I take a pause for stretching after warmup, if I need a toilet pause, ... or whatever.

In my opinion these pauses do not affect total impulse / stress / strain?

**Comment by grzeg1** [comment]
Now pause is calculated as "no moving". So when no movement is registered - like push-ups, skips etc during ABC training, the time is shortened. Also if you stop e.g after uphill run and your pulse is still high. Could be several minutes.
I'm not even sure if avg hr = avg for elapsed time or avg for time

**Comment by laufhannes** [comment]
Currently average is calculated as average value of heart rate array which is indeed wrong for non-equi-distant points: [class.ParserAbstractSingle.php#L204-L212](https://github.com/Runalyze/Runalyze/blob/master/inc/import/parser/class.ParserAbstractSingle.php#L204-L212)
I think that was already mentioned somewhere else (that we should use the real distribution).

I still think that the additional effect of a higher heart rate is negligible as long one does not "workout" inbetween. If one does exercises inbetween and want them to influence trimp and co they should not be paused.

I add just another activity for a workout inbetween as long as such a mixed workout is not supported (or do not stop my watch if I don't care about messed average values).

**Comment by grzeg1** [comment]
To sum up this one and #1269:
- when user uses 'Pause' on the watch he means he wants to exclude the time of pause from workout (as if it never happened)
- everything (HR avg, pace avg, TRIMP etc) is calculated for time outside pauses (=> Time, not Elapsed time)
- if user wants to do mixed workout, he uses Laps, not Pauses, to mark segments of workout. Then averages nad TRIMP are calculated for the whole time (and Time = Elapsed Time)
- for FIT import pressed Pauses are marked in the watch, so they should always be applied
- for TCX import pauses are auto-detected, so option to turn autodetection off is needed (to support mixed workouts or e.g ultra runs when you stop for drink/food)
- for GPX there's no pause detection so it can be later implemented with option

is that ok?

**Comment by laufhannes** [comment]
Perfect!

**Comment by grzeg1** [comment]
I reverted changes to FIT import, so the code should now work as above. PR #1277 should be ready when Travis finishes.

**Comment by grzeg1** [comment]
This one can be closed. To be continued in #1269 ;)
