### ISSUE TITLE
0 - distance splits cause Internal Server Error when trying to show details

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1271]
Made a few corrections but for a complete fix this we need time-based splits (#1264).
Will submit a pull request later.

**Comment by laufhannes** [comment]
As suggested changes go into 2.1: Can you provide an example where an error occurs on 2.0.x? Or did this only show up if treating distances in lap window not as incremental ones?

**Comment by grzeg1** [comment]
Start training. Run. Stop moving. Take a lap (split). Wait a while. Take another lap (split). Run. Stop. Stop training.
Import training. You'll get 3 laps/splits. Middle lap/split with 0 distance. Open 'More info about laps'. You'll get 500.
(if you move during middle lap it won't happen)
For me the easiest way to reproduce is when pool swimming and the watch uses accelerometer instead of GPS.

**Comment by laufhannes** [comment]
I created such an activity with my fenix 2 which supports indoor activities with gps disabled and distance by accelerometer. But I still get no error, not on 2.0.x and not on master. Do you have some more changes in your version that may cause this error?

The only problem I see: max. heart rate is minus infinity if not data is available.

![bildschirmfoto 2015-03-12 um 15 31 03](https://cloud.githubusercontent.com/assets/8313118/6619787/f12baa1c-c8cc-11e4-94bc-b8fa889b4057.png)

**Comment by laufhannes** [comment]
Okay. If I enter "0.11, 0.00, 0.12" as manual distances I get it: Target must be larger than current value.

**Comment by laufhannes** [comment]
I suggest to ignore 'empty' splits in 2.0.x as they require time-based splits to work and they'll probably need some more work.

**Comment by grzeg1** [comment]
I'm not sure about indoor activities, but for swimming the distance is real 0 (not 0.0001 which can be displayed as 0). Seems it is so in your case.
If it was for manual distances I wouldn't care. I just got the error for real training so I thought it should be fixed. The fix you merged into 2.1 is not complete, but prevents 500. I use git version for myself so I don't care as much for 2.0.x ;)
