### ISSUE TITLE
Laps editable only for Running, imported for every sport anyway

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1273]
I guess they need to be editable for other sports too

**Comment by laufhannes** [comment]
I have no problem with adding/editing them for e.g. cycling?

**Comment by grzeg1** [comment]
There's no config for it, is there?
I open my swimming tcx with laps, they're not there. When I switch to running they appear. Switching to any other sport hides them. Even when hidden they get imported anyway.

**Comment by laufhannes** [comment]
I figured it out: splits are only displayed in form if sport type supports activity types: https://github.com/Runalyze/Runalyze/blob/2392afe549e83daefdf3075a9f5fc94bb127c961/inc/training/schemes/scheme.Training.php#L42
