### ISSUE TITLE
Disable TRIMP for individual training

### ISSUE THREAD

**Issue by Jens9891** [Runalyze/Runalyze#1275]
Disable TRIMP for individual trainings, how it is possible for VDOT.

**Comment by grzeg1** [comment]
Why would you like to do it?

**Comment by Jens9891** [comment]
Hello,
I have imported many activities with the heartrate of my girlfriend when we run together. 
Before the update to 2.0 I disabled VDOT and removed the two heartrate fields after I uploaded the file. Because of this workaround the overall calculation of my runalyze account was not disturbed by individual foreign activities with heartrate values of my girlfriend. Now the workaround doesn't work anymore. :(
I would be very happy if this little option could be added, so that my account become clean again.
Regards Jens

**Comment by laufhannes** [comment]
I guess it's better to add an option to remove complete heart rate array (or any other array). I would need that for example for elevation data if my watch tracks elevation barometrically for indoor activities.

**Comment by grzeg1** [comment]
@laufhannes seems a good idea

**Comment by Jens9891** [comment]
Ok cool. With this solution, I think I could live.
Thx for the fast response

**Comment by grzeg1** [comment]
@Jens9891 for the time being you can probably use a text editor to delete HR data from your file (find and replace)

**Comment by laufhannes** [comment]
For reference: #1128

**Comment by grzeg1** [comment]
Moved to #1333
