### ISSUE TITLE
Cache for jd intensity is not updated

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1282]
Already mentioned as todo: https://github.com/Runalyze/Runalyze/blob/master/plugin/RunalyzePluginPanel_Rechenspiele/class.RunalyzePluginPanel_Rechenspiele.php#L151-L159

Activity related cache updates are done by inserter/updater model classes. To get this working we would have to check if the plugin exists, is enabled and shows jd points. I'm not sure if it's worth it.

**Comment by grzeg1** [comment]
cache is evil ;)

**Comment by grzeg1** [comment]
proposed solution: whenever activity within last 2 weeks is updated - clear JD cache
if not possible - whenever any activity is updated - clear jd cache
