### ISSUE TITLE
Configuration: validate route color

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1286]
Route won't be visible if user enters an invalid color.

**Comment by grzeg1** [comment]
proposed solution: use something like this: https://github.com/PitPik/tinyColorPicker

**Comment by laufhannes** [comment]
There's `<input type="color" ...` nowadays, but no support by IE or iOS Safarai (see https://caniuse.com/#feat=input-color). However, it's questionable whether we need this configuration value at all.

**Comment by mipapo** [comment]
We remove this option from our config as it will conflict with future design updates. And it's rarely used
