### ISSUE TITLE
Import Garmin Forerunner 15

### ISSUE THREAD

**Issue by campino2k** [Runalyze/Runalyze#1288]
Ich habe Runalyze auf meinem localhost installiert. Leider funktioniert der Import von der Forerunner weder über den Garmin Connector (Uhr wird gefunden, nach 2 Minuten immer noch keine Daten). Das Problem ist aber vermutlich kein Problem von Runalyze, sondern von dem Communicator selbst. Soweit ich das weiß will Garmin das Teil nach Möglichkeit für den eigenen Walled Garden abschaffen.

Aber: Von der Uhr bekomme ich die .FIT-Dateien nicht importiert.
```
Fatal error: Uncaught exception 'RuntimeException' with message 'Reading *.fit-file failed. First line was "Der Befehl "LANG" ist entweder falsch geschrieben oder".' in C:\Users\[user]\xampp\htdocs\runalyze\inc\import\filetypes\class.ImporterFiletypeFIT.php:100 Stack trace: 
#0 C:\Users\[user]\xampp\htdocs\runalyze\inc\import\filetypes\class.ImporterFiletypeFIT.php(76): ImporterFiletypeFIT->readFirstLine() 
#1 C:\Users\[user]\xampp\htdocs\runalyze\inc\import\filetypes\class.ImporterFiletypeFIT.php(47): ImporterFiletypeFIT->readFile() #2 C:\Users\[user]\xampp\htdocs\runalyze\inc\import\class.ImporterFactory.php(288): ImporterFiletypeFIT->parseFile('import/files/53...') 
#3 C:\Users\[user]\xampp\htdocs\runalyze\inc\import\class.ImporterFactory.php(277): ImporterFactory->importWithClass('ImporterFiletyp...') 
#4 C:\Users\[user]\xampp\htdocs\runalyze\inc\import\class.ImporterFactory.php(70): ImporterFactory->constructForFilename('539I0113.FIT') 
#5 C:\Users\[user]\xampp\htdocs\runalyze\inc\import\class.ImporterWindow.php(98): ImporterFac in C:\Users\[user]\xampp\htdocs\runalyze\inc\import\filetypes\class.ImporterFiletypeFIT.php on line 100
```

Ich habe mich testweise mal bei user.runalyze.de angemeldet und da funktioniert zumindest der Upload direkt von der Uhr (Communicator geht auch da nicht...)

**Comment by laufhannes** [comment]
Mir scheint der Perl-Befehl funktioniert in seiner bisherigen Art und Weise nicht auf Windows-Systemen. Wenn du in https://github.com/Runalyze/Runalyze/blob/master/inc/system/shell/class.PerlCommand.php#L66 das `LANG=C` entfernst sollte der Import klappen.

Schau aber bitte einmal, ob die Werte ansonsten soweit stimmen. Ich bin mir spontan aber auch nicht sicher, ob der Befehl auf Linux/MacOS notwendig ist.

**Comment by campino2k** [comment]
Nein, das hilft leider auch nicht, dann kommt folgendes:

```
Fatal error: Uncaught exception 'RuntimeException' with message 'Reading *.fit-file failed. First line was "Das System kann den angegebe"nen Pfad nicht finden.".' in C:\Users\cjung\xampp\htdocs\runalyze\inc\import\filetypes\class.ImporterFiletypeFIT.php:100 Stack trace: 
#0 C:\Users\[user]\xampp\htdocs\runalyze\inc\import\filetypes\class.ImporterFiletypeFIT.php(76): ImporterFiletypeFIT->readFirstLine() 
#1 C:\Users\[user]\xampp\htdocs\runalyze\inc\import\filetypes\class.ImporterFiletypeFIT.php(47): ImporterFiletypeFIT->readFile() 
#2 C:\Users\[user]\xampp\htdocs\runalyze\inc\import\class.ImporterFactory.php(288): ImporterFiletypeFIT->parseFile('import/files/53...') 
#3 C:\Users\[user]\xampp\htdocs\runalyze\inc\import\class.ImporterFactory.php(277): ImporterFactory->importWithClass('ImporterFiletyp...') 
#4 C:\Users\[user]\xampp\htdocs\runalyze\inc\import\class.ImporterFactory.php(70): ImporterFactory->constructForFilename('539I0113.FIT') 
#5 C:\Users\[user]\xampp\htdocs\runalyze\inc\import\class.ImporterWindow.php(98): ImporterFactory in C:\Users\[user]\xampp\htdocs\runalyze\inc\import\filetypes\class.ImporterFiletypeFIT.php on line 100
```

Könnte es sein, dass es daran liegt, dass Perl bei mir nicht installiert ist? (Ich hab da jetzt keins installiert, da in den Requirements nur was von PHP und MySQL steht. Sonst hau ich mir das auf den Raspberry oder so und gut ist... :)

**Comment by laufhannes** [comment]
Richtig, ohne installiertes Perl funktioniert der *.fit-Import nicht. Und wenn, muss der Pfad in https://github.com/Runalyze/Runalyze/blob/master/inc/system/shell/class.PerlCommand.php#L20 entsprechend gesetzt sein.

Je nachdem welche XAMPP-Version installiert ist, ist da aber evtl. Perl bereits mit dabei. Das wäre dann vermutlich `C:\Users\[user]\xampp\perl\bin\perl` als Pfad.

**Comment by campino2k** [comment]
Also: Vielen Dank für den super Support: Stand der Dinge: ich hatte mal neulich meinen XAMPP komplett abgeschossen. Dabei hab ich mein Perl scheinbar gelöscht. Aber ich werde das ganze dann einfach gleich auf ein ordentliches Serversystem umziehen ;)
--
Läuft auf dem Uberspace wie ne 1. Danke!
