### ISSUE TITLE
Technical decisions needed

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1295]
- [x] PHP version support - can it be >=5.4
- [ ] definie minimum resolution - everything below may not look right
- [ ] define optimal resolution - everything should look best at this one
- [x] building project - can we get rid of compiled files in git repo, instead use releases + nightly builds

probably more to come....

**Comment by laufhannes** [comment]
For php version: I've updated my system (php 5.6.3), so I won't veto anymore ;)

For resolutions: 1280px and 1366px have each around 15 % (current Piwik stats) and 1920px has 20 %. There are a lot of resolutions in between and nearly no desktop sizes below, but 12 % smartphones and 5 % tablets.

**Comment by grzeg1** [comment]
Common denominator between current debian, centos, xampp, ubuntu seems to be PHP 5.4+MySQL 5.5 - that requirement should cause no trouble for anybody.

**Comment by grzeg1** [comment]
Just checked on my Android phone - 720x1280. It's rather unusable. It's quite usable though with horizontal orientation  which becomes 1280x720.
It could be usable if there were:
- a few bigger buttons for mobile (e.g. calendar week change)
- some kind of liquid layout for training view (so it behaves like right-side panels)
There could be a "list of basic functions" that should be accessible on mobile screens, everything else can be a bit cumbersome. Like: navigate to previous weeks, choose training to display, display basic training details, display last weeks' statistics, display current training load.
For dataset there could be another option for each column 'hide for small displays'.

**Comment by uk3** [comment]
Just a remark here regarding PHP Versions: Hosted systems are not always bleeding edge and as a user you can not really influence that. Mine is still 5.3.3 and I wonder how many others not that current are out there.

**Comment by grzeg1** [comment]
@uk3 I can't believe it's not upgradeable. Even PHP 5.4 is going to be unsupported in 5 months.
