### ISSUE TITLE
Elevation correction not possible if no original data is there

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1299]
I can't find any link to 'correct' (or better: add) elevation based on srtm files if there is no original data.

**Comment by grzeg1** [comment]
Related to: #1334

**Comment by laufhannes** [comment]
It should be enough to check the following in [TrainingFormular::initElevationCorrectionFieldset()](https://github.com/Runalyze/Runalyze/blob/master/inc/training/class.TrainingFormular.php):
```
if ($this->dataObject->get('routeid')) {
	$Route = Context::Factory()->route($this->dataObject->get('routeid'));

	if ($Route->hasPositionData() && !$Route->hasCorrectedElevations()) {
		// ...
	}
}
```
