### ISSUE TITLE
Import zipped files

### ISSUE THREAD

**Issue by mzielinskim** [Runalyze/Runalyze#1302]
I upload all Trainings automatically to Germin Connect (Onlineplattform). There i can download the Activity in different Formats - when i Chose "Save as original" to get the *.fit file garmin puts that FIT-File into a ZIP-Container which contains the *.fit-File.

It would be great if i would have to unzip it by myself but runalyze schould unzip it by itself and the import the contained FIT-File

**Comment by laufhannes** [comment]
I guess that's a good idea for all extensions, not only for Garmin. We just have to make sure to only save files with a supported extension.

**Comment by mipapo** [comment]
Some thoughts:
Check how many files are in the zip -> If too many -> queue  
Think about files which can't be imported - Feedback for the user with file names. (Zip files again with a download?)
