### ISSUE TITLE
Recovery time

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1316]
How long is the time to be completely recovered (e.g. for a competition)

**Comment by grzeg1** [comment]
Actually I've been working on this one today ;)

**Comment by laufhannes** [comment]
I'm very interested on the ideas behind that! Garmin's recommendations are still confusing to me.

You're probably working on it based on trimp?

**Comment by grzeg1** [comment]
Just made a PR. I calculated number of days for reaching TSB=0. Values seem quite similar to what my Polar watch is showing. I've been comparing them before using form chart (looking for a place where absolute CTL and ATL charts cross) After all that's what TSB model is goo for - tracking recovery.

**Comment by laufhannes** [comment]
I'll have a look at my values the next days. My Fenix shows most of the time values between 10 and 20 hours and so far never more than 72 hours. - Maybe I haven't trained hard enough since last autumn.

**Comment by laufhannes** [comment]
Fixed since 2634d6c8e20a153a28a142ec4094754796e758a4.
