### ISSUE TITLE
Records: personal best splits

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1318]
Over distance and time
- 1 hour
- 2 hours
- 1km
- 1 mile
- 3km
- 3 miles
- 5 km
- 10km
- halfmarathon
- ...

Notation: 
- Before we think about this: don't forget to think about other sport types and their record types. 
- think about how to make these things flexible
(survey 2015 - 168, 184)

**Comment by grzeg1** [comment]
Some work done in #1151

**Comment by laufhannes** [comment]
This issue should be handled in #1688.
