### ISSUE TITLE
Check on data from Polar RC3

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1320]
"Ich wünsche mir die Möglicheit eines kompletten Uploads sämtlicher Daten meiner GPS-Uhr.
.GPX: es werden keine detaillierten Trainingsdaten (Pulsverlauf, Runden- bzw. Kilometerzwischenzeiten) übernommen.
.XML: detaillierte Daten vorhanden, jedoch ohne Streckenaufzeichnung
"

(survey 2015 - 205)

**Comment by laufhannes** [comment]
Do you have his name/email? Heart rate should be imported if properly saved and rounds are simply not saved.

**Comment by mipapo** [comment]
Because of missing data and contact possibilities closed
