### ISSUE TITLE
Language selection on shared pages

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1324]
Currently there is no chance to change the language on these pages

**Comment by grzeg1** [comment]
We need to gather all use cases first to make this right. Currently probably using ?lang= would do.

**Comment by mipapo** [comment]
True. And we have to add a detection for the languages

**Comment by laufhannes** [comment]
There is `Language::guessLanguage()`.

**Comment by grzeg1** [comment]
So back to square 1: we need use cases/issues to solve.
