### ISSUE TITLE
ATL/CTL explanation is wrong

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1332]
Explanations for ATL/CTL mention them as "average value/day". It should be stated that this is done with an exponential moving average.

**Comment by grzeg1** [comment]
For sure `Runalyze displays the relation to your present maximum, since the values themselves do not tell much.` should go. The other sentence `ATL and CTL are averaged values over a given time range.` is technically correct, it does not say arithmetic mean is used, just some kind of averaging.
