### ISSUE TITLE
Users must login: get rid of accountid=0 user with no account

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1335]
There's whole lot of unnecessary logic for handling single-user installations. These installations cannot be easily migrated to multi-user either.

Proposed solution: 
- get rid of accountid=0 logic
- always make single user a 'real user'
- change code to auto-login user with id=1

**Comment by laufhannes** [comment]
Just as a note: There may exist installations with a real user with accountid=0 and other accounts starting at accountid=1 (as a result of a previous migration from single- to multi-user).

**Comment by grzeg1** [comment]
But then looking at the code this data should be inaccessible, so we could just ignore it?

**Comment by laufhannes** [comment]
Why should it be inaccessible? `accountid = 0` is a valid result of account data in SessionAccountHandler. Of course that's not what it should be - but these cases exist.

It's just needed that this migration (transferring all data from 0 to 1) must not be done automatically as it may break.

**Comment by grzeg1** [comment]
I meant if you have single install with id=0 there's no account, so to migrate to multi-user you need to create account (db insert) to be able to access your data. If you knew how to do it, you will manage.

For installs with only `accountid=0` data, migrate it to `accountid=1` and create account with default user data.

**Comment by laufhannes** [comment]
Okay, you're right: Migration is only needed if there is no data in `runalyze_account`.

**Comment by mipapo** [comment]
Habe ich als "depracated" in den Blogpost mit aufgenommen, sodass man das in Zukunft entfernen kann

**Comment by laufhannes** [comment]
`USER_MUST_LOGIN` can stay, right? In that case, we just use `accountid = 1` instead of 0, right?

**Comment by grzeg1** [comment]
If it must stay, it can stay. But on the other hand: one can use 'remember me' option and maybe some expiration dates can be tweaked so it's not needed any more - you log in once, save password in browser and it almost never prompts you to log in again. So ditching it would be one option less to maintain.

**Comment by laufhannes** [comment]
Okay, we'll remove that one as well.

**Comment by grzeg1** [comment]
"Remember me" option does not work for me (`autologin_hash` column always empty) and I can't seem to locate the part of the code that would set it to non-empty value....

**Comment by laufhannes** [comment]
At least there is something in the code (but I never use it): [class.SessionAccountHandler.php#L264-L283](https://github.com/Runalyze/Runalyze/blob/master/inc/system/class.SessionAccountHandler.php#L264-L283)

**Comment by laufhannes** [comment]
It did work for me once. The `autologin_hash` was set correctly but the first login via (autologin) cookie caused the deletion of the hash, as no `$_POST['autologin']` is set.

Can you verify that it does work for you now?

**Comment by grzeg1** [comment]
seems to work now :)
