### ISSUE TITLE
Problems while changing time on summertime-change

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1343]
Open an activity and set its date to 29.03.2015 and change afterwards its daytime. Daytime will always be saved as one hour ahead (e.g. 10:20 will end up as 11:20).

**Comment by mipapo** [comment]
Were you able to relate it? - Cache?

**Comment by laufhannes** [comment]
Yes. Just try it. It still happens if I edit an activity from yesterday.

**Comment by mipapo** [comment]
Oh, yes i was able to relate it too. Date/time on the server is right...
