### ISSUE TITLE
Weekly chart - last 12 months - shows last year's April data as this year's

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1345]
(first week of last year's April is show on the right)
Probably something with wrong with dates and end of the month this week?

**Comment by laufhannes** [comment]
Is it possible that this was wrong the whole time? Weekly chart uses the following to determine indexes:
```php
((WEEK(FROM_UNIXTIME(`time`),1) + '.$this->timerEnd.' - '.date('W').' - 1)%'.$this->timerEnd.' + 1)
```

Which is for week 14 and a 52-weeks year back: `(week + 52 - 14 -1)%52 + 1`. 
The issue occurs if data with same week number from both years are fetched. Thus, using the following should solve the problem:
```php
protected function beginningOfLast12Months() {
	return strtotime("monday -".($this->timerEnd - 1)." weeks");
}
```
(so far there's no `- 1`)

**Comment by laufhannes** [comment]
This fix is included here: https://github.com/Runalyze/Runalyze/commit/73f90e8ec7d2b1a0345776b478484ef18008f4b5#diff-a7f6e156d06d8af21523a71dfdd15237.
