### ISSUE TITLE
Training points - should show value for 7 days not for current week

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1346]
Notice from a onlineversion user:
Training points - should show value for 7 days not for current week

Prognose wrong?
Example:
this week:45
last week :12
Prognose:210

**Comment by laufhannes** [comment]
Only as option (in plugin configuration). This value is an alternative to weekly kilometers and should be based on same intervals.

Concerning prognosis: Prognosis has nothing to do with last weeks value. If I run for 30 points on monday prognosis will be calculated as 7*30 = 210. (And I guess it uses exact time, i.e. 45 points on tuesday 12:00 result in 210 as prognosis.)

**Comment by laufhannes** [comment]
Training points are removed in v4.0.
