### ISSUE TITLE
Disallow spaces in usernames

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1349]
Don't think it's a good idea to allow something like this? 
Technically there is no problem with allowing this, but i don't know any other platform, which allows using spaces in usernames.

**Comment by laufhannes** [comment]
+1

**Comment by laufhannes** [comment]
Note: We had a discussion about usernames in #1236. But for this issue it does not matter whether we call it 'username' or 'alias'. In both cases this value will be used in user's public url (../shared/username/) and should not be changeable.

I'd keep our rules simple: 6 to 32 characters, [A-Z], [a-z], [0-9] and some special characters [-_.]? Maybe only a-Z as first character? Any other suggestions? Do we need to disallow any special case, e.g. no two successive [-_.]?
