### ISSUE TITLE
Cache problem training points

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1350]
"Seit ich auf 2.0 gewechselt habe, werden die Trainingspunkte der aktuellen Woche nach dem Import einer neuen Einheit nur aktualisiert, wenn ich die Funktion "Cache leeren" benutze. Ist das so geplant?"

**Comment by laufhannes** [comment]
Fixed since d871169ba8c8aa30dea7cf693c454b6a279b3242 in v2.0.1.
