### ISSUE TITLE
Übersetzung im Formular "Strecke" hieß früher "Bahn"

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1351]
- Englische Übersetzung prüfen "Route"
Route wird an vielen orten verwenet und ist definitiv die falsche Übersetzung für Bahn
Anschließend deutsche Übersetzung ändern.

**Comment by laufhannes** [comment]
Current translation (in Weblate, not in v2.0) of 'Track' is 'Bahn'.
