### ISSUE TITLE
Harden default sport types & improvements

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1357]
Sports like Running, Bycle (Road Race) and Swim should be:
- not deletable
- some default settings like short should be disabled
- Running is the "Running sport" (General setting)
(Yeah i know  - currently without this value Runalyze will break in some parts)

**Comment by laufhannes** [comment]
If someone is only running and never ever cycling or swimming: Why shouldn't he be able to delete the other sport types?

If someone is cycling every day to work (and back): Why shouldn't he be able to use short notation for it?

And how do you want to achieve this? These three sport types must be configurable at least in terms of icon, calories, avg. hr and pace unit.

**Comment by mipapo** [comment]
Okay, maybe it's fine, when just Running is not deleteable..

Same for the second. It was just an example

I don't know to which one your last statement belong to

**Comment by grzeg1** [comment]
I was going to ask same question the other way. 
For me basic sports are somewhat like icons - they're options you don't delete.
So names, icons and ids should not be editable. Names should be probably coded for translation.
Running sport ID should be configured internally when creating an account. 
All other = user-created sports should be editable with names and deletable.
OT: I'm also not sure why we need Long Run type.

**Comment by laufhannes** [comment]
Again my primary question: How do you want to implement that? As long as there are "some" editable values, it's the easiest way to keep our current table/structure.

If you want to prevent users from misusing (and misunderstanding) some configuration values:
 - ID for running is set while creating an account. I could agree on "fixing" that and disabling delete option for running.
 - ID for competition type should go into types configuration. I think that is already mentioned somewhere.
 - ID for long runs: Yes, I think that is not used anymore.
 - Checkbox for "short": This seems to confuse users all the time. A select box (Calendar view: "Complete row" or "Only icon") would be better.

**Comment by laufhannes** [comment]
The above todos are now done since f3477b1356bc4ca3e6ca130f897abc970be5cb16.

**Comment by laufhannes** [comment]
I'll close this one.

If we need to "fix" more sport types due to some analyses that do only work with a specific sport type (e.g. for swimming to analyze strokes etc.), please open a new issue and we can discuss whether to add another hidden configuration setting as it's currently done for `Configuration::General()->runningSport()` (previously `CONF_RUNNINGSPORT`).
