### ISSUE TITLE
Missing require_once 'inc/system/class.Request.php'; in update.php

### ISSUE THREAD

**Issue by genlinut** [Runalyze/Runalyze#1360]
Hi,

I recently tried to update my Runalyze 1.5 installation to the actual master, but got this error (wasn't readable in browser, I had to use the source view from firefox)
```html
<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="stylesheet" href="lib/less/runalyze-style.css">
	<link rel="shortcut icon" type="image/x-icon" href="img/favicon.ico">
                <link rel="alternate" href="<br />
<b>Fatal error</b>:  Class 'Request' not found in <b>/opt/users/www/genrob73web51/html/runalyze/inc/system/class.System.php</b> on line <b>86</b><br />
```

I added 
```php
require_once 'inc/system/class.Request.php';
```
before
```php
require_once 'inc/system/class.System.php';
```
in the update.php file. 

Finally the update process was successful.

**Comment by laufhannes** [comment]
Wondered why there were no problems while releasing v2.0 and why I could not reproduce this bug: it's only a few days old (a7f6153f61f5da70b1fba73d97fe5aee5ca165c0).
