### ISSUE TITLE
OpenCycleMap

### ISSUE THREAD

**Issue by uk3** [Runalyze/Runalyze#1361]
Hallo,

Irgendwann scheint bei den Karten die OpenCycleMap verloren gegangen zu sein. Als Radfahrer fand ich die sehr praktisch - wäre es möglich die wieder zu aktivieren?

lG uk3

**Comment by laufhannes** [comment]
Du musst bei der Auswahl lediglich scrollen. Zugegeben - ich habe das gerade auch nur gesehen, weil im Code deutlich mehr Layer aufgelistet waren. Da müsste man überlegen, wie man das visuell besser deutlich macht:
![bildschirmfoto 2015-04-11 um 22 20 22](https://cloud.githubusercontent.com/assets/8313118/7103130/1c279d3c-e099-11e4-8df0-f801b2841596.png)

**Comment by uk3** [comment]
Hallo,

Das ist mir nicht aufgefallen. Danke für den Tipp.

LG uk
