### ISSUE TITLE
inc/core/View/Activity/Plot/Series/Pace.php

### ISSUE THREAD

**Issue by uk3** [Runalyze/Runalyze#1362]
Hallo,

keine Ahnung ob es an meiner PHP version liegt oder an was anderem, nur im aktuellen git bekomme ich folgende Fehlermeldung:  

`PHP Parse error:  syntax error, unexpected '[' in /html/runalyze/inc/core/View/Activity/Plot/Series/Pace.php on line 210`

**Comment by laufhannes** [comment]
Liegt an der PHP-Version. Der Support für 5.3 wird mit v2.1 gestrichen (siehe auch #1295).

**Comment by uk3** [comment]
Hi,

> On 12 Apr 2015, at 16:56, Hannes <notifications@github.com> wrote:
> 
> Liegt an der PHP-Version. Der Support für 5.3 wird mit v2.1 gestrichen (siehe auch #1295 <https://github.com/Runalyze/Runalyze/issues/1295>).
> 
Alles klar. Ist zwar irgendwie blöd, weil ich auf die PHP-Version bei meinem Hosted System nicht wirklich einen Einfluss habe, aber dann muss ich mir wohl was anderes einfallen lassen.

Danke & lG uk
-- 
Ulrich Kiermayr, Vienna, AT
mail & jabber: ulrich@kiermayr.at

**Comment by laufhannes** [comment]
Keine Möglichkeit via .htaccess auf eine neue Version umzustellen? Zumindest bei größeren Hostern ist ja zumindest das meist möglich. Mipapo/Grzeg haben mich erfolgreich überredet, dass 5.3 bereits seit August nicht mehr mit Sicherheitsupdates versorgt wird.

Und für den Moment: Du könntest sonst den Array-Syntax dort wieder 5.3-konform anpassen. Das ist die einzige "offensichtliche" Änderung von 5.4, die dort bisher genutzt wird.
