### ISSUE TITLE
Language account option

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1365]
- ~~SelectBox Fieldlength in registration~~
- [x] Check if language setting is working

First change in 9329f2cb1f8ba6f9a37fe3648c84a01ea3dfa5db

**Comment by grzeg1** [comment]
What exactly will account language do?

*technical notice: if the code above may be non-working (2-nd checkbox), it should be done in a separate branch until verified, otherwise we'll have semi-working code at all times and it will be hard to release

**Comment by mipapo** [comment]
If the language on the login page is not detected correctly the user will have the correct language if he's logged in.

**Comment by grzeg1** [comment]
Now user can switch to a different language using login page. It will stay this way. Is account language necessary?
Also all field names and messages (wrong password) on login screen are now in autodetected/selected language. It won't be possible with account-settable language.

**Comment by mipapo** [comment]
It is necessary. At least at the registration. I saw several german accounts which got english mails.
And when I'm not totally wrong: for example the sport names are in that language, in which the user has done the registration

**Comment by grzeg1** [comment]
You're right. And the language for registration is chosen when registering. To register you need to understand what you're doing, so you set the language to language you want/understand. E.g. If I got Spanish autodetected, I would not understand it and switch it to English or Polish to register. Then I would log-in using my chosen language.

**Comment by grzeg1** [comment]
It seems if German accounts got English mails, the user was trying to register in English. Maybe it was on purpose?

**Comment by mipapo** [comment]
"To register you need to understand what you're doing"
There will always be some users, which will do it wrong and register themselves 

> It seems if German accounts got English mails, the user was trying to register in English. Maybe it was on purpose?
Maybe, maybe not . I don't see a further need for this discussion. 

This feature was a feature request by several users in the survey. 

You may see this completely different, but we should leave this feature in runalyze..

**Comment by laufhannes** [comment]
Just my two cents: This is not an absolutely necessary feature as one is already able to change language, but it's definitely a nice enhancement to keep language settings without needs for cookies / selection on login page.

--

Maybe we can still move this topic to a seperate branch as there are several topics to think about:
 - priorization of chosen language:
   - not logged in:
     1. get parameter `?lang=...`
     2. cookie
     3. browser language
   - after login:
     1. get parameter `?lang=...` -> update account settings (may happen if a user uses a language menu somewhere)
     2. account settings
     3. no valid value: switch to other case and set that language
 - menus to select language:
  - in general: this should be a select menu as our list of available languages may grow
  - positions:
    - login page
    - shared pages (#1324)
    - user view: account window should be enough

**Comment by mipapo** [comment]
Removed language field from registration in 45bb4a7d00ebb481c1cd0b8565b88185583d5594
Language is set automatically during registration process and for existing users when they log in.
