### ISSUE TITLE
Average gradient for a particular area

### ISSUE THREAD

**Issue by Jens9891** [Runalyze/Runalyze#1369]
If you mark a certain range in the graph, it would be cool, if the average gradient also is displayed and not only the average level.

**Comment by laufhannes** [comment]
See in addition #790.

**Comment by laufhannes** [comment]
This requires a complete `GradientSeries`, which is on hold until we use a butterworth filter or similar for the elevation profile, as the Douglas-Peucker algorithm is a bad choice to determine the gradient.

**Comment by laufhannes** [comment]
Fixed in 3614e5f444c6cbfccde61fc107589aa93c0ab4c6.
