### ISSUE TITLE
Make Runalyze compatible to MariaDB

### ISSUE THREAD

**Issue by diesl** [Runalyze/Runalyze#1370]
Recently I was about to test Runalyze and was puzzled that a basic task like adding a training resulted in a database error. After some investigation I found out the problem is that I use MariaDB as a database backend instead of MySQL, because after switching to a MySQL instance, things worked fine.

Nonetheless I would be happy to see Runalyze being compatible to MariaDB, which is a fork of MySQL.

I suspect the errors are result of a "dirty" SQL statement, which MySQL accepts while MariaDB does not. My used MariaDB version is 10.0.x. For example, the error after trying to add a training:

> PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column 'in_routenet' at row 1' in C:\www\runalyze\inc\system\class.PDOforRunalyze.php:245
Stack trace:
1. C:\www\runalyze\inc\system\class.PDOforRunalyze.php(245): PDO->exec('\n\t\t\tINSERT INTO...')
2. C:\www\runalyze\inc\core\Model\Inserter.php(147): PDOforRunalyze->exec('\n\t\t\tINSERT INTO...')
3. C:\www\runalyze\inc\core\Model\Inserter.php(108): Runalyze\Model\Inserter->runManualInsert()
4. C:\www\runalyze\inc\core\Model\Inserter.php(97): Runalyze\Model\Inserter->runInsert()
5. C:\www\runalyze\inc\training\class.TrainingObject.php(144): Runalyze\Model\Inserter->insert()
6. C:\www\runalyze\inc\html\formular\class.StandardFormular.php(98): TrainingObject->insert()
7. C:\www\runalyze\inc\html\formular\class.StandardFormular.php(72): StandardFormular->checkForSubmit()
8. C:\www\runalyze\inc\html\formular\class.StandardFormular.php(53): StandardFormular->ini in C:\www\runalyze\inc\system\class.PDOforRunalyze.php on line 245

**Comment by laufhannes** [comment]
If anyone has an idea of what's going wrong here ... `in_routenet` is a tinyint field and should not be related to date(time).

I recently got mails from a user who faced the same problem. He was able to resolve it by using sql mode `NO_ZERO_IN_DATE`.

**Comment by diesl** [comment]
The datetime warning led me into the wrong direction too. I think the SQL error description is used in other cases too and should be generalized, but that's another story ;-)

The SQL statement that caused the error uses an empty string as a value for `in_routenet`. A better solution would be to explicitly use `0` instead.

**Comment by laufhannes** [comment]
This will come together with some changes to our database structure (see #1284) and will therefore go into v2.1.
