### ISSUE TITLE
Stride length plot

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1373]
Neues Diagramm: Schrittlänge (oder in das gleiche Diagramm hinzufügen?)
Ggf. auch als neuen "Wert" zum anzeigen (Durchschnittliche Frequenz)

@laufhannes Sollte soetwas dauerthaft als Array in der DB gespeichert werden oder jedes Mal neu berechnet werden?

**Comment by uk3** [comment]
Hallo,

Im Prinizip ist so eine Berechnung auch für das Radfahren interessant. Dort ist das dann die aktuelle Entfaltung, also im Prinzip die Angabe, mit welchem Gang ich gerade Unterwegs war.

> On 21 May 2015, at 18:20, Michael Pohl <notifications@github.com> wrote:
> 
> Neues Diagramm: Schrittlänge (oder in das gleiche Diagramm hinzufügen?)
> Ggf. auch als neuen "Wert" zum anzeigen (Durchschnittliche Frequenz)
> 
> @laufhannes <https://github.com/laufhannes> Sollte soetwas dauerthaft als Array in der DB gespeichert werden oder jedes Mal neu berechnet werden?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/Runalyze/Runalyze/issues/1373>.
> 

lG uk
-- 
Ulrich Kiermayr, Vienna, AT
mail & jabber: ulrich@kiermayr.at

**Comment by laufhannes** [comment]
Meiner Meinung nach:
 - neues Diagramm
 - neuer Wert (Dataset & Boxed Value)
 - Array nicht in DB
