### ISSUE TITLE
Runtastic pause detection - TCX files workaround

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1374]
Runtastic doesn't provide good data for calculating pauses.
The only way to get the "real active time" is to look at the "TotalTimeSeconds". 
I will remove the pause detection for files from Runtastic. The users won't have to edit every single activity they are uploading.

**Comment by grzeg1** [comment]
It was already fixed in #1269 by introducing an option, wasn't it?

**Comment by mipapo** [comment]
@grzeg1 This is not working with Runtastic TCX files

**Comment by mipapo** [comment]
@grzeg1 It just about the following fact: When users import data from Runtastic they want to have the same "Time" they get presented there. They just don't want to edit every activity manually

**Comment by grzeg1** [comment]
When you set the option to not detect pauses, elapsed time should equal total time. Are you sure you set it to not detect pauses?

**Comment by mipapo** [comment]
@grzeg1 Don't you think I know about this option....
Try this file:
https://www.dropbox.com/s/dlfuz02o2qbc70w/runtastic_20150510_1613_Laufen.tcx?dl=0 
It should be 2:30:x "active time" and 2:41 elapsed time. When you import this tcx with activated "pause detetcion" you get 1:34h instead 2:30

**Comment by grzeg1** [comment]
I meant you should import with deactivated pause detection if pauses cannot be detected right. So it seems I don't understand what the new fix does. Does it do another kind of pause detection for Runtastic files?

**Comment by laufhannes** [comment]
It just deactivates pause detection and uses `<TotalTimeSeconds>` as total time and not what the parser reads. The current fix will still create all arrays based on elapsed time (~2:41).

**Comment by laufhannes** [comment]
And yes: `ParserTCXruntasticSingle` should extend `ParserTCXSingle` instead of copy&paste.

**Comment by laufhannes** [comment]
... and pace data has peaks around 300 km/h ...

**Comment by laufhannes** [comment]
Another note: If I import a 'good' tcx file to Runtastic and export it again, this fix will treat it as if it was a 'bad' tcx file from Runtastic and won't detect pauses.

**Comment by mipapo** [comment]
Well - it will be not happen very offen that someone Imports a "good" file and exports this file again
