### ISSUE TITLE
Restore "distance" option in sport configuration

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1378]
decision from our telephone conversation

**Comment by laufhannes** [comment]
The following commit has to be (partly) reverted: 8d8f7896922c97aa1035b80856e49556c2e23af4

In addition, please make sure that distance data will not be imported for those sport types.

**Comment by mipapo** [comment]
Commit in 44c7c6e28377781ce9a02d1bb7bfbb75898dd6c7

**Comment by laufhannes** [comment]
So, the previous changes are successfully reverted. The problem why I removed that option at first still exists.

**use case A**:
 - open form to create activity and set a distance
 - switch to a sport type without distances and save
 - **problem**: distance can't be set in the form but is visible in calendar and activity view
 - **solution**: ignore all distance-related fields while importing/creating an activity (e.g. distance, elevation, pace, cadence, ... and related trackdata arrays)

But **use case B**:
 - import a great activity with gps track and so on
 - accidentally choose a sport type without distance and save
 - **problem**: data will now bew lost if we ignored all these fields

**Three possible solutions**:
  1. keep it as it is: still show distance values
  1. ignore distance values on import
  1. add conditions to all views

**Comment by laufhannes** [comment]
The original issue is fixed and the "old" problem is now covered in #1405.
