### ISSUE TITLE
Event for deleting not activated users after x days

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1380]
MySQL Event for deleting non activated users after 7 days.

**Comment by mipapo** [comment]
Closed in 45bb4a7d00ebb481c1cd0b8565b88185583d5594

**Comment by uk3** [comment]
Hallo,

Dieses Update hat einen Haken v.a. für hosted Installationen:

mysql> SET GLOBAL event_scheduler = ON;
ERROR 1227 (42000): Access denied; you need the SUPER privilege for this operation

Wenn es nicht die eigene Datenbank-Installation ist, ist das u.U. nicht erlaubt. 


> On 04 Jun 2015, at 20:21, Michael Pohl <notifications@github.com> wrote:
> 
> Closed #1380 <https://github.com/Runalyze/Runalyze/issues/1380>.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/Runalyze/Runalyze/issues/1380#event-322786571>.
> 

lG uk
-- 
Ulrich Kiermayr, Vienna, AT
mail & jabber: ulrich@kiermayr.at

**Comment by mipapo** [comment]
Dachte ich mir fast - Dann müssen diejenigen damit leben, dass ggf "Leichen" in der Datenbank sind, wenn sie keine Events ausführen können. 
Ich finde die MySQL Lösungen schöner und zumeist auch peformanter als Cronjobs.

**Comment by uk3** [comment]
Hallo,

> On 05 Jun 2015, at 13:04, Michael Pohl <notifications@github.com> wrote:
> 
> Dachte ich mir fast - Dann müssen diejenigen damit leben, dass ggf "Leichen" in der Datenbank sind, wenn sie keine Events ausführen können. 

Damit kann ich eh gut leben ;-)

> Ich finde die MySQL Lösungen schöner und zumeist auch peformanter als Cronjobs.
> 
> 

Das sicher. 

wenn 1. der Fehler bei der Installation abgefagen wird und 2. ein manueller cleanup möglich ist (bei den Tools irgendwo) reicht das aber sicher auch vollkommen aus.

lG uk
-- 
Ulrich Kiermayr, Vienna, AT
mail & jabber: ulrich@kiermayr.at

**Comment by mipapo** [comment]
TODO:
- [ ] Check with "IF clause" if event scheduler can be activated / or is activated

**Comment by mipapo** [comment]
Moved to an extra SQL file in 5bcba99c5aee6829cf0f68debfc642e4f8c6028a
