### ISSUE TITLE
Import-Bug *.fit under Windows

### ISSUE THREAD

**Issue by alex1606** [Runalyze/Runalyze#1389]
Fatal-Error beim Import von .fit-Dateien einer Garmin Forerunner 220. 
Fehlermeldung:
Fatal error: Uncaught exception 'RuntimeException' with message 'Reading *.fit-file failed. First line was "'LANG' is not recognized as an internal or external command,".' in C:\xampp\htdocs\runalyze\inc\import\filetypes\class.ImporterFiletypeFIT.php:100 Stack trace: #0 C:\xampp\htdocs\runalyze\inc\import\filetypes\class.ImporterFiletypeFIT.php(76): ImporterFiletypeFIT->readFirstLine() #1 C:\xampp\htdocs\runalyze\inc\import\filetypes\class.ImporterFiletypeFIT.php(47): ImporterFiletypeFIT->readFile() #2 C:\xampp\htdocs\runalyze\inc\import\class.ImporterFactory.php(288): ImporterFiletypeFIT->parseFile('import/files/78...') #3 C:\xampp\htdocs\runalyze\inc\import\class.ImporterFactory.php(277): ImporterFactory->importWithClass('ImporterFiletyp...') #4 C:\xampp\htdocs\runalyze\inc\import\class.ImporterFactory.php(70): ImporterFactory->constructForFilename('785195772.fit') #5 C:\xampp\htdocs\runalyze\inc\import\class.ImporterWindow.php(98): ImporterFactory->__construct('785195772.fit') #6 C:\xampp\htdocs\runalyze\inc\import\cla in C:\xampp\htdocs\runalyze\inc\import\filetypes\class.ImporterFiletypeFIT.php on line 100

**Comment by laufhannes** [comment]
Wenn du in https://github.com/Runalyze/Runalyze/blob/support/2.0.x/inc/system/shell/class.PerlCommand.php#L66 das "LANG=C " entfernst, sollte das auch unter Windows klappen.
