### ISSUE TITLE
Use bower/gulp

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1393]
As already done in the symfony-branch. We will already use the `web/` directory for all accessible assets.

**Comment by campino2k** [comment]
You can merge my work from https://github.com/campino2k/Runalyze/tree/feature/fe-refactor-structure or just take that as inspiration. 

My work-life-balance the past month has gotten out of control somehow, which forced me to leave some things left undone :( Sorry for that.

**Comment by laufhannes** [comment]
No problem! I already used your branch as inspiration for our [feature/runalyze-with-symfony](https://github.com/Runalyze/Runalyze/tree/feature/runalyze-with-symfony) branch, were bower and grunt are used.

**Comment by laufhannes** [comment]
This is introduced in 26c37d42ae79bf725eea40d79873e62e66f2de27 in our [feature/runalyze-with-symfony](https://github.com/Runalyze/Runalyze/tree/feature/runalyze-with-symfony) branch and be considered as closed with 60f2228e5410f76e443416457610328d84abd6db as soon as the branch is merged into master.

**Comment by mipapo** [comment]
The feature/runalyze-with-symfony branch has been discontinued

**Comment by laufhannes** [comment]
... but it's in the feature/LoginController branch

**Comment by laufhannes** [comment]
... and now it's in the feature/micro-symfony branch (and we use gulp instead of grunt). I'm optimistic that it will reach the master this time.
