### ISSUE TITLE
Stressbalance: color error mode

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1394]
"Mein Problem, welches auch viele andere Männer (Frauen sind sehr selten betroffen) haben, ich kann beim Balken nicht unterscheiden ob er rot oder grün ist. Dies ist auch bei anderen Grafiken der Fall. Wäre es möglich einen Fehlfarben-Modus zu implementieren, wie z.B. hier: http://www.autobahn.nrw.de/nrw.html
"

**Comment by laufhannes** [comment]
Duplicate of the more general #2273.
