### ISSUE TITLE
Weblate - can't save translations.

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1402]
Server Error

The server had serious problems while serving your request. We've just sent our trained monkeys to fix the issue.

**Comment by mipapo** [comment]
Weblate is §%*§*%§&"&*

**Comment by mipapo** [comment]
Seems to work now. Permissions were wrong. 
FYI: The automated script is disabled, because the redesign branch made problems with the master branch. 
Will be updated manually in the future.

**Comment by mipapo** [comment]
Please check

**Comment by grzeg1** [comment]
It seems ok now.
