### ISSUE TITLE
Accountreset with automatically created json backup

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1414]
I often see users who delete their account, because they had trouble with importing activities (double entries or other problems). Then they create a new account...
There should be a way to reset the account. But for safety reason a automatic backup should be created (or reset just after a confirmation mail).

(Another point would be to easily delete activites through the search. (Maybe add a function "Look for double entries)

**Comment by laufhannes** [comment]
Probably the same as #634
