### ISSUE TITLE
Calculate average of hf for training types

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1416]
"die durchschnittliche HF die dort eingetragen ist, woher kommen die Werte? Die sehen aus wie Schätzwerte. Warum können da nicht "einfach" die durchschnittlichen Werte des letzten Jahres/der letzten hundert Trainings/die letzten 10 verwertbaren Training pro Trainingsart (LL, TDL, etc.) eingetragen werden? Get it? Beispiel: Meine letzten zehn TDL hatten im Durchschnitt eine HF von 161, dieser Wert kann dann auch ruhig für das elfte TDL Training genommen werden, wenn ich mal keinen HF-Gurt dabei habe. Die Deluxe-Version wäre es natürlich diese letzten zehn Werte mit der Pace, den Höhenmetern und vielleicht sogar der eingetragenen Temperatur zu koppeln, Korrelationen festzustellen und für das elfte Training dürfte ein guter geschätzter Durchschnittspuls errechnet werde =) Zu viel des guten? Wahrscheinlich ;)"
via Philipp

**Comment by laufhannes** [comment]
"Warum nicht einfach ... ?" - Weil zu dem Zeitpunkt, wo die Daten gesetzt werden, noch überhaupt keine Trainingsdaten vorhanden sind. Die Daten werden ohnehin nur für die Berechnung der Trimp-Werte verwendet. Und wer korrekte Werte haben will, muss mit Brustgurt laufen. Punkt.
