### ISSUE TITLE
Analysis / by Distance

### ISSUE THREAD

**Issue by uk3** [Runalyze/Runalyze#1417]
Hallo,

Beim Analysemodul funktioniert die analyse 'by distance' nicht (zeigt das selbe wie 'by percent'). by time hingegen funktioniert. 
(letztes origin/master aus dem git).

lG uk3

**Comment by mipapo** [comment]
![bildschirmfoto vom 2015-07-13 15 19 13](https://cloud.githubusercontent.com/assets/2135076/8650440/23911fe4-2973-11e5-804a-411fb5452b18.png)
Also bei mir ist nur das Problem, dass ich "Nach Distanz" zwei mal sehe. Das eine (untere) verlinkt richtig. Das andere nicht

**Comment by uk3** [comment]
Hallo,

Ich hab by distance nur einmal (und das falsch):




> On 13 Jul 2015, at 15:24, Michael Pohl <notifications@github.com> wrote:
> 
> 
> Also bei mir ist nur das Problem, dass ich "Nach Distanz" zwei mal sehe. Das eine (untere) verlinkt richtig. Das andere nicht
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/Runalyze/Runalyze/issues/1417#issuecomment-120925449>.
> 

-- 
Ulrich Kiermayr, Vienna, AT
mail & jabber: ulrich@kiermayr.at <mailto:ulrich@kiermayr.at>

**Comment by laufhannes** [comment]
Der doppelte Eintrag kommt durch den Merge bzw. Revert von "usesDistance()":
https://github.com/Runalyze/Runalyze/blob/master/plugin/RunalyzePluginStat_Analyse/class.RunalyzePluginStat_Analyse.php#L101-L106

Bei @uk3 sollte der Link daher vermutlich gar nicht erscheinen, da die Sportart keine Distanz "hat".

**Comment by uk3** [comment]
Hallo,

> Bei @uk3 <https://github.com/uk3> sollte der Link daher vermutlich gar nicht erscheinen, da die Sportart keine Distanz "hat”.

Hmmm, Radfahrer hat aber schon eine Distanz ;-) Und das hat bisher auch immer funktioniert.

Beim Sport Laufen hab ich übrigens das selbe Problem.

lG uk3

-- 
Ulrich Kiermayr, Vienna, AT
mail & jabber: ulrich@kiermayr.at <mailto:ulrich@kiermayr.at>

**Comment by laufhannes** [comment]
Ich vermute, dass bei dem Revert die Haken bei Distanz verloren gegangen sind und git-Nutzer die manuell wieder nachtragen müssen?

**Comment by uk3** [comment]
Hallo,

Ja, auch das. Aber bei dem Commit war aber auch ein drop von der sql-column dabei. Nachdem ich die händisch wieder hinzugefügt hab, konnte ich die haken auch wieder setzen.

jetzt hab ich by distance doppelt in dem menü, aber bei mir funktionieren beide links…..

Danke jedenfalls für den hint & lG uk3

> On 13 Jul 2015, at 15:32, Hannes <notifications@github.com> wrote:
> 
> Ich vermute, dass bei dem Revert die Haken bei Distanz verloren gegangen sind und git-Nutzer die manuell wieder nachtragen müssen?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/Runalyze/Runalyze/issues/1417#issuecomment-120927444>.
> 

-- 
Ulrich Kiermayr, Vienna, AT
mail & jabber: ulrich@kiermayr.at <mailto:ulrich@kiermayr.at>
