### ISSUE TITLE
Statistics plugins: show other dataset values as well

### ISSUE THREAD

**Issue by mdosch** [Runalyze/Runalyze#1420]
I'm missing the altitude in comparison of years. It would be great if you could add this feature. I'm sorry if this is already possible but I didn't find any setting for this.

**Comment by laufhannes** [comment]
You talk about the 'Statistics' plugin, right?

I guess we should show all values that are used for the summary in the calendar view, i.e. all fields of the dataset which are chcked for 'summary'. We only have to take care for empty rows, e.g. vdot / jd points etc. will be empty for sport types other than running.

**Comment by mdosch** [comment]
You're right. I forgot to mention that I'm talking about the "Statistics" plugin.
