### ISSUE TITLE
Statistics: Why don't show negative change?

### ISSUE THREAD

**Issue by mdosch** [Runalyze/Runalyze#1423]
Affected versions: 2.0.3; 2.1

In the Statistics you show the improvement per week, e.g.:

Week 29: 5km
Week 30: 10km +100%
Week 31: 15km + 50%
Week 32: 10km
Week 33: 15km +50%

But you don't show negative values if your training amount is decreasing. Is this wanted? If yes, why?
I'd suggest something like this:

Week 29: 5km
Week 30: 10km +100%
Week 31: 15km + 50%
Week 32: 10km -33%
Week 33: 15km +50%

**Comment by laufhannes** [comment]
The positive change is primarily shown because of the general recommendation of not increasing the weekly distance by more than 10 percent.

But I don't see a reason to not show the negative change as well (with the current design, it will propably be a light grey and thus not a problem for the above aim).

**Comment by mdosch** [comment]
Ok, I had recently +521%... Oo
But I use runalyze for cycling so it's easier to make a lot of distance and the training amount is more dependent on time as on power. ;)

But you impressed me with this very fast reply. :)

**Comment by laufhannes** [comment]
I had +135 % just two weeks ago, so even for running that's only a thumb rule.

And as we released v2.1, we have to be fast currently. There may be something important ;)

**Comment by mdosch** [comment]
What will be displayed if there was no training in the last week? I'd suggest +100%.

**Comment by laufhannes** [comment]
Fixed since 9880f0bcbaa163cc93a870a4bb7bf0a55041d156.
