### ISSUE TITLE
New tool: Trend analysis

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1425]
People may want to see a trend for some values of their activities, e.g. for cadence or pace. We should offer a plot of the trend of these values over time, similar to our current plots for running dynamics but with the date of each activity as x-axes instead of the concrete time series.
- **First step:**
  - [ ] A first and easy implementation could be to show average pace / heart rate / vdot and running dynamics if available for the last six months.
- **Second step:**
  - [ ] In a second step, it'd be perfect to offer a complete search form to limit the results (e.g. only easy runs between 5 and 15 k) and ...
  - [ ] to let the user choose the time range or number of activities to plot (e.g. 'last 6/12 months', 'up to X activities', 'specific time range') and ...
  - [ ] to offer the option to show averages (e.g. plot 'single activities', 'daily/weekly/monthly averages') and ...
  - [ ] to let the user choose which values to plot (checkboxes for all numeric fields, one plot for each)
- **Third step:**
  - [ ] Check whether it's possible to load all relevant data only once and use d3.js then to dynamically access and plot the data.

_Step two/three may become single tickets later on._

**Comment by mipapo** [comment]
+100

**Comment by mipapo** [comment]
@laufhannes  First step is done? ;)

**Comment by laufhannes** [comment]
I've added the remaining points to our internal todo list.
