### ISSUE TITLE
Use overflow-y: auto; instead of 'scroll' (e.g. for .training-row-info)

### ISSUE THREAD

**Issue by flrns** [Runalyze/Runalyze#1427]
In the activity view, the fields like Overview, Running Dynamics, Miscellaneous have unnecessary vertical scrollbars. This is even more odd when activating "show rows in full height" in the configuration, as it also happens for the splits then.

An easy fix would be to change overflow-y: scroll; to overflow-y: auto; in the CSS for .training-row-info. The only difference between these two is that the first one always show the scrollbars while the second one only does so if the content doesn't fit the box.

Glancing into the stylesheet, there are some other classes with overflow-y: scroll, so this might affect other views as well, but I'm not sure where these are in the frontend and whether the scrollbars are wanted there for layouting reasons.

**Comment by laufhannes** [comment]
I guess that's what the official documentation states for overflow? On a Mac, there are only scrollbars while scrolling and with a Firefox (v38) on Windows, I don't see unwanted scrollbars either. But I guess there's no drawback with switching to 'auto'.

Looking at our stylesheet, I found the following cases where `overflow(-x/y): scroll` is used (in addition to `.training-row-info`:
 - `#widget-calendar` the calendar to choose a specific time range for the calendar view
 - `#data-browser-container` the calendar view itself (i.e. the table for current activities)
 - `#statistics-container` appears once as '#statistics-container' and once as 'statistics-containerr' in the stylesheet but it's really a '.statistics-container' and that's the div for statistic plugins
 - `#ajax, #ajax-outer, #ajax.fullscreen, #ajax-navigation` for the overlay, the navigation is used in the multieditor
 - `.leaflet-control-layers-list` list of possible layers for a map
 - `code, textarea.code` e.g. code blocks in the installer

So, feel free to change that and have a short look at the examples if they work as expected.

**Comment by laufhannes** [comment]
Closed with a800693.
