### ISSUE TITLE
Dataset column labels should have separate (shorter) descriptions.

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1436]
Like "temp" for "Temperature" or "JDI" for "JD Intensity" or "type" for "Training type" or just "" for "VDOT Icon".
Tooltips should stay the same.

**Comment by laufhannes** [comment]
Shouldn't users who know what 'JDI' is already know what each column means, such that they won't need labels either? And where is the difference between showing 'temp' or 'Temper...' (what is currently shown for me).

**Comment by grzeg1** [comment]
Cut-off descriptions look messy, especially for narrower columns where labels almost touch each other. They may be even more messy in languages other than English.
