### ISSUE TITLE
Public link isn't working under subdomain

### ISSUE THREAD

**Issue by mdosch** [Runalyze/Runalyze#1439]
Trying to open the public link while using runalyze via a subdomain e.g. runalyze.example.org I get an 404 error: 

> The requested URL /var/www/virtual/user/runalyze.example.org/call/call.SharedTraining.php was not found on this server.

Using example.org/runalyze everything works well. I'm not sure if this is a runalyze bug or depending on my shared hosting but as I never had problems with other services I think it may be runalyze dependent.

**Comment by mipapo** [comment]
vTried it with the current master - works totally fine for me.
Try to uncomment the line "RewriteBase /" in the .htaccess file

**Comment by mdosch** [comment]
Works fine with the rewrite rule uncommented. :)
Why is this line commented per default?

**Comment by mipapo** [comment]
Because it has always been that way. ;)
But I have a look for the next version and the new .htaccess file. This one won't be used anymore

**Comment by laufhannes** [comment]
> Why is this line commented per default?

Because it does not work if you use Runalyze for example as `domain.com/runalyze/` ;)
