### ISSUE TITLE
global.calculateStrideLength.php not working (for me)

### ISSUE THREAD

**Issue by mtressl** [Runalyze/Runalyze#1441]
Did all the configs in the file, and executed it from CLI. It does something, but after finishing the stride length for newer activities is gone, and older ones are not calculated. Same for cadence and ground contact time.

Am I doing something wrong?

**Comment by mipapo** [comment]
Do you mean the arrays are missing or just the average values?
Try to execute this sql command manually: "UPDATE `runalyze_training` SET `stride_length` = (`distance`*1000*100/(`cadence`*2/60*`s`)) WHERE `cadence` > 0 AND `s` > 0;"

**Comment by mtressl** [comment]
Can you help me again with the SQL query? A copy/paste does not work and I cannot really follow what you want to do exactly, especially with the 1000100 part. Thx.

What I wanted to say with my report: the only value left is the cadence, stride length was there for the runs I uploaded after upgrading to 2.1, but after running the script they went away.

**Comment by mipapo** [comment]
UPDATE `runalyze_training` SET `stride_length` = (`distance`*1000*100/(`cadence`*2/60*`s`)) WHERE `cadence` > 0 AND `s` > 0 
This should work. The formatting was wrong.
Was the stride_length away in the _training table?

**Comment by mipapo** [comment]
I just had a second look at the script and I really don't see any problem there. 
Also i don't know why the fields in _trackdata should be missing after you run the script

**Comment by mtressl** [comment]
Cool, thank you. The SQL query brought back the stride length, yes.
I have no idea why it was wiped when I first executed the script.

**Comment by mipapo** [comment]
So everything is fine now? :)

**Comment by mtressl** [comment]
Yes, guess so. Stride length is back where possible.
Now I just have to figure out how to import the FIT files from garmin, since they just contain crap.

Issue resolved. Thx again.
