### ISSUE TITLE
Tooltips in Configuration window are shown under the window

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1442]

**Comment by laufhannes** [comment]
Probably introduced in https://github.com/Runalyze/Runalyze/commit/f22354b10e0386257707e33249014e80c1bf6dce#diff-7c4c86bcfc1e692fcc2126e33cea8fb9R34. I guess `#ajax .tooltip` has to be changed to `.overlay .tooltip`, as tooltips are appended to the body-node, not to the ajax-node.
