### ISSUE TITLE
update-v2.1-to-v2.2.sql

### ISSUE THREAD

**Issue by uk3** [Runalyze/Runalyze#1450]
Hallo,

Nicht wirklich ein Bug, aber eine Beobachtung:

Wenn man wie ich dem git zu folgt, ist es im moment recht schwierig, den anpassungen in der SQL Datenbank zu folgen und die richtig nachzuvollziehen. Besonders unangenehm ist mir das beim Merge von #1446 aufgefallen. Die beteiligte Änderung an der Datenbank ist nämlich weder am Ende des update-files noch mit einem aktuellen Datum versehen. Diese ist mir dann zufällig aufgefallen, aber die gefahr ist für mich, dann einmal eine Änderung zu übersehen und so in Problem zu laufen.

Die alte methode mit einem File pro änderung war da irgendwie übersichtlicher. Aber es hatte wohl Gründe das jetzt anders zu machen. Wobei bessere Idee hab ich atm auch keine.

lG Ulrich.

**Comment by mipapo** [comment]
Moin,
Meine persönliche Meinung ist da einfach: Produktiv nur das aktuelle Release nutzen.
Dafür ist einfach stable da...
Beim Entwickeln ist das halt so, dass man da hin und wieder mal mit der DB aufpassen muss. 
Ich versuche die Reihenfolge in der update * einzuhalten und das Datum dazuzuschreiben, aber es kann immer mal passieren, dass es nicht passt.
