### ISSUE TITLE
Connection to remote Mysql Database does not work

### ISSUE THREAD

**Issue by schannall** [Runalyze/Runalyze#1452]
Hi,
I don't succeed in having runalyze accessing a remote mysql database. I can connect via the commandline:
mysql -u runalyze -p -h alpha -D runalyze;
and also with php using the credentials given in the webgui. Can anyone confirm this is not working?
Thanks in Advance!

Jonas

**Comment by mipapo** [comment]
External connect should work. We use this in our onlineversion.
 Try the ip address of the external host.

**Comment by schannall** [comment]
Hi,
I also tried the IP and also with Port. This is why I asked :/ IÄll be searching further then thank you.

Jonas

**Comment by mipapo** [comment]
Can you look at the log of the external mysql server? There you should see, why the connection is denied.

**Comment by schannall** [comment]
It does not even show up in the logs - loggin in with mysql or php does write to the logs ...

Jonas

**Comment by mipapo** [comment]
When it does not show up in the logs of the external server, then php or mysql never tried to connect the correct host. Maybe try the FQDN name. Or write a simple php script, which tries to connect with the database.

**Comment by schannall** [comment]
Hi,
as previously written: i can connect via php and via the mysql command. The FQDN does not work either :(

Jonas

**Comment by laufhannes** [comment]
What do you mean by "connect via php"? Runalyze does use the following (see https://github.com/Runalyze/Runalyze/blob/stable/inc/system/class.DB.php#L39):
```php
$PDO = new PDO('mysql:dbname='.$database.';host='.$host.';charset=utf8', $user, $password);
```

**Comment by schannall** [comment]
The script does not seem to be ran - as it should connect to the server then. There is no firewall or proxy between which could hinder the communication.
Is there a "trace" command for apache2?
I thought that maybe pdo was not enabled but pdo seems to be enabled by default in ubuntu.
"Connect via PHP":

<?php
$servername = "192.168.2.21";
$username = "runalyze";
$password = "password";

// Create connection
$conn = new mysqli($servername, $username, $password);

// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}
echo "Connected successfully";
?>
This script does work.

**Comment by mipapo** [comment]
Try if you can read/write the database. With the script you just covered the connection between your server and the external mysql server.

**Comment by schannall** [comment]
Hi,
how would this help? Runalyze does not even connect to the database, beeing able to create/edit tables should not make a difference (editing tables does work from the mysql cli though)
I'm not a php guy enough to edit tables in mysql :/


Jonas

**Comment by laufhannes** [comment]
Which Runalyze-script are you talking of? You are probably trying to install Runalyze v2.1 through `install.php`? What is the exact message?

And, in your own test script, please test to connect to the database as well.

**Comment by schannall** [comment]
Correct. The Installer says:
 The connection settings are incorrect. We are not able to connect to the database.
But the mysql Server does not even log an access.
This is why I guess that the runalyze Installer does not even run the mysql connection script. As there is no log written from runalyze (not even with the debug option enabled) I can't really say that. Is there a way to manually run the script to see where it fails?

Jonas

**Comment by laufhannes** [comment]
You can try your debugging skills here: https://github.com/Runalyze/Runalyze/blob/stable/inc/class.Installer.php#L243-L271

**Comment by mipapo** [comment]
Closed due to no answer from the user.
