### ISSUE TITLE
Improve the overview layer

### ISSUE THREAD

**Issue by diesl** [Runalyze/Runalyze#1454]
Some suggestions to improve the overview layer:
- [x] The bar to toggle the different types of training does not wrap to the next line and breaks out of the layer window. See image.
- [x] UI: Clicking on the color boxes of the toggle bar does not have any effect, but the hand cursor is shown when hovering over it. Either make it clickable or remove hand curser
- [x] Improvement: Show a summary of current information that is currently displayed, because now you have to remember what is selected. For example: "Training & Wettkampf, TRIMP, Laufen, 2015" at the bottom of the layer or as part of the legend.

![runalyze](https://cloud.githubusercontent.com/assets/3629547/9137253/c0a54d3e-3d1c-11e5-9072-4cfda7d1bc47.png)

**Comment by laufhannes** [comment]
I don't think that the first one is possible with the current layout. Flot uses a table for the legend and it's not easy to make it responsible.

**Comment by mipapo** [comment]
Trainingtypes show up with their abbr. since 92abb390089f0efe1db7e08f74e3594cda60f8ad
