### ISSUE TITLE
Multisport fit Datei

### ISSUE THREAD

**Issue by uk3** [Runalyze/Runalyze#1455]
Hallo,

ich hab hier eine Multisport fit Datei (2x Radfahren). Beim Import werden die beiden Aktivitäten als separate laps dargestellt. Allerdings sind mir ein paar dinge aufgefallen, weshalb ich unsicher bin, ob das File richtig verarbeitet wird:

* Die Computed Laps ziegen nur die der 2. Aktivität
* der TCX Export dürfte auch nur die 2. Aktivität exportieren
* Was ich nicht weiss, aber mal testen kann, was passiert wenn ich bei den aktivitäten auch noch auto-lap aktiviert habe (war in dem Beispiel-Fall aus).

fit file stelle ich bei bedarf zur Verfügung (möchte es nur nicht im github haben)

lG Ulrich

**Comment by mipapo** [comment]
Ja ist bekannt, dass es bei Multisport noch einige Probleme gibt. Kannst natürlich jederzeit die Datei an mail (æt) runalyze.de schicken. 
Danke aber nochmal für den Hinweis ;)
