### ISSUE TITLE
Pool Length

### ISSUE THREAD

**Issue by uk3** [Runalyze/Runalyze#1456]
Bei der Eingabe einer Aktivität (ausser es ist laufen) wird immer zwingend eine Pool-Länge abgefragt (auch wenns z.B. Radfahren ist ;-).

lG Ulrich

**Comment by mipapo** [comment]
Das muss sich irgendwo beim Mergen eingeschlichen haben...
Danke fürs Melden!

**Comment by laufhannes** [comment]
Ich bezweifle, dass das mit dem aktuellen Code möglich ist, das zu unterbinden. Dazu bräuchten wir eine Klasse "only-swimming" o.ä., was daran scheitert, dass "Schwimmen" nicht als eindeutige ID hinterlegt ist sondern zu jeder ID gehören kann.

Meiner Meinung nach kann das Feld aber komplett versteckt werden. Wenn die Daten nicht ohnehin von der Uhr kommen, ist die Angabe der Bahnlänge völlig egal, weil sie keine Auswirkung auf die Auswertung hat.
