### ISSUE TITLE
Option: Start week on sunday

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1457]
"One request. I usually race on Saturday, so my training week is Sunday to Saturday. When I taper it is this seven day period that counts. So any chance of an option to make the Runalyze configureable for Sunday being the first day of the week?" via Facebook

**Comment by mipapo** [comment]
+1 via mail (JDs plans are written in that way)

**Comment by mipapo** [comment]
Bounty for 2.3

**Comment by grzeg1** [comment]
![indeks](https://cloud.githubusercontent.com/assets/8179857/10881698/4a11c66a-8165-11e5-8498-8af1da62d2f6.jpeg)

**Comment by mipapo** [comment]
Done in ae45acf34417497d82eb7675e434198988ddf917
