### ISSUE TITLE
Language always set to English

### ISSUE THREAD

**Issue by hmorandell** [Runalyze/Runalyze#1459]
HI,

I have a new installation running on http://www.runlikeachild.com/runalyze/ and the language is always in Elgish, even if you press on german or Italian on the top right corner? 
For the rest everything is working fine, it's just the language which seems for some resaon will not be translated although in the cookie the "lang" is set to "de"...

Anyone else facing the same issue? Sorry that I write here, I tried to register on the forum but I never received the activation mail...

thanks

**Comment by mipapo** [comment]
Did you download the runalyze installation package or directly downloaded it via git?
Then maybe the "php-gettext" package is missing or the corresponding locale is not activated on the server.

**Comment by hmorandell** [comment]
shame on me,
I forgot completely about the php-gettext package. Anyway, after the installation I had to edit "/etc/locale.gen" removing the comment from the languages I'm going to need and after that I had to run "locale-gen". Now everything is working fine.

Thanks a lot for the quick answer!
