### ISSUE TITLE
Typo: "weigth" instead of "weight"

### ISSUE THREAD

**Issue by sauff** [Runalyze/Runalyze#1464]
The word "weigth" is used in several instances instead of "weight". The error (typo) occurs as well in the user interface as in the code itself where it is used as a label or named variable.

**Comment by laufhannes** [comment]
As a variable as well? Github does only show these two occurences (+ key strings in translation files): https://github.com/Runalyze/Runalyze/search?l=php&q=weigth&utf8=%E2%9C%93

**Comment by sauff** [comment]
I'm sorry, I mistook one of the occurences as a variable because it started with a small "w" while the other begins with a capital "W". When it's not a variable then I only saw the two places that you mentioned (plus several copies in the localization files).

**Comment by laufhannes** [comment]
There is no reason to excuse yourself, we appreciate any kind of help! I just wanted to check, as I'm not sure whether Github's search does show every occurance.
