### ISSUE TITLE
Account reset

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1465]
Make it possible for a user to reset the account to default settings (and remove all data). 
(For security reasons user should retype the password to confirm reset)

**Comment by laufhannes** [comment]
Theoretically that's possible with importing [default-empty.json.gz](https://github.com/Runalyze/Runalyze/blob/master/tests/testfiles/backup/default-empty.json.gz) through our database backup/import tool. But of course it's better to have a nice user interface.

(And I guess this issue replaces #634?)

**Comment by mipapo** [comment]
When you begin only to search for english search strings you won't find the german tickets :P 
I don't think any user knows the default-empty.json.gz ;) I close this one

**Comment by laufhannes** [comment]
> When you begin only to search for english search strings you won't find the german tickets :P 

That's why I thought about replacing the old one with this one ;)

> I don't think any user knows the default-empty.json.gz ;) I close this one

That's right. I think I only mentioned it one or two times in a support response.
