### ISSUE TITLE
Hide build dir from public

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1476]
Hide build dir from public

**Comment by laufhannes** [comment]
What's with the [.htaccess](https://github.com/Runalyze/Runalyze/blob/master/build/.htaccess) in there?

**Comment by mipapo** [comment]
It is not much use if you use nginx...Will have to add this to the nginx configuration. If the js wouldn't be in there everyone could delete the directory after using it. 
In the future we hopefully don't need such a directory anymore.

**Comment by laufhannes** [comment]
That's right. As soon as grunt is used, the `*.js`-files and the `build.*`-files won't be there anymore. The `global.*`-files need database settings anyway and users are prompted to remove the credentials or delete the files afterwards.
