### ISSUE TITLE
Command-line file import

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1478]
I'd love to have a command-line import utility that I'd use like:

```
runalyze-import --user=grzeg1 --file=/tmp/workout.tcx
```

alternatively a way to call importer class from other project, but it would be harder because of all the classmaps etc.

Can you at least point me in the right direction? The whole uploader/multi-editor stuff is quite complicated....

**Comment by mipapo** [comment]
I just know that the ImportFactory is not that easy to use in an other way than by Runalyze...I think it's currently linked with an logged in user..

**Comment by laufhannes** [comment]
Do you want to code this for yourself or do you want a stable and secure way for our core? So far, most of the import stuff still relies on the old 'TrainingObject'. My attempt would be to first refactor the parser and importer stuff to use the new models from `inc/core/` before I care for new features like that.

Anyway, to get it working, the following may help:
  1. Create a `FrontendCLI extends Frontend`
    - don't show header or footer
    - ask/check password
    - find a way to tell `SessionAccountHandler` to use this account (`SessionAccountHandler::getId()` is widely used, you may just add another if case there)
  1. `new ImporterFactory($arrayOfFilenames)` may be used as it is
    - so far, filenames must be relative to `FRONTEND_PATH`
    - parsed activities are available via `$ImporterFactory->trainingObjects()`
  1. `$TrainingObject->insert()` may be used as it is
    - so far, parsed activities will be display with `TrainingFormular` or `MultiImporterFormular` first, but that's not necessary

**Comment by grzeg1** [comment]
I have this simple https://github.com/grzeg1/polarsync script that imports all new workouts from Polar Flow (I'm using Polar V800 and with Polar everything has to go to their web app first). It would be a lot easier for me if they could go straight to my Runalyze. Until there's no proper Runalyze API that would handle it, I'd like at least a simple command line utility.

**Comment by mipapo** [comment]
@laufhannes I don't think it asking/checking password is needed for the "runalyze-import" script. When we use controller we have anyway get rid of the hard-wired Frontend classes. Every method/class should work with a cli and frontend.

**Comment by mipapo** [comment]
+1 via google+

**Comment by laufhannes** [comment]
Providing a new console command is really easy with Symfony (although the current mix of our old Frontend class and new Symfony stuff is quite dirty).

**Comment by mipapo** [comment]
Example
`php bin/console runalyze:activity:bulk-import mipapo /home/mpo/activityfiles`

Some ideas for a better command when the importer is refactored
- move or delete already/imported activity files
- only import files not older than x

**Comment by Vebryn** [comment]
Great! I'm going to configure an incron rule to automatically import my tcx files :)
