### ISSUE TITLE
Sport types redesign for auto-upload/auto-sync

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1479]
In addition to custom sport types we need fixed sport types if we want to handle automatic syncing/uploading to/from other platforms. Otherwise all sports besides Running can not be recognized.
So probably at least the most common sport types like Running, Swimming, Biking need to be hardcoded in some way.
Could maybe be implemented as a dictionary. You would select sport's name from the dictionary (then it would get certain dictionary id) or you would just use a custom name, then it would be treated as "other".

A small thing related to current design: Running sport name is not editable and not translatable right now. So, as in online Runalyze my account that was created in German, I will never be able to change Laufen to my native language.

**Comment by mipapo** [comment]
I think the running sport name is not editable because that was a first try to hardcode some sports.
But we had no idea how to hardcode it ;)

**Comment by laufhannes** [comment]
What do you mean with 'dictionary'?
My idea of a dictionary would be that users can map their own sport types to "pre-defined" names.

I don't really like the idea of having fixed sport types or only fixed names (yes, for running that's not good at the moment). People may want to delete 'Cycling' or 'Swimming' if they do never ever use it or they may want to call it 'Trailrunning' instead of 'Running' because that's how they call it.

**Idea 1:**
Add a new column to `runalyze_sport` and fix some dictionary ids. Possible problem: A user could select more than one type to be synced as 'Running'. That's okay to sync from Runalyze to another platform but ambiguous to sync from another platform to Runalyze.

Symbol | Name | ... | Sync as
---------- | -------- | --- | -----------
... | My sport type | ... | drop down of typical names from other platforms/devices

**Idea 2:**

Use configuration variables (as `RUNNING_SPORT` so far) and provide another table below the standard config table. The sync problem is now the other way round: That's good to sync from another platform (or to map sport types from devices) but bad to send activities from Runalyze to another platform.

External sport type | Mapped to your sport type
------------------------- | -----------------------------------
Running | drop down of user's sport types
Cycling | ...
... | ...

**Comment by mipapo** [comment]
+1 for the first idea ;)

**Comment by grzeg1** [comment]
There's always a trade-off.
Fixed sport types allow for better data exchange, quicker and simpler initial set-up and features like comparison with other users (like in Strava you can view other user's profile and compare some values side-by-side).
Free-form sports let you delete unwanted items and use your own names (but these names will not be translatable if you share the results).
The decision should be based on how the app is going to develop. As an example:
I do both running and trail running. Mostly trail. I like VDOT values, though they come completely different for both types. If there was a way to get 2 average VDOT-s and prognoses and sum up weekly km, I'd have 2 sport types - running and trail running. But now there is no way to do it, so I'm just using one sport type.
What also bothers me is that every time I import a file I need to manually specify sport type, whereas other platforms do it automatically...
I guess my idea for now would be to have the most used and meaningful sport types hardcoded with ability to add free-entry ones and delete what you don't need.

Symbol | Name | ... | Custom
---------- | -------- | --- | -----------
... | Running | ... | 
... | Cycling | ... | 
... | Swimming | ... | 
... | Trail running | ... | 
... | Mountain biking | ... | 
... | Jumping on one leg | ... | X 
... | [Combo box - dropdown for hardcoded types, free-entry for custom] | ... |

**Comment by mipapo** [comment]
Good argument - but how we would move on with the current data? Translated values (names) are in the database. The name in the database has to be renamed to the english one (okay should beo no problem)

Customfield is an good idea.
+ Hardcoded sport types should not just deliver the name, also the corresponding settings for the sport.

**Comment by laufhannes** [comment]
> The name in the database has to be renamed to the english one

I don't think that pre-configured sport types need a name in the database anyway. Just add a field `internal_sport_id` (or whatsoever) and if that is set, use the name from an internal class.

I think the form must provide a way for users to transform a pre-configured sports type into a custom one and vice versa.

 - migration script: look for typical names and set `internal_sport_id`
 - form: maybe use 'custom' as first (or second) column and switch between dropdown and free textfield based on current state

> Hardcoded sport types should not just deliver the name, also the corresponding settings for the sport.

Pre-configured, yes. But not fixed. Users may want to change pace unit, types and short mode, for example. There is no need to fix these settings.

**Comment by mipapo** [comment]
+1 @laufhannes  Great hints

**Comment by McGo** [comment]
I think one has to distinguish between the runalyze internal need for defining custom sport types and the external view when it comes to syncing.

Internally each sport type that could basically be treated differently when it comes to statistics has to be some kind of hard coded or "tagged" with the statistic engine. It seems to me that it makes no sense to analyze VDOT for a "jump on one leg" sport type. But it could make sense to add another analyzation-engine for other sport types like biking (cadence, power, ... ) or swimming (swolf, technique). 

Externally the sport types of each service differ a lot. There is no real standard for sport types (or at least not one that is used widely). I am syncing my polar data to strava, runkeeper, runtastic, endomondo, smashrun and my dropbox with tapiriik / rungap and am constantly running into trouble when it comes to selecting the correct sport type (running, treadmill, swimming, indoor swimming, workout, bike). This could not be solved on a general level but could be solved by letting the user define what external sport type is meant by their individual settings. 

So to combine those two I would recommend to do the following:
- Let the user define all sport types on their own. 
- There are no hard coded sport types
- For each sport type, the user has to select a "analyzation engine" which could be just geo data or the current running focused engine.
- When it comes to syncing, the settings for the synced account has to store which external sport types match to the user defined ones.

**Comment by laufhannes** [comment]
> * When it comes to syncing, the settings for the synced account has to store which external sport types match to the user defined ones.

I don't like the complexity of allowing a completely individual sport type mapping. Clearly, not all platforms offer standard names for sport types, but at least the FIT format has fixed ids for a lot of sport (and sub-sport) types.

An individual mapping can be an additional enhancement but not *the* solution for all files.

And, talking of some future community features, fixed sport types are needed to compare records / stats of different users.

> * Let the user define all sport types on their own.
* There are no hard coded sport types
* For each sport type, the user has to select a "analyzation engine" which could be just geo data or the current running focused engine.

Our suggestions from above will let users define all sport types on their own. We just give a pre-configuration for some of them but that will be still adjustable. The "analyzation engine" you're talking about is somehow that adjustment. Currently, that's only: has distances, has power, has outdoor data. But others can follow ...
