### ISSUE TITLE
Refactor for equipment just erased all my shoe data

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1486]
I guess it may be related to single-user install with no entries in account table...
#1335 - having no account is evil...
luckily I remembered to make backup just between running sql update and refactor script ;)

**Comment by grzeg1** [comment]
indeed, after adding a dummy account with id 0 it worked
```
insert into runalyze_account (id, username, name, mail, language, password, salt) values (0, 'grzeg1','grzeg1','grzeg1@localhost','pl','aaa','aaa');
update runalyze_account set id=0;
```

**Comment by laufhannes** [comment]
Always good to have a recent backup!

I've added a notice if there's no account, so that the script will stop. I guess it's enough to state "Please register an account" and provide some `inc/install/switch-accountid-from-0-to-1.sql`?

**Comment by laufhannes** [comment]
Just another notice: The equipment tables are using constraints on foreign keys such as `accountid`. It's not only the refactor script, the whole master won't work anymore without a real account.
