### ISSUE TITLE
Error when importing FIT-file - Unable to execute '/usr/bin/perl 

### ISSUE THREAD

**Issue by Ivo1975** [Runalyze/Runalyze#1491]
When I tried to upload the fit file to the database. I got the error:

WARNING	shell_exec(): Unable to execute '/usr/bin/perl D:\www\ivonobel.nl\www\runalyze\inc/../call/perl/fittorunalyze.pl "D:\www\ivonobel.nl\www\runalyze\inc/import/files/63578523751000000016.fit" 1>"D:\www\ivonobel.nl\www\runalyze\inc/import/files/63578523751000000016.fit.temp" 2>&1' (in D:\www\ivonobel.nl\www\runalyze\inc\system\shell\class.PerlCommand.php::77)
WARNING	fopen(D:\www\ivonobel.nl\www\runalyze\inc/import/files/63578523751000000016.fit.temp): failed to open stream: No such file or directory (in D:\www\ivonobel.nl\www\runalyze\inc\import\filetypes\class.ImporterFiletypeFIT.php::74)
WARNING	unlink(D:\www\ivonobel.nl\www\runalyze\inc/import/files/63578523751000000016.fit.temp): No such file or directory (in D:\www\ivonobel.nl\www\runalyze\inc\import\filetypes\class.ImporterFiletypeFIT.php::86)

the site runs oke. Only uploading doesn't work. 

Has anyone an idea how to fix this?

Ivo

**Comment by laufhannes** [comment]
You need Perl on your server and [inc/system/shell/class.PerlCommand.php#L20](https://github.com/Runalyze/Runalyze/blob/master/inc/system/shell/class.PerlCommand.php#L20) must point to its location.
