### ISSUE TITLE
Mode values in addition to averages

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1494]
I'd like some median values, especially for cadence, but also maybe pace&HR.
Example: 
Riding a bike I'm trying to keep cadence of 90, but at times I will stop pedalling or go slower.
Average cadence will drop to e.g. 80 but mean cadence should show 90.
Running I want to keep pace of 5:00 min/km, but I will slow down at turns so average pace will be slower.
What do you think?

**Comment by laufhannes** [comment]
I just added the median to [Distribution.php](https://github.com/Runalyze/Runalyze/blob/master/inc/core/Calculation/Distribution/Distribution.php), but I think the differences will be in general negligible. For my todays run:

```
Pace:
   mean:        4:40,7 (based on histogram)
   median:      4:38
   avg:         4:37 (based on total distance/time)
Heart rate:
   mean:        135.803
   median:      137.000
```

For running dynamics the maximal difference is `0.3`.

--

Do you have our [Playground](https://github.com/Runalyze/runalyze-playground) 'installed' (probably just put a checkout in a directory next to your Runalyze-installation)? That's where I got the above values from: `http://localhost/runalyze-playground/example/distribution/statistics.php?id=3294`

**Comment by laufhannes** [comment]
Somehow related: #1157

**Comment by grzeg1** [comment]
Ok, I did statistics too long ago ;). In fact what I wanted would be mode (most frequent value), not median. I guess it would be most important for cycling cadence.

**Comment by laufhannes** [comment]
I just added the mode to [Distribution.php](https://github.com/Runalyze/Runalyze/blob/master/inc/core/Calculation/Distribution/Distribution.php) as well. Example for my todays interval workout:

```
Pace:
   mean:        4:02 (based on histogram)
   median:      3:30
   mode:        3:20
   avg:         3:48 (based on total distance/time)
Heart rate:
   mean:         153
   median:       163
   mode:         175
Cadence:
   mean:          95
   median:        98
   mode:          99
```

What is your idea for displaying these values? Do you think of a configuration option to choose how to calculate the "average" which is saved in database? So that you can choose whether mean, median or mode is shown in data browser? Or should go into the detailed activity view? (or even into an extra window?)

**Comment by grzeg1** [comment]
I thought about displaying it separately in activity view.
It would be interesting to me for pace/speed and cadence.
IMO it needs to be treated as an additional value, independent of average. Tells me what my "cruising speed/cadence" is, ignoring all the times I was turning, passing someone, going up a small hill etc.
For a true interval workout it will not be interesting probably, just like average speed/pace - you want rather average speed/pace of work phases, not whole workout.
