### ISSUE TITLE
Shoe -> Equipment

### ISSUE THREAD

**Issue by uk3** [Runalyze/Runalyze#1497]
Hallo,

eher eine Frage als ein Issue: Gibt es schon ein Script oder einen Weg, die Schuh-Daten in die neue Equipment-Struktur zu konvertieren (das ich übersehen hab) oder ist das noch offen bzw. manuell zu machen?

lG Ulrich

**Comment by mipapo** [comment]
https://github.com/Runalyze/Runalyze/blob/master/refactor-equipment.php Sollte das eigentlich erledigen ;)
