### ISSUE TITLE
Training paces on main screen

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1499]
Where are these taken from? I always have to open JD tables to look for paces as these don't match....

**Comment by laufhannes** [comment]
In both cases values are calculated by formulas derived from JD's tables. Basically, they are defined by a percentage of `vVDOT`, the actual pace that can be kept for around 11 minutes.

But JD's tables are inconsistent: At one point there's a table defining pace ranges for all types, e.g. 83 - 88 % for threshold pace, but in another table there are single paces for all types and we had to reverse engineer the percentages and they are not always in the previously defined range. For threshold this value is 90 % for example.

You can find used percentages in [class.RunalyzePluginTool_JDTables.php#L136-L145](https://github.com/Runalyze/Runalyze/blob/master/plugin/RunalyzePluginTool_JDTables/class.RunalyzePluginTool_JDTables.php#L136-L145)

**Comment by grzeg1** [comment]
Ok, but as the tables are there already, should the paces come right from the tables?
I need to look up Running Formula, I just remember the tables, but don't remember calculations...

**Comment by laufhannes** [comment]
There are no formulas/direct calculations in his book, they are out there in the world wide web, e.g. http://www.simpsonassociatesinc.com/runningmath2.htm.

I think it's good to have ranges for paces. Maybe we can just enlarge ranges for marathon and threshold pace to include tables values?

**Comment by grzeg1** [comment]
I'd rather stay with Daniels's fixed values. If these paces are the ones you're supposed to train at, I don't think you want to use the whole range on a day-to-day basis, but rather you want to use a single value. 
So e.g. marathon pace should correspond to your prognosis pace, so your body can learn optimal pacing. But now it's in the lower end of the quite wide range, so it tells me nothing and I just look it up using the tables.
Or am I trying to use these values in a different way than they were meant to?

**Comment by laufhannes** [comment]
"_If these paces are the ones you're supposed to train at, ..._ - that's the question, as both definitions appear in his book. But I have to admit that I always look at the exact value for intervals, not at the range. So I'm okay with it.

**Comment by laufhannes** [comment]
Daniels' training paces have been removed in v4.0.
