### ISSUE TITLE
Sport configuration: activity type box needed?

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1502]
If I would uncheck the box the type configuration will still work, but the sport would change the next time.
How about removing the checkbox from the sport configuration and just check if activity types are existing for a sport and either show the activity type dropdown in the formular or  hide it.

**Comment by laufhannes** [comment]
That's right. I think there are not many locations where `$Sport->hasTypes()` is used (see [search](https://github.com/Runalyze/Runalyze/search?utf8=%E2%9C%93&q=hasTypes)). In the activity form, the dropdown can be just empty - I think it's not really needed to hide it.

**Comment by mipapo** [comment]
Well in the future anything which cannot be filled out should not be show to make it easier for the end user
