### ISSUE TITLE
Multiple Equipment panels

### ISSUE THREAD

**Issue by uk3** [Runalyze/Runalyze#1504]
Hello,

another idea regarding Equipment. Currently the Equipment Panel only shows one type of Equipment and the panel itself can only be shown once.

Since I have Shoes, Bikes and other types of Equipment in Runalyze it would be nice to see them all (or some of them).

I think the best solution would be to be able to show multiple instances of the equipment panel (each for one type of Equimpment).

lG Ulrich

**Comment by grzeg1** [comment]
Would having a drop-down with equipment category at the panel's header satisfy you?
Would allow to switch category easily.
Much easier to do. Multiple instances would need a lot of refactoring I think.

**Comment by laufhannes** [comment]
That's much easier to realize, right.

Should all statistics be fetched for each request and dynamically switched (as for 'month', 'year' and 'total' in sports panel) or should a switch trigger a reload (and change of the plugin's config)?

**Comment by uk3** [comment]
Fine with me as well

Lg Ulrich

**Comment by grzeg1** [comment]
I think plugin config's can be left untouched for starters.
