### ISSUE TITLE
Equipment panel icons

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1505]
The icon to add/edit equipment should be `+` (like in body types) or pen. The little cog is used for plugin configuration everywhere so it's misleading.

**Comment by laufhannes** [comment]
Not sure how that icon got there - probably because it's a link to one of the general configuration tabs. I'm not very happy with that configuration tab, as it's quite big for all of my shoes. But that's another topic. So far, +1 for `+`.
