### ISSUE TITLE
When removing data sequence "cadence" -> remove average score

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1510]
Beim Entfernen der Datensequenz "Trittfrequenz" bleibt in der Aktivitätsübersicht der Mittelwert enthalten. Dieser sollte auch entfernt werden.

**Comment by laufhannes** [comment]
It has to be checked if the activity's value is still equal to the array's average first.

For example, I always set another temperature as the average value of my device's sensor. I don't want that my 'manual' value gets removed only because I remove the data series.
