### ISSUE TITLE
Undo the deletion of running equipment.

### ISSUE THREAD

**Issue by guotsuan** [Runalyze/Runalyze#1516]
I accidentally  deleted two running showes in configureation->equipment after just finish updating the code with refractoring of equipment. I'm wondering if I can recover them?
Thank you very much in advance.

**Comment by laufhannes** [comment]
There is no possibility if you don't have a backup. Runalyze does not have any 'revision'- or 'undo'-table.

**Comment by guotsuan** [comment]
I see. Thank you very much.
