### ISSUE TITLE
Show equipment in Edit-Mode only when activity date before end date

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1521]
- [x] Show equipment  in Edit-Mode only when activity date before end date of equipment
- [x] order equipment by date (newest first)

**Comment by laufhannes** [comment]
So far, only "active" ones are shown if a new activity is created and all are shown if an old activity is edited. Showing only equipment that was active at that date requires both start and end date as additional attributes for the options and some dynamic javascript to care for that.

I don't think that this is needed for v2.2. This has not been different in previous versions and it's not a real bug.

**Comment by laufhannes** [comment]
Just as note: order by date did work all the time.
