### ISSUE TITLE
Position tracking on map is wrong (imperial unit)

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1526]
data assignment km<->miles

**Comment by laufhannes** [comment]
Does this depend on any special settings (apart from imperial units)? I can't see any problem with that in my case.

**Comment by laufhannes** [comment]
Example: ![map-tracking-example](https://cloud.githubusercontent.com/assets/8313118/10535824/5fd0ebc0-73e6-11e5-9fb3-87c535a5804a.jpg)

Of course, the map marker '3' belongs to 3 miles (and hovering the map does show that as well).

**Comment by mipapo** [comment]
![tooltip_068](https://cloud.githubusercontent.com/assets/2135076/10536050/4f211974-73e8-11e5-96ec-6a37b6cb6881.png)

**Comment by laufhannes** [comment]
Okay, using time as x-axis is the problem.

**Comment by laufhannes** [comment]
We should not manipulate data in [DistanceSeries.php#L57-L65](https://github.com/Runalyze/Runalyze/blob/master/inc/core/View/Activity/Plot/Series/DistanceSeries.php#L57-L65) but set a `$this->UnitFactor`, which is not possible so far but should be easy, see https://github.com/Runalyze/Runalyze/blob/master/inc/core/View/Plot/Series.php#L125 for what is currently done to hide the distance series (which does not work for miles).

**Comment by laufhannes** [comment]
Remember: so far with `Configuration::ActivityView()->usesTimeAsXAxis()` only the combined plot (pace + hr + elevation) adds `DistanceSeries` to enable position tracking on map. See #1307 to enable that for all plots.
