### ISSUE TITLE
config.php and refactor-equipment.php have different parameter

### ISSUE THREAD

**Issue by Wenerus** [Runalyze/Runalyze#1530]
config.php
  $host = 'XXXXXXXXXXXX';

refactor-equipment.php
  $hostname = 'XXXXXXXXXXXX';

**Comment by mipapo** [comment]
Well, not that important. But why not...

**Comment by Wenerus** [comment]
yes i now :-)

**Comment by laufhannes** [comment]
I'm not sure if there are any references in some documentation (e.g. in older blog posts showing how to use the refactor script for v2.0), so ...

**Comment by laufhannes** [comment]
Oh come on, @mipapo, let me write what I want to write! :D

**Comment by laufhannes** [comment]
... so add an additional check in https://github.com/Runalyze/Runalyze/blob/master/refactor-equipment.php#L35:

```
if (!isset($host) && isset($hostname) {
	$host = $hostname;
}
```
