### ISSUE TITLE
Option: other scale for absolute atl/ctl

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1532]
User request: There is an option to show atl/ctl in absolute values instead of a percentage of the total maximum, but this does not change the scale in the form plot and of the progress bars.

I tag this as 'Idea' as I'm not sure which scale to choose.

**Comment by laufhannes** [comment]
![atl-peak](https://cloud.githubusercontent.com/assets/8313118/10573400/8b9ff294-764f-11e5-9880-4bf27661e06b.png)

A logarithmic scale could be used.

**Comment by grzeg1** [comment]
I've been always using absolute values and have no problem with scale. It nicely shows how much ATL relates to CTL and thus how big TSB is.
I'm wondering how you got TRIMP as high as 14000? Either I'm missing something or there is some wrong data input here.

**Comment by laufhannes** [comment]
It's not my data, it's a screenshot from an ultrarunner. That is his real data and he requested an option to remove a single activity from trimp calculations or another way to get a readable plot.

**Comment by laufhannes** [comment]
I guess he does not use a heart rate strap such that trimp is calculated by type's default avg. hr, which is by default much too high for ultra races.

**Comment by grzeg1** [comment]
There's no point in having a chart based on wrong values. So I guess he'll have to either use right values or, if he still wants to play with wrong data, put in some arbitrary low average HR for the ultra race to get low TRIMP.

**Comment by laufhannes** [comment]
He did that and the plot looks good now.
