### ISSUE TITLE
index.php fails to load required autoload.php

### ISSUE THREAD

**Issue by aoleinik22** [Runalyze/Runalyze#1533]
PHP message: PHP Fatal error:  require_once(): Failed opening required '/var/www/html/runalyze/inc/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/runalyze/inc/system/class.Autoloader.php on line 22" while reading response header from upstream, client: 10.20.90.2, server: _, request: "GET /index.php HTTP/1.0", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "run.vrm.alxndr.ninja"

New install from current master. Installed into /var/www/html/runalyze with web server root indicated as /var/www/html/runalyze

**Comment by laufhannes** [comment]
Installations from master (and not from a prepared release *.zip) require currently
```bash
composer install
```
and
```bash
php build/build.php
```
