### ISSUE TITLE
Website always in english

### ISSUE THREAD

**Issue by winnieXY** [Runalyze/Runalyze#1539]
runalyze is always in english, even if I  try to switch to german or another language, although I've installed php-gettext and have the correct locales enabled on the system. 

I even tried to link the gettext.php and stream.php to the root folder of runalyze, but this doesn't help either.  I don't know what is going wrong here, there is nothing obvious in the error.log of the server.

**Comment by mipapo** [comment]
Have you compiled the language files `build/build.php translations`

**Comment by mipapo** [comment]
On Ubuntu you may have to install the locales: http://stackoverflow.com/questions/5257519/cant-get-gettext-php-on-ubuntu-working

**Comment by mipapo** [comment]
Have you restarted your apache server?

**Comment by winnieXY** [comment]
Restarting the apache was not the problem, nor the locales. I've not build the translations using build/build.php. Is this documented somewhere? I've not found this information, when I search for a solution.

**Comment by mipapo** [comment]
It's just mentioned here: https://github.com/Runalyze/Runalyze/wiki/How-to-release
But I think the best solution for you is to use the official releases.
We will add this information to http://docs.runalyze.com/

**Comment by laufhannes** [comment]
We should add documentation tickets in the respective repositories, not here. Nevertheless, I've updated our readme file and the checkout instructions in our docs.
