### ISSUE TITLE
Explanations for equipment configuration

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1540]
Tooltip says "An equipment can only be deleted if no references exist."

**Comment by laufhannes** [comment]
Just change the tooltip - that is outdated. And maybe display `[ ] delete` in each row.

Equipment can be deleted although references exist, thanks to foreign keys. (And that's why we highly recommend InnoDB!) 
Honestly, if users do things they didn't want to, it's their fault.

**Comment by mipapo** [comment]
+add tooltip to "End of use"  - "The equipment will be marked as inactive"
+add tooltip to "prev. distance" - "If you have already used your equipment for a while...." (something like that)

**Comment by laufhannes** [comment]
Maybe just add an info text box as for equipment types with a few additional lines, e.g.

> *RUNALYZE collects data and calculates statistics for each of your equipment objects. To correctly estimate its lifetime you can specify a 'previous distance' which is added to its calculated distance, e.g. if you used your running shoes for 200 km before tracking them. In addition, you can specify a start and end date for its usage. Objects will be displayed as 'inactive' as soon as you have entered an end date.*
