### ISSUE TITLE
Remove error toolbar

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1542]
The error toolbar is not recognized by users and does look bad in a productive environment. We should remove debug mode completely.

Use [Monolog](https://github.com/Seldaek/monolog) instead of our Error class, see #424 as well.

---

 * [x] remove visual toolbar and `Runalyze.Log`
 * [x] ~~use Monolog instead of `Error` (and `var/logs/` instead of `data/log/`)~~ #1890

**Comment by mipapo** [comment]
Not just "for example" - definitely use Monolog ;-)

**Comment by laufhannes** [comment]
The remaining todo has it's own issue for later processing.
