### ISSUE TITLE
Race data: place (age class/gender/total)

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1543]
We received this kind of request multiple times, e.g. show the trend of one's quantile (faster than 75% of all participants).

It could be necessary to add a new table `runalyze_race` (or `runalyze_competition`) where we save meta data for race activities. This way, we could add fields for "official distance" and "official time" as well and may solve the problem that we support only one race type id so far.

**Comment by mipapo** [comment]
+Great idea!

**Comment by laufhannes** [comment]
```sql
CREATE TABLE IF NOT EXISTS `runalyze_race` (
  `activityid` unsigned int(10) NOT NULL,
  `accountid` unsigned int(10) NOT NULL,
  `official_distance` decimal(6,2) NOT NULL,
  `official_time` decimal(8,2) NOT NULL,
  `name` varchar(50) NOT NULL DEFAULT '',
  `place_total` unsigned mediumint(8) NOT NULL DEFAULT 0,
  `place_gender` unsigned mediumint(8) NOT NULL DEFAULT 0,
  `place_ageclass` unsigned mediumint(8) NOT NULL DEFAULT 0,
  `participants_total` unsigned mediumint(8) NOT NULL DEFAULT 0,
  `participants_gender` unsigned mediumint(8) NOT NULL DEFAULT 0,
  `participants_ageclass` unsigned mediumint(8) NOT NULL DEFAULT 0,
  PRIMARY KEY (`activityid`),
  KEY  `accountid` (`accountid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

Is there anything missing?

**Comment by mipapo** [comment]
Looks good. If we want to show a table from same race, but different years we have to do this via the name? Thought about another table. But would be fine without

**Comment by laufhannes** [comment]
Is there anything else besides `name` that should/could be stored in this extra table `runalyze_race_event`? I guess this table can be independent of a single account?

**Comment by mipapo** [comment]
Think that's all...
