### ISSUE TITLE
CRITICAL: DB Backup Import Bug

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1544]
When using the import/export database tool plugin every entry in "_activity_equipment" will be deleted.

---

Getting Integrity constraint violations during Import:
"2015/10/25 13:25:31 [error] 31033#0: *123712 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '11-3' for key 'PRIMARY'' in /var/www/runalyze/user/plugin/RunalyzePluginTool_DbBackup/class.RunalyzeBulkInsert.php:61"

**Comment by laufhannes** [comment]
The error message seems to be unrelated to this bug.
