### ISSUE TITLE
Datepicker shows NaN sometimes

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1545]
Open a form with an empty datepicker input (e.g. equipment form) and click into the field. The datepicker should show current month.

This works for me, but if I enter a few whitespaces, leave the input and reenter it, NaNs are shown.

For the relevant code, see https://github.com/Runalyze/Runalyze/blob/master/lib/runalyze.lib.feature.js#L159 (we use http://www.eyecon.ro/datepicker/)

**Comment by mipapo** [comment]
See: https://github.com/eternicode/bootstrap-datepicker/issues/148
It's a fork of eyecon datepicker
https://github.com/eternicode/bootstrap-datepicker

**Comment by laufhannes** [comment]
The linked issue states that the problem does __not__ appear in eyecon's version?

**Comment by mipapo** [comment]
True
