### ISSUE TITLE
DB export: protect backup files

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1554]
**Current situation:** 
Backups are saved for example as `plugin/RunalyzePluginTool_DbBackup/backup/1-runalyze-backup-20150314-1592-653a.json.gz`, where `653a` is some random hash.

**Problem:** 
These files can theoretically accessed by everyone as long as they guess the correct file name.

**Comment by mipapo** [comment]
Folder is now protected with an htaccess file 
Download is from now on only possible by the owner.
Fixed in 332cc061d0881d1e86e4d756c1dc58eb852f4f56
