### ISSUE TITLE
Exporter: directly send file for download

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1555]
**Current situation:** 
Exporting an activity saves the file for example as `inc/export/files/1-Training_2015-10-06_09-14_768496.tcx`.

**Suggestion:** 
It's much harder to guess this filename in comparison to #1554, but still, it's not good practice and there is no need to keep these files. Instead, triggering the export should directly serve the file for downloading it.

**Comment by mipapo** [comment]
Exporter files are currently generated on the fly (4e8a1c7d7479ee82d06c01b11eae42c8f4b0f4e1)
