### ISSUE TITLE
Compress arrays in database

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1556]
**Current situation:**
- `_trackdata`, `_route`, `_hrv` and `_swimdata` contain large arrays
- these arrays are saved as `LONGTEXT` into our database, imploded by `|`
- this data causes the majority of the required disk space

**Suggestion:**
- compress data to reduce required disk space and traffic between php and mysql
- use `BLOB` and transfer binary data

**Ideas:**
- `gzcompress` +
  - `implode/explode`
  - `serialize/unserialize`
  - `json_encode/json_decode`
- https://github.com/msgpack/msgpack-php
  - must be installed as php extension and thus needs some fallback (and that fallback needs to be dynamically recognized)
- https://github.com/igbinary/igbinary
  - must be installed as php extension and thus needs some fallback (and that fallback needs to be dynamically recognized)
- develop a new binary coding
  - we only have numerical values (not true for geohashes ...) and no relevant array keys
  - e.g. a few bytes for a header and then each value as char/short/long depending on header

I found some php class that does not need to be installed as igbinary or msgpack, don't know if it's good: http://www.phpclasses.org/package/5242-PHP-Serialize-and-unserialize-values-in-binary-format.html#view_files/files/26449

More links:
https://igor.io/2012/09/24/binary-parsing.html

**Comment by mipapo** [comment]
* 3 byte - "RUN" (ASCII, also 52 55 4E in hex)
 * 1 byte - Versionsnummer des Formats (erstmal also 01 in hex)
 * 1 byte - enum des Feldtyps (z.B. 0: char, 1: short, 2: long, 3: geohash, ... (unsigned brauchen wir auch für Temperatur))
 * 2 byte - Datenlänge (die uns garantiert, dass die Daten am Ende nicht korrupt sind)
 * x bytes - Array selbst

Reader, Writer, Fieldtype (abstract, mit static 'factory') + für jeden Feldtyp eine eigene Klasse.

For inspiration: https://github.com/rotano/BinaryIO/

**Comment by laufhannes** [comment]
The enum should distinguish between successive values (time as `1, 3, 5, 6, 9, ...`) and additive values (time as `1, 2, 2, 1, 3, ...`) as well. Time and distance should probably be saved with additive values.

**Comment by grzeg1** [comment]
I investigated BSON once and during the analysis it turned out that binary data can actually take more space than text numeric values delimited (binary data has to be fixed size, delimited values are variable size). 
So gzcompress is definitely a good choice, alternatively it could be mysql's compress/uncompress or even compressed row format (this way it would require no changes to php code).

**Comment by mipapo** [comment]
@grzeg1 Using mysql's compress/uncompress row format seems to be really slow. I tried it with our data on two systems and the performance wasn't that good after that. 
Binary coding + gzcompress would reduce the communication between webserver and database server. And the user db backups would be smaller.

**Comment by grzeg1** [comment]
I'd say yes to gzcompress if needed, but no to binary data - as I wrote before, for Runalyze-like arrays binary data tends to be larger than plain text data.
Check it out.

**Comment by laufhannes** [comment]
Well, BSON is different to what we want to do. BSON needs to allow all types and saves field types and field names for every field (+ additional x00). It is not surprising - especially for typical json data with named keys - that it may take even more space.

I don't understand your point that "binary data has to be fixed size"? Am I missing something about binary data? 
For e.g. heart rate we'll use one byte (unsigned char) for each value (giving a range of 0 - 255). Our current database representation as a string requires two or three bytes (two chars for `60`, three for `123`) plus one byte for the `|` delimiter. Yes, that length is variable, but that does not help if it's still larger.

Yes, it's not that easy for all arrays. For time and distance, we'd have a problem if we want to save distance in meter not considering additive values. To allow distance values above 100.00 km, we'd need four bytes for every value (unsigned long), even for low values producing some overhead. (Still, four bytes is less than what a string of '100.000|' requires.) And for geohashes there's probably no real difference between a new binary approach and the current representation (in the geohashes branch), as they are still strings and we only save the delimiter.

Anyway, we'll try that out and compare size and performance.

**Comment by grzeg1** [comment]
I said about BSON as I was comparing BSON to JSON the other day and was surprised it was actually bigger (because of fixed size).
You're right as for heart rate, it can fit in one byte. Same probably for cadence.
Distance entries look now like 1.0234 so indeed 4 bytes unsigned long would be enough as these can be saved as fixed precision and without comma (so it's even possible to increase precision). Even 3 bytes could be enough as 255*255*255/10000=1658 which is way bigger than the longest real activity.

**Comment by laufhannes** [comment]
Yes, three bytes are enough. But as far as I can see php's (un)pack function does not provide any three-byte-datatype. I'm not sure how easily reading/writing three chars for one value does work in that case.

**Comment by grzeg1** [comment]
To be architecture independent I think we need a custom code/decode function anyway.

**Comment by laufhannes** [comment]
Php's [pack()](http://php.net/manual/en/function.pack.php) function offers among other things the following architecture independent types:
> `c` - signed char
> `C` - unsigned char
> `n` - unsigned short (always 16 bit, big endian byte order)
> `N` - unsigned long (always 32 bit, big endian byte order)
> `J` - unsigned long long (always 64 bit, big endian byte order)

**Comment by mipapo** [comment]
+ There should be binary encoding typ for arrays which are always just increased by 1 or a steaby value. (Maybe: increasing value | (startvalue) | expected end value).

Would be cool to have an idea for repeating values too, but that's not that easy

**Comment by laufhannes** [comment]
That's only possible if there is a known 'pattern' (which is never the case). The general handling of reducing recurring data will be done by `gzcompress()`.

**Comment by laufhannes** [comment]
For reference: http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/cookbook/advanced-field-value-conversion-using-custom-mapping-types.html

**Comment by mipapo** [comment]
This issue is invalid now - We will just compress/minify the time array and change the storage type of trackdata, swimdata, hrv, route afterwards
