### ISSUE TITLE
Plots: selection tooltip partially hidden

### ISSUE THREAD

**Issue by Sp33dfreak** [Runalyze/Runalyze#1557]
![hidden](https://cloud.githubusercontent.com/assets/15370214/10833988/09468d04-7e96-11e5-9b07-364eaafdce08.PNG)
When i select a part of the Pace /HR Diagramm at the right end of the Diagramm, the tooltipp is partially hidden. Tested on FF (v41.0.2) & Edge

**Comment by laufhannes** [comment]
Removing `.training-row-plot { overflow: hidden; }` in [runalyze-training.less#78](https://github.com/Runalyze/Runalyze/blob/support/2.2.x/lib/less/runalyze-training.less#L78) solves the problem, but the commit 959bd2efd169efce0befc974336ea5fbb7eb1c65 from september '14 states that it fixes some styling bug. I just don't know which kind of bug ...

**Comment by laufhannes** [comment]
I could not detect any problems and, especially, I couldn't find any other solution than removing this overflow definition. If this causes troubles again, please find another solution than adding this definition again.
