### ISSUE TITLE
Disable account activation in application config

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1567]
For local installation without mail server or internet connection

**Comment by laufhannes** [comment]
In theory, 'localhost' installations should not set any activation hash, see https://github.com/Runalyze/Runalyze/blob/master/inc/system/class.AccountHandler.php#L223:
```php
$activationHash = (System::isAtLocalhost()) ? '' : self::getRandomHash();
```

**Comment by mipapo** [comment]
This check just seems not to work...
