### ISSUE TITLE
Pass-through filter for activities

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1576]
Test files are in `Supportticket #000114`.

TCX file contains a lot of datapoints without heart rate data. This data should be filled with next valid value, similar to our 'pace-fix' for Runtastic files (which is not in master as we don't save pace in trackdata anymore).

**Comment by grzeg1** [comment]
How about creating a pass-through filter for activities that would accept an object and return a filtered/corrected object? It would be input-format independent then.

**Comment by laufhannes** [comment]
The filter should be applied in abstract parser after parsing the file to correct heart rate data, am I right? Sounds good.

**Comment by grzeg1** [comment]
Could correct anything, like null positions at the beginning of the file, out-of-range data etc.
There could be even a set of options for choosing what to correct.
Filter could also be the place where altitude correction is done.

**Comment by laufhannes** [comment]
For internal use only or as a tool that can be applied by users for "defect" activities?

I could think of both:
 - filtering new activities with some default options
 - tool to correct existing activities with options to be chosen by user
   - could be linked instead of showing an internal server error when activity view fails due to wrong array sizes

**Comment by laufhannes** [comment]
+1 via Support-Ticket 000352

**Comment by jjqoie** [comment]
Please review - during import it use LastValidHR to fill the gaps

[class.ParserTCXruntasticSingle.php.txt](https://github.com/Runalyze/Runalyze/files/138856/class.ParserTCXruntasticSingle.php.txt)

**Comment by laufhannes** [comment]
This ticket will handle the pass-through filter. Your fix is applied and tracked in #1742.

**Comment by laufhannes** [comment]
The commits fixed #1917 and not this one, of course.

**Comment by laufhannes** [comment]
Another case that could be added to the filter later on: #1951 (too big value for stride length)

**Comment by laufhannes** [comment]
In general, all values should be checked for their range and set to null if they are invalid (see #1951 for stride length and #1980 for fit training effect).
