### ISSUE TITLE
Update to v2.2: don't run sql queries if no account exists

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1580]
It seems that people don't read upgrade instructions ...

**Comment by mipapo** [comment]
It's not surprising...
The problem I see is that we have to update the current release 2.2. Because users may think that they first have to install 2.2 and then 2.2.1...

**Comment by laufhannes** [comment]
Just state in the release notes of v2.2.0 that users should update directly from v2.1.0 to v2.2.1. It's their problem if they don't read warnings and hints.
