### ISSUE TITLE
upgrade to 2.2 / single-user install of 2.1 / duplicates in table

### ISSUE THREAD

**Issue by KarolTx** [Runalyze/Runalyze#1582]
Hi,

I retried the steps in the upgrade guide several (at least 5) times (everytime from a fresh copy of the backup) and everytime I got duplicates in sports types, plugins, panels.
In 2.1 I had few activity types renamed (just lower case) and after I created a new account, the sports and activity types were reinserted along with new conf-entries for panels and plugins.

I tried to copy just one row from the account table and start from the backup: as didn't execute step 2., only inserted the copied row into the account table. However this didn't end well either, f.e.:
"Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`runalyze`.`runalyze_plugin_conf`, CONSTRAINT `runalyze_plugin_conf_ibfk_1` FOREIGN KEY (`pluginid`) REFERENCES `runalyze_plugin` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)' in /opt/lampp/htdocs/runalyze/inc/system/class.PDOforRunalyze.php:267 Stack trace: #0 /opt/lampp/htdocs/runalyze/inc/system/class.PDOforRunalyze.php(267): PDO->query('INSERT INTO `ru...') #1 /opt/lampp/htdocs/runalyze/inc/system/class.PDOforRunalyze.php(167): PDOforRunalyze->query('INSERT INTO `ru...') #2 /opt/lampp/htdocs/runalyze/inc/plugin/config/class.PluginConfiguration.php(113): PDOforRunalyze->insert('plugin_conf', Array, Array) #3 /opt/lampp/htdocs/runalyze/inc/plugin/config/class.PluginConfiguration.php(92): PluginConfiguration->insertValueToDatabase(Object(PluginConfigurationValueBool)) #4 /opt/lampp/htdocs/runalyze/inc/plugin/config/class.PluginConfiguration.php in /opt/lampp/htdocs/runalyze/inc/system/class.PDOforRunalyze.php on line 267"

Any ideas?

**Comment by mipapo** [comment]
When you mean single-user installation: Do you mean you don't have to login?
Then try this https://gist.github.com/mipapo/349bfa25962ede059eb6 insted of the switch-accountid-to-1.sql

**Comment by KarolTx** [comment]
Hi mipapo,

maybe I "over"-complicated things.
In few words, when I follow steps http://docs.runalyze.com/en/latest/update.html#upgrade-from-2-1-to-2-2, I repeatedly end up with duplicate panels. If I then take a look a the settings I see that the plugins are duplicated too etc.
Anyway, as this is not working, I will try to migrate my 2.1 data to to clean 2.1 multiuser setup and then ugrade to 2.2.

**Comment by mipapo** [comment]
Well but like I said: please try the changed switch-accountid-to1.sql I posted in my last entry. I think we missed the double entries because users have to make the new account

**Comment by laufhannes** [comment]
Yes, that's kind of what @mipapo's gist tries to do.

Registering a new account will automatically insert default dataset/plugins etc. and thus they'll be duplicated after switching all existing data to the new account. I'm wondering if there are really only a few people switching from single- to multi-user installtion or what's the reason for not everybody crying that it does not work.

This is probably something that needs to be fixed in v2.2.1.

**Comment by laufhannes** [comment]
... as always, @mipapo and I am doing same things at the same time.

**Comment by KarolTx** [comment]
Thanks, that solved it. I will use it for a time and report back if anything pops out again..
