### ISSUE TITLE
Bring back Weather Equipment analysis

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1583]
Just a bit related to #1503

**Comment by mipapo** [comment]
Current state would be okay for 2.3

**Comment by laufhannes** [comment]
For me, none of the equipment tables does work.

By default, no equipment type is chosen:
![bildschirmfoto 2015-11-26 um 20 38 42](https://cloud.githubusercontent.com/assets/8313118/11429864/f15d7e5c-947d-11e5-9d3f-5f23101ec8bd.png)

But for my shoes
![bildschirmfoto 2015-11-26 um 20 39 02](https://cloud.githubusercontent.com/assets/8313118/11429865/f1624180-947d-11e5-97d6-6543fd73da83.png)

and for my clothes
![bildschirmfoto 2015-11-26 um 20 39 19](https://cloud.githubusercontent.com/assets/8313118/11429866/f164e4e4-947d-11e5-9dfe-1620491be745.png)

they are definitely wrong.
