### ISSUE TITLE
Exception for fit file  (Sport pace unit)

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1585]
Line 65 in Laps.php
File https://drive.google.com/file/d/0B-U5BzbXUeKYTHJDdDRVcld0cVk/view?usp=sharing
```
 [Fri Nov 20 20:43:08.479229 2015] [:error] [pid 5573] [client 127.0.0.1:44922] PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'Invalid option ("") for select value.' in
/home/mpo/htdocs/run20/inc/core/Parameter/Select.php:35\nStack trace:\n#0 
/home/mpo/htdocs/run20/inc/core/Parameter/Application/PaceUnit.php(104): Runalyze\\Parameter\\Select->set('')\n#1 
/home/mpo/htdocs/run20/inc/core/Model/Sport/Object.php(146): Runalyze\\Parameter\\Application\\PaceUnit->set('')\n#2 
home/mpo/htdocs/run20/inc/core/View/Activity/Plot/Laps.php(65): Runalyze\\Model\\Sport\\Object->paceUnit()\n#3 /home/mpo/htdocs/run20/inc/core/View/Activity/Plot/ActivityPlot.php(79): Runalyze\\View\\Activity\\Plot\\Laps->initData(Object(Runalyze\\View\\Activity\\Context))\n#4 /home/mpo/htdocs/run20/inc/training/view/section/class.SectionLapsRowManual.php(22): Runalyze\\View\\Activity\\Plot\\ActivityPlot->__construct(Object(Runalyze\\View\\Activity\\Context))\n#5
/home/mpo/htdocs/run20/inc/training/view/class.TrainingViewSectionRow.php(64): SectionLapsRowManual->setPlot()\n#6
 /home/mpo/htdocs/run20/inc/training/view/section/class.SectionL in /home/mpo/htdocs/run20/inc/core/Parameter/Select.php on line 35, referer: http://run.mipapo.de/index.php 
```

**Comment by laufhannes** [comment]
This is probably the same as #1562. The above error is generated if an activity has no sportid.

It seems that the multi-inserter does not set the default sportid.

**Comment by mipapo** [comment]
So when you're importing such a file without editing any values this will happen? Correct?

**Comment by laufhannes** [comment]
That's my guess, yes. (So, it can only happen if you upload more than one file. Otherwise the form will show up and there is no option to select no sport type.)

**Comment by laufhannes** [comment]
- [ ] [Activity/Inserter.php](https://github.com/Runalyze/Runalyze/blob/support/2.2.x/inc/core/Model/Activity/Inserter.php#L105-L116) should use `\Runalyze\Configuration::General()->mainSport()` if no sportid is set.
 - [ ] [Parameter/Select.php](https://github.com/Runalyze/Runalyze/blob/support/2.2.x/inc/core/Parameter/Select.php) should get a property `UseFallback = false;` which can be set to true such that [$Select->set(...)](https://github.com/Runalyze/Runalyze/blob/support/2.2.x/inc/core/Parameter/Select.php#L34-L36) does not throw exceptions. (Maybe this can be true by default)
 - [ ] We need an update script to fix missing sportids.

**Comment by mipapo** [comment]
Update script should use main Sport for missing sportids? Correct?

**Comment by laufhannes** [comment]
Yes. I guess that's possible with a query (so: no need for a refactor script in that case).
