### ISSUE TITLE
New Running Dynamics: GCTB and vertical ratio

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1587]
add vertical ratio support and ground contact time balance (running dynamics)

**Comment by mipapo** [comment]
Left TODOs: 
- [ ] Unittests
- [ ] Check db export/import
- [ ] Average of the added values
- [ ] Graphs

**Comment by mipapo** [comment]
- [ ] Vertical Ratio should be calculated on the fly

**Comment by laufhannes** [comment]
See http://www8.garmin.com/manuals/webhelp/forerunner630/EN-US/GUID-2C73735B-C792-412D-AA92-706A8647DD77.html and http://www8.garmin.com/manuals/webhelp/forerunner630/EN-US/GUID-B917540E-186D-4546-943F-4CD694B11BDC.html for color-definitions.

**Comment by laufhannes** [comment]
Search added in 7122fb574bc91cc88ce39cfab8843e657e271df4.
