### ISSUE TITLE
Configuration tab for tags

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1599]
Follow up for #1048.

**Comment by mipapo** [comment]
For deleting unused tags use:
`DELETE FROM runalyze_tag WHERE id NOT IN (SELECT tagid FROM runalyze_activity_tag) AND tag NOT IN ('Technice','Ćwiczenia biegowe','Lauf-ABC', 'Running drills', 'Loop ABC', 'tècnica');`
