### ISSUE TITLE
garmin communicator plugin: wrong api key?

### ISSUE THREAD

**Issue by Sp33dfreak** [Runalyze/Runalyze#1604]
when i open the garmin communicator plugin, i'm getting the message "The plug-in was not unlocked successfully. The administrator has to set the correct API-key."

**Comment by mipapo** [comment]
Where?
Then get your api key? https://my.garmin.com/api/communicator/key-generator.jsp

**Comment by Sp33dfreak** [comment]
sorry, i'm testing the beta
Its on svn.runalyze.com -> "training hinzufügen" -> Garmin Comm.
so I think its your api key

**Comment by mipapo** [comment]
Then say that ;) I have set the API key now. Please check it.

**Comment by Sp33dfreak** [comment]
haha thought that my ticket gets autotagged with "BETA or something like that, when i go to github -> milestone -> Beta relase and than -> click new issue... ;-) 

just checked it. same message. still the same after log out and login again

**Comment by mipapo** [comment]
Okay. Still it's no bug. Just ignore it and upload your activity via the file upload.
I will try to get it work, but it's no real bug.

**Comment by mipapo** [comment]
@Sp33dfreak Important question. Do you access the page via svn.runalyze.com or svn.runalyze.de?

**Comment by Sp33dfreak** [comment]
unlike written in my first answer i'm accessing the page via svn.runalyze.de.
...dot com works like charm

**Comment by mipapo** [comment]
Then just use svn.runalyze.com. I will add a rewrite from .com to .de
