### ISSUE TITLE
Glossary

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1611]
Abbreviations and some important definitions should get their own description window.

**Expected result:**
- terms like 'VO2max' are displayed with a dashed underline and linked to an overlay
- the overlay shows some information, e.g. a definition, some hints, graphics and references

**How it should be done:**
- glossary topics must be translatable
- glossary topics should be maintained as additional repository
- untranslated topics are shown in English with a message like _'This topic is not available in your language. Help to translate it at ...'_

**My ideas so far ...**
- glossary topics are written in markdown
- a build process creates html files
- `Runalyze/glossary`
  - contains the glossary itself, i.e. `topics/vdot/en.md` (translations get their own file)
  - contains the build file to generate `html/en/vo2max.html`
- `Runalyze/glossary-dist` could contain current html files of a current build (webhook based)
- `Runalyze/glossary-provider` could contain php classes to provide the glossary, i.e. mainly a static method to create links if the requested topic exists (`glossary-dist` could provide an index of available topics as php array)

**Comment by mipapo** [comment]
<3
