### ISSUE TITLE
Update von V. 2.1 auf V. 2.2.1 - refactor-equipment.php Zeile 123

### ISSUE THREAD

**Issue by pinguinside** [Runalyze/Runalyze#1612]
Ich hatte bei o.a. Update beim ausführen der refactor-equipment.php immer wieder einen Fehler:

<b>Fatal error</b>:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'language' in 'field list'' in /homepages/runalyze/refactor-equipment.php:123
Stack trace:
#0 /homepages/runalyze/refactor-equipment.php(123): PDO-&gt;query('SELECT \`id\`, \`l...')
#1 {main}
  thrown in <b>/homepages/runalyze/refactor-equipment.php</b> on line <b>123</b><br />

Der besagt das das Script in einer Tabelle eine Spalte "language" nicht findet.

Nach kurzem Nachsehen im Script + Datenbank hab ich festgestellt das es sich um die Tabell "PREFIX_account" handelt, es aber in dieser keine Spalt "language" gibt.
Weiterhin konnte ich im Script "refactor-equipment.php" keine weitere Verwendung des Inhalts dieser Spalte erkennen.

Lösung:

Ich habe die Zeile 123 der "refactor-equipment.php" von:
accounts = $PDO->query('SELECT \`id\`, \`language\`  FROM \`'.PREFIX.'account\` WHERE \`refactored\`=0 LIMIT '.    LIMIT);

auf: 
accounts = $PDO->query('SELECT \`id\`  FROM \`'.PREFIX.'account\` WHERE \`refactored\`=0 LIMIT '.    LIMIT);

geändert. als " ,\`language\` " entfernt.

Mit dieser Änderung lief die "refactor-equipment.php" ohne Fehler durch.

**Comment by mipapo** [comment]
Ja schön, dass du das geändert hast, aber das hat schon einen Grund, wieso das da steht:
Das scheint als wäre deine Version noch gar nicht auf Version 2.1 oder 2.0 gewesen? 
Bzw du hattest keinen Account angelegt http://docs.runalyze.com/en/latest/update.html#upgrade-single-user-installation

**Comment by pinguinside** [comment]
Meine Version war auf 2.1 + Multiuser. Aber seltsamer Weise gab es keine Spalte für die Sprache bei den accounts. und gibt es jetzt auch nicht.

**Comment by mipapo** [comment]
Dann ist schon vorher etwas beim anderen Update falsch gelaufen. Was können wir dir auch nicht sagen. Auf jeden Fall macht deine genannte Änderung oben kein Sinn.

**Comment by pinguinside** [comment]
okey das scheint dann so zu sein, dann muss ich nochmal nachsehen, Danke für die schnelle Info.
