### ISSUE TITLE
Number of steps

### ISSUE THREAD

**Issue by weechatter** [Runalyze/Runalyze#1623]
Would be fine to have an "item" that will display the number of steps done during the activity

**Comment by laufhannes** [comment]
+1 via http://forum.runalyze.de/viewtopic.php?t=332&p=1305#p1305

**Comment by mipapo** [comment]
@laufhannes new column in training? 
Like for step length we would need a switch for steps and rotation (running and other sports?)

**Comment by laufhannes** [comment]
I'd just compute on the fly. I don't see a need to use this value in any queries. Imho it's not a big drawback if this field is not searchable.

**Comment by mipapo** [comment]
I don't like the naming of "total cadence", but had no better idea.
