### ISSUE TITLE
Support stryd (check)

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1628]
File https://drive.google.com/open?id=0B-U5BzbXUeKYRkd5Yk1oT2RYUDQ

**Comment by mipapo** [comment]
Works fine if "Power" is enabled in the sport configuration and "Calculate power" is deactivated in the general settings

**Comment by mzielinskim** [comment]
Please support stryd Footpod. 
The solution only shows the average Power of the Workout but no Curves:
-IQ Power
-IQ Cadence
-IQ ground Time
-IQ Vertical Oszillation
also they announced to implement nanother measurement: IQ Leg Stiffnes

https://drive.google.com/file/d/0B1dzNIuqSoyYdnVSTGNORDFlRHM/view?usp=sharing

**Comment by mipapo** [comment]
@mzielinskim All values except "IQ Leg Stiffnes" are already supported

**Comment by mzielinskim** [comment]
Shure? Cadence/ground Time/Vertical Oszillation are 2 times in that file: 
1 from garmin HRM
2.From Stryd Footpod

I only saw the garmin ones..in runalyze. have to test what happens when i  dont use the garmin HRM.

**Comment by mipapo** [comment]
@mzielinskim you didn't told us that in your first answer. The original FIT values take precedence over the IQ fields. And I don't see a reason to change this.

**Comment by mzielinskim** [comment]
That is O.k. !! Thanks.

**Comment by mipapo** [comment]
@mzielinskim Please open a new issue for "Importing "IQ Leg Stiffnes" from fit files" 
Please include more information about the meaning of that value
