### ISSUE TITLE
Problem with dataset configuration if empty

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1629]
Strange behavior in dataset configuration window. Unchecking some fields does not work always.

See http://forum.runalyze.de/viewtopic.php?t=287&p=1091#p1091

**Comment by laufhannes** [comment]
Not directly related to the users problem (can't uncheck splits): keys which must be shown (sport type and duration) are not disabled.

**Comment by laufhannes** [comment]
Bug identified: if dataset is empty, default configuration is loaded. But that will result in `true == $this->Configuration->exists(...)` and thus the config tab will try to update instead of insert dataset fields.

**Comment by mipapo** [comment]
Seems not to be working again
