### ISSUE TITLE
VDOT value in dataset is not altitude-adjusted

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1633]
I guess it should be. At least the summary value at the bottom of dataset is.

**Comment by laufhannes** [comment]
I think `Keys\VdotValue::column()` and `Keys\VdotIcon::column()` should be the following:
```php
public function column() {
    if (\Runalyze\Configuration::Vdot()->useElevationCorrection()) {
        return 'vdot_with_elevation';
    }

    return 'vdot'; ? 'IF(`vdot_with_elevation`>0,`vdot_with_elevation`,`vdot`)*`s`' : '`vdot`*`s`';
}
```

The `SummaryMode` uses
```php
$Sum = 'IF(`vdot_with_elevation`>0,`vdot_with_elevation`,`vdot`)*`s`' : '`vdot`*`s`';
```
but I think the dataset classes don't support such a value and `vdot_with_elevation` should be equal to `vdot` if elevation is zero. @mipapo: Can you check in our database if there are activities with `vdot_with_elevation = 0 AND vdot > 0`?
