### ISSUE TITLE
Use phpfastCache via composer

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1634]
Use phpfastCache via composer

**Comment by laufhannes** [comment]
Reopened as https://github.com/Runalyze/Runalyze/issues/1281 is again the case. We need to apply https://github.com/Runalyze/Runalyze/commit/c041c650b94517c570cd8e8d8bad51cedd15df0c to an own fork of phpFastCache.

**Comment by mipapo** [comment]
https://github.com/Runalyze/phpfastcache

**Comment by mipapo** [comment]
Pull request was accepted. https://github.com/khoaofgod/phpfastcache/pull/156#event-494888760
