### ISSUE TITLE
Exporter Sharing with/or without link

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1636]
- Share with link if public activity
- Share without link when it's a private activity  (and just general information sport/km/time/pace)

**Comment by laufhannes** [comment]
- [x] HTML does work
 - [ ] Twitter: just leave `url=` (otherwise referrer will be added)
 - [ ] Google: should not be possible (I don't know a way to share content without url)
 - [ ] Facebook: probably the same as for Google

**Comment by laufhannes** [comment]
Facebook seems to work without url. Still, there's a slash too much in `$image = System::getFullDomain(true).'/web/assets/images/runalyze.png';` and this image won't work for non-public web servers anyways.

**Comment by laufhannes** [comment]
Fixed since f273d402534831922c76986a32e3a8be1a1c6d8b.
