### ISSUE TITLE
No average in plot combination

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1639]
via runnersworldforum 
http://forum.runnersworld.de/forum/pulsuhren-gps-trainingssoftware/71147-kick-off-runalyze-lauftagebuch-16.html#post2090535
"Wenn ich in der Übersicht eines Laufes im "kombinierten Diagramm" einen Abschnitt markiere, wurde mir sonst in einem Tooltip z.B. die markierte Streckenlänge, die Zeit des Abschnitts sowie die Durchschnittspace angezeigt. Dies ist aktuelle nicht mehr der Fall, der Tooltip zeigt mir die Werte an, die an der letzten Position des Mauszeigers vorliegen."

**Comment by laufhannes** [comment]
```
scripts.js?v=2.3.0:7116 Uncaught TypeError: series.yaxis.tickFormatter is not a function
```
