### ISSUE TITLE
Import gpx file with no GPS data

### ISSUE THREAD

**Issue by guancio** [Runalyze/Runalyze#1645]
First thanks for the great system.
It would be nice to be able to import gpx files having no GPS coordinates.
For workouts, for example, can be useful to import hearth rate sensors.
For treadmills, can be useful to import cadence and computed distance and speed.

**Comment by laufhannes** [comment]
Do you have a sample file for us?

**Comment by laufhannes** [comment]
It could be enough to remove the `return` in https://github.com/Runalyze/Runalyze/blob/support/2.3.x/inc/import/parser/class.ParserGPXSingle.php#L196-L197 and set lat/lon to null instead, but I'm not sure if there are any drawbacks for files with gps data.

**Comment by guancio** [comment]
I was uploading an example and I understood that this is a problem of my files.
I record activities with Wahoo fitness, upload to Strava then sync to dropbox using tapriik.
I just realize that the resulting file (for treadmill work) has not data at all. I imagine this is due to Strava non-exporting the data correctly.
I'll try to obtain the gpx file directly from Wahoo fitness.

**Comment by guancio** [comment]
I'm sorry, the problem was my gpx files. I'm now importing a tcx directly from Wahoo and it works.
