### ISSUE TITLE
Put Power instead of Stride length in lap window for Cycling when cadence is available

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1650]
now it's stride length which just makes no sense

**Comment by mipapo** [comment]
@laufhannes This is related to the dataset class currently?  
The problem is that it's a general name. The dataset could switch the name depending on the sport (#1479) ?, but this makes no sense when the dataset is used to show multiple activities like in the databrowser.

**Comment by laufhannes** [comment]
This has nothing to do with the dataset? And there is no need to change a name as stride length just shouldn't be displayed if the sport type is not running.

The problem here is that lap's calculator does only know trackdata - not the sport type.
