### ISSUE TITLE
Sport aus FIT Datei

### ISSUE THREAD

**Issue by uk3** [Runalyze/Runalyze#1654]
Hallo,

mir ist aufgefallen dass beim Import von FIT-Dateien (von meinem Forerunner 310XT) der Sport nicht automatisch ausgewählt wird (obwohl die information cycling o. running im FIT File enthalten ist).

Beim Import der TCX Dateien, die der ANT Agent ebenfalls erzeugt, funktioniert die auswahl allerdings sehr wohl.

Nachdem ich den FR sowohl zum Laufen wie auch zum Radfahren verwende, wäre die automatische Zuordnung auch für FIT Dateien ganz praktisch.

Falls notwendig kann ich die FIT zum vergleich zur Verfügung stellen.

lG Ulrich.

**Comment by laufhannes** [comment]
Just as a note: this is related to #1479

**Comment by uk3** [comment]
Hallo,

funktioniert irgendwie noch nicht.
Ich muss dazu sagen, dass ich als main sport "radfahren"

und wenn ich nun versuche, einen Lauf (sport running) aus dem Forerunner zu importieren, kommt er trotzdem als 'radfahren' im runalyze an.

WIe gesagt, beim TCX file geht das richtig, dort kommt die aktivität als laufen an.

**Comment by laufhannes** [comment]
Du müsstest mal https://github.com/Runalyze/Runalyze/blob/master/inc/import/filetypes/class.ImporterFiletypeFIT.php#L76 auskommentieren und schauen, welche Sportart in der *.fit steht. Beim Import bleibt dann jetzt eine *.temp liegen, wo recht weit event eine Sport-Message steht.

https://github.com/Runalyze/Runalyze/blob/master/inc/import/parser/class.ParserAbstractSingle.php#L97-L126 versucht dann, die Sport-ID zu raten. Das klappt natürlich nur, wenn die Sportart auch als "Laufen" etc. angelegt ist und wenn eben ein entsprechender Wert in der *.fit hinterlegt ist.

Eine genauere Zuordnung kann erst mit #1479 geschehen.

**Comment by uk3** [comment]
Hallo,

also das fit enthält mehrfach:
[uk@login runalyze]$ grep sport ./inc/import/files/20151227-122724-1-1446-ANTFS-4-0.FIT.temp
--- sport=1=running

und 1x 
--- sub_sport=0=generic


Das TCX mit dem es funktioniert enthält zum vergleich:
    <Activity Sport="Running">

Kann es sein dass der (uper)case da relevant ist?

lG Ulrich

**Comment by laufhannes** [comment]
Da `mb_strtolower()` verwendet wird, dürfte das keinen Unterschied machen.

"sport" sollte aber eigentlich auch bei einem 
```
= TYPE=? NAME=sport NUMBER=??
```
auftauchen? (Wo dann unterhalb einmal `--- name="..."` und einmal `--- sport=1=running` auftaucht.

**Comment by uk3** [comment]
Hallo,

Das sieht irgendwie anders aus.
ich hab das --- sport=1=running
bei jedem LAP event und einmal beim
TYPE=9 NAME=session NUMBER=18
(dort ist auch der sub-type)

ich hab dir das fit und tcx file jetzt per mail geschickt, dann kannst du selber mal reinschauen.

lG Ulrich.
