### ISSUE TITLE
Default main equipment after registration

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1655]
as in description
I only have shoes as equipment anyway

**Comment by grzeg1** [comment]
one more thing: example value in dataset is empty

**Comment by laufhannes** [comment]
Did you save your sports configuration once since dataset refactoring?

**Comment by grzeg1** [comment]
Ok, I just did that. Then I chose Shoes for Running as they were not chosen. Now everything is fine and an example also shows right.
I misread the description in dataset that tells you to set main type for each sport in sport configuration window - and thought it was  the same equipment as the one to display in stats panel.

Anyway, I guess Shoes should be automatically selected for running sport.

**Comment by grzeg1** [comment]
Thanks for your help, of course ;)
