### ISSUE TITLE
Import of GPX zip file

### ISSUE THREAD

**Issue by uk3** [Runalyze/Runalyze#1656]
Hallo,

ich habe Probleme mit mit dem Import von manchen ZIPs die mehrere GPX files enthalten (genaugenommen wenn die gpx-files von locus pro exportiert worden sind). Fehlermeldung war: PHP Fatal error:  Uncaught exception 'Exception' with message 'Serialization of 'SimpleXMLElement' is not allowed' in /home/user08/uk/html/runalyze/inc/import/class.MultiImporterFormular.php:102

Wenn ich die gpx-files einzeln importiere funktioniert alles fehlerfrei....

Interessanterweise tritt das problem zwar in meiner Eigeninstallation (git master) auf, nicht aber auf www.runalyze.de.

Wenn ich entsprechend 
http://stackoverflow.com/questions/6058966/uncaught-exception-exception-with-message-serialization-of-simplexmlelement
in Zeile 102 ein (string) ergänze, sieht zwar das import-fenster die richtigen daten, aber das importieren selber haut nicht so wirklich hin (da fehlen dann die meisten daten).

Irgend eine Idee, woran das liegen könnte?

**Comment by mipapo** [comment]
Moin,
bitte schicke uns mal per Mail eine Zip mit ein paar locus pro GPX Dateien (mail@)

**Comment by uk3** [comment]
Funktioniert jetzt, danke!

Falls ihr das ZIP trotzdem noch braucht, gebt bescheid.

lG Ulrich.
