### ISSUE TITLE
Add database port to configuration

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1660]
read the title again

**Comment by mipapo** [comment]
@laufhannes Could you check if the connection is working on your system?  I think it should always use the default port, when no port ist given

**Comment by laufhannes** [comment]
There's of course an `Undefined variable: port ` notice if there's no `$port` declaration in `config.php`. But everything works fine.

**Comment by mipapo** [comment]
Added information to https://github.com/Runalyze/Runalyze/issues/1661
