### ISSUE TITLE
Vo2max not shown for cycling

### ISSUE THREAD

**Issue by mzielinskim** [Runalyze/Runalyze#1667]
When i import a Bicycle- Garmin.fit File with Vo2Max then it doenst get shown when selecting Bicycling - it only appears when i upload the same File as Running....

**Comment by mipapo** [comment]
Please provide an example file.

**Comment by laufhannes** [comment]
Guess we don't need an example file. The dataset just hides this value if it's not running, see [FitVdotEstimate.php#L72-L74](https://github.com/Runalyze/Runalyze/blob/support/2.3.x/inc/core/Dataset/Keys/FitVdotEstimate.php#L72-L74):
```php
public function stringFor(Context $context)
{
	if ($context->isRunning()) {
		return $context->dataview()->fitVdotEstimate();
	}

	return '';
}
```

Anyway, it seems that these values are removed from fit files in Garmin's latest beta firmwares.

And: Runalyze itself does only look at VDOT estimates, not at VO2max estimates, and they are only defined for running.

**Comment by mzielinskim** [comment]
I use the 920xt with the Beta Software and yes - the vo2max isnt shown in garmin connect - but it is in the file - it gets shown when i upload the file to runalyze (Forerunner 920XT software version 6.13 Beta)
