### ISSUE TITLE
Export TCX for activities that does not contain gps-data

### ISSUE THREAD

**Issue by guancio** [Runalyze/Runalyze#1679]
An activity (mainly indoor like treadmill and workout) can contain data (e.g. heart rate, pace, cadence) even if there is no gps-data. Can be useful to export such activity as TCX.
I attach one of these activities that has been recorded with Wahoo fitness.

**Comment by guancio** [comment]
[20160107_1839_Treadmill.tcx.zip](https://github.com/Runalyze/Runalyze/files/82540/20160107_1839_Treadmill.tcx.zip)

**Comment by mipapo** [comment]
I will add this to 2.4

**Comment by mipapo** [comment]
https://gist.github.com/mipapo/12100f8e6fd10b34059d
Todos:
- [ ] Add RunCadence & Speed if available

**Comment by mipapo** [comment]
@guancio We have too look into that Treadmill import, because I don't think that you have a Cadence of 348 spm ;)

**Comment by laufhannes** [comment]
Where does the file come from? Strava e.g. has a bug while exporting gpx files, see #1367.

**Comment by laufhannes** [comment]
Some remarks to your gist, @miapo:
 - checking for `$this->Context->hasRoute()` is not enough. A route may exist with only elevation but without latitude/longitude
 - distance of trackdata may be empty (`$Trackdata->distance()` should return 0 in that case)
 - power can be exported similarly to cadence 
 - unit tests are needed for (at least that no error occurs, even better: check data after importing the generated tcx again) ...
   - [ ] no trackdata, no route
   - [ ] trackdata with heart rate, without distance
   - [ ] complete trackdata, no route
   - [ ] trackdata with heart rate, route with elevation
   - [ ] complete activity

**Comment by guancio** [comment]
Hi, if you want I'm experimenting a little bit with this feature.
Regarding the cadence, this is a Suunto footpod connected to Wahoo fitness (Android app). Wahoo shows a cadence of 174 but its export double this number (this happen both if I export to strava or to a tcx file)

**Comment by mipapo** [comment]
@guancio I will work on the points mentioned by @laufhannes this evening.
But you could have a look at the "problem" with the cadence of your file ;)

**Comment by laufhannes** [comment]
I guess that's a simple bug in one of the external services, nothing we or a user can change. We can just apply https://github.com/Runalyze/Runalyze/commit/dc33e00e1fc5213455af9bd5984cc9c4bc12e368 for our tcx parser as well (`correctCadenceIfNeeded()` and `RPM_LIMIT_FOR_CORRECTION` should go into abstract parser and only be called from tcx/gpx parser).

**Comment by mipapo** [comment]
Gist does no check if has geohashes. Cadence added
