### ISSUE TITLE
Catch failed conversion of ttbin Parser

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1682]
If 'Unable to process output format: tcx'

**Comment by laufhannes** [comment]
Where does this happen? Is this the content of the resulting tcx file or where can it be catched?

**Comment by mipapo** [comment]
It's the output on the command line. No file will be generated

**Comment by laufhannes** [comment]
But where does it go when it's called inside of Runalyze? Is it available as return value of `$Command->run()`?

```php
// class.ShellCommand.php#L43
public function run() {
	return shell_exec( $this->command.' 2>&1' );
}

// class.ImporterFiletypeTTBIN.php#L37
public function parseFile($Filename) {
	$this->Filename = $Filename.'.temp.tcx';
	$Command = new ShellCommand(TTBIN_PATH.' -t < '.FRONTEND_PATH.$Filename.'  > '.FRONTEND_PATH.$this->Filename.'');
	$Command->run();

	$this->readFile();
}
```
see [class.ShellCommand.php#L43](https://github.com/Runalyze/Runalyze/blob/support/2.3.x/inc/system/shell/class.ShellCommand.php#L43) and [class.ImporterFiletypeTTBIN.php#L37](https://github.com/Runalyze/Runalyze/blob/support/2.3.x/inc/import/filetypes/class.ImporterFiletypeTTBIN.php#L37)

As many different error messages may be thrown, we should just use
```php
if (!file_exists($this->Filename)) {
	$this->Errors[] = 'Importing your *.ttbin-file did not work. Please compile ttbincnv for your environment.';
	$this->Parser = new ParserTCXMultiple('');

	return;
}
```
in [readFile()](https://github.com/Runalyze/Runalyze/blob/support/2.3.x/inc/import/filetypes/class.ImporterFiletypeTTBIN.php#L63), if no file is generated at all. (Looking at `readFile()` I'd guess that there's always a tcx file as the command line output will be forwarded into that file.)
