### ISSUE TITLE
"Today" navigation in dataset

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1690]
After a few days of playing with it I suggest Today is moved from the center to the right of arrows:
```< > o```
Would make browsing weeks a lot easier.
Actually it's now the third way to move to today: you can click refresh pagem click RUNALYZE just above navigation and now there's Today circle.

**Comment by laufhannes** [comment]
I agree for `< > o`.

And if there's any icon that fits better, we're happy for it!

**Comment by mipapo** [comment]
Refresh is not so innovative. (Many users doesn't know that you can reload a plugin/widget/the databrowser)
When you click RUNALYZE above too much is loaded. This solution is right for me. 
For me it's okay when the 0 is moved to the right...

**Comment by grzeg1** [comment]
I thought about a house icon => home. But I'm not sure if it's more today-ish ;) that the circle.

**Comment by mipapo** [comment]
Well I hope that font awesome will finally have a Today button. It's has been there in a discussion for a long time

**Comment by laufhannes** [comment]
Just as a reference: https://github.com/FortAwesome/Font-Awesome/issues/3609

**Comment by laufhannes** [comment]
Ah, I just see: it was already referenced in #1137.

**Comment by grzeg1** [comment]
To be honest, as there is already one calendar at the left, the circle seems more intuitive than another calendar-like icon....

**Comment by mipapo** [comment]
Yup - Therefore I chose the circle

**Comment by mipapo** [comment]
@grzeg1 So it's fine now? ;) Then I would close this issue

**Comment by grzeg1** [comment]
Yes Sir! ;)
