### ISSUE TITLE
Stats/plugins/chart selection boxes should show current selection

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1691]
I think they should always show current selection instead of text like "Choose sport" etc.
Some of the work done in #1493.
To be done:
- [x] Sports panel
- [x] Equipment panel
- [x] Target panel
- [x] Weather plugin
- [x] Weather temp chart
- [x] Competition plugin trend chart
- [x] Tag analysis
- [x] Monthly training chart (link on dataset)
- [x] Weekly training chart (link on dataset)
- [x] Prognosis panel chart
- [x] Form chart

**Comment by laufhannes** [comment]
Some work done in #1804 / aa0a101.
