### ISSUE TITLE
Search form - delete/add all sports needed

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1692]
Currently it's very user-unfriendly to search just for a single sport workout. You need to click remove for each of the sports you're not interested in.

**Comment by mipapo** [comment]
+1

**Comment by grzeg1** [comment]
"All" does not work for me (Firefox)
It does work in Chrome though.

I also noticed that there are lots of new fields in the filter, but they seem to be placed in random order. E.g. weather data or running dynamics data are not grouped together.

**Comment by mipapo** [comment]
Can reproduce it in firefox & in IE too

**Comment by laufhannes** [comment]
Just a remark: Grouping was previously done in a way such that 'similar values' were grouped column-wise*, not row-wise. That got corrupted as running dynamics (already in 2.3) and weather were added.

* Column-wise looks imho way better.
