### ISSUE TITLE
FIT-Import failing with perl-locale error on FreeBSD

### ISSUE THREAD

**Issue by sr-rolando** [Runalyze/Runalyze#1701]
Hi,

Starting with Runalyze 2.2 (and at least up until 2.3.3), the FIT import doesn't work anymore on a FreeBSD server running nginx. The import used to work with Runalyze 2.1.

The error is logged as:

```
#6 /home/www/runalyze/inc/import/class.ImporterWindow.php(98): ImporterFactory->__co" while reading response header from upstream, client: 46.223.201.157, server: run.sr-rolando.com, request: "GET /call/call.Training.create.php?file=20141221-122353-1-1345-ANTFS-4-0.FIT HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "run.sr-rolando.com", referrer: "http://run.sr-rolando.com/index.php"
2016/01/16 12:09:36 [error] 52174#0: *124368 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Reading *.fit-file failed. First line was "perl: warning: Setting locale failed.".' in /home/www/runalyze/inc/import/parser/class.ParserFITMultiple.php:77
Stack trace:
#0 /home/www/runalyze/inc/import/parser/class.ParserFITMultiple.php(42): ParserFITMultiple->readFirstLine()
...
```

Setting up the following simple test php script, copying it into the runalyze directory on the server and calling its URL in the browser works just fine and does not throw any perl locale error:

```php
<?php
$file = '/var/log/nginx/run.sr-rolando.com.access_log';
$i = 1;
$fp = fopen( $file, 'r' );
while ( !feof ( $fp) )
{	
    $buffer = stream_get_line( $fp, 4096, PHP_EOL );

	if (trim($buffer) != 'SUCCESS') {
		echo "stream_get_line does NOT return SUCCESS<br />";
	}

	/*** this successfully outputs the lines from the log file: ***/
	echo "Line " . $i . ": " . $buffer . "<br />";
	$i++;
	$buffer = '';
}
fclose($fp);
?>
```

Any pointers to support chasing down this error would be much appreciated.

**Comment by laufhannes** [comment]
Can you try to change [inc/system/shell/class.PerlCommand.php#L66](https://github.com/Runalyze/Runalyze/blob/master/inc/system/shell/class.PerlCommand.php#L66) from
```php
$this->command = self::$PERL_PATH.' '.$command;
```
to
```php
$this->command = 'LANG=C '.self::$PERL_PATH.' '.$command;
```

We had to remove that part some time ago as it does not work on windows.

**Comment by sr-rolando** [comment]
Way to go! This indeed works as expected (even though I still don't fully understand why this is explicitly needed when stream_get_line() and thus perl are working in the above test script).

Thanks.

**Comment by mipapo** [comment]
@sr-rolando You're never calling any perl script or command in your test script ;)

**Comment by sr-rolando** [comment]
Neither is the `readFirstLine()` function in `class.PerlCommand.php` that was throwing the error message in the first place.

But anyways. Thanks for the pointer. I now know what to do on updates and will spend the time on running instead of worrying about perl silliness.

**Comment by Strubbl** [comment]
I had the same issue on Debian. I had to run `dpkg-reconfigure locales` and after that it was fine again.

**Comment by mlegner** [comment]
This is still an issue for me in 4.3.x, although the conversion was refactored in 1ac99a417f22f01312b687ce3075c5330ccefecb. I solved the problem by changing the file `inc/core/Parser/Activity/Converter/FitConverter.php` to 
```
protected function buildCommand($inputFile, $outputFile)
{
    return sprintf('LANG=C %s %s "%s" 1>"%s"', $this->PathToPerl, $this->PathToFitPerlScript, $inputFile, $outputFile);
}
```
