### ISSUE TITLE
Synchronization of start/endpoints does not ignore empty points

### ISSUE THREAD

**Issue by uk3** [Runalyze/Runalyze#1702]
Hallo,

beim Ausführen von refactor-night.php ist mir aufgefallen, dass ich bei einigen (~10%) der Routen einen Startpoint von 7zzzzzzzzz habe.
Das liegt offenbar daran dass bei einigen Tracks die erste paar Punkte des Tracks 0-Werte waren (auch zu sehen an der original-Elevation). Das hatte bis jetzt meiner Beobachtung nach keine praktischen Auswirkungen, aber führt nun u.a. dazu dass die Nacht nicht detektiert werden kann.
Vielleicht könnte man hier einfach per script 0-Werte am Anfang eines Tracks aus dem geohash zu entfernen oder nur als Startpoint den ersten von 7zzzzzzzzz verschiedenen Punkt zu verwenden.

lG Ulrich

**Comment by mipapo** [comment]
Es gab mal ein Script welches die ungültigen Koordinaten korrigiert (als wir noch keine geohashes)  hatten. Wenn man das nochmal an die geohashes anpassen würde, müsste man nichts am refactor- Night ändern

**Comment by uk3** [comment]
Hallo,

das hab ich gemeint. es ist mir nur beim refactor-night das erste mal aufgefallen. 

Kommt anscheinend häufiger mal vor, weil es auch bei einem Lauf von letztem Sonntag passiert ist (FIT File vom FR 310). Originellerweise aber nicht nach einem reimport heute. Woran das liegt kann ich aber nicht sagen. (HEAD von Sonntag vs. HEAD von heute...)

lG Ulrich

**Comment by mipapo** [comment]
Das Skript läuft auf jeden Fall wieder durch:
https://gist.github.com/mipapo/8849cfd21c86e7e573ce
Habe gerade nur keine Testdaten mit denen es ordentlich funktionieren würde

**Comment by laufhannes** [comment]
@uk3 Kannst du verifizieren, dass neu hochgeladene Dateien tatsächlich einen falschen Startpunkt in der DB besitzen? (also zB. die Datei von letztem Sonntag)
Eigentlich sollte beim `synchronize()`, was jeweils vor dem Insert aufgerufen wird, in [Route/Entity.php#L401-L435](https://github.com/Runalyze/Runalyze/blob/master/inc/core/Model/Route/Entity.php#L401-L435) jeweils der erste "gefüllte" Startpunkt gewählt werden.

**Comment by uk3** [comment]
Hallo,

ich hab jetzt das File von letztem Sonntag probiert und da ist der Startpunkt reproduzierbar falsch.

**Comment by laufhannes** [comment]
Kannst du mir die Datei einmal schicken? Dann prüfe/fixe ich das.

**Comment by uk3** [comment]
Ist per mail direkt unterwegs.

Es sind immer die ersten 2 Punkte falsch (incl. elevation 0)

lG Ulrich.
