### ISSUE TITLE
build/global.routefix.php

### ISSUE THREAD

**Issue by uk3** [Runalyze/Runalyze#1705]
Hallo,

Wenn ich das script ausführe ist jetzt zwar der Startpoint richtig, dafür sind min und max NULL. Sollte wohl auch so nicht sein, oder?

Ausserdem ist der Ort des scripts ungünstig für Eigeninstallationen die nicht auf 127.0.0.1 liegen, weil das htaccess im build-verzeichnis das ausführen verbietet (was zu Problemen beim update führen könnte).

lG Ulrich.

**Comment by laufhannes** [comment]
Da hast du recht, wird gleich korrigiert.

Was den Pfad betrifft: Wer über das Problem stolpert, muss in dem Fall für das einmalige Durchführen die Datei ins Hauptverzeichnis verschieben. Das traue ich den Nutzern zu (und schreibe zur Not auch die netten, einsilbigen Supportantworten).

**Comment by uk3** [comment]
Hallo,

auch auf die Gefahr lästig zu werden ;-) .... Und ich weiss auch nicht ob es für irgendwas relevant ist, aber, jetzt ist bei den betreffenden routen min überall 7zzzzzzzzz

**Comment by laufhannes** [comment]
Ich bin froh, dass du es jeweils überprüfst - dazu war ich bisher nämlich zu faul ;)

**Comment by uk3** [comment]
Hallo,

:-) 

btw ich hab den query auf  WHERE `geohashes` LIKE  "7zzzzzzzzzzz|%”’ geändert, damit das auf alle fälle immer neu ausgeführt wird.

lG Ulrich

**Comment by mipapo** [comment]
@uk3 was macht das für ein Sinn?

**Comment by uk3** [comment]
Es ging um einen Test ob das Script min und max auf NULL setzt oder es wo anders her kommt. 

Ein import eines Tracks mit 7zzzz… setzt nämlich alle 4 werte (start/end/min/max) richtig. Damit das Script auch über den Track drüber geht, hab ich den Query dahingehend modifiziert weil er sonst ignoriert werden würde. 

Gleiches würde jetzt ja passieren, wenn sich an dem script irgendwo nochmal was ändert wegen min=7zzzzzz 

damit diese routes dann nochmal korrigiert werden ist WHERE `startpoint` = "7zzzzzzzzz”’ nicht mehr ausreichend, weil die startpoints ja jetzt stimmen.

deshalb.

lG Ulrich.

**Comment by mipapo** [comment]
Ich meinte eigentlich "where startpoint =7zzzzz.. Or endpoint=7zzzzu or min=7zzzzz or max=7zzzz. Das sollte ja auch alle nötigen Routen abdecken. Aber ist ja jetzt nicht mehr so wichtig  ;)
