### ISSUE TITLE
Documentation Update: $port usage in config.php

### ISSUE THREAD

**Issue by rob-st** [Runalyze/Runalyze#1713]
To prevent `PHP Notice:  Undefined variable: port in /home/kellercl/public_html/runalyze/inc/class.Installer.php on line 167` the admin-documentation should be updated to mention that the `config.php` needs a `$port` for the database.

Especially helpul for already running (self-) installations that want to update.
Or put an example into the new config-folder.

**Comment by mipapo** [comment]
Please add this do runalyze/docs
