### ISSUE TITLE
Update instructions for refactor script are wrong

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1715]
See Runalyze/admin-docs#4

**Comment by timekiller089** [comment]
Ist jetzt kein Bug, aber eben verwirrend, wenn man aufgefordert wird das Skript anzupassen, dies dann in diesem Falle aber gar nicht erforderlich ist, da die Daten ja in data/config.php stehen.
![update2 4](https://cloud.githubusercontent.com/assets/16840218/12516763/830ba6fc-c12f-11e5-9103-44a2d0b93db0.PNG)

**Comment by mipapo** [comment]
@timekiller089 Steht ja auch im oben genannten Ticket ;)
