### ISSUE TITLE
Update 2.3-2.4: Typo in cache directory?

### ISSUE THREAD

**Issue by sauff** [Runalyze/Runalyze#1717]
Yesterday night I installed 2.4 dev version.
The installation process asked me to make all directories under data/* writeable. So I did. Among others I made the directory data/cache/ writeable. After running refactor-night.php (in fact it was an update from 2.3 to 2.4, not a fresh install) I tried to login. Login failed with the error message that the directory data/cache-/ was not writeable. This directory was not there before. After making data/cache-/ writeable as well everything is fine. Looks like a typo somewhere, because only the cache-directory with the dash in the end (data/cache-/) seems to be used while data/cache/ seems to be empty all the time.

**Comment by mipapo** [comment]
This is a problem by phpfastcache. I already added a ticket there

**Comment by sauff** [comment]
What about removing data/cache-/ and replacing it with a symlink to data/cache/?

**Comment by mipapo** [comment]
We will use an older version. A symlink isn't practical
