### ISSUE TITLE
kleiner Fehler in Garmin Communicator Plugin Erläuterung

### ISSUE THREAD

**Issue by timekiller089** [Runalyze/Runalyze#1718]
![gc_meldung](https://cloud.githubusercontent.com/assets/16840218/12516046/ad8c49ee-c12b-11e5-93bf-65da1fa59608.PNG)

**Comment by timekiller089** [comment]
Äh... wo gibt man denn hier die Version ein?
* Eigeninstallation
* 2.4.-Beta

**Comment by mipapo** [comment]
Die Übersetzung kannst du auch auf translate.runalyze.de selbst korrigieren  ;)

**Comment by mipapo** [comment]
Übersetzung ist gefixt
