### ISSUE TITLE
Activity matcher for garmin communicator fails

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1720]
Anyone out there who can test it? @mipapo and I can't anymore as we have no working devices (and browsers) for it.

There are at least some brackets missing in https://github.com/Runalyze/Runalyze/blob/master/call/ajax.activityMatcher.php#L21:
```php
// currently
$DuplicateFinder = new DuplicateFinder(DB::getInstance);
// better ;)
$DuplicateFinder = new DuplicateFinder(DB::getInstance());
```

In addition, `$DuplicateFinder->checkForDuplicates(array ...)` should be used.

--

Or we just drop the activity matcher, as duplicates should be detected in the next step (right?).

**Comment by uk3** [comment]
Hi,

On Jan 22, 2016 9:16 PM, "Hannes" <notifications@github.com> wrote:

>
> Or we just drop the activity matcher, as duplicates should be detected in
the next step (right?).

+1
In my experience the duplicate detection in the communicator plugin is not
working very reliable anyway.

Lg Ulrich

**Comment by laufhannes** [comment]
It should work now. We'll keep in mind to remove it the next time we have to touch it.
