### ISSUE TITLE
Detection of duplicates doesn't work

### ISSUE THREAD

**Issue by MarcDahlem** [Runalyze/Runalyze#1721]
I didn't upload files since 2 weeks until today.
But now, the duplicate detection doesn't work anymore for me.

I always uploaded my tracks with the garmin communicator plugin; and it did previously only select the new tracks in the upload dialog. But today, it showed me all my tracks on the device as 'new' in the upload dialog.
It would be great, if the old behavior can be reestablished, as it is totally annoying to always unselect all old tracks before uploading only the new ones.

By the way: thanks for the great tool!

Greetings from Kaiserslautern ;-)

**Comment by weechatter** [comment]
Für mich sieht es danach aus, das lediglich ältere Aktivitäten nicht erkannt werden. Also solche die vor der Einführung dieser Funktion angelegt worden sind. Für neuere Aktivitäten erscheint bei mir die Meldung: Es scheint, dass du diese Aktivität bereits importiert hast

**Comment by laufhannes** [comment]
I think there was an error while updating the timestamps we look at. Can you check if it's now working, @MarcDahlem?

--

As internal note for the update script (if it did the trick):
```sql

UPDATE `runalyze_training` SET `activity_id` = `activity_id` + 3600 WHERE `time` - `activity_id` BETWEEN 3600 AND 3659;
UPDATE `runalyze_training` SET `activity_id` = `activity_id` + 7200 WHERE `time` - `activity_id` BETWEEN 7200 AND 7259;
```

**Comment by MarcDahlem** [comment]
@laufhannes At least on your hosted site https://runalyze.com/index.php (account: mdahlem) it does not work. It detects around 10 activities (one I added today and the others from 2014) as already added. But 8 others added today and all other activities on my device (forerunner 305) it does not detect.

**Comment by laufhannes** [comment]
Okay, you are right. There was another bug. (I hate stuff like that, that we can't test ourselves.)
Can you try it again?

For internal notes:
```php
// This part is new and required
$IgnoreIDs = array_map(function($v){
	return (int)floor(strtotime($v)/60)*60;
}, $IgnoreIDs);

foreach ($IDs as $ID) {
	// The following line is new and required
	$dup = $DuplicateFinder->checkForDuplicate((int)floor(strtotime($ID)/60)*60);
	$found = $dup || in_array($ID, $IgnoreIDs);
	$Matches[$ID] = array('match' => $found);
}
```

**Comment by MarcDahlem** [comment]
Yes, it seems to work now. At least, the upload dialog shows all previous tracks as 'vorhanden' (existing). 

Two remarks:

1. I don't know, if new tracks are shown as new (as I don't have new tracks on my device).
2. I had at least one track marked as 'ignored'. This track was now shown as 'new' (I ignored it again).
