### ISSUE TITLE
Embed assets with protocol-relative url or https

### ISSUE THREAD

**Issue by schmidi** [Runalyze/Runalyze#1732]
To avoid mixed content warnings in the browser while accessing runalyze via https, urls should be written with protocol-relative url (//url.example.org) or https://.

Map APIs like google maps should provide assets via https anyway.
![runalyze-mixed-content-warnings](https://cloud.githubusercontent.com/assets/411354/12705072/e881d02e-c869-11e5-8972-63a74133ebef.png)
![runalyze-mixed-content-warnings2](https://cloud.githubusercontent.com/assets/411354/12705095/5e3cd00c-c86a-11e5-9d76-01c3ec450b26.png)

**Comment by mipapo** [comment]
Yep - we just had this thought last week :)

**Comment by mipapo** [comment]
For everyone who wanna use tiles without https support should have a look at https://blog.stadtplan-ilmenau.de/2014/01/tiles-ueber-https/
