### ISSUE TITLE
Wrong calculation of the average HR with LapsComputed

### ISSUE THREAD

**Issue by jjqoie** [Runalyze/Runalyze#1742]
HI
when migrating to runalyze I imported my activities from runtastic and observed a problem with the average HR values in the class.TableLapsComputed.php Table
The problem is that the trackdata of these activities doesn't have for each datapoint a valid HR value. In this case the HR value = 0

The average calculation in Loop.php doesn't consider this
See below my proposed fix for this

best regards
jochen

	/**
	 * Average value for current section
	 * @param string $key
	 * @return int
	 */
	public function average($key)
	{
		if ($this->LastIndex >= $this->Index) {
			return 0;
		}

		if ($this->Object->has($key)) {
			$sum = 0;
			$avg_i = 0;
			for ($i = $this->LastIndex; $i <= $this->Index; ++$i) {
				$new_value = $this->Object->at($i, $key);
				if ($new_value != 0) {				
					$sum += $new_value;
					++$avg_i;
				}
			}
		}

		return $sum / $avg_i;
	}

**Comment by laufhannes** [comment]
Related to #1576 and `Supportticket #000352`.

---

Your fix would result in wrong average values for time series that allow `0` as a valid value (e.g. `temperature`). A simple method argument to enable/disable this fix or to explicitly set the value to ignore would do the job.

And your fix will throw a `Division by zero` error if there are only zeros in the selected segment ;)

**Comment by jjqoie** [comment]
[class.ParserTCXruntasticSingle.php.txt](https://github.com/Runalyze/Runalyze/files/138854/class.ParserTCXruntasticSingle.php.txt)

**Comment by steffenkuss** [comment]
I think this will fix the problem with the laps.
But calculated TRIMP is also not correct.
