### ISSUE TITLE
Import performance condition from fit files

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1747]
There's a large undocumented block before each `event=38` (which contains suggested recovery time in minutes and is written everytime heart rate reaches some recovery threshold after pausing the activity). `xxx17=-2=-2` gives the baseline information, similar to what is shown within the first 12 minutes after starting the activity.

> While the 'Ending Performance Condition' is hidden in a data block seemingly written just prior to when the 'Recovery Advice' time in minutes is (event 38). You see it here as the value -2 third from the end of the section. The block also contains a copy of the recovery time 1164, seventh value from the beginning (present on older watches as well, eg FR620):

```
==
= TYPE=11 NUMBER=140
--- xxx253=824984769=824984769
--- xxx2=3924722=3924722
--- xxx3=5442535=5442535
--- xxx5=873134=873134
--- xxx6=74920840=74920840
--- xxx7=1255223=1255223
--- xxx9=1164=1164
--- xxx10=409=409
--- xxx14=0=0
--- xxx15=0=0
--- xxx16=0=0
--- xxx0=161=161
--- xxx1=0=0
--- xxx4=30=30
--- xxx8=25=25
--- xxx11=1=1
--- xxx12=0=0
--- xxx13=0=0
--- xxx17=-2=-2
--- xxx18=97=97
--- xxx19=0=0
==
= TYPE=2 NAME=event NUMBER=21
--- timestamp=824984769=2016-02-21T10:26:09Z
--- data=1164=1164
--- event=38=38
--- event_type=3=marker
```

**Comment by laufhannes** [comment]
`Supportticket #000526` contains a file that gives the baseline value (on the 100-scale, i.e. `xxx18=97=97`) as our 'hrv score'. Maybe Garmin did change again what's in their event 38.

**Comment by laufhannes** [comment]
I can't confirm that `NUMBER=140` contains the performance condition (fenix3, v7.00). The `NUMBER=140` appears after every pause with values of 0 in the beginning and -8 / -7 later on, while the watch showed a -3. That's what in the `event=39`:
```
= TYPE=2 NAME=event NUMBER=21
--- timestamp=832328189=2016-05-16T10:16:29Z
--- data=97=97
--- event=39=39
--- event_type=3=marker
```

**Comment by MJDevel** [comment]
laufhannes wrote: "I can't confirm that NUMBER=140 contains the performance condition". No, it does _not_. It contains, as I wrote in the mail, the 'Ending Performance Condition' which is continually adjusted during your run, like you saw -8 or -7 (you must have worked hard!). We have Performance Condition within 20 minutes as event 39 on the FR630 (probably on the new FR735XT as well) and the Fenix3. After it has been established, it can be shown as a data-field on the watch, and is tracked in that NUMBER=140 blob when pausing the watch and after the activity is finished - when the event 38 Recovery Advisor time is logged.

Hope that clarifies the issue. Your comment forced me to sign up...

**Comment by laufhannes** [comment]
... and finally we got you here - Thanks for the clarification!

I think it'd be good to track the ending performance condition as well.

**Comment by MJDevel** [comment]
Yeah, it really reflects the exercise. Today I did an hour long run, 20 minutes at 75% of HRMax, then 2 x 10 minutes at 85% of HRMax with 10 minutes at 75% of HRMax in between, and ended with 10 minutes at 75% of HRMax.

Start Performance Condition = +3
End Performance Condition = -4
Training Effect = 3.5

Looking back at those figures in the future, I'll know that it was a really nice training. Perfect in fact. I even got a slight uptick in the VO2Max estimate...

Oh, and by the way, you can go ahead and add the FR735XT to the 'Performance Condition' watches:
http://www8.garmin.com/manuals/webhelp/forerunner735/EN-US/GUID-901ACCFC-FB0D-414E-B80C-54970AF4E357.html

If you don't know how to detect it yet, Ray Maker has made a .fit file public that you can find under the heading "Download Set Files" (it's called set.zip and contains amongst others Garmin-FR735XT-Optical-1171246388.fit) furthest down on the page:

https://analyze.dcrainmaker.com/#/public/27f6ec11-0dd2-43bd-7b5a-16c08beec189

**Comment by mipapo** [comment]
FR 735XT - --- garmin_product=2158=2158
