### ISSUE TITLE
Activity Plot Series Heartrate.php - wrong average heart rate line shown

### ISSUE THREAD

**Issue by jjqoie** [Runalyze/Runalyze#1748]
In the heart rate plot for all my activities the average heart rate line and number is wrong
The wrong value comes from the setManualAverage calculation which looks like a relative heart rate is calculated. I changed it as below but  I don't know maybe there is an option to change the plot view between bpm mode and relative % mode

	public function __construct(Activity\Context $context) {
		$this->setManipulationFactor();
		$this->initOptions();
		$this->initData($context->trackdata(), Trackdata::HEARTRATE, true);
		$this->manipulateData();
	/*	$this->setManualAverage(round(100*$context->activity()->hrAvg()/$this->HRmax)); */
		$this->setManualAverage(round($context->activity()->hrAvg()));
	}

**Comment by laufhannes** [comment]
Try a `git pull` if you're on our master. This should've been fixed five days ago: https://github.com/Runalyze/Runalyze/commit/3f73a9065b7c430e235eb1fb2e33610ed14b2e8c ;)

(So, yes: `correctUnit()` is needed for switching between different hr units)
