### ISSUE TITLE
TCX Upload Endpoint (for mobile App)

### ISSUE THREAD

**Issue by aschix** [Runalyze/Runalyze#1749]
Hallo!
Ich nutze runalyze seit längerer Zeit und will für meine Android App eine upload Funktionalität nach runalyze einbauen.
Ich habe versucht den upload wie er im Browser gemacht wird nachzubauen und einen multipart/form-data request auf http://runalyze.aschix.net/call/call.Training.create.php zu posten.
Ich bekomme aber statt des json response (success=true) immer nur und ein html snippet (klar ist auch ein ajax call).
Aber selbst wenn ich damit noch weiterkomme, ist ja die actitivty nicht gespeichert, oder? Im Browser muss ich auch immer zuerst den create-dialog ausfüllen und speichern.
Gibt es eine einfache Möglichkeit ein txc file auf runalyze rauf zu laden, oder könnte man das einfach einbauen?
Schöne Grüße,
Daniel

**Comment by laufhannes** [comment]
Grundsätzlich soll es dafür im Laufe des Jahres eine offizielle API geben (#498), die im ersten Schritt für die Verbindung mit tapiriik genutzt werden soll. Weitere Services sind aber auch im Hinterkopf (#1648).

Einen "quick&dirty"-Umweg werden wir bis dahin nicht offiziell unterstützen. Wenn das Ganze nur für deine eigene Installation gedacht, kannst du aber natürlich beliebig rumspielen. Eine kleine Diskussion gab es dazu bereits unter https://forum.runalyze.com/viewtopic.php?t=277
