### ISSUE TITLE
Wrong conversion of wind speed?

### ISSUE THREAD

**Issue by realflunschi** [Runalyze/Runalyze#1752]
According to the OpenWeather API documentation ([http://openweathermap.org/current#current_JSON](http://openweathermap.org/current#current_JSON)), wind speed is provided in m/s per default. However, function windSpeed (line 163 of inc/core/Data/Weather/Openweathermap.php) seems to assume that the value is given in mph:
`$WindSpeed->setMilesPerHour($this->Result['wind']['speed']);`

**Comment by laufhannes** [comment]
Seems that you are right!

OWM currently gives 3.61 m/s for my city, which is equal to 12.996 km/h, but Runalyze shows it as 6 km/h. I guess there's no chance to revert this bug for existing activities as we can't be sure which data is from OWM and which is inserted by hand. Or can we assume that people don't set e.g. air pressure by hand?

**Comment by realflunschi** [comment]
Maybe, the update of existing trainings can be made optionally (at least for self-hosted versions). However, I do not mind whether the old trainings are touched by an update or not.

As I have not changed wind speed manually (and use the default prefix), I may run 
`UPDATE runalyze_training SET wind_speed=2.25*wind_speed WHERE wind_speed <> 0;`
to correct the existing DB entries as good as possbile and change line 163 in Openweathermap.php to
`$WindSpeed->setMilesPerHour(2.25 * $this->Result['wind']['speed']);`
as a workaround in my local installation (rather than adding a new public function setMeterPerSecond in WindSpeed.php and use it in Openweathermap.php) for new trainings.
