### ISSUE TITLE
Velocity scaling is off

### ISSUE THREAD

**Issue by pymiras** [Runalyze/Runalyze#1756]
![20160310097](https://cloud.githubusercontent.com/assets/17769439/13679378/bb7a559e-e6f3-11e5-93cc-da0b348fdeef.png)
Die Sakla passt nicht zum Wert in der schwarzen Box. Runalyze v2.4.1

Gruß,
Michael

**Comment by pymiras** [comment]
Ohne "Kurven glätten" passt die Skala. Trackdaten schicke ich Dir per Mail.

**Comment by laufhannes** [comment]
Ich kann das mit der Testdatei weder lokal noch online nachstellen.

Ich vermute, das wurde als #1739 durch 7dbf6d105c01a33732ebc82aadc7e9557929fa92 gelöst und wird in v2.5 nicht mehr auftreten?
