### ISSUE TITLE
no mapview for older tracks

### ISSUE THREAD

**Issue by pinguinside** [Runalyze/Runalyze#1758]
Hello, i use the version 2.4.1 on my own server and Multiuser.
Today i noticed that the ativitis bevor 13.02.15 have no map view.

I think i found the GPS Data in the mySQL Database Tabel "_route" but, i have no display in the Programm.

The hights, heartbeat and time are displayed.

Did anyone know how to fix this?

greets

**Comment by mipapo** [comment]
Are you sure that you had executed the refactor-geo.php script during the update? 
http://docs.runalyze.com/en/latest/update.html#upgrade-from-2-2-to-2-3

**Comment by pinguinside** [comment]
i'm not sure, can i try this now? with the newer version?

**Comment by mipapo** [comment]
It should work - but we cannot give any guarantee

**Comment by pinguinside** [comment]
ok i tryed it and i think it worked, thanks for your quick help..:)
