### ISSUE TITLE
No timezone is set in registration process

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1777]
`timezone` is missing in [AccountHandler::createNewUserFromPost()](https://github.com/Runalyze/Runalyze/blob/support/2.4.x/inc/system/class.AccountHandler.php#L226-L228):
```php
$newAccountId   = DB::getInstance()->insert('account',
	array('username', 'name', 'mail', 'language', 'password', 'salt' , 'registerdate', 'activation_hash'),
	array($_POST['new_username'], $_POST['name'], $_POST['email'], Language::getCurrentLanguage(), self::passwordToHash($_POST['password'], $newSalt), $newSalt, time(), $activationHash));

```

**Comment by laufhannes** [comment]
Which timezone should we use? We can only detect an timezone id based on lat/lng coordinates but we don't have them. We could look at the javascript timezone offset, but that gives an offset in minutes only - no exact timezone.

**Comment by mipapo** [comment]
What about using https://github.com/moment/moment-timezone for the beginning on the registration page (as a hidden field). 
`var tzString = moment.tz.guess(); // returns eg "Australia/Sydney"`
Check in registration formular if it's a valid timezone and save that on in the database?
