### ISSUE TITLE
Automatically load elevation data for activities with gps but without elevation profile

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1778]
*.ttbin-files are an example for that. I don't see a reason to not load elevation data by default for those files.

**Comment by weechatter** [comment]
How about a check-button in the Add-workout-Form? Maybe there is a reason to not load elevation data for an workout, for example track and field training.

**Comment by laufhannes** [comment]
I think it's easy enough to remove elevation data afterwards.
