### ISSUE TITLE
Wrong times (1 hour off) for imported activities

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1779]
File type: TCX (did not test others)
Timestamps inside the file are like this: 2016-04-10T18:41:01.000+01:00
Time zone set to Europe/Warsaw
Resulting time is 18:41 instead of 19:41
Is it DST related? Not sure where to start debugging.

**Comment by mipapo** [comment]
Could you just give us an example file?

**Comment by grzeg1** [comment]
[2016-04-10T20:40_x_Running.tcx.zip](https://github.com/Runalyze/Runalyze/files/212475/2016-04-10T20.40_x_Running.tcx.zip)

**Comment by grzeg1** [comment]
OK, I read the update docs ;) and installed sqlite database. But it did not help. I did not get any error messages before though. How do I check that the whole sqlite/spatialite thing is really working?

**Comment by mipapo** [comment]
The sqlite/spatialite is not necessary for the recognition of the timezone during the upload. 
It just fills the timezone_offset field in the database (may be used for statistics in the future)
You could manually access the sqlite db:
```
# sqlite timezonedb.sqlite
sqlite> select load_extension('/usr/lib/x86_64-linux-gnu/libspatialite.so.5');
sqlite> SELECT spatialite_version();
sqlite> SELECT tzid FROM tz_world WHERE ST_Contains(geometry,MakePoint(-122.420706, 37.776685));
```
During the upload of the activity we look at the timestamp of the tcx file and try to figure out the UTC time:
2016-04-10T18:40:58.000+01:00 -> in UTC: 17:40
than we add the offset by the date with your timezone configuration. This will be added to the UTC time and saved in the time field.

Just don't know why it's not working in your case. What is your current offset in Europe/Warsaw? 
+2? 
Mh - Runalyze should show up 19:40 in the end

**Comment by grzeg1** [comment]
Ok, in my case you need a different set of commands (does it matter?):
```
>sqlite3 timezonedb.sqlite
SQLite version 3.11.0 2016-02-15 17:29:24
Enter ".help" for usage hints.
sqlite> select load_extension('mod_spatialite');

sqlite> SELECT spatialite_version();
4.3.0a
sqlite>  SELECT tzid FROM tz_world WHERE ST_Contains(geometry,MakePoint(-122.420706, 37.776685));
America/Los_Angeles
```

My clock:
```
>date
pon, 11 kwi 2016, 10:14:22 CEST
>date -R
Mon, 11 Apr 2016 10:14:25 +0200
```
My timezone setting:

![shutter_063](https://cloud.githubusercontent.com/assets/8179857/14420823/5c272e98-ffce-11e5-84e9-e267bcc20e07.png)

Still, the resulting time is 18:40

**Comment by laufhannes** [comment]
I don't see a Runalyze bug here? That's how the compound date / time format is defined: `2016-04-10T18:40:58.000+01:00` is equal to 18:40:58 at some place where the current time zone offset is one hour.

It seems that the offset in that file is wrong if your current offset is +02:00 and not +01:00. Where do you get this file from?

**Comment by mipapo** [comment]
I remember that Polar is the problem
`pe="Device_t"><Name>Polar V800</Name>`
https://forum.runalyze.com/viewtopic.php?f=33&t=375&sid=b4595f02cf85cb5fadfefffad4c897ba

**Comment by grzeg1** [comment]
I've never had any problems with importing of these files into any of the available platforms (Strava, Endomondo, TrainingPeaks etc.) Now, after timezone merge, Runalyze is the only one with a problem.

**Comment by grzeg1** [comment]
Re: Polar
They've had issues with timezones for exported TCX files, but it's not the case here. My files are fixed if necessary and they import just fine into other platforms.

**Comment by grzeg1** [comment]
@laufhannes if I understand correctly, Runalyze now assumes that if timezone offset is not 'Z' (zulu) then the time without offset is treated as local time. This is not right. Any platform can export activity in any timezone+offset combination (like Garmin will export with Zulu timezone). There should be no difference between the way activity is imported, regardless of timezone.

**Comment by laufhannes** [comment]
Garmin exports everything as UTC, right. In that case, we consider the user's timezone, as `Z` can be interpreted as *I don't know the time zone*: https://github.com/Runalyze/Runalyze/blob/master/inc/import/parser/class.ParserAbstractSingle.php#L121-L133

But if there's a time zone given in a file, we have to respect that. And `2016-04-10T18:40:58.000+01:00` is clearly `18:40:58` local time. If a platform exports an activity as `-07:00` although the activity was in `+05:00`, it's a problem of that platform (or the user and his settings). It's not a bug of Runalyze if somebody tells us `+01:00` and we take it at as it is.

---

 * If there are billions of platforms exporting a wrong time zone, we can think of adding a configuration variable *Ignore time zones given in a file and always use my account's time zone.*
 * We can think of favoring the time zone determined by our TimezoneLookup (which uses `timezonedb.sqlite`) instead of the time zone given within a file, to always trust the coordinates and not the file's time zone.

**Comment by grzeg1** [comment]
Both solutions seem reasonable. 
Now that I think about it, it seems every other platform uses TimezoneLookup as I never had any problems importing any file to any platform, regardless of what format/timezone the timestamps were in. So I guess performing TZLookup by default would be nice, especially that in the future import API should do the same.
