### ISSUE TITLE
Dates in form plot seem to be wrong again

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1783]
Yes, it's a duplicate of #1463 which was solved for v2.1.1 ... this finally needs some unit tests or a simple fix to always make sure that shown dates are correct.

**Comment by laufhannes** [comment]
Unit tests and an understandable solution require a complete rewriting, I guess.

**Comment by laufhannes** [comment]
... well, guess who's back? :(

**Comment by mipapo** [comment]
*Hello, it's me. I was wondering if after all these years. You'd like to meet*
