### ISSUE TITLE
Date in manual form is wrong (timezone)

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1796]
Does not consider timezone (weight window works as expected)

**Comment by laufhannes** [comment]
* [TrainingObject::fillDefaultObject()](https://github.com/Runalyze/Runalyze/blob/support/2.5.x/inc/training/class.TrainingObject.php#L60) uses `LocalTime`
 * [FormularValueParser::$PARSER_DATE](https://github.com/Runalyze/Runalyze/blob/master/inc/html/formular/class.FormularValueParser.php#L297-L324) uses `date` etc.
 * [FormularInputDayAndDaytime::validate()](https://github.com/Runalyze/Runalyze/blob/support/2.5.x/inc/html/formular/class.FormularInputDayAndDaytime.php#L62-L75) uses `strtotime`

... #headache
