### ISSUE TITLE
Catch errors while reading fit files

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1799]
Catch exceptions like the following:
```
Uncaught exception 'RuntimeException' with message 'Reading *.fit-file failed. First line was "main::Garmin::FIT::fetch#4079@...
```

Maybe check if the first line begins with `main::Garmin::FIT`, show a readable error message for the user and tell him to check the fit file (i.e. send it to us).

**Comment by mipapo** [comment]
Would be great if we could log (in the future with monolog) such problems and save the information error message and file
