### ISSUE TITLE
Translation: average values

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1813]
The ø sign (slashed o) notation for average is probably used only in German.
In English, "avg." abbreviation is commonly used.
So the "oslash" needs a translation.
I think the better way would be to separately translate average and types of values and then use string concatenation in code (instead of translating value types and average value types separately).

**Comment by grzeg1** [comment]
I'd probably call it a trivial bug, not an enhancement, as people over here don't know what the sign means ;)

**Comment by laufhannes** [comment]
As translation handling in branches is not that easy, this does not go into v2.5.2.
