### ISSUE TITLE
Track 'ending performance condition' for activities

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1829]
From https://github.com/Runalyze/Runalyze/issues/1747#issuecomment-219980660:

> It [`NUMBER=140`] contains, as I wrote in the mail, the 'Ending Performance Condition' which is continually adjusted during your run, like you saw -8 or -7 (you must have worked hard!). We have Performance Condition within 20 minutes as event 39 on the FR630 (probably on the new FR735XT as well) and the Fenix3. After it has been established, it can be shown as a data-field on the watch, and is tracked in that NUMBER=140 blob when pausing the watch and after the activity is finished - when the event 38 Recovery Advisor time is logged.

This could be added to our 'Pauses' object to track this value over the complete activity. (But an additional entry will be needed for the last one, as the pauses object does not contain a pause for the final end.)

**Comment by MJDevel** [comment]
I'm now using v2.6.0 and the PC column with the 'Starting' value looks good. I would suggest putting the very last 'Ending' value in the same column, like: +3/-12 Perhaps not that beautiful, but it is comprehensive (to my eyes at least).
