### ISSUE TITLE
Database migration tool needed

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1831]
Something like https://github.com/ruckus/ruckusing-migrations
Otherwise it's very hard to develop&stay with partial upgrades.

Until it's done, all sql files should be maintained in an incremental way. I mean
nothing should be modified (unless it causes data loss), only new lines should be added.
I just had to do a manual update of some tables because the update file was modified.
Nothing I could not manage, just not necessary.

**Comment by mipapo** [comment]
This will come with the use of symfony later

**Comment by mipapo** [comment]
#1831 is a (german duplicate) of this issue

**Comment by laufhannes** [comment]
Console commands for doctrine migration are already working (but there are no migrations to run).

BUT: Currently a table `migration_versions` is created/used. This table has to use the RUNALYZE prefix as well!

**Comment by grzeg1** [comment]
It would be nice to have at least one dummy migration and maybe even a few words of howto before closing this one... Also, how is this going t work for an end-user? I.e. how will the migrations be called?

**Comment by mipapo** [comment]
Doctrine/Symfony migration documentation:
http://symfony.com/doc/current/bundles/DoctrineMigrationsBundle/index.html

We will add the command `php bin/console doctrine:migrations:migrate` to the checkout instrucions
You can still use /update (calling the command locally with output)
