### ISSUE TITLE
Race Results: Values for Gender

### ISSUE THREAD

**Issue by rob-st** [Runalyze/Runalyze#1841]
Input fields for Gender in the Race Results Plugin are validated, but don't seem to accept any proper value (tried: male, Male, m, M, männlich, Männlich - they all failed).
For user experience they could be changed to a dropdown/select-field.

**Comment by laufhannes** [comment]
The fieldset is labeled with '_Placements_', it's meant to enter your place of all males. The fact, that you are male, can/should be set in the account settings.

**Comment by rob-st** [comment]
Oh ok.
It *is* set in the account settings, still shows the nasty question mark in the results table for that column.
Could be taken from user settings anyway - but then there'd be no need for that input field.

**Comment by laufhannes** [comment]
As I said: It's meant to put your placement in there:
 - Total: 17. of 230
 - Gender: 15. of 143
 - Age class: 3. of 21

**Comment by rob-st** [comment]
narf, now I got it -.-
