### ISSUE TITLE
Competition Details: Official Distance for Marathon

### ISSUE THREAD

**Issue by rob-st** [Runalyze/Runalyze#1842]
A Marathon's distance is 42.195 km - in the details panel, it will always be rounded up to 42.20 km.

**Comment by grzeg1** [comment]
@rob-st so? you like it? you don't? you' d like to have it any other way?

**Comment by rob-st** [comment]
Well, in activities' details, distances are rounded up to three digits behind comma - so it would be straight to keep this behaviour here as well. Also, I dunno *in what way these distances are or will be used in other places*.
But actually it's only 50cm and fixing wouldn't help for HM distance anyway, so ... I guess I'm just being a pedant :-D

**Comment by laufhannes** [comment]
These values are used for 'personal bests' and so on. So far, all pre-configured settings used `42.2` as marathon distance and that's the main reason why we kept it.

If we use three decimals, a half-marathon has to be entered as `21.098 km` which is wrong as well but going with four decimals seems a bit overkill. Anyway, _most_ people always have `42.2` and `21.1` in mind. Trying to enter the "full" distance should result in the rounded version. The other way round, if we use three (or four) decimals and people enter only `42.2`, they'll have a problem as this distance won't be recognized as personal best for the marathon.

**Comment by laufhannes** [comment]
I'll add a tooltip clarifying that we use two decimals there.
