### ISSUE TITLE
Zero-Distance values in the beginning of activity files should be imported

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1845]
Maybe with the condition if other values (hr, cadence) are not null.

See https://connect.garmin.com/modern/activity/1183781662
vs
https://runalyze.com/shared/s3hg

**Comment by laufhannes** [comment]
These values are imported correctly, but they are only visible when using time as x-axis. A dynamic handling of the x-axis will be considered as soon as we use d3js for it.
