### ISSUE TITLE
Import of JSON.GZ failed with "There was an error: 500 Internal Server Error"

### ISSUE THREAD

**Issue by PonessM** [Runalyze/Runalyze#1848]
used Version 2.6.

Want to transfer data from own Install to runalyze.com result in this Error

json.gz size: 11.6 MB

**Comment by mipapo** [comment]
Have you updated your own installation of RUNALYZE?

**Comment by mipapo** [comment]
@PonessM I had a look into our logs. It seems you never completed the `refactor-geohash.php` script, which had to be executed in the update from version 2.2->2.3
http://docs.runalyze.com/en/latest/update.html#upgrade-from-2-2-to-2-3
It should be fine to just execute it now until it's done. (But we can't give any  guarantee)

**Comment by PonessM** [comment]
i will try it

**Comment by mipapo** [comment]
@PonessM When I saw it correctly in the logs the script was "done" but the column "refactored" was not removed. If you're not missing any route of an activity you could simply execute 
`ALTER TABLE runalyze_route DROP COLUMN refactored`
(You may have to adjust the prefix of the table name)

**Comment by PonessM** [comment]
Script erneut ausgeführt auf Command Line und erfolgreich abgeschlossen.  Neuer Export und dann erneuter Import versucht. 

Ergebnis:  gleicher Fehler

**Comment by mipapo** [comment]
@PonessM Da war ich wohl schneller mit dem Antworten ;)

**Comment by PonessM** [comment]
Spalte personell gelöscht. Export ; Import. Keine Änderung im Ergebnis

**Comment by mipapo** [comment]
@PonessM stand beim Durchführen des Skriptes, dass er fertig war? Auch die Spalten `lats` und `lngs` wurden nicht gelöscht - was darauf hinweist, dass das Skript nicht fertig war. Es kann also sein, dass dir am Ende GPS Daten fehlen. 
Wenn du sicher gehen willst, dann füge die `refactored` Spalte wieder hinzu und lasse anschließend das Skript erneut laufen (und schaue, dass die Meldung am Ende auch besagt, dass das Skript durch ist)

```
ALTER TABLE `runalyze_route` ADD `refactored` TINYINT UNSIGNED NOT NULL DEFAULT 0 FIRST;
ALTER TABLE `runalyze_route` ADD INDEX `refactored` (`refactored`);
UPDATE `runalyze_route` SET `lats` = NULL, `refactored` = 1 WHERE `lats` = "" OR `lats` IS NULL;
```

**Comment by PonessM** [comment]
jetzt hat es geklappt.

Lösung: die eigene SQL Datenbank, Tabelle runalyze_route splitten in pre 2.3, script ausführen und im Anschluss wieder mergen.

Danach hat der Export / Import einwandfrei funktioniert.

Danke für die Hilfe und macht weiter so.
