### ISSUE TITLE
making training public

### ISSUE THREAD

**Issue by lebkayn** [Runalyze/Runalyze#1852]
a tiny suggestion: if i make a training public via the link on the main screen, the lock stays open. in other words: it would be great (and easier), if the lock changed according to the status of the training in question. at the moment i need to go to the editing screen to see, if the training is public or not.

**Comment by laufhannes** [comment]
About which "main screen" are you talking? The drop-down menu in the calendar view? If I click there the calendar view gets reloaded and the drop down menu changes as it should ('Make activity private' instead of 'Make activity public').

**Comment by laufhannes** [comment]
Okay, I see: It does not work within the search window (same applies for the deletion of an activity).

**Comment by lebkayn** [comment]
very curious. i could swear, i didn't work a while ago. but now it behaves as i expected & wish, so you can safely disregard my suggestion.
