### ISSUE TITLE
Age Grade Performance

### ISSUE THREAD

**Issue by Kelmart** [Runalyze/Runalyze#1855]
I love the new 'Competition Results/Race Results' data entry and the positions. I would like to see a field for manual entry of 'Age Grade', which is a standalone figure. Ideally it could be created automatically, with reference to the 'Age Grade' algorithm, but failing that allowing for manual entry is fine. Make it an option in the preferences, maybe.

For reference: 
http://www.runningforfitness.org/calc/racepaces/rp/rpother
http://www.parkrun.org.uk use age grade as a measure of performance on the day, and generate the figure automatically. Eg. http://www.parkrun.org.uk/peckhamrye/results/latestresults/

Reasons:- Age grade is a measure of performance on the day, and a great way of comparing results, over time, and at a particular event. It allows for differences in age and gender to be taken into account. Because it is a distance independent figure, it could be used as a plot of race performances over time at different distances, and so get all _your_ races on one chart.

**Comment by mipapo** [comment]
We already have it on our list: https://github.com/Runalyze/Runalyze/issues/1820
We could think about not adding something like this but adding a "birth day/year" to the account setting

**Comment by laufhannes** [comment]
:+1: for age-grading.

Are there any exact examples of the calculations? Both of your examples seem to hide their exact formulas.

The records available at http://www.world-masters-athletics.org/records/current-records start at M/W35 and contain only 10k and marathon (+ track distances). What is with people younger than 35? How to interpolate ages between 35 and 40? How to interpolate between 10k and marathon? How to interpolate for longer distances? Older people tend to perform (relatively) better on longer distances than younger poeple.

**Comment by Kelmart** [comment]
@mipao. Age grade is **not** the same as 'Age Group'. Age grade relates to your age in years, and not your Age Group. EG.
**I am a 54 year old man**, I am in the age group VM 50-54, but my age grade for an event is calculated based on the distance and time and age (in years).

I ran a 10k in 44:41. My age grade is 71% for this event.
I ran a 5k in 20:25. My age grade is 74.6% for this event. (My PB)
I ran a 10k in 42:25. My age grade is 74.8% for this event. (My PB)
I ran a half marathon in 1:35:12. My age grade is 72.8% for this event.

So my age grades over time reflect how well I am doing. It is based on the very best performances in the World. So 70% is 70% of the very fastest in the World. The algorithm is a smoothed curve, that removes outliers, and provides a best fit, to judge your performance. It is updated every few years, based on new performances at the elite end of the sport. It is internationally recognised. It is produced by the World Masters Athletics. http://www.world-masters-athletics.org/index.php

This is what parkrun says about age grades:

> WHAT IS AGE GRADING
> 
> All parkrun events use age grading to allow athletes to compare results.
> 
> Age grading takes your time and uses the world record time for your sex and age to produce a score (a percentage). This score allows you to compare your personal performance against other people's performances even though they might be a different age and a different sex to you - the higher the score the better the performance.
> 
> The scores can also be compared across different race distances - to allow you to, for example, compare a 5km time against a marathon.
> 
![screen shot 92](https://cloud.githubusercontent.com/assets/19855859/15963080/0f21f944-2f07-11e6-8dff-1af0cffcc36e.jpg)

**Comment by laufhannes** [comment]
Okay, I found some tables with the factors (which have to be combined with a recent table of all world records):
 * http://www.howardgrubb.co.uk/athletics/data/wavacalc15.xls from [howardgrubb.co.uk](http://www.howardgrubb.co.uk/athletics/wmaroad15.html)
 * http://www.runscore.com/Alan/MaleRoadStd2015.xlsx and 
 * http://www.runscore.com/Alan/FemaleRoadStd2015.xlsx from [runscore.com](http://www.runscore.com/Alan/AgeGrade.html)

**Comment by Kelmart** [comment]
@laufhannes, you beat me to it. 

The 'authoritative' table is produce by WMA, and would be available from them, at their discretion, on request. Thanks for looking into this. It might be a useful feature, for a future release.

**Comment by mipapo** [comment]
@Kelmart  My comment was just a bit ambiguous. I understood what you generally meant, but adding "age group" is now totally redundant if you add the birthdate of the user and calculate the age grade performance.

**Comment by justsomebody42** [comment]
I would be very interested in this!

**Comment by mipapo** [comment]
@Kelmart  http://www.world-masters-athletics.org/ seems to be down :(

**Comment by laufhannes** [comment]
We don't really need the 'official' website, using the tables from runscore.com should be enough. I'd like to put them into a stand-alone repository (as pure php arrays wrapped into a simple class), but we have to check the license (as there's nothing mentioned on runscore.com).

**Comment by mipapo** [comment]
"Thanks for the note. Yes you can use the tables. No restrictions other than to acknowledge the USATF and WMA and myself. If you have questions, don't hesitate to write.
Regards,
Alan "

**Comment by laufhannes** [comment]
Feel free to have a look at the `feature/ageGrade` branch. It uses the new repo https://github.com/Runalyze/age-grade and shows age grade within race results table and detailed activity view for race results (please ignore mixed languages):

![bildschirmfoto 2016-10-04 um 11 55 43](https://cloud.githubusercontent.com/assets/8313118/19070855/9da1cab0-8a2d-11e6-904a-65522b62308b.png)

![bildschirmfoto 2016-10-04 um 12 22 10](https://cloud.githubusercontent.com/assets/8313118/19070856/9da218b2-8a2d-11e6-96c5-ee19ae8c25e5.png)

Have in mind that tables provided by Alan Jones do start at 5k, so there is no age grade for shorter distances. (And, of course, age grade can only be shown if gender and year of birth are properly set.)

**Comment by mipapo** [comment]
> And, of course, age grade can only be shown if gender and year of birth are properly set
If year of birth is not set it should just now show up  ;)
