### ISSUE TITLE
isHttps - make it configurable

### ISSUE THREAD

**Issue by jhartlep** [Runalyze/Runalyze#1858]
Hi,
I am using Runalyze in a docker container.
Inside this container, my installation is non ssl...

but outside of my docker container I have a nginx-reverse-proxy using ssl.
Now Runalyze thinks, I have no ssl, because 
`return isset($_SERVER['HTTPS']) && !empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] != 'off';`
returns false...

Could you please change this - at least let the statement check a config-file-setting...

e.g.
config.php:
`define('USE_HTTPS', true);`

class.Request.php
`return (USE_HTTPS) || (isset($_SERVER['HTTPS']) && !empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] != 'off');`

This would help installing Runalyze behind a proxy...

Best Regards,
Jens

**Comment by mipapo** [comment]
Not sure if it will change with using symfony - we will see it after the next release

**Comment by jhartlep** [comment]
Thanks for the quick response!

**Comment by laufhannes** [comment]
There seem to be only two pieces of code that use `Request::getProtocol` (which is the only one that uses `Request::isHttps()` (see [search](https://github.com/Runalyze/Runalyze/search?utf8=%E2%9C%93&q=getProtocol)):
 - [System::getDomain()](https://github.com/Runalyze/Runalyze/blob/0eab8fb7d02ac481162b4f1735f8a506d80a9d21/inc/system/class.System.php#L91)
 - [call.garminCommunicator.php](https://github.com/Runalyze/Runalyze/blob/0eab8fb7d02ac481162b4f1735f8a506d80a9d21/call/call.garminCommunicator.php#L138)

Can you try to remove `Request::getProtocol()` and the following colon? Using `//domain.tld/...` is part of our internal refactoring tasks #1695 and we could use it for v2.6.2, independently of symfony in v3.0.0.

**Comment by laufhannes** [comment]
I was able to test the stuff with Cloud9 and Safari (which still supports the Garmin Communicator), but the Garmin Communicator does not support `pathKeyPairsArray: ["//domain.tld", "..."]`. As the Garmin Communicator is deprecated anyway, I'll only fix the part in `System::getDomain()`.
