### ISSUE TITLE
fit Upload Failed (setting locale failed perl)

### ISSUE THREAD

**Issue by matmatkeke** [Runalyze/Runalyze#1865]
Hello,

I tried to upload a .fit file but I received the following error:

2016-05-14-16-29-41.fit: Upload failure reason unknown
There were problems while uploading.

[Thu Jun 23 08:44:23.535632 2016] [:error] [pid 13951] [client :56426] PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Reading *.fit-file failed. First line was "perl: warning: Setting locale failed.".' in /var/www/webhostdir/web/inc/import/parser/class.ParserFITMultiple.php:77\nStack trace:\n#0 /var/www/webhostdir/web/inc/import/parser/class.ParserFITMultiple.php(42): ParserFITMultiple->readFirstLine()\n#1 /var/www/webhostdir/web/inc/import/filetypes/class.ImporterFiletypeFIT.php(74): ParserFITMultiple->parse()\n#2 /var/www/webhostdir/web/inc/import/filetypes/class.ImporterFiletypeFIT.php(47): ImporterFiletypeFIT->readFile()\n#3 /var/www/webhostdir/web/inc/import/class.ImporterFactory.php(290): ImporterFiletypeFIT->parseFile('../data/import/...')\n#4 /var/www/webhostdir/web/inc/import/class.ImporterFactory.php(279): ImporterFactory->importWithClass('ImporterFiletyp...')\n#5 /var/www/webhostdir/web/inc/import/class.ImporterFactory.php(72): ImporterFactory->constructForFilename('2016-05-14-16-2...')\n#6 /var/www/webhostdir/web/inc/import/class.ImporterWindow.php(99):  in /var/www/webhostdir/web/inc/import/parser/class.ParserFITMultiple.php on line 77, referer: https://www.homepage.de/index.php

Version is: V2.6.1

What is the error?

Best 
Mathias

**Comment by matmatkeke** [comment]
in the admin overview I can see the error: Perl scripts cannot be used.
How to fix this?

**Comment by mipapo** [comment]
Either your perl path is not correct or the correct locales are missing...
https://www.google.de/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=site:forum.runalyze.com+runalyze+perl+setting+locale+failed

**Comment by laufhannes** [comment]
A "dirty" hack can be to prefix the perl command with `LANG=C` as suggested in https://github.com/Runalyze/Runalyze/issues/1701#issuecomment-172206498. But this won't "survive" any updates and as @mipapo says, the main problem lies in your perl settings.

**Comment by matmatkeke** [comment]
Problem solved:
in the to files:
class.ParserFITMultiple.php
- class.ImporterFiletypeFIT.php


I edited this lines:

 protected function readFirstLine() {
      // XXX: Workaround for Perl locale Warnings
      //      Lines like the following are ignored silently:
      // --- Console log of perl running with undefined locale ---
      // perl: warning: Setting locale failed.
      // perl: warning: Please check that your locale settings:
      //         LC_ALL = "en_US",
      //         LANG = "en_US"
      //     are supported and installed on your system.
      // perl: warning: Falling back to the standard locale ("C").
      // --- end ---

      do {
         $FirstLine = stream_get_line($this->Handle, 4096, PHP_EOL);
      } while(trim($FirstLine) != 'SUCCESS' && ! feof($this->Handle));

      if (feof($this->Handle)) {
         //while(($line = stream_get_line($this->Handle, 4096, PHP_EOL)) != false && !feof($this->Handle
         //      $FirstLine .= $line;
         fclose($this->Handle);
         unlink($this->Filename);
         throw new RuntimeException('Reading *.fit-file failed. First line was "'.$FirstLine.'".');
      }
   }

**Comment by mipapo** [comment]
This does not solve the actual problem that your system is not configured correctly. 
You will have to make this workaround each time as you are updating RUNALYZE

**Comment by matmatkeke** [comment]
I fixed the problem:
Solution was: locale-gen de_DE.UTF-8
