### ISSUE TITLE
Mutiple (permanent) login sessions

### ISSUE THREAD

**Issue by danielBreitlauch** [Runalyze/Runalyze#1869]
I logged in on one system and set "stay logged in". Just reloading the page shows that I stay logged in.
But if I log in on a different system and set "stay logged in" then the original session is gone.

Looks like there is only one session per user.
It would be very helpful to have sessions per device.
This way user can stay logged in from multiple devices and don't have to re-login all the time.

**Comment by mipapo** [comment]
This is just like it works now.
This will change with version 3.0

**Comment by mipapo** [comment]
Done in:
b43bfb6ad2622ee59d82e113d3df9c7876700069
517dd45083c63ed9b7ea254e318d83173b4c8e61
d4e4688e89a795cf01e7071c7c668d2922e39d87
