### ISSUE TITLE
Shared view not working despite RewriteBase

### ISSUE THREAD

**Issue by dbeniamine** [Runalyze/Runalyze#1874]
# Issue description

Hello,

I've been using Runalyze since a few months (on your servers) and I just installed it on my own server, everything went well except that the shared page always end in a 404.

I'm accessing my runalyze via an url like `mysub.domain.com/runalyze` and I added a `.htaccess` containing: `RewriteBase /runalyze` as explained here: https://docs.runalyze.com/en/latest/faq.html#the-public-activity-view-is-not-working . Yet it didn't fix the issue ...

Do you have any clue on what I should do ?

# Server Informations

    Runalyze version: 2.6.1

    PHP version: 5.6.23-0+deb8u1
    
    MySQL version: 5.5.49-0+deb8u1
    
    Time limit: 3600
    
    Memory limit: 512M
    
    Upload limit: 4G
    
    Post limit: 4G
    
    Perl scripts can be used.

**Comment by mipapo** [comment]
Is it a Apache webserver?

**Comment by dbeniamine** [comment]
Yes it is:, version 2.4.10

**Comment by mipapo** [comment]
Do you have control over the Apache-vHost configuration? Is it allowed to use htaccess? 
Should be `AllowOverride All` or something similiar in the `directory` part

**Comment by dbeniamine** [comment]
I have full control on the server configuration.
`AllowOverride All` appears in the `directory /` configuration.

I tried to add a configuration for directory `/runalyze` with only `AllowOverride All` inside, after restarting apache2 the issue persists...

**Comment by mipapo** [comment]
mod rewrite is installed?
Then I have really no idea - anywhere else it's working

**Comment by dbeniamine** [comment]
mod rewrite installed and work perfectly fine (I use it a lot).

Also setting the   `RewriteBase` inside the Directory part of the Vhost doesn't change anything.

**Comment by mipapo** [comment]
You could try something which has been mentioned here: https://forum.runalyze.com/viewtopic.php?t=390

**Comment by dbeniamine** [comment]
I don't speak german but I tried to add the following lines to my .htaccess:

    <IfModule mod_rewrite.c>
        RewriteEngine on
        RewriteBase /runalyze
        RewriteRule ^shared/([^./]*)$ call/call.SharedTraining.php?url=$1 [L]
        RewriteRule ^shared/([^/]*)/$ call/call.SharedList.php?user=$1&%{QUERY_STRING} [L]
        RewriteRule ^call/login.php$ call/login.php [L]
        RewriteRule ([^./]*)/login.php$ login.php [L]
        RewriteRule ^call/img/([^./]*) img/$1 [L]
    </IfModule>

Everything seems to work fine now :)

Thanks for your help

**Comment by laufhannes** [comment]
Your previous version did not contain all the RewriteRules? Than it's clear that it did not work.

How did you install Runalyze? The installation should contain a [.htaccess](https://github.com/Runalyze/Runalyze/blob/support/2.6.x/.htaccess) by default which should only be adjusted, not replaced, in case of any troubles.

**Comment by dbeniamine** [comment]
I installed the archive from [github](ihttps://github.com/Runalyze/Runalyze/releases), it did not contain any `.htaccess` file:

    $ md5sum runalyze-v2.6.1.tar.gz 
    aefeb9c7028b762995c58b960a53f0a7  runalyze-v2.6.1.tar.gz
    $ tar xvzf runalyze-v2.6.1.tar.gz runalyze/.htaccess
    tar: runalyze/.htaccess: Not found in archive
    tar: Exiting with failure status due to previous errors

I found the (partial) workaround in this doc: https://docs.runalyze.com/en/latest/faq.html#the-public-activity-view-is-not-working

**Comment by mipapo** [comment]
Just missing in the *.tar.gz files - I will have a look into the script generating the release files

**Comment by dbeniamine** [comment]
So I download the zip archive that contains the `.htaccess` and copied this specific file, it works fine without any modification.

**Comment by mipapo** [comment]
Beginning with the bugfix release 2.6.2 the `.htaccess` file will be there again.

**Comment by dbeniamine** [comment]
Great, thanks again for your help !
