### ISSUE TITLE
FIT file upload does not work

### ISSUE THREAD

**Issue by greendoor8** [Runalyze/Runalyze#1877]
I tried to upload a FIT file from my Garmin Fenix 3 watch. But I was not able to upload this activity to runalyze. After some seconds I got this warnings:

1)
unlink(/<myServer>/inc/../data/import/schwimmen.FIT.temp): Datei oder Verzeichnis nicht gefunden (in /<myServer>/inc/import/filetypes/class.ImporterFiletypeFIT.php::76)

2) 
fopen(/<myServer>/inc/../data/import/schwimmen.FIT.temp): failed to open stream: Datei oder Verzeichnis nicht gefunden (in /<myServer>/inc/import/parser/class.ParserFITMultiple.php::40)	

3)
shell_exec() has been disabled for security reasons (in /<myServer>/inc/system/shell/class.PerlCommand.php::77)	

But I was able to import a TCX file without problems (after downloading this file from Garmin Connect website).

Environment: installation on own server; version 2.6.1; garmin fenix 3

**Comment by mipapo** [comment]
Enable php exec function
http://stackoverflow.com/questions/24999673/how-to-enable-shell-exec-and-exec-on-php

**Comment by greendoor8** [comment]
Perfect. Now it works.

Thanks for you fast help.

**Comment by mipapo** [comment]
Great! have fun with Runalyze :)
