### ISSUE TITLE
Automatic activity upload from Runtastic, Strava & co.

### ISSUE THREAD

**Issue by PrimeF** [Runalyze/Runalyze#1883]
Hello,
could you please implement the possibility to automatic upload the activities from a Runtastic or Strava account. It would simplify the process a lot and it would make the application even more performant and efficient.

Many Thanks

Fabrizio

**Comment by mipapo** [comment]
This is planned in the future. A ticket already is exisiting (API)

**Comment by laufhannes** [comment]
For additional reference: #498 and #1648.
