### ISSUE TITLE
Need guidelines to install 3.0 in subdirectory

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1885]
I'd like to install 3.0 in subdirectory - e.g. http://localhost/runalyze3/
Never had a problem with previous versions, but the new one is somehow hardcoded to base url.

**Comment by laufhannes** [comment]
Which problems do occur in your case? My local version runs as `http://localhost/runalyze/` and I don't have any problems accessing `http://localhost/runalyze/web/` (or `http://localhost/runalyze/web/app_dev.php/`). So far, general instructions to install v3.0 and use a local checkout are available at https://docs.runalyze.com/en/3.0/install.html and https://docs.runalyze.com/en/3.0/checkout.html.

If I don't want to use the `/web/` directory, I need to adjust my `.htaccess`, i.e. remove the leading `/` before `web`:
```
<IfModule mod_rewrite.c>
RewriteEngine on

RewriteCond %{REQUEST_URI} !^web/
RewriteRule ^(.*)$ web/$1 [NC,L]
</IfModule>
```
Maybe that's wrong in the current `.htaccess`, @miapapo?

**Comment by mipapo** [comment]
It is just broken. Like I just said internally it is a mess to support subdirectories with the current state. 
If someone will use it that way he must copy the `web` directory to `/runalyze`. All the rest should be copied e.g. to `/app` and the `app.php` path has to be modified. 
This does not work in the moment, because it breaks some paths of e.g. reading the configuration file into our old database class and certainly some others paths for downloading files or anything else will break too.

I don't have an idea to do this correctly via the .htaccess file. The problem is that the redirect contains the subdirectory and symfony cannot find the correct route.

**Comment by laufhannes** [comment]
It's not completely broken. As I said, my local version works just fine via `http://localhost/runalyze/` with the `.htaccess` as shown above. (And without any `.htaccess`, it still works fine as `http://localhost/runalyze/web/`.)

On my c9 workspace, I don't get a working version in a subdirectory without using explicitly `web/`, right.

I don't see a problem with telling people:
 1. We highly recommend mounting the `web/` directory as root of some (sub)domain. We guarantee that everything works fine there.
 2. If people can only install RUNALYZE in a subdirectory, it *may* work with the provided `.htaccess` (I'd commit the above change). People *may* need to set a `RewriteBase` or adjust some other paths, but we won't guarantee anything.
 3. If people can't get a working version via `domain.tld/runalyze/`, they *may* try `domain.tld/runalyze/web/` but it's their liability to make sure that other files outside the web directory are not accessible.

**Comment by grzeg1** [comment]
After changing `.htaccess` it seems that (when I add `/web`) it works. Thanks.

**Comment by laufhannes** [comment]
Good to hear! The symfony way is not what I personally prefer, but there are tons of other reasons to use symfony, so I guess we can deal with it.

**Comment by ausminternet** [comment]
> We highly recommend mounting the web/ directory as root of some (sub)domain. We guarantee that everything works fine there.

That's not right, at least for my installation at https://uberspace.de/.
I soft-linked the web directory to a subdomain and I had to set `RewriteBase / `to get it to work.
