### ISSUE TITLE
kcal/h in Activity Types

### ISSUE THREAD

**Issue by blu2lz** [Runalyze/Runalyze#1889]
Feature request:
Option to set kcal/h for each activity type. If I do a regeneration run I won't have the same kcal/h as if I'm running fast. I think it's comparable to avg. HR where you have a "global" setting for the sport type but can refine it for each activity type.

**Comment by mipapo** [comment]
I think that would be too much configuration.
We just should just a better formula (https://github.com/Runalyze/Runalyze/issues/1090)

**Comment by laufhannes** [comment]
... and that formula will use heart rate from sport/activity type if there's no exact heart rate data. So, I guess that kcal/h option will be removed entirely later on.

**Comment by blu2lz** [comment]
That sounds better indeed. Thanks for the fast reply. Keep up the great work!
