### ISSUE TITLE
Migration: How to use prefix?

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1895]
Usage of prefix with symfony/doctrine seems to be complicated.
In the moment we have a PrefixListener. This works fine for all generated queries by symfony/doctrine.

Problem: How to get the prefix in the migrations

(As we have decided to have no database structure changes for 3.0 we don't have to hurry, but we should have an in idea for this in near term)

See full question at StackOverflow http://stackoverflow.com/questions/38890284/symfony-doctrine-migration-with-prefix

**Comment by mipapo** [comment]
This moment when you just have looked everywhere to solve this problem and than found a working solution in half an hour...
Migrations just have to implement the `ContainerAwareInterface`

```
<?php

namespace Runalyze\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;
use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;


/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20160810121166 extends AbstractMigration implements ContainerAwareInterface
{
    private $container;

    public function setContainer(ContainerInterface $container = null)
    {
        $this->container = $container;
    }
    
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        $em = $this->container->getParameter('database_prefix'); //Just use the parameter directly in the migration calls
	$this->addSql('CREATE TABLE `'.$em.'sessions` (`sess_id` VARBINARY(128) NOT NULL PRIMARY KEY, `sess_data` BLOB NOT NULL, `sess_time` INTEGER UNSIGNED NOT NULL, `sess_lifetime` MEDIUMINT NOT NULL) COLLATE utf8_bin, ENGINE = InnoDB');


    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
    }
}
```

**Comment by laufhannes** [comment]
The `down()` method should remove the table again, right?
