### ISSUE TITLE
Store sessions in the database again

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1896]
As we have said that we don't want any changes in the database structure for 3.0 we had to store the sessions as files for the beginning.
I wanted to store the sessions in the database again in 3.1, but when I change the config the users couldn't execute the migration via `/update`.
Therefore the session table will be created in 3.1, but I will change the config in 3.1.1 oder 3.2 
This feature is more or less only important for our official hosted version at runalyze.com, because of the high usage

**Comment by maglnet** [comment]
Just as an idea, because I don't exactly know the background of this issue:

For performance, wouldn't it be great to use memcached or another in memory storage? Afaik it is possible to simply configure this in the framework.

This would have the side effect, that there won't be any adjustments needed in the database.

This configuration could be done for the online version of runalyze only, so it won't break backwards compatibility.

**Comment by mipapo** [comment]
@maglnet It's already implemented to use storing sessions in db. And if you use multiple servers for one application using memcache would be a bad idea. 
And I don't want to put any effort in the moment in this issue, as it justs works now

**Comment by maglnet** [comment]
Well, if it already works, that's fine and no further adjustments are needed.

Memcached won't be the best solution, but there are other faster solutions available than a relational database. ;)

**Comment by mipapo** [comment]
> Memcached won't be the best solution, but there are other faster solutions available than a relational database. ;)
For small instances a relational database is just fine. Memcache is not always available. For our production we may use another setup. And everyone who has some knowledge about  the symfony configuration could change it themself.

**Comment by laufhannes** [comment]
@mipapo So does this work in v3.1 due to #1950?

**Comment by mipapo** [comment]
The config is not active - Still have to check it the sessions are started when trying to access the `/update` and `/install` page

**Comment by mipapo** [comment]
Okay, I will remove the Migration file from our repo and don't implement it. For every small installation (and well also our hosted version is still running fine with thte current setup) it's not necessary to use another session handler. 
If it's really necessary for our official hosted version I will just overwrite the session handler and we're doing our own thing.
