### ISSUE TITLE
Comment is cut

### ISSUE THREAD

**Issue by kabakakao** [Runalyze/Runalyze#1904]
Within the Summary Table the comment is cut, although there is enough space to show the whole content. The whole content will be shown in tooltip, but it would be nice, if the whole comment will be shown, if there is enough space for it.

![bildschirmfoto_2016-08-16_20-14-53](https://cloud.githubusercontent.com/assets/18161756/17710684/a40843d0-63ee-11e6-8e68-ea3257074bd2.png)

**Comment by mipapo** [comment]
Just read the dataset info. "Comments are cut after 20 characters"

**Comment by kabakakao** [comment]
Sorry for that. I didn't see that hint. So. No Problem

**Comment by laufhannes** [comment]
There's #1075 to make the cut optional. I'm not sure whether a general `text-overflow: ellipsis` does work in tables.
