### ISSUE TITLE
Wrong values importing malformed (?) tcx file

### ISSUE THREAD

**Issue by diesl** [Runalyze/Runalyze#1905]
When removing the `<DistanceMeters>` in the `<Trackpoint>`, importing works correctly.
[20160727_134333-issue.zip](https://github.com/Runalyze/Runalyze/files/422314/20160727_134333-issue.zip)

**Comment by mipapo** [comment]
What do you want to tell us?

**Comment by diesl** [comment]
@mipapo Sorry, hit Enter a bit too fast ;-)

**Comment by mipapo** [comment]
Where does the File come from?

**Comment by diesl** [comment]
Exported from [Endomondo](http://www.endomondo.com), shortened to a reasonable amount of Trackpoints for this issue.

**Comment by mipapo** [comment]
Please add the full file. I think it's a typical "garbage in" "garbage out" problem. 
We use the DistanceMeters if they are avialable. If not we recalculate the distance by the positions

**Comment by laufhannes** [comment]
The file's markup is okay so far, it's just that all `<DistanceMeters>` are useless:
```
          <Trackpoint>
            <Time>2016-02-27T14:48:24Z</Time>
            <Position>
              <LatitudeDegrees>49.544982</LatitudeDegrees>
              <LongitudeDegrees>11.787027</LongitudeDegrees>
            </Position>
            <AltitudeMeters>343.0</AltitudeMeters>
            <DistanceMeters>7.53344</DistanceMeters>
          </Trackpoint>
          <Trackpoint>
            <Time>2016-02-27T14:48:35Z</Time>
            <Position>
              <LatitudeDegrees>49.544916</LatitudeDegrees>
              <LongitudeDegrees>11.787384</LongitudeDegrees>
            </Position>
            <AltitudeMeters>344.0</AltitudeMeters>
            <DistanceMeters>7.56023</DistanceMeters>
          </Trackpoint>
          <Trackpoint>
            <Time>2016-02-27T14:48:42Z</Time>
            <Position>
              <LatitudeDegrees>49.544836</LatitudeDegrees>
              <LongitudeDegrees>11.787466</LongitudeDegrees>
            </Position>
            <AltitudeMeters>346.0</AltitudeMeters>
            <DistanceMeters>7.5709</DistanceMeters>
          </Trackpoint>
```

`DistanceMeters` is defined to be in meters, not in kilometers. (Is this part from the middle of the activity?)

We could add a check to #1576 to check if the distance array looks suspicious, but I really don't know how to check for this specific problem.

**Comment by diesl** [comment]
Yes, maybe I should have attached the full file from the beginning. Here it is:
[20160727_134333-issue-full.zip](https://github.com/Runalyze/Runalyze/files/422374/20160727_134333-issue-full.zip)

**Comment by mipapo** [comment]
Endomondo is just a bad platform - I would call them the second "Polar flow"
Rembering https://github.com/Runalyze/Runalyze/issues/1404#issuecomment-117127471
https://github.com/Runalyze/Runalyze/issues/1131#issuecomment-58818983
and the one you already have reported (@diesl)
https://github.com/Runalyze/Runalyze/issues/1445

**Comment by diesl** [comment]
I was not sure if it is a import error or Endomondo violating the tcx specs, as the xml file looked okay for me. But in general, you seem to be right with your opinion about Endomondo. The pain to change the running app was just not big enough yet ;-)

**Comment by diesl** [comment]
Ok, just to sum it up: The `<DistanceMeters>` are indeed given in kilometers and not in (correct) meters. I did not see the obvious and this is of course a bug from Endomondo. I try to report it to Endomondo.

@mipapo Is there an app you can recommend in combination with runalyze? Best would free and open source of course ;-)

**Comment by mipapo** [comment]
@diesl There is an app called "runnerup". It's open source and someone has added RUNALYZE to upload the recorded workouts.  
It's "okay" how he has implemented it (still ugly that way, but it seems to work), but we don't give any support if activities make problems in RUNALYZE. (Still his implementation is not available in the official version at Google Play). 
But here: https://github.com/rickyepoderi/runnerup/releases/tag/v1.54-alpha
The design of runnerup is really bad, but the functionalities are great!

We hope that we can add a official API to RUNALYZE soon

**Comment by laufhannes** [comment]
I close this one as 'wontfix'. It's referenced in #1576 so that it can be added there if possible and required.
(But: feel free to discuss about alternatives to Endomondo)
