### ISSUE TITLE
Importer: activities without cadence show 'NAN' in form

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1907]
Maybe caused by 5e4fd0aa2f8e540661e508c016d93895bbf274fe.

**Comment by laufhannes** [comment]
Can't reproduce this in my c9 environment for v2.6.4, only in our official online version. Maybe there's a bug in our internal production branch only.

Example is in `Supportticket #000779`.

**Comment by mipapo** [comment]
Was a missing fix in our production branch for runalyze.com
