### ISSUE TITLE
embedded.js is missing 

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1913]
- [ ] File is still in `lib`, but due folder changes not accessable (we need to move the file to `web/js`
- [ ] Url in IFrame is without protocol

**Comment by laufhannes** [comment]
Where is `runalyze.com` hard configured? Using the `embedded.js` from our official online version is intended, as the detection of "local" installations does not always work.

**Comment by mipapo** [comment]
https://github.com/Runalyze/Runalyze/blob/92cd6eb32971a9a64c09f0d2bfa5e3f6ac2ad3ae/inc/core/Export/Share/Html.php#L115
But okay - I understand why we do it that way
