### ISSUE TITLE
Databrowser fails due too many notices

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1914]
https://github.com/Runalyze/Runalyze/blob/master/inc/class.DataBrowser.php#L151

```
 isset($Training['typeid']) && in_array($Training['typeid'], $this->TypesShort) ||
```
sollte es fixen...

**Comment by laufhannes** [comment]
Better solution is to add `typeid` to [Dataset\Query::defaultColumns()](https://github.com/Runalyze/Runalyze/blob/b4270c9cef69b1987a7af1d16eb675b96d82c1cd/inc/core/Dataset/Query.php#L308-L311). Otherwise short mode will not work correctly if types are not shown in the calendar.

**Comment by mipapo** [comment]
That was my second thought - but you know *tired*
