### ISSUE TITLE
gpx importer uses the wrong duration

### ISSUE THREAD

**Issue by danielBreitlauch** [Runalyze/Runalyze#1916]
Hi there, not sure if I miss a configuration option that I just have to toggle…

The gpx importer takes the overall duration not the 'moved duration'.
I can put the moved duration in there by hand then the activity shows both: duration and moved duration (Zeit, Verstrichene Zeit).

Do I do something wrong or is it a bug?

**Comment by mipapo** [comment]
GPX is a bad format. It could contain pauses, but doesn't have to. (Depends from which platform you're exporting.
We are trying to recognize pauses (General settings->Activity form->Detect pauses).

Better use another format like fit files or maybd tcx
