### ISSUE TITLE
Import from meerun android app

### ISSUE THREAD

**Issue by cmusik** [Runalyze/Runalyze#1929]
Importing a tcx file from meerun android app leads to wrong values for average heartbeat. Also the trimp value is wrong. In my training files I have an average heartbeat of 20 bpm. With the attached file you will be able to reproduce this behavior.
[run.txt](https://github.com/Runalyze/Runalyze/files/453868/run.txt)

**Comment by mipapo** [comment]
That file is really bad
Always repeating timestamps (why they do that?)
```
                    <Trackpoint>
                        <Time>2016-08-02T17:03:23.631Z</Time>
                    </Trackpoint>
                    <Trackpoint>
                        <Time>2016-08-02T17:03:23.631Z</Time>
                    </Trackpoint>
                    <Trackpoint>
                        <Time>2016-08-02T17:03:23.631Z</Time>
                        <HeartRateBpm xsi:type="HeartRateInBeatsPerMinute_t">
                            <Value>145</Value>
                        </HeartRateBpm>
                    </Trackpoint>
```
Have you removed the GPS points?

**Comment by mipapo** [comment]
And I don't have any problems importing that file in version 3.0

**Comment by cmusik** [comment]
Yes, this also happens in 3.0. Import works, but the calculated values are not correct. See 
![screenshot_20160904_120421](https://cloud.githubusercontent.com/assets/150486/18230342/e3f2be3c-7297-11e6-9f3e-e368be4daeec.png)

I also tried to remove these empty points, but somehow I the file does not import correctly. What works right now is importing to runtastic and export it.

**Comment by mipapo** [comment]
Your first problem description wasn't that clear ;)
First of all you should contact meerun: They should fix that issue with equal data points (timestamps). Our parser is confused by that data. If that would be correct the shown paces would be alright.

We will have a look at the parser to ignore same data points in the future, but that does not change the fact that the file is not correct.

**Comment by mipapo** [comment]
And to fix the problem at once - Remove the time series from that activity (edit the activity). You won't see any laps anymore, but the TRIMP and JD value would be corrected.

**Comment by laufhannes** [comment]
Never saw such a horrible file so far ...

**Comment by mipapo** [comment]
As it's definitely a bad file produced by meerun android app we won't put any effort into this to fix their errors
