### ISSUE TITLE
Certificate error at https://blog.runalyze.de/feed/

### ISSUE THREAD

**Issue by jluttine** [Runalyze/Runalyze#1930]
For your information, the certificate is improperly configured at https://blog.runalyze.de/feed/ thus RSS readers don't work.

**Comment by mipapo** [comment]
It's really curious - Sometimes I can reproduce that problem (at home), but at another moment not. I will have a second look at it.
You're using Google Chrome?

**Comment by jluttine** [comment]
Nope, Iceweasel (i.e., Firefox).

**Comment by mipapo** [comment]
@jluttine Can you verify that it works now?

**Comment by mipapo** [comment]
@jluttine Can you confirm that it works? 
We moved the sites to another server and for one host the certificate was missing. Sorry for that

**Comment by jluttine** [comment]
I still get the error when reloading/refreshing the page. Does it take some time to propagate?

**Comment by jluttine** [comment]
```
blog.runalyze.de uses an invalid security certificate.
The certificate is only valid for blog.runalyze.com
Error code: SSL_ERROR_BAD_CERT_DOMAIN 
```

**Comment by jluttine** [comment]
With .com TLD it works: https://blog.runalyze.com/feed/
But there was a link to .de TLD at the bottom of this page: https://blog.runalyze.com/ (the feed icon)

**Comment by jluttine** [comment]
So perhaps you want to change the links pointing to .de to point to .com?

**Comment by mipapo** [comment]
Sorry - Only now I see that you meant .de. Forgot to support the old domain when moving to the new server

**Comment by jluttine** [comment]
No problem, didn't notice that myself first either. Thanks!
