### ISSUE TITLE
GPX-Import: use last valid heart rate as fallback

### ISSUE THREAD

**Issue by Celphor** [Runalyze/Runalyze#1936]
Hi,

this applies to Version 3.0.0 (didn't check previous versions)

I did a slow steady run at approx. 140 bpm and found that the calculation of average HR values in laps is wrong. As well the absolute value in the day analysis view as the percentage value in the laps details view.
I checked that values in the mysql table are correct.

The bug comes from runalyze/inc/core/Data/Laps/Calculator.php 

$Lap->setHR($this->TrackdataLoop->average(Trackdata\Entity::HEARTRATE), $this->TrackdataLoop->max(Trackdata\Entity::HEARTRATE));

The average function already delivers the wrong values. Values are always way too low.

Find attached a file to reproduce it. Avg should always be around 140 bpm (except for the beginning maybe)

[Workout-2016-09-16-16-31-46.zip](https://github.com/Runalyze/Runalyze/files/477704/Workout-2016-09-16-16-31-46.zip)

Cheers and happy running

Add 1: Further investigation showed that the track file doesn't include HR data for every track point ;-) This means, that the divisor in the average function must not necessarily be the number of track points, it must be the number of non-zero HR trackpoints 

Add 2: This affects also TRIMP, VDOT and JD calculation. Global HR avg is not affected since zeros are handled properly in inc/core/Calculation/Distribution/TrackdataAverages.php

Add 3: As I don't know how the values for TRIMP, VDOT and JD are calculated in detail, wouldn't it be the easiest solution (despite using a device producing better GPX data :-P ) to interpolate the missing data during import?

**Comment by Celphor** [comment]
Here is the trivial fix to reuse the last known bpm, see comment.

File is  class.ParserGPXSingle.php

       /**
         * Parse extension values
         * @param SimpleXMLElement $Point
         * @return int
         */
        private function parseExtensionValues(SimpleXMLElement $Point) {
                $bpm  = 0;
                $rpm  = 0;
                $temp = 0;

                if (isset($Point->extensions)) {
                        if (count($Point->extensions->children('gpxtpx',true)) > 0) {
                                if (isset($Point->extensions->children('gpxtpx',true)->TrackPointExtension)) {
                                        $TPE = $Point->extensions->children('gpxtpx',true)->TrackPointExtension;
                                        if (count($TPE->children('gpxtpx',true)) > 0 && isset($TPE->children('gpxtpx',true)->hr))
                                                $bpm = (int)$TPE->children('gpxtpx',true)->hr;

                    if (count($TPE->children('gpxtpx',true)) > 0 && isset($TPE->children('gpxtpx',true)->cad))
                                                $rpm = (int)$TPE->children('gpxtpx',true)->cad;

                    if (count($TPE->children('gpxtpx',true)) > 0 && isset($TPE->children('gpxtpx',true)->atemp))
                                                $temp = (float)$TPE->children('gpxtpx',true)->atemp;
                                }
                        }

                        if (count($Point->extensions->children('gpxdata',true)) > 0) {
                                if (isset($Point->extensions->children('gpxdata',true)->hr))
                                        $bpm = (int)$Point->extensions->children('gpxdata',true)->hr;

                                if (isset($Point->extensions->children('gpxdata',true)->cadence))
                                        $rpm = (int)$Point->extensions->children('gpxdata',true)->cadence;

                                if (isset($Point->extensions->children('gpxdata',true)->temp))
                                        $temp = (int)$Point->extensions->children('gpxdata',true)->temp;
                        }
                }
                /**
                 * Add this if-clause to fix
                */
                if($bpm == 0 && sizeOf($this->gps['heartrate']) > 0) {
                   $bpm = $this->gps['heartrate'][sizeOf($this->gps['heartrate'])-1];
                }
                $this->gps['heartrate'][] = $bpm;
                $this->gps['rpm'][]       = $rpm;
                $this->gps['temp'][]      = $temp;
        }

`

**Comment by laufhannes** [comment]
The general problem will be fixed with a pass-through filter for activities (#1576) in future. But as that will need some more time, I'll apply b39eced7874e68178a0e567cb6c63b107fe9dc62 for the gpx parser as well (it's only in the tcx parser so far for fixing #1742 - and it's nearly the same as you're proposing).
