### ISSUE TITLE
Add activity tool to analyze time series

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1943]
Add tool for activities to analyze time series.
- [X] analyze all available time series in terms of mean/min/max/median/cov/std
- [x] show mode as well [see #1494]
- [x] ~~explain why 'mean pace' is not equal to `total time / total distance`~~
- [x] use unit system from config
- [x] tooltips / explanations for single values

Optional features using d3js:
- [ ] add sparklines
- [ ] add histograms for zones

**Comment by mipapo** [comment]
@laufhannes  So what we need for "use unit system from config"?

**Comment by laufhannes** [comment]
A configuration service that provides configuration values for a given user (with default values as fallback), such that we can use this service, or more precisely: the config value, as parameter for a twig filter, i.e. `{{ currentDistance | distance(configuration(app.user).general.unitSystem) }}` or something like that.

**Comment by laufhannes** [comment]
Unit system is added in 5e03e29264472132c8c008aee63a9b4233417df2.
