### ISSUE TITLE
Update via browser fails because account table is not up to date

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1950]
The update controller is a standard frontend controller such that it loads current user from sessions' security token. This fails, as the account table changed but this change has not been applied to the database:
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 't0.gender' in 'field list'
```

**Comment by mipapo** [comment]
I don't like the browser updater  ;) I wish we could just remove it

**Comment by laufhannes** [comment]
I'm open for any ideas for another way to update installations on shared hosts without console access ;)

**Comment by laufhannes** [comment]
... still no answer at http://stackoverflow.com/questions/39696728/symfony-migration-of-user-table-via-browser

**Comment by laufhannes** [comment]
Well, using the following in our `security.yml` works:
```yaml
security:
    firewalls:
        setup:
            pattern:  ^/(update|install)
            security: false
```

Currently, I don't see a problem with that as we don't use admin accounts for authentication so far and any user can access these routes anyway (assuming that `update_disabled: no` in `config.yml`).

I just don't see a way to solve this issue if we use actual accounts for admin login some day (see #1110).
