### ISSUE TITLE
Add info to vdot in calculation panel

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1961]
Add info button if VDOT is 0.00 -
e.g. "VDOT value can be only calculated if your activities contain heartrate data"

![14642663_1161855457241380_1924439398_n](https://cloud.githubusercontent.com/assets/2135076/19218884/accb8388-8e05-11e6-88f2-1cb576f2cf2f.png)

**Comment by laufhannes** [comment]
+ hide prognoses (i.e. show warning instead)
 + hide pace suggestions

**Comment by mipapo** [comment]
These are things we could add just now, but I would prefer to add it after refactoring the panels with using twig tpl

**Comment by laufhannes** [comment]
There was another question at laufforum.de because of similar values. Seems this is a 'must' enhancement for v3.1, no matter if plugins are refactored or not.
