### ISSUE TITLE
Import Wahoo Tickr files - *.wf (and csv)

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1965]
See _support ticket  000873_ for example files

Running Dynamics (Vertical Oscillation and Ground Contact Time ) are available in the wf and csv file. 
> (denoted as "gct" and “vertoscillation” in the .wf file and “ma_gct” and “ma_vertosc” in the .csv file).

**Comment by laufhannes** [comment]
There's a lot of merging required when importing .wf-files. I prefer to support their .csv-files only.
