### ISSUE TITLE
ttbin parser/importer extract wrong/different steps-per-minute (spm) values

### ISSUE THREAD

**Issue by dominik0711** [Runalyze/Runalyze#1967]
[Running_11-34-32.ttbin.zip](https://github.com/Runalyze/Runalyze/files/541502/Running_11-34-32.ttbin.zip)

Importing attached ttbin file into online-runalyze version v3.0.1 I did receive a wrong/different spm value according to https://mysports.tomtom.com.

Mysports page displays 179 steps/min and runalyze 168 steps/min.

Why do I get such a huge difference between these two values?

I'm using TomTom GPS Runner Cardio

**Comment by mipapo** [comment]
Please zip the file and add it to your issue report

**Comment by laufhannes** [comment]
We can't tell you how MySports/TomTom calculates this value and we can't guarantee that the resulting tcx file of the ttbin converter is correct, as it's a third party tool.

But looking at the resulting cadence values in the tcx file, our result of 168/min is absolutely correct. There are not even values above 180/min, i.e. 179/min as mean seems very unrealistic.

Feel free to provide a screenshot of the cadence graph from MySports/TomTom, but I guess it's an issue on MySports' side.

**Comment by dominik0711** [comment]
@mipapo Sorry for the cross-postings! I have added the zipped ttbin-file in my post.
@laufhannes MySports/TomTom didn't show up a diagram with spm but the average value. See screenshot attached:
![screen shot 2016-10-20 at 19 22 03](https://cloud.githubusercontent.com/assets/1011188/19570525/b0c6d6ce-96fa-11e6-9032-65d6d9002df7.png)

Importing the **fit** file format to runalyze didn't show spm, Bodenkontaktzeit, Vertikale Bewegung and Vertikales Verhältnis values at all. Is there a reason for that?
Is it correct, that the only option to import data from TomTom is the **ttbin** file format? 

What about all the other values like:
- Bodenkontaktzeit
- Vertikale Bewegung
- Vertikales Verhältnis

**Comment by mipapo** [comment]
@dominik0711 I think you should be able to export from MySports a gpx or tcx file.
The specs of the ttbin file format are unfortunately not public.
In the future we will have a direct sync with MySports - Anytime in the beginning  of the next year

Bodenkontaktzeit, Vertikale Bewegung, Vertikales Verhältnis are not recorded by TomTom

**Comment by dominik0711** [comment]
@mipapo Thanks for the info! Importing gpx or tcx file height meters and spm values missing as well. See screenshot:
![screen shot 2016-10-20 at 19 43 40](https://cloud.githubusercontent.com/assets/1011188/19571271/c89311ca-96fd-11e6-8a8d-c48e4f033e08.png)

**Comment by mipapo** [comment]
@dominik0711 okay gpx does not support those type of information. TCX should contain  the spm data, but I've never seen a tcx file by TomTom, so you have to add the file here.
The elevation will be added after inserting the activity.

**Comment by dominik0711** [comment]
@mipapo This is the exported TCX file. See attachment.
[run-20161020T113432.tcx.zip](https://github.com/Runalyze/Runalyze/files/542474/run-20161020T113432.tcx.zip)

**Comment by dominik0711** [comment]
Sorry, I just hit the wrong button ;-)

**Comment by mipapo** [comment]
@dominik0711 That's so sad :( TomTom MySports seem not to export the data - So I cannot say if the third-party converter is wrong. But the data of the converted file we are importing is correct. 

Is there a graph/plot for the cadence of the activity? 
I'm still waiting that TomTom is creating a dummy account for testing for me.

In the moment I would just say, that you should write a message in there forum:
https://en.discussions.tomtom.com/mysports-connectappswebsite-389
Including the feature request to add the cadence information to the tcx file export.
I don't think that they will answer to the question: "I'm using the ttbin converter at https://github.com/ryanbinns/ttwatch - They include the cadence information in the tcx file, but the average is different to MySports - Is there something wrong on your website".

I don't have time to write a message to the forum. Would be great if you do it and add the url to the post here

**Comment by dominik0711** [comment]
The [altera2015](https://github.com/altera2015/ttwatcher) application based on [ryanbinns-ttwatch](https://github.com/ryanbinns/ttwatch) ttbin converter. This application extracts the cadence (rpm) which is exactly the same as spm in the tool. So the ttbin format does have the values for spm.
See developer answer at [TomTom-Forum](https://en.discussions.tomtom.com/mysports-connectappswebsite-389/running-cadence-not-posting-to-strava-831433):

The watch does track the cadence on a per data point basis. I don't know why TomTom doesn't export the data but it's there. I've written a tool so you can see and export to tcx files your cadence for running activities.

https://github.com/altera2015/ttwatcher

**Comment by mipapo** [comment]
@dominik0711 You didn't understand me - I never said that ttbin does not contain the rpm/spm! 
The "ttwatcher" does use the ryanbinns-ttwatch so it will have the same values.

**Comment by mipapo** [comment]
@dominik0711 Have you contacted TomTom? Any further questions or can I close this issue?
