### ISSUE TITLE
Laps window wrongly uses %HRreserve for vdot calculation

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1981]
That should be `inHRmax()` instead of `inPercent()` in [Data/Laps/Calculator.php#L306](https://github.com/Runalyze/Runalyze/blob/9ca1e9de13455f9407ea843f61298e4fdb8df09b/inc/core/Data/Laps/Calculator.php#L306):
```php
$VDOT = new Calculation\JD\VDOT();
$VDOT->fromPaceAndHR(
	$distance,
	$Lap->duration()->seconds(),
	$Lap->HRavg()->inPercent() / 100
);
```

*Can be cherry-picked for v2.6.8.*

**Comment by mipapo** [comment]
cherry picked for 2.6.8: 05b5d63fa1c55c511dd0f110b937139059bd4275
