### ISSUE TITLE
Idea: recalculation daemon/tool

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#1988]
As the system grows I think there is a need to push recalculations to a background process/tool.
What I imagine is a flag on activity that marks it for recalculation. The daemon would scan for activities that need recalculation and recalculate them. The UI would show if there are any activities that are waiting for recalculation.

**Comment by mipapo** [comment]
What kind of recalculations on activities do you mean?

In general ragarding queing system - We will use/add http://bernard.readthedocs.io/ in the future

**Comment by grzeg1** [comment]
For starters, everything that is under database cleanup.

**Comment by mipapo** [comment]
Yep, same applies for backup creation.

**Comment by mipapo** [comment]
summarized in #1989
