### ISSUE TITLE
Session file needs to be deleted after deletion

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1994]
When the user is logged in and deletes their account by clicking the uri the session is not deleted. 
Runalyze will not be accessible for that user

**Comment by laufhannes** [comment]
Is something like `$request->getSession()->invalidate()` what we need? E.g.
```php
    public function deleteAccountConfirmedAction($hash, Request $request)
    {
        if ($this->getAccountRepository()->deleteByHash($hash)) {
            $request->getSession()->invalidate();

            return $this->render('account/delete/success.html.twig');
        }

        return $this->render('account/delete/problem.html.twig');
    }
```

**Comment by laufhannes** [comment]
In which way is the page '*not accessible*' for the user? I tried it both ways, with invalidation and without. In both cases, trying to access the base url directly after deleting an account throws the following error:

> request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "You cannot refresh a user from the EntityUserProvider that does not contain an identifier. The user object has to be serialized with its own identifier mapped by Doctrine." at ../vendor/symfony/symfony/src/Symfony/Bridge/Doctrine/Security/User/EntityUserProvider.php line 86

But refreshing the page successfully redirects to login form.

**Comment by laufhannes** [comment]
Okay, the token has to be set to null as well:
```php
$this->get('security.context')->setToken(null);
```
