### ISSUE TITLE
Darksky provider: wind speed is wrong

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1998]
We use `$WindSpeed->setMeterPerSecond($this->Result['currently']['windSpeed']);` but the [docs](https://darksky.net/dev/docs/response#data-point) state "_The wind speed in miles per hour._".

**Comment by mipapo** [comment]
`UPDATE runalyze_training SET wind_speed=wind_speed*2,23694 WHERE weatherid=3 AND wind_speed IS NOT NULL`

**Comment by mipapo** [comment]
`UPDATE runalyze_training SET wind_speed=wind_speed*0.44704 WHERE weather_source=3 AND wind_speed IS NOT NULL`

**Comment by mipapo** [comment]
`update runalyze_weathercache set wind_speed=wind_speed*0.44704 where weather_source=3 AND wind_speed is not null;`
