### ISSUE TITLE
Tool: ANOVA boxplots

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#2013]
Add a new tool to analyze some basic values grouped by e.g. sport or activity type.

 - Selection should be possible by at least
   - [x] time range
   - [x] sport type 
 - Grouping should be possible by
   - [x] time (month / year)*
   - [x] sport type
   - [x] activity type
   - [x] equipment types (that are in 'single' mode)
 - Use d3.js for plotting, use json responses
 - Optional bonus feature:
   - [ ] option for a second grouping that is done within each group and shown by different colors
      - example:
        - look at duration grouped by sport + grouped by year for each sport
        - group by year _and_ month (the default grouping will merge different years if grouped by month)
      - how to show axis/legend?
 - Further improvements in future:
   - grouping by zones?

\* requires something like https://github.com/beberlei/DoctrineExtensions

Current example:
![bildschirmfoto 2016-12-11 um 22 13 15](https://cloud.githubusercontent.com/assets/8313118/21083568/64c3e484-bff3-11e6-9716-420273fd18f8.png)

Currently missing:
 - [x] scale is very bad for 'inverse' units (e.g. km/h)
- [x] cut axes labels (similar to `text-overflow: ellipsis`) in case of long group names
   - [ ] tooltip or similar would be great
 - [ ] option to show only groups with data (depends on grouping; hardcoded so far)
  - [ ] additional group _None_ for nullable groupings? (only optional?)
 - [ ] show total number of activities for a group

**Comment by mipapo** [comment]
Respects km/miles user settings?

**Comment by laufhannes** [comment]
That should work already (although I did not try to change my settings so far), as there's `QueryValueInterface::getValueUnit(UnitSystem $unitSystem)` and the json response contains a `tickFormatter`:
```php
return $this->json([
    'tickFormatter' => JavaScriptFormatter::getFormatter($query->getValueUnit($unitSystem)),
    // ...
]);
```

**Comment by laufhannes** [comment]
This is ready for merging.

The remaining todos do not hurt. Feel free to add new PRs for them if you'd like to have the additional gimmick.
