### ISSUE TITLE
Use geohashline to reduce required space for routes

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#2016]
- First step: use geohash line in database 
 - Optional: use geohash line for leaflet visualization (see #1296)

See #1556 for a general ticket for array compression in database.

Work is in progress in branch [geohashline](https://github.com/Runalyze/Runalyze/tree/geohashline).

**Comment by mipapo** [comment]
@laufhannes "Optional: use geohash line for leaflet visualization" would need to recode the GeohashLine Method in js - correct?

**Comment by laufhannes** [comment]
Yep.
