### ISSUE TITLE
Tool (for admins): check database structure

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#203]
**Reported by laufhannes on 29 Feb 41912084 16:26 UTC**
Ist die Datenbank-Struktur so, wie sie sein soll?

In verschiedenen eigenen Methoden soll festgelegt werden knnen, wie die Datenbank auszusehen hat. (Kombination/Erstellung der structure.sql?) - Falls Spalten fehlen etc. -> Fehlermeldung.

berlegung fr Performance:
- Soll die berprfung jedes Mal ausgefhrt werden?
- nur wenn Fehler in der Mysql-Klasse auftreten?
- nur wenn eine update.php o.. hinterlegt wurde?

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/203

**Comment by laufhannes** [comment]
Doctrine will do this some day ... we don't need to put any special effort in this.
