### ISSUE TITLE
Add Retina Map Support

### ISSUE THREAD

**Issue by chpusch** [Runalyze/Runalyze#2036]
I have checked the map providers for retina support. My first analysis provided following results:

Only listed providers with retina support
- CartoDB: //{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}**@2x**.png
- Esri: //server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}@2x
- Esri Sat: //server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}@2x
- Stamen Toner: //stamen-tiles.a.ssl.fastly.net/terrain/{z}/{x}/{y}**@2x**.png

I have found an additional terrain retain map provided by Stamen without api key. Maybe this map is an ideal replace for other terrain maps (see screenshot below):
- Stamen Terrain: //stamen-tiles.a.ssl.fastly.net/terrain/{z}/{x}/{y}@2x.png

<img width="958" alt="bildschirmfoto 2017-01-08 um 14 17 26" src="https://cloud.githubusercontent.com/assets/10895164/21750169/3de4c8c2-d5ad-11e6-80de-53f5274fd512.png">

Regards,
Christian

**Comment by mipapo** [comment]
Thank you for you suggestion for improvement.
It has not that high priority for us, but I will keep an eye on it.

**Comment by laufhannes** [comment]
I did not look long into this, but as far as I understand, there are two ways to "support" retina displays:
 1) set `detectRetina: true` in leaflet's options (_If true and user is on a retina display, it will request four tiles of half the specified size and a bigger zoom level in place of one to utilize the high resolution._)
 2) set respective urls in [runalyze.leaflet.layers.js](https://github.com/Runalyze/Runalyze/blob/support/3.1.x/lib/leaflet/runalyze.leaflet.layers.js) based on `L.Browser.retina`
(ctrl+f "retina" on http://leafletjs.com/reference.html)

The first one will work for all layers but triggers more requests, the second one does only work for some layers. I guess it's not (easily) possible to combine both.

**Comment by chpusch** [comment]
Thanks for your fast answer. 

I have tried booth solutions with another "project" I am working on. 
With the leaflet option activated (no. 1) it is not possible to read names etc. on maps. The second solution is not available for every map, but it seems to be the better solution. 

Both screenshots are attached. I have used an iPhone 6s. 

No. 2 - retina tiles and good readability. 
![img_2426](https://cloud.githubusercontent.com/assets/10895164/21786036/6278a8be-d6c2-11e6-8e8b-8d827c8e486e.PNG)

No. 1 - leaflet's retina option. 
![img_2427](https://cloud.githubusercontent.com/assets/10895164/21786037/629e0758-d6c2-11e6-9036-1dd6d7e9c957.PNG)

Regarding the pull request. I will do it within the following week.

**Comment by chpusch** [comment]
I would suggest to use the second option. If the tile server supports retina tiles, the code should look like this:

`    var map = L.map('map');
     L.tileLayer('//api.mapbox.com/styles/v1/chpusch/xyz/tiles/256/{z}/{x}/{y}' + (L.Browser.retina? '@2x': '') + '?access_token=xyz').addTo(map);`

This is an example from my mapbox code. I will integrate the L.Browser.retina option within the following file Runalyze/lib/leaflet/runalyze.leaflet.layers.js, if the tile server supports retina.
