### ISSUE TITLE
Poster tool

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#2049]
Ideas and discussion at: https://forum.runalyze.com/viewtopic.php?f=8&t=604
Using adjusted version: https://github.com/laufhannes/GpxTrackPoster/tree/runalyze

Decide if the python script should run in a venv environment or not (I prefer yes) 
Will need something like
`$result = system("ENV/bin/python test.py");`

Tool depends on #1989 - (Won't work without queuing)

- [x] Choose year
- [x] Choose sport
- [x] Change title

Before a discussion begins: Using different languages for a (big) project is quite normal, it's like using microservices. We will not recode everything into php but stay with python in this case.

**Comment by laufhannes** [comment]
Currently missing in the branch:
 - [ ] option to keep title empty

And, at least for me, circular poster does not show month names?
