### ISSUE TITLE
Wahoo TICKR X csv from Android app

### ISSUE THREAD

**Issue by rostykk** [Runalyze/Runalyze#2052]
So we have working csv import from wahoo generated by iOS app #1965 
Don't ask why Wahoo team choose a different way of export in android app.

So i made all possible exports and found that "Running analytics" (like Ground contact time, Vertical oscillation, Smoothness) export only in CSV file.
Android app generates several CSV files depending on the type of sensor attached, unlike iOS app.

As I understand key sync data is timestamp (due different ID counts in files)
A data field name also differ from iOS.
According to Wahoo support running smoothness algorithm start worked after reaching 9.5 km/h speed

I attached a sample export: [20170129_132351_1.zip](https://github.com/Runalyze/Runalyze/files/737608/20170129_132351_1.zip)
+ screenshots how it looks from app
![screenshot_2017-01-29-16-39-00](https://cloud.githubusercontent.com/assets/3607571/22405452/46340b18-e643-11e6-9306-ef982fffd4c7.png)
![screenshot_2017-01-29-16-39-14](https://cloud.githubusercontent.com/assets/3607571/22405453/46375840-e643-11e6-8b83-d8a6df43ae4c.png)
![screenshot_2017-01-29-16-39-26](https://cloud.githubusercontent.com/assets/3607571/22405454/463a89d4-e643-11e6-9a9b-9fa495352df6.png)
![screenshot_2017-01-29-16-39-37](https://cloud.githubusercontent.com/assets/3607571/22405455/463d4b92-e643-11e6-90bc-4295596476e6.png)
![screenshot_2017-01-29-16-39-48](https://cloud.githubusercontent.com/assets/3607571/22405456/463fffea-e643-11e6-82fd-1623e976dbd8.png)

**Comment by laufhannes** [comment]
All these four files (i.e. four sensors) have different sample rates. That's essentially very similar to the iOS' .wf-file which I decided not to support so far, as a lot of merging (and approximations) will be required to get samples with equal sample rate.

Of course, we are open for pull requests for this issue, but we will probably not put any effort in this on our own.

**Comment by mipapo** [comment]
Android app and IOS does support TCX, FIT, GPX, PWX export again. (" We brought back TCX, PWX, GPX, FIT export options "). 
But we will contact them to support pushing activites directly to Runalyze
