### ISSUE TITLE
Add Strava activity import

### ISSUE THREAD

**Issue by ebrensi** [Runalyze/Runalyze#2053]
Hello, I'd like to add Strava activity import.  I've done this with my own Python app https://heatflask.herokuapp.com but I need to get familiar with this code base.  Can someone point me to where I would add that feature?

In order for that to work, someone needs to 
 (1)set up a Strava account for this app, 
(2) set  STRAVA_CLIENT_ID and STRAVA_CLIENT_SECRET environment variables with that account's client id and client secret from the account settings.

**Comment by mipapo** [comment]
There is no way to add Strava activity import to RUNALYZE in the moment. Sorry

**Comment by mipapo** [comment]
So you should wait until we have an API (Instead of adding the APIs on our side we will start with supporting tapiriik.com and other activity sychronisation sites).

**Comment by ebrensi** [comment]
@mipapo, what you are suggesting is quite complicated.  Tapiriik is a file syncing system.  If you go that route, clients will have to set up a Tapiriik account in addition to their other accounts, and you will have to download and store files, convert file-types, etc.    With Strava's API you don't need to download or store any files, you don't need to deal with anyone's passwords, and most people are already on Strava.

Anyway, I have experience with Strava API and I'm willing to help if you change your mind.

**Comment by mipapo** [comment]
@ebrensi Well the problem is that is really hard to support so many APIs like Polar, Garmin Connect, Strava and so on. We don't have time always looking at their changes. So we have decided to add an API to Runalyze to provide a fast solution (adding every API is really time consuming)

**Comment by laufhannes** [comment]
> and most people are already on Strava

Well, from our point of view, Strava is a competitor. There may be a lot of users on Strava, but covering Garmin Connect, Polar Flow and Movescount is more important. And we don't want to give users a reason to register at Strava, if they didn't so far ;)

Serving a complete API is quite challenging, but it will allow us to cover all other platforms at once. As soon as we have an open API, it's not our job to support special platforms. That can be done by other people writing scripts to move data from such a platform to Runalyze. (At that point, you can write a sample script to connect Strava and Runalyze)

**Comment by ebrensi** [comment]
ok sounds good!  I have wanted to use Runalyze, but downloading and uploading thousands of files is such a pain that I don't bother.   I'm sure a few other people must feel that way too.  Anyway I'd love to contribute.

**Comment by ebrensi** [comment]
Also I want to point out that Garmin's official API costs $5000 to use, last I checked.  Tapiriik does not use the Garmin API, but rather uses a hack script that scrapes Garmin Connect using your username and password, which you supply to Tapiriik.  

Is your idea that you want users to keep their own files and upload metadata? or do you store copies of all the activities on Runalyze?

**Comment by mipapo** [comment]
@ebrensi We know that. And sadly Tapiriik does not support the sync of fit files. (Strava doesn't provide the original files too!)
We don't keep the original files, but we store the files in our database.

**Comment by laufhannes** [comment]
> have wanted to use Runalyze, but downloading and uploading thousands of files is such a pain that I don't bother. I'm sure a few other people must feel that way too.

My default response is that Runalyze is a platform for a detailed training analysis. This won't work with just pushing all data at once without adjusting them (especially the activity type). So, at least for me, I'm always setting more data that can be imported automatically and thus there's not a big difference if I need to spend one more minute each day to get the fit files from Garmin.

But yes, I know that there are other people that feel the same way you do, and yes, we know that the lack of a way to automatically sync other platforms with Runalyze is a big issue. Indeed, it's one of the three biggest issues we currently have.

A few months ago, we were planning to add vendors with their respective apis, starting with a small one like TomTom. But as @mipapo said: We'd have to read and understand all these apis and write syncing services for them.

But I'm not an api expert in any sense, so I can't tell how to start with the api stuff and what's required. But that is what needs to be done now: Create a 'plan' of how to create that api.

> Also I want to point out that Garmin's official API costs $5000 to use, last I checked. Tapiriik does not use the Garmin API, but rather uses a hack script that scrapes Garmin Connect using your username and password, which you supply to Tapiriik.

Well, for Tapiriik it shouldn't be a problem to collect $5000. And if I get it right, it's still possible to automatically connect Strava and Garmin Connect and then use Tapiriik to sync Strava with any other platform (i.e. Runalyze later on) without supplying a password?
