### ISSUE TITLE
Gulp/JS: check why scripts.min.js is that large

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#2054]

**Comment by mipapo** [comment]
Same problem? https://github.com/terinjokes/gulp-uglify/issues/236

**Comment by laufhannes** [comment]
Source maps seem to cause this issue. Only `scripts.min.js` has a source map added and its file size reduces to 0.8 MB without it.

We should write source maps to external files, see https://www.npmjs.com/package/gulp-sourcemaps#write-external-source-map-files. As stated in https://blog.sentry.io/2015/10/29/debuggable-javascript-with-source-maps.html, "_browsers only download and apply source maps when developer tools are open. There is no performance impact for regular users._".
