### ISSUE TITLE
ANOVA: Es ist ein Problem aufgetreten. (Fehler beim Plotten)

### ISSUE THREAD

**Issue by schmidi** [Runalyze/Runalyze#2055]
I tried to get boxplots with the new feature. Unfortunately I always get the error: 
Es ist ein Problem aufgetreten. (Fehler beim Plotten).

![screenshot-004](https://cloud.githubusercontent.com/assets/411354/22419364/74868f5a-e6dd-11e6-8f09-b4df62c1fde0.png)

Console shows the following error:

![screenshot-004](https://cloud.githubusercontent.com/assets/411354/22419438/ca141aa0-e6dd-11e6-9172-3d5069f212b8.png)

The ajax request works as expected and delivers a json object with values.

**Comment by mipapo** [comment]
Bitte lade dir das Paket erneut herunter (Siehe https://forum.runalyze.com/viewtopic.php?f=45&p=2737)
Die Javascriptdatei war nicht aktuell

**Comment by schmidi** [comment]
Danke für die schnelle Antwort. Nun funktionierts.
