### ISSUE TITLE
Backup tool: sql backup is not production ready

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#2056]
The sql backup does not contain all tables, e.g. `runalyze_weathercache` is missing.

 * **Option a)**: Remove the sql backup completely. Athlete-specific backups should be done as .json.gz and installation-specific backups should be done by admins (via cli/phpmyadmin) only.
 * **Option b)**: Add definitions for all tables in sql-backups. This requires [AbstractBackup](https://github.com/Runalyze/Runalyze/blob/78db9ab89c183976e5a5f9c8a673f64187021b94/src/CoreBundle/Component/Tool/Backup/AbstractBackup.php#L58) to stay consistent with our database structure.
 * **Option c)**: State clearly that sql-backups should only be used to fill an existing database structure. In that case, `AbstractBackup::saveTableStructure()` can be removed as it's not used by `JsonBackup` and there's no need to save table definitions in sql anymore.

**Comment by mipapo** [comment]
I prefer Option a)
That kind of sql backup is not important for most people and a general backup should be done via admin tools (cli / pma)

**Comment by mipapo** [comment]
@laufhannes What do you prefer?

**Comment by laufhannes** [comment]
I'm not quite sure. I don't like b), so I prefer to use c) for 3.x and drop the sql export in some future 4.x.

**Comment by mipapo** [comment]
Sounds good
