### ISSUE TITLE
Gpx-import: Only first extension is used

### ISSUE THREAD

**Issue by TkTzLabs** [Runalyze/Runalyze#2064]
Hello there ,

I am facing a problem with GPX file. There are a lot of information as HR,CADENCE and etc but I believe that only HR was parsed - could you check that out ? 
[stepan-s-hr.zip](https://github.com/Runalyze/Runalyze/files/753289/stepan-s-hr.zip)

Regards,

Tktz

**Comment by laufhannes** [comment]
The problem is that multiple extensions are used:
```
          <gpxtpx:TrackPointExtension xmlns:gpxtpx="http://www.garmin.com/xmlschemas/TrackPointExtension/v1">
            <gpxtpx:hr>108</gpxtpx:hr>
          </gpxtpx:TrackPointExtension>
          <gpxdata:cadence>42</gpxdata:cadence>
```

So far, our importer does only support one extension. That's why only hr is imported. We'll have a look at it.

In the meantime, just use another format. I think Movescount has sml and maybe even fit files?
