### ISSUE TITLE
RPE: Coloring like e.g. TRIMP

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#2065]
RPE values, from blue, to green, to yellow, to red.

https://forum.runalyze.com/viewtopic.php?f=8&t=639

**Comment by laufhannes** [comment]
The trimp coloring works by coloring the text itself, but that's probably not very beautiful it is used for more than one color on that scale. I'd prefer a colored circle as indicator.

There seem to be various color scales out there, probably without any 'official' version. I like http://lifestylefitnessmanagement.com/wp-content/uploads/2015/10/RPE-scale.jpg from http://lifestylefitnessmanagement.com/understanding-training-benchmarks/

**Comment by mipapo** [comment]
![auswahl_039](https://user-images.githubusercontent.com/2135076/31316114-d6789046-ac26-11e7-8fb6-440d7f5770ee.png)
