### ISSUE TITLE
Add body-data from Medisana scale via bluetooth to self-hosted installations

### ISSUE THREAD

**Issue by genlinut** [Runalyze/Runalyze#2073]
With https://github.com/keptenkurk/BS440 you can read out body-data from Medisana bluetooth scales. With some modifications (https://github.com/genlinut/BS440/tree/Runalyze-Local-Integration-01 , just waiting for pull) it is possible to automatically add new measurements to your self hosted runalyze instance. 

What you need:
* linux with python
* bluetooth le on your server which serves runalyze (alternative: your mysql server is reachable via network)
* Medisana scale (maybe others)

**Comment by mipapo** [comment]
Nice idea, but I don't think that we will add it by ourselves as it makes no sense if only self hosted installation work. There should be a way over an API/Endpoint where someone could push that data to. 
Someone could add a command to Runalyze if it's interesing for him/her

**Comment by mipapo** [comment]
Oh I see  - Misunderstood what you've done. So it's just a information and we will not need to do anything?

**Comment by genlinut** [comment]
It would also work with an API, but right now the API is in development, right? As soon as the API works, I/anyone could extend the software.

Right, nothing to do now, except finishing the API :-)

**Comment by mipapo** [comment]
@genlinut Yep, but talking with the API would be part of the other software. 
So I will close this issue
