### ISSUE TITLE
Countable Exercises

### ISSUE THREAD

**Issue by timtammittee** [Runalyze/Runalyze#2075]
It would be amazing if there would be an option to create countable exercises. For example for push-ups pull-ups ...

This could be implemented as an additional option in the sports configuration.
Diagrams could then show number of repetitions instead of duration.

**Comment by mipapo** [comment]
From our idea the same like #164 so I will close this one.
In short: Needs a good concept and it's not in our focus yet. 
Added this to the other ticket as reference
