### ISSUE TITLE
Other Sport: Analysis not showing workout / Analyse zeigt ein Workout nicht an

### ISSUE THREAD

**Issue by nitzel** [Runalyze/Runalyze#2088]
1st: Analysis is a really cool feature. Thanks!
2nd: The bug-report is in english and in german. 

**EN**
When using a manually added kind of sport, one encounters a bug in Analysis. This does not appear when tagging the workout with *Running*.

While statistics is showing me *N* workouts and *M* kilometres total distance, analysis shows me *N-1* workouts and *M* kilometres total distance.
It seems that the workout with the highest speed is missing. 

But: With two workouts, 2nd one being the one with the higher speed, both were shown. Couldn't reproduce with 3 workouts. Could indeed reproduce with 4 workouts.

**DE**
Benutzt man eine manuell eingegeben Sportart, so zeigt sich unter Analyse ein Bug. Dieser taucht nicht auf, wenn man das Workout als *Laufen* taggt.

Während ich unter Statistik *N* Workouts zu insgesamt *M* Kilometern finde, zeigt Analye mir *N-1* Workouts - aber immer noch *M* Kilometer Gesamtstrecke.
Es scheint so, als würde das Workout mit der größten Geschwindigkeit ausgelassen werden. Wenn ein Workout mit höherer Geschwindigkeit hinzugefügt wird, wird das davor ausgelassene angezeigt.

Aber: Bei zwei Workouts, zweiteres hatte die höchste Geschwindigkeit, wurden alle angezeigt. Nicht mir 3 reproduzierbar? Dafür aber mit 4 reproduzierbar.

**Statistics** 1 workout, not shown in analysis
![image](https://cloud.githubusercontent.com/assets/8362046/23609186/14d38954-026d-11e7-9f18-c2a0289c477c.png)

**Analysis** 1 workout, not shown in analysis
![image](https://cloud.githubusercontent.com/assets/8362046/23609209/35dce1ae-026d-11e7-9e5a-7d7dc5a05b72.png)

**Overview** 3 workouts, one missing in analysis
![image](https://cloud.githubusercontent.com/assets/8362046/23609817/2c8cf2c6-0270-11e7-8c74-6c21394bc3cc.png)

**Statistics** 3 workouts, one missing in analysis
![image](https://cloud.githubusercontent.com/assets/8362046/23609758/e1d9e720-026f-11e7-8a81-dc6d9d4f43bb.png)

**Analysis:** 3 workouts, one missing in analysis
![image](https://cloud.githubusercontent.com/assets/8362046/23609787/0b7f3ac6-0270-11e7-856b-43f3d3022ff8.png)

**Even worse** 3 workouts, the two last missing, both max speed (same if only last one is max speed)
![image](https://cloud.githubusercontent.com/assets/8362046/23609937/cd41d07e-0270-11e7-96af-7b8342833d77.png)

**Working fine** 4 workouts, last is not max speed
![image](https://cloud.githubusercontent.com/assets/8362046/23610186/f200034e-0271-11e7-9de6-b470e5fdccb9.png)

**Sport-Type** (Also tested with pre-configured swimming and biking)
![image](https://cloud.githubusercontent.com/assets/8362046/23609520/bba4f03c-026e-11e7-8c75-b5e7f928915b.png)

I think this issue regards [file](https://github.com/Runalyze/Runalyze/blob/master/plugin/RunalyzePluginStat_Analyse/class.RunalyzePluginStat_Analyse.php). But because of my little php knowledge and no comments I am not able to find my way through. Maybe @laufhannes can help here.

**Comment by nitzel** [comment]
Additionally, Analysis has a dropdown to configure the timespan of what is shows (last years, 12 months, 6 months, etc). This seems to not work correctly, too.

**Comment by laufhannes** [comment]
My initial guess is that it depends on chosen pace unit for sport (i.e. it works for min/km for running but not for km/h) and it may be caused by some rounding error / `>=` inconsistency (i.e. it may work for a max speed of 5 km/h = 720 s/km but not for 4,2... km/h as it has some decimals in s/km).

I'll take a deeper look into this.

> Additionally, Analysis has a dropdown to configure the timespan of what is shows (last years, 12 months, 6 months, etc). This seems to not work correctly, too.

Can you specify in which way this does not work? I can't spot a problem there though it may look unfamiliar that 'Last 6 months' shows next 6 months as well.

**Comment by nitzel** [comment]
Sorry, I forgot to specify further. It is, as you expected, the future 6 months that confused me.

Your guess about the rounding error seems to be right. Heard about a rule of thumb not to use `=` and similar comparators with floating numbers. 
`3330m/1h`, about `18:11/km` does not show up with `min/km`. 
Adding another one at `33000m/1h`, about `1:49/km` makes the `18:11/km` show up but itself does not.
The order does not matter.
So I'll add to your guess, that the stride length / step width / increment (Schrittweite) that is used to group the speeds takes part in the problem. 

Thanks for the quick response!
