### ISSUE TITLE
MySql 5.7 not working

### ISSUE THREAD

**Issue by zaubererty** [Runalyze/Runalyze#2092]
I'm in the middle of creating a docker container for Runalyze.
My current progress is that I'm able to start the current master but not the latest support branch, there are some gulp issues open.
But back to the mysql point, the documentation recommends to use mysql 5.7, so I use 5.7.17.
It turns out that there is a breaking change in mysql between 5.6 and 5.7.

Here is the issue when you load the dashboard on a fresh installation:
`[2017-03-08 00:31:01] request.CRITICAL: Uncaught PHP Exception PDOException: "SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'runalyze.t.time' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by" at /var/runalyze/inc/system/class.PDOforRunalyze.php line 271 {"exception":"[object] (PDOException(code: 42000): SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'runalyze.t.time' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by at /var/runalyze/inc/system/class.PDOforRunalyze.php:271)"} []`

To fix that you might run on your server:
`SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));`

This is might something to state in the documentation.

As the sql_mode could not be set per database, only global or session, this may be something to be fixed.  

[Some more details](http://johnemb.blogspot.ch/2014/09/adding-or-removing-individual-sql-modes.html)

**Comment by laufhannes** [comment]
This is stated in our docs as known problem: https://docs.runalyze.com/en/latest/faq.html#runalyze-does-not-show-up-completely-mysql-only-full-group-by-problem

We might mention that in the system requirements but I do not favor trying to set `sql_mode` within the code base.

**Comment by laufhannes** [comment]
This is now mentioned in the installation instructions as well, see Runalyze/admin-docs@eef063141db172ec76daa4cdda15160322d92d20.

**Comment by zaubererty** [comment]
Thanks, great job.
