### ISSUE TITLE
AthletePosterCommand broken in branch master

### ISSUE THREAD

**Issue by sidddy** [Runalyze/Runalyze#2096]
Executing the AthletePoster command in current master branch fails, because the method TrainingRepository::getQueryForJsonPosterData() meanwhile expects a Sport object instead of a sportid integer:

 [Symfony\Component\Debug\Exception\ContextErrorException]                                                                                                                
  Catchable Fatal Error: Argument 2 passed to Runalyze\Bundle\CoreBundle\Entity\TrainingRepository::getQueryForJsonPosterData() must be an instance of Runalyze\Bundle\CoreBundle\Entity\Sport, integer given, called in /var/www/runalyze/src/CoreBundle/Command/AthletePosterCommand.php on line 92 and defined

**Comment by mipapo** [comment]
I think we will remove the command for the beginning. 
Feel free to fix the command or recreate it based on the new integrated version

**Comment by mipapo** [comment]
If anyone is interested in recreate the command should look at https://github.com/Runalyze/Runalyze/blob/master/src/CoreBundle/Queue/Receiver/PosterReceiver.php#L103  to understand how it should be done.
