### ISSUE TITLE
import tcx file laps using bulk-import feature

### ISSUE THREAD

**Issue by kootox** [Runalyze/Runalyze#2097]
Hi, I use the bin/console runalyze:activity:bulk-import to import activities on my runalyze instance. Activities are in tcx format coming from my Forerunner 405 watch using a python script (i'm using Linux).

I have none on the actual laps coming from my activities on runalyze. If i delete the activity and reimport it using the import form, I have all my actual laps.

Is it possible to fix the bulk-import feature so that laps form the tcx file are used ?

**Comment by laufhannes** [comment]
Can you try to add `$training->updateAfterParsing();` in [src/CoreBundle/Command/ActivityBulkImportCommand.php#L78](https://github.com/Runalyze/Runalyze/blob/3f59a9375eb748f439ca54a0e8b0afd8b9b8b829/src/CoreBundle/Command/ActivityBulkImportCommand.php#L78) just before `$training->insert();`?

**Comment by kootox** [comment]
Thanks for the quick response.

With adding this line, the import fails :

File: 20170309-113307.tcx
Warning: A non-numeric value encountered 
Failed imports

If I remove the line and try reimporting, everything is fine, but no lap from my file.

I joined my test file if you need it.
[20170309-113307.tcx.zip](https://github.com/Runalyze/Runalyze/files/835872/20170309-113307.tcx.zip)

**Comment by laufhannes** [comment]
And there's nothing below *Failed imports*? The warning shouldn't be enough to let the import fail although I'm not sure on that. What's your php version?

For me, the import works with adding the line and laps are there.

**Comment by kootox** [comment]
The whole stacktrace is :

File: 20170309-113307.tcx
Warning: A non-numeric value encountered 
Failed imports
20170309-113307.tcx - Warning: A non-numeric value encountered
Done

My PHP version is 7.1.2 : 

$ php --version
PHP 7.1.2 (cli) (built: Feb 14 2017 21:24:49) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

**Comment by kootox** [comment]
I applied your patch. The output is still the same : 

```
20170309-113307.tcx

Failed imports:
 - 20170309-113307.tcx: Warning: A non-numeric value encountered

Done.
```

**Comment by mipapo** [comment]
Please check if the file was still imported. The message is just a warning. So the message is not placed correct. 
The command is far away from perfect and is just a quick'n'dirty solution.

**Comment by laufhannes** [comment]
I don't know if Symfony's command execution uses some error handler that converts this `E_WARNING` into an exception, but php 7.1 is not officially supported by Runalyze so far. We run unit tests for 7.1, but there are tons of this *A non-numeric value encountered* warnings.

**Comment by kootox** [comment]
I switched back my laptop (where runalyze is running) to php 7.0.16 and I can confirm everything is working fine with your patch.

Thanks a lot.

I guess i'll wait until php 7.1 is supported to use php standard version on my distro.
