### ISSUE TITLE
Migration 20161224173160 fails - missing lock column

### ISSUE THREAD

**Issue by grzeg1** [Runalyze/Runalyze#2111]
Migrating up to 20170311194525 from 20161209173160

  ++ migrating 20161224173160

Migration 20161224173160 failed during Execution. Error [Semantical Error] line 0, col 63 near 'lock = 1': Error: Class Runalyze\Bundle\CoreBundle\Entity\Route has no field or association named lock

**Comment by grzeg1** [comment]
```
Version20161209173160.php:        $this->addSql('ALTER TABLE `'.$prefix.'route` DROP `lock`');
```

**Comment by laufhannes** [comment]
Your quote from `Version20161209173160` is in its `down()` method, the field `route.lock` is added in its `up()` method. That field should be available after that migration.

Do you migrate via cli or via web interface? Probably the cache has to be cleared in advance and that is done automatically only for the update via web interface in prod mode.

**Comment by grzeg1** [comment]
Finally somehow I managed to clear the needed part of the cache - seems there are multiple kinds of cache. I guess you could make a script/list of things to do after update.
Now the only thing that's broken is "There was a problem trying to show the map" and some stacktrace in the JS console. Any clues? No errors in logs.

**Comment by laufhannes** [comment]
I adjusted the docs a little bit. The default `cache:clear` command does not clear doctrine's cache which is responsible for the above error. It's right that that wasn't stated clearly.

Regarding *There was a problem trying to show the map*, that's thrown by [inc/core/View/Leaflet/Map.php#L142](https://github.com/Runalyze/Runalyze/blob/c327584542ace19eb9f0c54cf61ce3dd85640f7d/inc/core/View/Leaflet/Map.php#L142) if there are any errors in the generated js code of the map. So, the stacktrace and the `<script>...</script>` contents for the map are of interest in that case.

**Comment by grzeg1** [comment]
Found it. I was using OpenCycleMaps before. Now it seems without API key you can't use them. You neither can set the map to any other. Unless you delete the configured map type from database....
