### ISSUE TITLE
Use notifications instead of mails after queued task has been finished

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#2117]
- [x] Poster generation
   - [ ] + catch output of poster commands and log errors
 - [x] Backup creation

*Follow-up for #472.*

**Comment by mipapo** [comment]
+
- [ ] Create a notification after registration "Starting guide at @ https://help.runalyze.com/latest/starting-guide/getting-started.html

**Comment by mipapo** [comment]
- [ ] Add a notificatoin after registration which directs you to body values -> enter HR rest/max

**Comment by mipapo** [comment]
Tasks added to new issue #2147
