### ISSUE TITLE
login error after 3.2 upgrade

### ISSUE THREAD

**Issue by Vebryn** [Runalyze/Runalyze#2122]
Hello,

First of all, great tool! I'm using Runalyze 2.6 since 2016.

I upgrade to 3.2 with https://docs.runalyze.com/en/latest/upgrade/3.x.html#upgrade-from-2-6-to-3-0. Everything went fine, except when I try to login, I'm face an error "Authentication request could not be processed due to a system problem.".

- config.yml is configured according old config.php
- error.log & access.log don't show any relevant informations
- var/logs directory is empty

I read documentation more in depth. https://docs.runalyze.com/en/latest/installation/3.x.html#ubuntu-debian-distributions specifies that I have to install following packages : php-gettext php-zip php-curl php-xml php-mbstring libxml2 gettext php-intl perl. I only found some of these like php-gettext, php-pclzip, php5-curl, php5-intl and libxml2. I run Debian Jessie.

Best regards.

**Comment by mipapo** [comment]
The info is too generic as that we can debug it. Sorry. Try to clear the cache (var/cache/*)

**Comment by Vebryn** [comment]
Forgive me, I tried to upgrade from 2.6 to 3.2. Upgrade from 2.6 to 3.0 first solved my issue.
