### ISSUE TITLE
Change leaflet layers

### ISSUE THREAD

**Issue by Salzi** [Runalyze/Runalyze#2129]
Hi
I just found runalyze and I really like it. I installed it on my home server and wanted to change a few things. Starting with a very simple task: Removing layers from leaflet which I don't really need. Therefore I removed the sections in lib/leaflet/runalyze.leaflet.layers.js. But when I refresh the webpage, the entries are still there. I already cleared the caches. I also searched in the docs but I didn't find anything what else I have to do.
Could someone please tell me what I have to do? Thanks!

**Comment by mipapo** [comment]
You have to run gulp to recompile the css/js files:
https://docs.runalyze.com/en/latest/checkout.html#installation-of-dependencies
