### ISSUE TITLE
Mapbox Outdoor is not visible in public activity

### ISSUE THREAD

**Issue by Salzi** [Runalyze/Runalyze#2156]
Added a mapbox api key and the outdoor map is visible within my personal account. When I share the activity the outdoor map layer is not visible on the public link.

**Comment by laufhannes** [comment]
Our new templates do not correctly set js options in https://github.com/Runalyze/Runalyze/blob/master/app/Resources/views/shared/base.html.twig#L32 (and the same applies for all `base.html.twig`). The correct js code is created in https://github.com/Runalyze/Runalyze/blob/master/inc/html/class.Ajax.php#L77-L94 (but that class is deprecated and shouldn't be used).

We need some `views/js_footer.html.twig` that handles that stuff and can be included in base templates.
