### ISSUE TITLE
Temperature plot for activity does not respect user's temperature unit

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#2160]
via https://forum.runalyze.com/viewtopic.php?f=47&t=742&p=3223#p3223

**Comment by mipapo** [comment]
@laufhannes is there a test file with temperature? I don't own any

**Comment by laufhannes** [comment]
@mipapo `ctrl + F` within `ImporterFiletypeFITTest.php` shows multiple files that should contain temperature data, e.g. the files coming from a Fenix2 or Fenix3 and from o-Synce.
