### ISSUE TITLE
Single user installation fails when running 'doctrine:migrations:migrate'

### ISSUE THREAD

**Issue by mtressl** [Runalyze/Runalyze#2173]
copy/paste from my command line:

```
Migrating up to 20170424090001 from 20170311194530

  ++ migrating 20170320194525

     -> CREATE TABLE IF NOT EXISTS `runalyze_notification` (
                          `id` INT UNSIGNED AUTO_INCREMENT NOT NULL,
                          `messageType`  tinyint unsigned NOT NULL,
                          `createdAt` INT UNSIGNED NOT NULL,
                          `expirationAt` INT UNSIGNED DEFAULT NULL,
                          `data` TINYTEXT NOT NULL,
                          `wasRead` tinyint(1) unsigned NOT NULL DEFAULT 0,
                          `account_id` INT UNSIGNED NOT NULL,
                          INDEX IDX_F99B51889B6B5FBA (account_id),
                          PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB
                        
     -> ALTER TABLE runalyze_notification ADD CONSTRAINT FK_F99B51889B6B5FBA FOREIGN KEY (account_id) REFERENCES runalyze_account (id)
Migration 20170320194525 failed during Execution. Error An exception occurred while executing 'ALTER TABLE runalyze_notification ADD CONSTRAINT FK_F99B51889B6B5FBA FOREIGN KEY (account_id) REFERENCES runalyze_account (id)':

SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint
```

Is there a possible bug in the migrate script?

**Comment by mipapo** [comment]
Your database is maybe not clean. Do you have an account with id 0?
That's not a bug

**Comment by mtressl** [comment]
There is only one account in my DB, it has id 1.
I just followed the update from 4.0 -> 4.1 instructions.
How do I clean the DB?

**Comment by laufhannes** [comment]
Please make sure that your table `runalyze_account` is an InnoDB table and its column `id` is `INT UNSIGNED NOT NULL`.

You can find the specific error with running `SHOW ENGINE INNODB STATUS;` and having a look at the `LATEST FOREIGN KEY ERROR` section.

**Comment by mtressl** [comment]
Actually, it seems there is the bug (but why)...

table runalyze_account -> MyISAM
column id -> int(10)		UNSIGNED not NULL and AUTO_INCREMENT (--> so this seems fine)

I have access via phpMyAdmin, can I just change the table through it?

**Comment by laufhannes** [comment]
We switched to InnoDB at v2.2. At that point, it was optional but nowadays it's required and we probably did not mention that clearly at any point.

Yes, you can switch to InnoDB via phpMyAdmin. You can compare your database layout with [inc/install/structure.sql](https://github.com/Runalyze/Runalyze/blob/support/4.1.x/inc/install/structure.sql)

**Comment by mtressl** [comment]
Thanks so far... one step further, but there goes the next error in the migration script:

```
  ++ migrating 20170424090000

     -> CREATE UNIQUE INDEX unique_key ON `runalyze_dataset` (`accountid`, `keyid`)
Migration 20170424090000 failed during Execution. Error An exception occurred while executing 'CREATE UNIQUE INDEX unique_key ON `runalyze_dataset` (`accountid`, `keyid`)':

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-16' for key 'unique_key'

                                                                               
  [Doctrine\DBAL\Exception\UniqueConstraintViolationException]                 
  An exception occurred while executing 'CREATE UNIQUE INDEX unique_key ON `r  
  unalyze_dataset` (`accountid`, `keyid`)':                                    
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-16  
  ' for key 'unique_key'                                                       
                                                                               

                                                                               
  [Doctrine\DBAL\Driver\PDOException]                                          
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-16  
  ' for key 'unique_key'                                                       
                                                                               

                                                                               
  [PDOException]                                                               
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1-16  
  ' for key 'unique_key'  
```

**Comment by laufhannes** [comment]
As it says, you have duplicate entries in your dataset table. The combination of accountid and keyid must be unique but you have multiple entries for (at least) keyid 16 (that's fit_recovery_time). You need to remove duplicate entries.

**Comment by mtressl** [comment]
Seems there are actually some duplicate KEYID for that table. How can I remove those entries? Trough the web application? I cannot drop lines through phpMyAdmin...

**Comment by laufhannes** [comment]
There's no way to do that via runalyze itself. Normally, phpMyAdmin offers a way to delete entries (not while editing a single entry but within the complete list of entries).

If you can't delete single entries, you can clear the whole table. Runalyze will insert all dataset keys automatically when configuring them the first time. (Of course, all current adjustments will be lost)

**Comment by mtressl** [comment]
Got the .sql from the table through phpMyAdmin, removed the 3 duplicate entries with text editor. Cleared table through phpMyAdmin, imported .sql

Done, fixed.
And migration script ran through.

Just one additional question:
-> should all tables be InnoDB tables, or are there some MyIsam left? Anywhere I can double check that?

Thanks so far for your help!

**Comment by mtressl** [comment]
And one more issue... (but I guess that's the final one):
-> all tiny icons (e.g. .vo2max-icon.fa-arrow-right.fa-rotate-45) do not show. Also worked before.

**Comment by mipapo** [comment]
@mtressl Just download the mentioned css and js files here: https://forum.runalyze.com/viewtopic.php?t=747&p=3241#p3241

**Comment by mtressl** [comment]
My prior question was not yet answered:

> Just one additional question:
> -> should all tables be InnoDB tables, or are there some MyIsam left? Anywhere I can double check that?

**Comment by mipapo** [comment]
No everything should be innodb

**Comment by mtressl** [comment]
Thanks!
