### ISSUE TITLE
[dependencies] Package builder in travis fails

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#2174]
Icons and images are missing (partly)

I have removed the package from the release

**Comment by mipapo** [comment]
I'm not sure why, but I have just downloaded the js/css files from our onlineversion and will upload the packages again as soon as I have Wifi

**Comment by mipapo** [comment]
I'm not sure, but I think we had that problem before? Any change in the component which generates the css files?

**Comment by laufhannes** [comment]
This seems to be caused by ef7d35a140bdb7c7e35b0e85754d15fee38bbcff and a newer version of `gulp-clean-css`.
