### ISSUE TITLE
Monthly stats plugin does not respect user's distance unit

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#2176]
It's labeled miles, but distance is in km (via Twitter)

**Comment by laufhannes** [comment]
The `AnalysisData` class for the monthly stats plugin uses an internal `$DefaultValue` that holds an instance of some `DisplayableValue`, depending on the chosen statistic to look at. Sadly, this object forgets any given `UnitInterface` after construction and remembers the unit string only. Thus, calling `$this->DefaultValue->setRawValue(...)` can't respect any chosen unit.

We probably need to create a new object for every `getValue()` call as it's currently done in `getDefaultValue()`. That will cost a little bit of performance but it should be correct at least.
