### ISSUE TITLE
Update references in sport table (equipmenttypeid, default_typeid)

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#2181]
We have to check main_equipmenttypeid and default_typeid as they could contain no longer existing equipment types or training types. This results in a 500er error 

So if a equipment type or training type is deleted the references have to be set to null

**Comment by laufhannes** [comment]
Could be solved with adding respective foreign key constraints, right? (Migration would need to fix 'broken' relations first)

**Comment by mipapo** [comment]
Yep
```
UPDATE runalyze_sport SET main_equipmenttypeid=NULL WHERE main_equipmenttypeid = 0;
```
Excuted some queries at runalyze.com to fix those issues. Forgot to add it to my gist. I will add them later here.

**Comment by mipapo** [comment]
`UPDATE runalyze_sport s LEFT JOIN runalyze_equipment_type t ON t.id=s.main_equipmenttypeid SET s.main_equipmenttypeid=NULL WHERE s.main_equipmenttypeid IS NOT NULL AND t.id IS NULL;`
Fixing main_equipmenttypeid before constraint

**Comment by mipapo** [comment]
Not sure about that
`ALTER TABLE runalyze_sport
ADD FOREIGN KEY (main_equipmenttypeid) REFERENCES runalyze_equipment_type (id) 
  ON DELETE SET NULL ON UPDATE CASCADE; `

`ALTER TABLE runalyze_sport
ADD FOREIGN KEY (default_typeid) REFERENCES default_typeid (id) 
  ON DELETE SET NULL ON UPDATE CASCADE; `
