### ISSUE TITLE
Inconsistent "Climb Score" in activitiy overvew and climb score view

### ISSUE THREAD

**Issue by sidddy** [Runalyze/Runalyze#2189]
When using the new "climb score" feature from master branch, I see inconsistent climb score values for the same activity: The value which is shown in the activity overview page (in the elevation block) is different from the value in the climb score view. E.g. for the examnple in attached screenshot, climb score is 5.8 in the overview and 4.9 in the climb score view. In my understanding these two values should be equal.

![image](https://user-images.githubusercontent.com/13465394/27676876-f6606c10-5caf-11e7-9b02-918fdcd0a902.png)

BTW: I love the new climb score feature!!! :-)

**Comment by laufhannes** [comment]
Yep, I observed that as well but did not have time to take a look into this. The climb score in the overlay is calculated with js, while the activity view's value is calculated in php.

Seems that the `StepwiseElevationProfileFixer` is not used in the `Inserter`, but that should only affect new activities with 'corrected' elevation data. And I guess the calculation is not updated at all when correcting elevation data.
