### ISSUE TITLE
Multiple upload/import

### ISSUE THREAD

**Issue by ddddavidee** [Runalyze/Runalyze#2190]
It would be nice to be able to import multiple files.
A batch uploader with no modification of the data

**Comment by ddddavidee** [comment]
Maybe it is possible with a script who emulate the POST and GET requests?

**Comment by laufhannes** [comment]
I don't get your problem? The import form does support multiple files. Simply select more than one file.

**Comment by ddddavidee** [comment]
yes, sorry for the noise. I've tested before opening the issue and didnt work as expected. probably a problem on my side. 
please ignore (or delete)

**Comment by laufhannes** [comment]
No problem. Better too many issue reports than too few.
