### ISSUE TITLE
Climb Score not visible on public site

### ISSUE THREAD

**Issue by Salzi** [Runalyze/Runalyze#2195]
Just updated my local installation to the newest and I really like the new climb score feature. Thanks for that! Unfortunatly I couldn't see it on my public athlete page. Is it wanted like that or is this a bug?

**Comment by mipapo** [comment]
You mean in the dataset or where?

**Comment by mipapo** [comment]
Tools are not meant to be visible on the public page for the moment. There is no real reason - It has been just like that since a long time ;)

The values are perfectly visible on the public athlete overview and in the activity details:
https://testing.runalyze.com/athlete/mipapo?start=1498867200&end=1501545599

**Comment by Salzi** [comment]
When I share an activity via public link I could see the 'Climb Score' and the 'Percentage hilly' in the table view under 'Course and elevation data' but the nice additional window from my private view 'Climb Score view' with the detailed information is not accessible.

**Comment by mipapo** [comment]
Like I said - It's not meant to be visible for the public in the moment. We will discuss if we want to open that for the public (I think it would be okay as I don't see a privacy issue there)

**Comment by Salzi** [comment]
In my opinion there is no privacy reason not to share the climb score values.

But by the way: I really appreciate your focus on privacy - which was one of the main reason why I switched to runalyze.

**Comment by laufhannes** [comment]
I agree that there's no reason to hide climb score view (while I see no use-case to make vo2max and elevation info public), probably the same for time series and best segment analysis. I'm just not sure whether overlays will work as expected.

**Comment by mipapo** [comment]
I will try it out this evening - I remember that it worked perfectly

**Comment by mipapo** [comment]
919121528dd269e0d2e63504a10386163b18f108

**Comment by Salzi** [comment]
@mipapo works when clicking on the climb score in the table. It would be nice to also have a link within the activity under 'Course and elevation data' (like in the private view).
