### ISSUE TITLE
Dataset: "Tool" needs to check if tools are available

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#2199]
Analyze splits and subsegments are failing if the activity has not the required data.
Don't know how to fix that

**Comment by laufhannes** [comment]
For splits it should be enough to add `splits` to `column()` and check that they are not empty.

For subsegments, that might be more challenging. See `AbstractEquipment` for an example that requires a join, but I'm not sure whether there's a simple way to combine a simple column (for splits) and a join.

**Comment by mipapo** [comment]
Should for splits, don't see a nice way for the other tools
