### ISSUE TITLE
IE11 compatibility - Climb score

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#2203]
Check compatibility with IE11

**Comment by Salzi** [comment]
Did a quick test and it didn't work. The loading spinner turns for ever. 

The debug console stops in climb-scrore.js at line 261 with:
`Das Objekt unterstützt die Eigenschaft oder Methode "log2" nicht`

The console shows the output:
`SCRIPT438: Das Objekt unterstützt die Eigenschaft oder Methode "log2" nicht
Datei: scripts.min.js, Zeile: 24, Spalte: 8713`

Hope that helps

**Comment by laufhannes** [comment]
Really, IE? Every other browser supports `Math.log2(...)` (see [https://developer.mozilla.org/](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Math/log2#Browser_compatibility)).

We can use the following polyfill:
```js
Math.log2 = Math.log2 || function(x) {
  return Math.log(x) * Math.LOG2E;
};
```
