### ISSUE TITLE
Fat, Water and Muscle not valid if written with comma

### ISSUE THREAD

**Issue by vendetta1987** [Runalyze/Runalyze#2204]
For some time now i'm getting error messages about incorrectly entered values when putting in new data to the  body table. While the the weight field supports my habit of entering comma separated decimal values, the fat, water and muscle fields don't. Both Firefox (55 and before) as well as Edge (up to build 16251) behave the same here and will accept the form only if i change the comma to a dot.

![grafik](https://user-images.githubusercontent.com/1315601/28935061-7f57be12-7883-11e7-9417-c94628f42f15.png)

**Comment by mipapo** [comment]
In the moment we just support the "." version. But we will look into it. Maybe in the next version.
