### ISSUE TITLE
JSON import: potential conflicts because of duplicate internal sport types

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#2214]
`internal_id` must be unique, but our json importer doesn't catch that so far. This may corrupt the complete json import.

**Comment by mipapo** [comment]
So we just need a mapping for the internal_id - If a sport with an internal_id exists use that one?

**Comment by laufhannes** [comment]
Yes, sounds like a valid solution. So far, sports are only mapped by their name.
