### ISSUE TITLE
Title should be recognized in RSS feed

### ISSUE THREAD

**Issue by rretsiem** [Runalyze/Runalyze#2232]
If I enter a title in a workout, the RSS feed should represent this title instead of the normal "date - sport - distance"

Maybe configurable with some templates in configuration, so that distance and sport can be placed as well in the title.

**Comment by mipapo** [comment]
I don't want any additional RSS feed settings for the user. 
Using the title instead "date - sport - distance" would be ok

**Comment by laufhannes** [comment]
* The date is obvious by the feed item's date, isn't it?
 * Distance: Not all activities need to have a distance. This needs a fallback to duration.
 * If selected, sport type should be shown as well.

My suggestion (sport type and title only if available):
```
Sport (sport type): distance or duration, title
```

If required the date can be put at the beginning.
