### ISSUE TITLE
Useragent: Mobile - Adding tags not possible

### ISSUE THREAD

**Issue by Uatschitchun** [Runalyze/Runalyze#2240]
When using a mobile layout (handy) it isn't possible to add tags as it isn't recognized as textfield and no keyboard comes up. Choosing from existing tags is possible but not adding. 
It works well in desktop layout (tablet).

**Comment by Uatschitchun** [comment]
user agent, not layout

**Comment by mipapo** [comment]
Runalyze has no real mobile layout so it doesn't make sense to create a new issue for every problem
And we will not work on these problems on the moment. Please use your pc

Added to #2243
