### ISSUE TITLE
databrowser doesn't reload after changing dataset

### ISSUE THREAD

**Issue by Uatschitchun** [Runalyze/Runalyze#2241]
When changing the dataset for calendar, the changes only take effect after reloading the page or dataset.

Would be convenient to have a reload triggered when settings page is closed

**Comment by mipapo** [comment]
Worked in the past  - isn't triggered anymore

**Comment by laufhannes** [comment]
Some
```php
$this->get('app.automatic_reload_flag_setter')->set(AutomaticReloadFlagSetter::FLAG_DATA_BROWSER);
```

in `SettingsController::datasetPostAction` should be enough: https://github.com/Runalyze/Runalyze/blob/f7ab09a86f0cb3d2aedc1614f50545e2fca6ccdf/src/CoreBundle/Controller/Settings/SettingsController.php#L161-L169
