### ISSUE TITLE
Useragent: Mobile - Multieditor covers track edit

### ISSUE THREAD

**Issue by Uatschitchun** [Runalyze/Runalyze#2242]
With useragent: mobile, the multieditor's window overlays the track editor make it impossible to edit track.

![screenshot_20171110-193218](https://user-images.githubusercontent.com/25088926/32673162-4de53968-c64e-11e7-9aaf-4d160d3b7701.png)

**Comment by mipapo** [comment]
Runalyze has no real mobile layout so it doesn't make sense to create a new issue for every problem
And we will not work on these problems on the moment. Please use your pc

Added to #2243
