### ISSUE TITLE
Manual times placeholder tooltip error

### ISSUE THREAD

**Issue by ftorto** [Runalyze/Runalyze#2249]
When accessing `More details about your laps` panel, the `manual times` placeholder is `e.g. 30:00, 1:00:00 or +15', 30', 15'`
but the second example doesn't work.

Each value is **absolute**, not **relative** to the previous one (but should be).

I have to provide `+15', 30', +45` if I want the expected behaviour.

**Comment by laufhannes** [comment]
I can't confirm that issue. My example activity has a total time of 44 minutes, so I use `+5', 10', 5'` as input and that works as expected:
 - 1. lap of 5:00, total duration 5:00
 - 2. lap of 10:00, total duration 15:00
 - 3. lap of 5:00, total duration 20:00
 - 4. lap of remaining time (24:18, total duration 44:18)

**Comment by ftorto** [comment]
KO screen
![ko](https://user-images.githubusercontent.com/14920494/33685059-aa051d08-dad0-11e7-8c8e-8f9d10730ae2.png)

OK screen
![ok](https://user-images.githubusercontent.com/14920494/33685058-a9ec2370-dad0-11e7-8afc-4d066a1ed185.png)

After some new checks, if I begin with a "+" interval, It works correctly.

**Comment by laufhannes** [comment]
Yep, that's what the placeholder tries to tell: the first char must be a `+`. If that's the case, all distances or times will be treated as additive.

**Comment by ftorto** [comment]
Oh! Sorry for time wasting. 
I understood it was a sign to indicate a kind of working/rest interval, 
Shame on me...

**Comment by Uatschitchun** [comment]
The role of the '+' could be documented/explained a little better

**Comment by ftorto** [comment]
> List with all times, comma seperated. Put "+" at the beginning to treat times as intervals.

could be improved to :

> List with all absolute times, comma seperated. Put "+" at the beginning to consider times as relative to previous one.

but a boolean flag (checkbox) in front of the textbox should be better for understanding
