### ISSUE TITLE
SRTM not working

### ISSUE THREAD

**Issue by uk3** [Runalyze/Runalyze#2258]
Hallo,

wenn ich versuche die Höhendaten mit lokalen files zu korrigieren, dann bekomme ich im letzten git ein "Es konnten keine Höhendaten empfangen werden."

in der Version 4.2.0 funktioniert das allerdings. Nachdem ich jetzt nicht die commits schritt für schritt durchgehen wollte - vielleicht habt ihr ja eine Idee?

lG Ulrich

**Comment by laufhannes** [comment]
Das Einzige, was mir dazu auf die Schnelle einfällt, ist #2222 mit dem dazugehörigen Commit 0a8bb25695f58117d9223673dbe940ad2ba9ca85. Es gibt jetzt die Möglichkeit das Data-Verzeichnis an einen anderen Ort zu legen. In der `app/config/export_config.yml` ist aber das bisherige Verzeichnis als Default hinterlegt.

Die deutlich größeren Änderungen kommen erst mit #2257. Wobei auch in dem Fall sich "eigentlich" nichts im Vorgehen geändert haben sollte.

Zum Überprüfen, ob bisher tatsächlich die SRTM-Daten (und nicht eine der anderen APIs genutzt wurde): Steht in `runalyze_route.elevations_source` jeweils `GeoTIFF`?

Und hast du in deiner Umgebung die Möglichkeit, die UnitTests laufen zu lassen? Es genügt in diesem Fall [GeoTIFFTest.php](https://github.com/Runalyze/Runalyze/blob/master/tests/inc/core/Service/ElevationCorrection/Strategy/GeoTIFFTest.php), benötigt z.B. `data/srtm/srtm_38_03.tif`:
```
./vendor/bin/phpunit --bootstrap tests/bootstrap.php -c tests/config.xml --group dependsOnSRTM
```

**Comment by uk3** [comment]
Hallo,

es hat offenbar wirklich mit 0a8bb25 zu tun. es dürfte (in meinem Setup) %kernel.root_dir% nicht stimmen. wenn ich nämlich data_directory händisch auf den absoluten (und richtigen) Pfad setze, funktioniert alles wie es soll.

Gibts eine stelle, an der ich sehe, was als %kernel.root_dir% verwendet wird?

lG Ulrich.

**Comment by mipapo** [comment]
src/CoreBundle/Controller/DefaultController.php
```
     */
    public function dashboardAction(Request $request, Account $account)
    {
        echo $this->getParameter('kernel.root_dir');
        echo $this->getParameter('data_directory');
```
Kernel.root_dir würde ich an deiner Stelle nie ändern - das wird nicht unterstützt.
Ich bekomme die SRTM Daten aber auch nicht ans Laufen.

**Comment by uk3** [comment]
Mein Workaround, mit dem es funktioniert war
`    data_directory: /home/user08/uk/html/runalyze/data
`
ins `data/config.yml`

**Comment by laufhannes** [comment]
`kernel.root_dir` wird von Symfony via [app/AppKernel.php#L74](https://github.com/Runalyze/Runalyze/blob/master/app/AppKernel.php#L74) gesetzt und sollte auf `./app` zeigen.

In meinem Fall:
```
kernel.root_dir: "[...]/runalyze/app"
data_directory: "[...]/runalyze/app/../data"
```

Der GeoTIFF-Reader schaut dann in `%data_directory%/srtm`.

Auf was hat das Data-Verzeichnis bei dir denn fälschlich gezeigt? Activity-Uploads etc. landen ja auch dort.

**Comment by uk3** [comment]
Das komische ist, dass in der dashboardAction die werte richtig sind. dort steht das korrekte data_directory drinnen.

**Comment by uk3** [comment]
Hallo,
Das Problem liegt genau an dieser Änderung: https://github.com/Runalyze/Runalyze/commit/0a8bb25695f58117d9223673dbe940ad2ba9ca85#diff-a9baa872e7f689ae9c75abd00e267b57

Die rückgängig machen und es geht (warum hab ich aber nicht verstanden).

**Comment by mipapo** [comment]
Ist ja leider nur nicht die Lösung ;)

**Comment by uk3** [comment]
Klar,
Aber vielleicht hilft es, das Problem einzugrenzen. Wo die Variable dort
gesetzt wird, hab ich nämlich nicht durchschaut ;-)

LG Ulrich

-- 
Ulrich Kiermayr
ulrich@kiermayr.at

**Comment by laufhannes** [comment]
Das Problem dürfte im Parser-Branch nicht bestehen und damit durch #2257 behoben werden.

In [class.Frontend.php#L117](https://github.com/Runalyze/Runalyze/blob/master/inc/class.Frontend.php#L117) wird `%kernel.root_dir%` nicht korrekt aufgelöst. Im Parser-Branch wird aber ohnehin der Parameter innerhalb der Symfony-Welt verwendet und nicht unser `DATA_DIRECTORY`. Trotzdem ist auch dort die Umwandlung korrekt in [class.Frontend.php#L117](https://github.com/Runalyze/Runalyze/blob/refactor/parser/inc/class.Frontend.php#L117).

Du könntest es bei dir also vermutlich auch lösen, indem du dort folgendes nutzt:
```php
define('DATA_DIRECTORY', str_replace('%kernel.root_dir%', FRONTEND_PATH.'/../app', $this->yamlConfig['data_directory']));
```

**Comment by uk3** [comment]
Der einfachste workaround für mich ist der Eintrag im config.yml.
Ich warte Mal auf den fix im master und schau es mir dann wieder an.
Danke und LG Ulrich

**Comment by uk3** [comment]
Hallo,

das Problem ist mit #2257 behoben. Aber jetzt passiert was anderes:
Wenn ich bei der Korrektur auf 'via srtm' klicke, kommt 'Die Höhendaten wurden korrigiert. (RouteAdapter)"
wenn ich auf 'via geonames' klicke, kommt 'Die Höhendaten wurden korrigiert. (GeoTiff)'
und bei maps.google.com kommt 'Es konnten keine Höhendaten empfangen werden.'

Irgendwas scheint da durcheinander zu sein.

**Comment by laufhannes** [comment]
Danke!

GoogleMaps werden wir vermutlich bald von den möglichen Anbietern dort entfernen. Ohne API-Key liefert der Service in der Regel keine Daten mehr und die Verwendung der Höhendaten ist eigtl. auf die direkte Anzeige neben der Karte beschränkt, was bei uns nicht zwangsläufig eingehalten wird.

Immerhin sollte jetzt jeweils in `var/logs/external_services.log` die entsprechende Fehlermeldung stehen:
```
external_services.WARNING: GoogleMaps request failed: You have exceeded your daily request quota for this API. ...
```

**Comment by uk3** [comment]
Hallo,
Irgendwas ist noch immer nicht ganz sauber: bei einer activity, die mittels GeoTIFF korrigiert wurde sagt er auch nach einer Korrektur mittels geonames weiterhin dass mit GeoTiff korrigiert wurde (solange die entsprechenden srtm vorhanden sind - nur wenn die fehlen, dann korrigiert er anscheinend wirklich via geonames).
Ist zwar eher kosmetisch, aber der vollständigkeit halber.
lG Ulrich.

**Comment by laufhannes** [comment]
Hm, das Problem kann ich nicht nachstellen. Ich gehe folgendermaßen vor:

1. Aktivität wird angelegt und übernimmt (barometrische) Höhendaten aus der Datei
2. Bei _Mehr über die Höhenmeter_ wähle ich _» Jetzt korrigieren_
    * Dadurch wird automatisch die GeoTIFF-Korrektur ausgewählt:
    * _Die Höhendaten wurden korrigiert. (GeoTIFF)_
3. Wenn ich nun _» erneut korrigieren via geonames.org_ auswähle, erscheint im Anschluss
    * _Die Höhendaten wurden korrigiert. (Geonames)_

**Comment by uk3** [comment]
Hallo,
wenn ich in der konfig die Automatische Höhenkorrektur im Eingabeformular ausschalte funktioniert es wie du beschrieben hast.
Wenn die automatische höhenkorrektur beim Upload eingeschaltet ist, verhält es sich so komisch....

**Comment by uk3** [comment]
Hallo,
Jetzt funktioniert es wie es soll 👍
lG Ulrich
