### ISSUE TITLE
Get CURRENT activity VO2Max-estimate from Garmin .fit file

### ISSUE THREAD

**Issue by MJDevel** [Runalyze/Runalyze#2264]
In contrast to https://github.com/Runalyze/Runalyze/issues/1725 which pulls in "VO2max estimates before the respective activity" I've found the CURRENT value. Felt proper to open a new issue...

There is a long story behind this find of the VO2Max-estimate at activity END on a Garmin Fenix 5X, but I will just jot down the salient points:

A .csv view in Garmin/Metrics/7CPE5132.fit from a "Run" activity ended Mon 25 dec 2017 13:52:39 CET according to the Garmin timestamp 883140759 (do not know why the filename decodes to 14:51:32 of the same day; 7 is 2017, C is 12 for December, P is the 25th, E is the hour 14 while 5132 are the minutes and seconds)

[...]
Data,5,unknown,unknown,"883140759",,unknown,"865718",,unknown,"460",,unknown,"20",,unknown,"0",,unknown,"1",,unknown,"0",,unknown,"5",,unknown,"0",,,,,
Data,4,unknown,unknown,"883140762",,unknown,"331",,unknown,"220",,unknown,"503",,unknown,"607",,unknown,"1",,unknown,"0",,unknown,"4",,unknown,"2",,unknown,"3",,

The value 331 after the timestamp on the last line is the "Training Load Last 7 Days" number. On the previous line, after timestamp, 460 is the rounded VO2Max-estimate 46 at activity end. The preceding value 865718 is an obfuscated version of the full estimate:

865718 / 64 = 13526,84375 = 13526 * 3,5 = 47341 / 1024 = 46,2314453125

I chose this activity date to illustrate that they cut any fraction when computing the obfuscated METMax number 13526 which - as we well know - they place at the beginning of the _next_ activity .fit file:

A .csv peek in Garmin/Activity/2017-12-27-12-04-11.fit

[...]
Data,9,unknown,unknown,"883307051",,unknown,"13526",, [...]
Data,10,sport,name,"Run",, [...]

The find would have meant very little if the latest VO2Max-estimate had been isolated to the files in the Garmin/Metrics directory, but luckily Garmin print it out in a blob at the end of the current activity .fit file:

A .csv snippet from Garmin/Activity/2017-12-25-12-18-31.fit (filename is when the "Run" activity began; excessive trailing commas deleted)

[...]
Data,2,event,timestamp,"883140759",s,data,"1338",,event,"38",,event_type,"3",,
Data,2,event,timestamp,"883140759",s,data,"219",,event,"48",,event_type,"3",,event_group,"1",,
Data,8,unknown,unknown,"883140759",,unknown,"7657071",,unknown,"7670885",,unknown,"686814",,unknown,"70079660",,unknown,"865718",,unknown,"0",,unknown,"1338",,unknown,"48232",,unknown,"0",,unknown,"0",,unknown,"0",,unknown,"151",,unknown,"0",,unknown,"33",,unknown,"24",,unknown,"1",,unknown,"0",,unknown,"0",,unknown,"-2",,unknown,"0",,unknown,"0",,unknown,"0",,unknown,"8",,unknown,"0",,

Event 38 is the old established Recovery (Advisor) time in minutes. Event 48 I believe to be a dummy such - it always is 219 which I've seen used as a dummy value elsewhere. Our ending 'VO2Max' 865718 is the fifth value after the timestamp - at least in files written by main watch firmwares 4.10 to 7.10 (bought the Fenix 5X in July 2017).

Judging by a publicly posted Forerunner 935 activity .fit file, the same 'VO2Max' structure is present there as well.

When it comes to my older watch, the Forerunner 630, there is a slight alteration in the computation to line up the plain-text METMax, as seen both at the beginning of the activity .fit file (START 'VO2Max') and in GARMIN/SETTINGS/SETTINGS.FIT (where the END value is saved), with the fifth value in the blob - written just _above_ the event 38 line. Here are views from two activity files and saved off and renamed SETTINGS files:

2017-10-27_07-16-39_7AR71639.csv
[...]
Data,7,user_profile, [...] unknown,"12.519196",, [...]
[...]
Data,6,unknown,unknown,"878022219",,unknown,"3571985",,unknown,"5352190",,unknown,"642839",,unknown,"69372475",,unknown,"826362",,unknown,"1280",,unknown,"4097",,unknown,"0",,unknown,"0",,unknown,"0",,unknown,"145",,unknown,"0",,unknown,"32",,unknown,"23",,unknown,"1",,unknown,"0",,unknown,"0",,unknown,"0",,unknown,"100",,unknown,"0",,
Data,2,event,timestamp,"878022219",s,data,"1280",,event,"38",,event_type,"3",,

2017-10-27_07-16-39_7AR71639-SETTINGS.csv
[...]
Data,3,user_profile, [...] unknown,"12.609283",, [...]

Converting the fifth value in the blob to VO2Max we do this:

826362 / 64 = 12911,90625 / 1024 = 12,6092834473 * 3,5 = 44,1324920654

Nicely aligned with the METMax! Here is the following activity to demonstrate the validity:

2017-10-30_09-57-48_7AU95748.csv
[...]
Data,7,user_profile, [...] unknown,"12.609283",, [...]
[...]
Data,5,unknown,unknown,"878294629",,unknown,"1243608",,unknown,"4727072",,unknown,"572114",,unknown,"63313130",,unknown,"832001",,unknown,"1164",,unknown,"4097",,unknown,"0",,unknown,"0",,unknown,"0",,unknown,"136",,unknown,"0",,unknown,"30",,unknown,"19",,unknown,"1",,unknown,"0",,unknown,"0",,unknown,"0",,unknown,"88",,unknown,"0",,
Data,2,event,timestamp,"878294629",s,data,"1164",,event,"38",,event_type,"3",,

2017-10-30_09-57-48_7AU95748-SETTINGS.csv
[...]
Data,3,user_profile, [...] unknown,"12.695328",, [...]

Computing VO2Max:

832001 / 64 = 13000,015625 / 1024 = 12,6953277588 * 3,5 = 44,4336471558

It would be more 'scientifically' correct, in my opinion, to skip the obfuscation/truncation operation they do with the Fenix 5 family (and Fenix 3?), and use the fifth blob value as in the FR630. My Fenix 5X example would then be:

865718 / 64 = 13526,84375 / 1024 = 13,2098083496 * 3,5 = 46,2343292236
Instead of:
865718 / 64 = 13526,84375 = 13526 * 3,5 = 47341 / 1024 = 46,2314453125

Not much different, but... you know... :-)

**Comment by MJDevel** [comment]
Forgot to mention that my FR630 runs an ancient Firmware (v4.70) so the .fit file structure could be aligned differently than what I show above - eg where the 'event' is written in relation to the blob.

**Comment by MJDevel** [comment]
I no longer retain a Forerunner 620 watch (first Garmin to compute VO2Max estimates), but have kept the .fit activity files on disk. And although that device never showed or made any known use of VO2Max fractions, the fifth blob value is present - almost wrote 'element' there ;-)

Since often being injured during that early time of my running 'career', I had to go way back amongst the files in order to find a steady phase where three consecutive runs triggered a, presumed rounded, 1 mL rise or dip with return; thus constituting a sort of proof of the blob value's fractional VO2Max nature even with the FR620.

Here's the .csv versions (superfluous commas deleted) with my conversions added. Event 37 is the Garmin VO2Max rounded computations, showing 42, 43 and 42:

2014-04-09_18-29-47_449I2947.csv
[...]
Data,12,unknown,unknown,"765997547",,unknown,"8997707",,unknown,"8997707",,unknown,"775896",,unknown,"28006195",,unknown,"782495",,unknown,"1396",,unknown,"340",,unknown,"153",,unknown,"0",,unknown,"34",,unknown,"7",,
Data,2,event,timestamp,"765997547",s,data,"1396",,event,"38",,event_type,"3",,
Data,2,event,timestamp,"765997547",s,data,"42",,event,"37",,event_type,"3",,

[ 782495 / 64 = 12226,484375 / 1024 = 11,9399261475 * 3,5 = 41,7897415161 = 42 ]

2014-04-11_07-18-58_44B71858.csv
[...]
Data,12,unknown,unknown,"766130338",,unknown,"10545500",,unknown,"10545500",,unknown,"803321",,unknown,"31895875",,unknown,"796256",,unknown,"1728",,unknown,"340",,unknown,"157",,unknown,"0",,unknown,"37",,unknown,"22",,
Data,2,event,timestamp,"766130338",s,data,"1728",,event,"38",,event_type,"3",,
Data,2,event,timestamp,"766130338",s,data,"43",,event,"37",,event_type,"3",,

[ 796256 / 64 = 12441,5 / 1024 = 12,1499023438 * 3,5 = 42,5246582031 = 43 ]

2014-04-14_09-08-37_44E90837.csv
[...]
Data,12,unknown,unknown,"766397017",,unknown,"17126891",,unknown,"17146771",,unknown,"742205",,unknown,"47199475",,unknown,"791126",,unknown,"3332",,unknown,"340",,unknown,"154",,unknown,"0",,unknown,"46",,unknown,"23",,
Data,2,event,timestamp,"766397017",s,data,"3332",,event,"38",,event_type,"3",,
Data,2,event,timestamp,"766397017",s,data,"42",,event,"37",,event_type,"3",,

[ 791126 / 64 = 12361,34375 / 1024 = 12,0716247559 * 3,5 = 42,2506866455 = 42 ]

I would hazard a guess that all the other later VO2Max-devices (FR920XT, FR735XT etc) write this full fractional estimate in the same way.

**Comment by laufhannes** [comment]
Thanks for your work on this! Values look fine.
