### ISSUE TITLE
config.yml - python3_path not used.

### ISSUE THREAD

**Issue by uk3** [Runalyze/Runalyze#2265]
Hallo,

Ich hab ein bisserl gebraucht, um rauszufinden, warum der Postergenerator nicht funktioniert bei mir. Anscheinend wird python3_path aus der config.yml nicht benutzt/respektiert. Es wird trotzdem /usr/bin/python3 versucht aufzurufen. Nachdem python3 bei mir aber woanders ist, ist der Postergenerator fehlgeschlagen. 

(zur gegenprobe: es in src/CoreBundle/Component/Tool/Poster/GeneratePoster.php manuell setzen:  ```$this->Python3Path = '/home/uk/fileserver/bin/python3'; //$python3Path;``` hat das Problem erstmal beseitigt.)

Nachdem ich mir nicht sicher bin, wo $python3Path her kommt, konnte ich es nicht auf die schnelle selber fixen.
lG Ulrich.

**Comment by mipapo** [comment]
Please try to use - not only in the issue title - english

**Comment by uk3** [comment]
n.p., will remember for the next issue.

**Comment by mipapo** [comment]
Just to be sure: So you changed the python3_path in data/config.yml  - deleted the cache under var/cache and restarted the queue?

**Comment by mipapo** [comment]
Because I get the correct path when I echo "        echo $python3Path;" in the class GeneratePoster

**Comment by uk3** [comment]
Hello,
2 things here:
Appearently a ```bin/console cache:clear --env=prod``` was not fully sufficient to clear that part of the cache. ```rm -rf``` helped here.
But this also removed var/poster and so broke the poster generator again - it seems that var/poster is not regenerated if it is missig (?)
Strange anyway ...
Cheers, Ulrich.

**Comment by laufhannes** [comment]
For clearing the cache I always use `rm -rf var/cache/*` (or e.g. `rm -rf var/cache/doctrine/*` to only refresh doctrine meta classes). Symfony's `cache:clear` has some troubles for me as well.

**Comment by mipapo** [comment]
So I would say - Everything is alright?

**Comment by uk3** [comment]
Yes, working now
