### ISSUE TITLE
default_privacy missing from inc/install/structure.sql

### ISSUE THREAD

**Issue by uk3** [Runalyze/Runalyze#2266]
Hello,

it seems that there are some of the recent updates to the database are missing from the structure.sql (therefore a clean install from git fails at the moment).

This is the case at least for the migration Version20171217215800

cheers, Ulrich.

**Comment by mipapo** [comment]
That's correct...you could make a PR

**Comment by uk3** [comment]
PR?

**Comment by mipapo** [comment]
Pull Request
