### ISSUE TITLE
Uncaught PHP Exception because null passed as arg to DuplicateFinder::checkForDuplicates()

### ISSUE THREAD

**Issue by Strubbl** [Runalyze/Runalyze#2283]
I just checked my logs and found this error:

```
Jan 21 13:20:01 server [16717]: request.CRITICAL: 
  Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: 
  "Type error: Argument 1 passed to Runalyze\Activity\DuplicateFinder::checkForDuplicates()
  must be of the type array, null given, called in 
  /var/www/runalyze/inc/import/class.MultiImporterFormular.php on line 77" 
  at /var/www/runalyze/inc/core/Activity/DuplicateFinder.php line 64 
  {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): 
  Type error: Argument 1 passed to Runalyze\\Activity\\DuplicateFinder::checkForDuplicates() 
  must be of the type array, null given, called in 
  /var/www/runalyze/inc/import/class.MultiImporterFormular.php on line 77 
  at /var/www/runalyze/inc/core/Activity/DuplicateFinder.php:64)"} []
```
I added some newlines for readability. **Maybe this error should be taken care of?**

(original log line was:

`Jan 21 13:20:01 server [16717]: request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Type error: Argument 1 passed to Runalyze\Activity\DuplicateFinder::checkForDuplicates() must be of the type array, null given, called in /var/www/runalyze/inc/import/class.MultiImporterFormular.php on line 77" at /var/www/runalyze/inc/core/Activity/DuplicateFinder.php line 64 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 1 passed to Runalyze\\Activity\\DuplicateFinder::checkForDuplicates() must be of the type array, null given, called in /var/www/runalyze/inc/import/class.MultiImporterFormular.php on line 77 at /var/www/runalyze/inc/core/Activity/DuplicateFinder.php:64)"} []`
)

**Comment by laufhannes** [comment]
As there's no `class. MultiImporterFormular.php` in current master, you're installation is probably not up to date? ;)

**Comment by Strubbl** [comment]
Oh, you are right. Thanks for the hint!

**Comment by Strubbl** [comment]
Just for the record: This issue is seen with RUNALYZE 4.2.0, which is the version i am currently running. 

But there have been nearly 40 commits to master since then https://github.com/Runalyze/Runalyze/compare/v4.2.0...support/4.2.x So with the next release the issue shouldn't be seen anymore.
