### ISSUE TITLE
Consider accepting donations on Liberapay.com

### ISSUE THREAD

**Issue by craftyguy** [Runalyze/Runalyze#2289]
Hi! I would very much like to support runalyze, but I (like several others I know) do not necessarily want to use/trust paypal. Have you considered using a more libre/FOSS-friendly service like [Liberapay](https://liberapay.com/about/) to also accept donations?

**Comment by mipapo** [comment]
Sorry, we will not support this

**Comment by craftyguy** [comment]
That's too bad for a project like this that is looking for financial support.
