### ISSUE TITLE
Can't build current Master

### ISSUE THREAD

**Issue by Salzi** [Runalyze/Runalyze#2291]
Hi
I tried to checkout and build the current master. I followed the instructions in the docs (https://docs.runalyze.com/en/latest/checkout.html)
But when I start `gulp` I got the following error:

> [18:55:22] Using gulpfile /tmp/Runalyze/gulpfile.js
> [18:55:22] Starting 'default'...
> [18:55:22] Starting 'translate'...
> [18:55:22] Starting 'clean'...
> [18:55:22] Finished 'clean' after 19 ms
> [18:55:22] Starting 'styles'...
> [18:55:22] Starting 'stylesInstaller'...
> [18:55:22] Starting 'scripts'...
> [18:55:22] 'scripts' errored after 44 ms
> [18:55:22] Error: File not found with singular glob: /tmp/Runalyze/node_modules/d3-scale-chromatic/build/d3-scale-chromatic.min.js (if this was purposeful, use `allowEmpty` option)
>     at Glob.<anonymous> (/tmp/Runalyze/node_modules/glob-stream/readable.js:84:17)
>     at Object.onceWrapper (events.js:255:19)
>     at Glob.emit (events.js:160:13)
>     at Glob._finish (/tmp/Runalyze/node_modules/glob/glob.js:197:8)
>     at done (/tmp/Runalyze/node_modules/glob/glob.js:182:14)
>     at Glob._processSimple2 (/tmp/Runalyze/node_modules/glob/glob.js:688:12)
>     at /tmp/Runalyze/node_modules/glob/glob.js:676:10
>     at Glob._stat2 (/tmp/Runalyze/node_modules/glob/glob.js:772:12)
>     at lstatcb_ (/tmp/Runalyze/node_modules/glob/glob.js:764:12)
>     at RES (/tmp/Runalyze/node_modules/inflight/inflight.js:31:16)
> [18:55:22] 'default' errored after 67 ms
> [18:55:22] The following tasks did not complete: translate, styles, stylesInstaller
> [18:55:22] Did you forget to signal async completion?

What did I wrong?

**Comment by mipapo** [comment]
try a "Bower install"

**Comment by Salzi** [comment]
`bower install` exit without output but still not working

(Didn't have bower before just installed it)

**Comment by mipapo** [comment]
Try "npm install" then "bower install" or the other way round

**Comment by Salzi** [comment]
same result ...

**Comment by mipapo** [comment]
no idea - everything works fine for me

**Comment by laufhannes** [comment]
I guess they did a backwards incompatible change at d3-scale-chromatic. Can you check `./node_modules/d3-scale-chromatic/` for the correct path of that file (I guess `./node_modules/d3-scale-chromatic/dist/d3-scale-chromatic.min.js`) and adjust https://github.com/Runalyze/Runalyze/blob/master/resources.json#L77?

**Comment by Salzi** [comment]
@laufhannes Thank you. Had to change build to dist and now it's working!
