### ISSUE TITLE
Strecken als Dropdown

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#263]
**Reported by sebastianf on 12 Dec 42057088 09:46 UTC**
Ich muss immer nach schaun wie ich die Strecke genannt hab, wenn ich sie ein zweites mal Laufe. schner wre hier ein Dropdown mit bereits verwendeten Strecken.

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/263

**Comment by laufhannes** [comment]
Duplicate of #358.
