### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#268]
**Reported by laufhannes on 3 Nov 42066639 14:40 UTC**
von @SoSoLahLah:
"Ich wnsche mir etwas mehr Dokumentation, um den vollen Nutzen aus dem Runalyze ziehen zu knnen."

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/268

**Comment by laufhannes** [comment]
Docs now have their own repositories.
