### ISSUE TITLE
Calculations: visualize paces

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#273]
Als zustzliches Tool?

In einer kleinen Grafik, wie eine Zeitleiste, von grn bis rot die verschiedenen Tempi darstellen

**Comment by mipapo** [comment]
@laufhannes Do you know what was the idea? Don't get it from the description. What kind of plot?
Paces from all e.g. running activities?

**Comment by laufhannes** [comment]
I know it, but it's not worth it.

(Not from any activity, only for suggested paces by Jack Daniels; showing them somehow like zones in an empty plot)
