### ISSUE TITLE
Nach Installation: Tour - "Runalyze kennen lernen"

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#282]
**Reported by laufhannes on 25 Dec 42079905 09:46 UTC**
Zum Kennenlernen nach der Installation:

Konfiguration:
- wichtige Einstellungen (Geschlecht/PLZ/...)
- Sportarten
- Trainingstypen
- Kleidung
- Plugins (a la "Was ist alles mglich ...")

Erstellen:
- Schuhe
- Sportlerdaten

Importieren:
- Trainings

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/282

**Comment by laufhannes** [comment]
Duplicate of #1091.
