### ISSUE TITLE
Graphic editor

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#288]
**Reported by laufhannes on 21 Jul 42082152 09:20 UTC**
Groes Overlay fr:
- Zoom
- Achsen einstellen
- etc.
- Link zur speicherbaren Grafik (mit Grenangaben?), siehe #189

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/288

**Comment by laufhannes** [comment]
Closed as 'wontfix' as long as we don't even know which plotting library to use.
