### ISSUE TITLE
Panel: motivational quotes

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#29]
**Reported by laufhannes on 26 Jul 41018029 13:46 UTC**
groe Auswahl an motivierenden Sprchen, evtl. Jahreszeit-bezogen

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/29

**Comment by mipapo** [comment]
@laufhannes  Close? :D

**Comment by laufhannes** [comment]
Noooooooo :(

;)
