### ISSUE TITLE
DB backup plugin: partial export

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#291]
Es sollte ermglicht werden, nur Teile der Datenbank (bestimmte Tabellen, nur gewisse Anzahl von Spalten) zu exportieren.

Siehe dann auch: #293

**Comment by laufhannes** [comment]
I'm pretty sure @mipapo agrees with a 'wontfix' ;)

**Comment by mipapo** [comment]
yes I do
https://youtu.be/tW3HN_pvbE4?t=40
