### ISSUE TITLE
Data browser: dynamically show configuration

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#313]
**Reported by laufhannes on 8 Jul 42170052 15:06 UTC**
Mit einem Button sollte die Konfiguration fr den DataBrowser direkt ber der Tabelle eingeblendet werden (mit fade-Effekt):

Checkboxen fr:
 - "Training hinzufgen"-Link
 - "Training bearbeiten"-Link
 - leere Zeilen ausblenden

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/313

**Comment by mipapo** [comment]
@laufhannes Was meintest du denn hiermit?

**Comment by laufhannes** [comment]
@mipapo Zum Beispiel oberhalb der Tabelle ein kleiner Link "Optionen einblenden". Bei Klick darauf blenden sich die Checkboxen/Einstellungen aus der Kategorie "Kalenderansicht" der normalen Konfiguration ein: Label für Dataset anzeigen, nur Tage mit Aktivitäten zeigen, Training-Hinzufügen-Link anzeigen.

Es ist grundsätzlich schöner, Einstellungen direkt dort vornehmen zu können, wo sie verwendet werden (vorausgesetzt, sie haben eben einen so eindeutig definierten "Platz").

Ist aber nicht wichtig. Alternativ können wir analog zu dem Ticket "Internal notes for refactoring" ein Ticket mit "Internal notes with small ideas" oder so ähnlich anlegen und dort solche Sachen sammeln, bevor sie - sobald sie konkret genug sind - ins eigentliche Ticketsystem wandern.

**Comment by laufhannes** [comment]
Moved to #1871.
