### ISSUE TITLE
Option für Grafiken: Zeit als X-Achse

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#329]
**Reported by laufhannes on 3 Jul 42192412 18:13 UTC**
Bei fehlender Distanz wird fr den Puls bereits die Zeit als X-Achse genommen. Sollte fr Distanz/Hhe zumindest als Option angeboten werden.

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/329

**Comment by laufhannes** [comment]
+1 from Matthes via mail
