### ISSUE TITLE
Form-Diagramm: Training Load

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#333]
**Reported by laufhannes on 23 Nov 42200861 03:33 UTC**
http://www.pingjeffgreene.com/archive/2010/07/sport-tracks-training-load-explained/

Es gibt den Wunsch, ein "Form"-Diagramm analog zum Training-Load-Diagramm beim SportTracks-Plugin zu erstellen.

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/333

**Comment by laufhannes** [comment]
Already fixed.
