### ISSUE TITLE
Form: improve duration field

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#344]
**Reported by mipapo on 4 Aug 42214761 09:46 UTC**
Das Zeitfeld sollte als Eingabefeld bleiben, aber dennoch eine Vervollstndigungsfunktion bekommen. Nach der Eingabe der Stunde(Beispiel 22) sollten die "Standardzeiten" 00,15,30,45 erscheinen und auswhlbar sein. 

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/344

**Comment by mipapo** [comment]
Wanna see something like this: http://keith-wood.name/timeEntry.html (scrolling through hour/minutes with a mouse scroll).
Or something like (http://www.k-tounyu.jp/common/js/timepicker/page/)

**Comment by laufhannes** [comment]
I prefer the first one.

**Comment by mipapo** [comment]
Thought so ;)

**Comment by laufhannes** [comment]
Added to #1871.
