### ISSUE TITLE
Trainingsformular: Autocomplete für Trainingspartner und Strecke

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#358]
**Reported by calle_unterwegs on 15 Nov 42281686 17:46 UTC**
Damit Trainigspartner und Strecken immer gleichartig eingegeben werden, wre eine Autocomplete-Funktion sehr hilfreich. Das erspart nachtrgliche nderungen, wenn die Schreibweise verschieden ist oder manchmal abgekrzt wird. 

Beispiel Strecke:
"Rh. Bahn" vs. "Rheinische Bahn": Wenn schon eines von beiden erfasst wurde, mchte ich das sehen, wenn ich "rh" tippe.

Beispiel Trainingspartner:
"Rudolf" vs. "Rudi": "ru" sollte den bereits frher erfassten Wert zeigen.

Die Autocomplete-Funktion sollte case-insensitiv sein. 

Evtl. sollten sogar nicht nur Anfnge, sondern Teilstrings gefunden werden, z. B. wurde "Sportpark Wedau" bereits erfasst und wird zur Auswahl angeboten, wenn "Wedau" getippt wird.

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/358

**Comment by laufhannes** [comment]
+1 via forum by DSan

**Comment by laufhannes** [comment]
Duplicate of #1473.
