### ISSUE TITLE
Fehler-Toolbar: Bericht senden

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#367]
**Reported by laufhannes on 10 Mar 42301793 07:06 UTC**
Es sollte die Mglichkeit geben, die Fehlermeldungen bequem an uns zu melden.

1. Mglichkeit: PDF/HTML-Seite erstellen -> Speichern -> E-Mail
2. Mglichkeit: direkt an z.B. api.runalyze.de/sendErrors.php senden

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/367

**Comment by mipapo** [comment]
Von meiner damaligen Idee würde ich mittlerweile ganz absehen:
Kontaktmöglichkeit direkt von Runalyze aus. Einfaches Formular, welches userid, name etc per Mail an eine definierte Adresse schickt:
Logging der Aktionen könnte dann durch #424 eingesehen werden

**Comment by laufhannes** [comment]
Stimme dir zu. Die Error-Toolbar wird ohnehin so gut wie gar nicht mehr benutzt. Wirkliche Fehlermeldungen sollten abgefangen werden und kleinere Hinweise an der jeweiligen Stelle auftauchen anstatt dort zu landen.
