### ISSUE TITLE
GMap: Kurs-Unterbrechnungen anders feststellen

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#373]
**Reported by laufhannes on 16 Sep 42305087 21:46 UTC**
Bisher wird die Linie unterbrechen, wenn:
"Distanz > $MAXIMUM_DISTANCE_OF_STEP" (50m - bei angegebener Durchschnittspace ndert sich der Wert auch)

Problem:
Fr jeden Schritt muss zunchst die zurckgelegte Distanz berechnet werden. Das kann immerhin 3s bei der Skript-Laufzeit ausmachen.

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/373

**Comment by laufhannes** [comment]
Fixed with 87353dbea6f74c1e2cc62e3e1ba1fe4ce38a181b.
