### ISSUE TITLE
Trainingskalender

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#381]
**Reported by thomas@rehwald.eu on 19 Mar 42336581 02:40 UTC**
Liebe glden Wunderlampe, 

ich wnsche mir in runalyze einen Trainingskalender, in welchem die Einheiten im Vorfeld geplant und dann mittels der eingecheckten/hochgeladenen Trainingseinheiten als erledigt gekennzeichnet werden knnen (z.B. knnte beim Erstellen des Trainings auch der passende Kalendereintrag mit ausgewhlt werden). 

Idealerweise sollte dieser Kalender sogar (ergnzend) ber einen reinen "Trainer-Account" gepflegt und der jeweilige Erledigt-Status abgfefragt werden knnen (evtl. ber ein Haupt- und Nebenaccount-Mechanismus beim Login realisierbar?).

Liebe Gre
Monseniore Nimmersatt :-)

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/381

**Comment by laufhannes** [comment]
Duplicate of #662.
