### ISSUE TITLE
Suche: Group by

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#39]
**Reported by laufhannes on 5 Nov 41034591 06:13 UTC**
Bei der Suche sollte das Gruppieren nach bestimmten Eigenschaften mglich sein. Dabei mssen dann automatisch die entsprechenden Felder summiert/gemittelt werden

**Comment by laufhannes** [comment]
This should not be coupled with search functionalities. If there's a concrete analysis required for grouped statistics, a new issue can be created for that exact use-case.
