### ISSUE TITLE
SessionHandler: Login in mehreren Browsern

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#392]
**Reported by laufhannes on 1 Jan 42399410 04:00 UTC**
Wenn ich das richtig sehe, kommt es derzeit im "zweiten" Browser zu Umleitungsfehlern.

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/392

**Comment by laufhannes** [comment]
Duplicate of #783.
