### ISSUE TITLE
Weather: humidity/air pressure

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#396]
**Reported by anonymous on 20 Jul 42435389 17:46 UTC**
Es wre schn wenn es zustzliche Felder zur Eingabe von Luftfeuchtigkeit und Luftdruck geben wrde. Diese WErte sind fr mich wichtiger als die Temperatur und ob es regnet oder die Sonne scheint.

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/396

**Comment by laufhannes** [comment]
+1 via http://forum.runalyze.de/viewtopic.php?p=1132#p1132
