### ISSUE TITLE
Zwischenzeiten bei Bestzeiten beachten

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#406]
**Reported by laufhannes on 9 Jul 42452500 12:26 UTC**
Wenn man noch wenige Wettkmpfe hat aber z.B. einen schnellen Tempodauerlauf ...

Msste dafr wohl ein neues Feld geben, oder sobald bei den Zwischenzeiten alle Zeiten gespeichert werden, um auch die Ruhepausen zu beachten und nicht 5x1000m als 5-km-Bestzeit zu werten.

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/406

**Comment by laufhannes** [comment]
See #1151 and #1318.
