### ISSUE TITLE
Detailed log for all actions

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#424]
**Reported by laufhannes on 22 Aug 42485611 11:33 UTC**
- Login/Logout
- Training hochgeladen/erstellt
- Training bearbeitet
- Konfiguration bearbeitet?

evtl. mit IP? oder umgewandelter IP? oder Session-ID?

**Comment by mipapo** [comment]
IP im Format 123.123.x.x wäre in Ordnung.
Und um weiter in Schritt Framework zu gehen: Zum Einsatz sollte Monolog kommen (könnte ebenfalls das ganze Loggingsystem ersetzen)

**Comment by laufhannes** [comment]
Closed as 'duplicate'. Decisions about what to log should be done within #1890.
