### ISSUE TITLE
Cache weather data

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#449]
**Reported by laufhannes on 3 Aug 42510002 14:13 UTC**
Derzeit wird die Anfrage an Google bei jedem ffnen des Importers gesendet.

Die Wetterinformationen sollten aber - ich sage mal mindestens fr drei Stunden - gecached werden.

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/449

**Comment by laufhannes** [comment]
Pay attention: requests may be time- and location-related. I guess it's enough to cache 'general requests' (which occur everytime I open the empty create form).
