### ISSUE TITLE
Testcript: check external apis

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#455]
**Reported by laufhannes on 31 May 42515560 07:06 UTC**
Test auf:
- Funktionalitt
- Geschwindigkeit

Fr:
- Hhendaten (Google/Geonames)
- Wetter (Google)

Am besten als Link im Admin-Fenster.

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/455

**Comment by laufhannes** [comment]
Moved to Runalyze/runalyze-playground#6.
