### ISSUE TITLE
Language-Files: Übersetzung

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#460]
**Reported by laufhannes on 21 May 42528182 07:33 UTC**
Zunchst evaluieren:
- auf welche Weise lassen sich PHP-Projekte am einfachsten/sinnvollsten bersetzen?

Dann:
- entsprechende Methoden berall verwenden
- deutsche Sprachdatei erstellen
- englische Sprachdatei erstellen

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/460

**Comment by laufhannes** [comment]
Language support is done so far.
See #1218 and #1197 for last fine tuning.
