### ISSUE TITLE
Block content/links until js is loaded completely

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#483]
**Reported by laufhannes on 6 Jan 42540371 20:53 UTC**
Wenn beim ersten Aufruf alles geladen wird, sollte zunchst nur ein Ladesymbol den Inhalt fllen und erst wenn alle Inhalte geladen (und die jQuery-Funktionen gebunden) sind verschwinden und die Seite "freigeben".

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/483

**Comment by laufhannes** [comment]
Moved to #1871 (and questioning whether this is of any use at all).
