### ISSUE TITLE
Detailed analysis for activity

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#497]
**Reported by laufhannes on 6 Dec 42561136 18:40 UTC**
- weitere Infos zu Puls-/Tempo-Zonen
- ausfhrliche TRIMP/VDOT-Berechnung
- Prognosemodelle
- Splits-Analyse (s. #350)

Knnte in der Toolbar des Trainings verlinkt sein ("Training analysieren") und als Popup aufgehen.

**Comment by laufhannes** [comment]
Every concrete idea of such analysis tools gets its own ticket, e.g. #1943 and #1949.
