### ISSUE TITLE
Befinden als Extrafeld bei der Trainingsdokumentation

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#500]
**Reported by mipapo on 15 May 42583800 05:46 UTC**
Wunsch von Suelztalrunner: https://twitter.com/Suelztalrunner/status/227350885032919040

Befindlichkeitsbutton fr jeden Lauf z.B.:
sehr gut :-)) 
gut :-)  
ging so :-| 
schlecht :-( 
sehr schlecht :-((

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/500

**Comment by laufhannes** [comment]
Duplicate of #876.
