### ISSUE TITLE
Export races / personal bests

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#517]
**Reported by Brennr.de on 10 Dec 42629987 14:13 UTC**
Es wre toll, wenn man analog zu den einzelnen Lufen auch die Wettkampf- / Bestzeitenbersicht exportieren knnte (HTML + Iframe). Somit knnte ich die Liste permanent auf meinem Blog einbinden.

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/517

**Comment by laufhannes** [comment]
see #1183
