### ISSUE TITLE
Docs: Trimp/ATL/CTL/TSB

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#550]
**Reported by laufhannes on 27 May 42733619 00:26 UTC**
Eine ausfhrliche Erklrung, evtl. im Blog.

Als Anreiz:
http://fellrnr.com/wiki/TRIMP

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/550

**Comment by laufhannes** [comment]
Moved to Runalyze/docs#4.
