### ISSUE TITLE
Activity data: kind of route

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#564]
**Reported by laufhannes on 10 Apr 42759255 04:53 UTC**
'Generell wre begrenswert, die Art der gelaufenen Strecke angeben zu knnen (es gibt nur die Checkbox "Bahn"): Asphalt, Schotterweg, Waldweg, Wiese, Bergpfad, Sand, Schneebelag usw.'

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/564

**Comment by laufhannes** [comment]
Tags can be used for this.
