### ISSUE TITLE
Integrate search in data browser

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#62]
**Reported by laufhannes on 12 Oct 41310570 08:53 UTC**
Die Lsung als PopUp ist zwar schick und einfach, um jedoch nach dem Klick auf ein Training zurck zur Suche zu knnen, sollte die Suche in den DataBrowser integriert werden. (Zurck-Button wie bei den Trainings unten)

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/62

**Comment by laufhannes** [comment]
I don't think that this is practicable.
