### ISSUE TITLE
TCX-Import: Grenze für AutoPause angeben und nutzen

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#624]
**Reported by laufhannes on 4 Mar 42866252 00:26 UTC**
Wenn man AutoPause am Garmin aktiviert hat, werden diese Pausen in der TCX-Datei nicht markiert.

Konfiguration -> AutoPause: Entweder eine Geschwindigkeit angeben oder 0 fr gar nicht

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/624

**Comment by laufhannes** [comment]
Will be done in #913.
