### ISSUE TITLE
Shared view: list of last activities

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#632]
**Reported by laufhannes on 6 Dec 42871319 16:00 UTC**
- Anzahl?
- Sportarten?
- ...

-> Konfiguration evtl. lokal speichern, damit nicht jeder sie bei der Ansicht ndern kann

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/632

**Comment by laufhannes** [comment]
Duplicate of #1183.
