### ISSUE TITLE
Reset account data

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#634]
in Datenbank Export/Import integrieren:
- delete all activities
- delete equipment

maybe:
- reset to default settings (configuration, dataset, plugins, sports, training types, clothes..)

**Comment by mipapo** [comment]
(Another point would be to easily delete activites through the search. (Maybe add a function "Look for double entries)

**Comment by mipapo** [comment]
Okay I think we just say "Wontfix".
If should be enough if we implement the feature to delete/edit multiple activities via search function. 
If a user really want to delete all his activities/get a clean account he just have to delete his account and register again.

**Comment by laufhannes** [comment]
Closed as 'wontfix'.
