### ISSUE TITLE
"Kalorien berechnen" erläutern/verbessern

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#639]
**Reported by laufhannes on 28 Jan 42881643 01:20 UTC**
- Import ber FR: kcal vom FR
- nderung der Zeit: eigene Berechnung

-> starke Unterschiede

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/639

**Comment by laufhannes** [comment]
Will be calculated by heart rate if available: #1090.
