### ISSUE TITLE
Save data from performance diagnosis

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#644]
**Reported by anonymous on 3 Feb 42884653 15:06 UTC**
Hallo,
ich nutze eure Software Runalyze und finde sie super gut,
es wre aber noch besser, wenn man in der Konfiguration des Sportlers die Daten einer Leistungsdiagnostik eingeben knnte, damit auch die entsprechenden Daten im Training mit ausgewertet werden knnen.
Evtl knnt ihr das ja in der nchsten Version umsetzen, wre sicher fr so manchen Sportler interessant.
Viele Gre
Gisela

**Comment by laufhannes** [comment]
There is no standardized "result" of a performance diagnosis and as long as there isn't, I don't see a reason to include this directly in RUNALYZE. Currently, this would be the same as providing a textarea for free input. If required, notes can be used for this, see #916.
