### ISSUE TITLE
Configuration field: free input

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#697]
**Reported by laufhannes on 10 Dec 43030296 16:53 UTC**
see http://stackoverflow.com/questions/9988161/select-or-free-text/9988230#9988230

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/697

**Comment by laufhannes** [comment]
This is not a general issue. Currently there's no configuration variable that requires this feature.
