### ISSUE TITLE
Plugin: repetitive activities

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#707]
**Reported by jukamawe on 9 Apr 43057279 07:06 UTC**
es wre schn, wenn man kalenderbestimmt feste Trainingszeiten eintragen knnte. Ich mache z.B. jeden morgen 15 min Gymnastik. Immer das Gleiche. Wenn ich das einmalig als Dauertermin eintragen knnte, wrde das viel Arbeit ersparen. Vielleicht lsst sich das so realisieren, das automatisch beim Einloggen die bis dahin noch nicht eingetragenen Tage nachgetragen werden. Dadurch wrde der Eintrag fr die Zukunft vermieden, der sost vielleicht bei Auswertungen zu Verflschungen fhren knnte

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/707

**Comment by laufhannes** [comment]
Probably a duplicate of #1432.
