### ISSUE TITLE
Runden in den Diagrammen kennzeichnen

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#729]
**Reported by anonymous on 2 May 43168917 13:46 UTC**
Es wre super wenn der jeweilige Mittelwert der gestoppten Runden in den Diagrammen gekennzeichnet wren. Gerade fr Intervalle und hnliches, dann knnte man direkt sehen wie schnell welches Intervall gelaufen wurde und wie lange die Pausen waren usw. Ich habe mal in ein Diagramm eingezeichnet wie das aussehen knnte.

https://dl.dropbox.com/u/8776144/bsp/diagramm.png

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/729

**Comment by laufhannes** [comment]
Screenshot is not available anymore. Sounds similar to #66.
