### ISSUE TITLE
Splits: Zeiten aus GPS-Daten lesen

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#769]
**Reported by laufhannes on 4 Nov 43339016 00:26 UTC**
im Formular ber JS
-> bei leeren Zeitfeldern ber Array iterieren und setzen
(class::Splits kann das bereits)

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1482

**Comment by laufhannes** [comment]
Duplicate of #1500.
