### ISSUE TITLE
Activity data: official race distance

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#770]
**Reported by laufhannes on 20 Mar 43339687 13:20 UTC**
Damit die Distanz trotz aufgezeichneter 10,1 z.B. als 10-km-Wettkampf gewertet wird.

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1483

**Comment by laufhannes** [comment]
Will get an extra table, see #1543.
