### ISSUE TITLE
Stay logged in on multiple devices

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#783]
Derzeit funktioniert das "eingelogged bleiben" Feature nur bei Verwendung eines einzigen Rechners. 

Wenn man runalyze auf mehreren Rechnern/Browsern verwendet, bleibt man quasi immer nur am letzten eingelogged. Wechselt man den Rechner muss man sich jedenfalls neu einloggen. Fein wre es, wenn man auf allen eingelogged bliebe.

**Comment by laufhannes** [comment]
This seems to work thanks to Symfony.
