### ISSUE TITLE
Sortierung beim Import via Garmin Plugin

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#785]
**Reported by uk3 on 30 Oct 43355907 13:46 UTC**
Hallo,

mir ist aufgefallen dass die Sortierung der Trainings beim Import via Garmin Plugin verwirrend ist:

Die Liste enthlt zuerst (chronologisch absteigend) alle Single-Sport Trainings (egal ob Laufen, Rad oder other), erst danach dann chronologisch absteigend alle Multi-Sport Trainings. Dadurch sind auch die neuesten Multisport-Trainings nicht ganz oben in der Liste, sondern irgendwo in der Mitte, und man muss sie erst suchen. (Anbei auch ein Screenshot davon).

Ich weiss nicht ob das das Plugin selber macht bzw. ob man das berhaupt beeinflussen kann. Wenn ja wrs aber irgendwie praktischer wenn alle Trainings unabhngig von ihrer Art chronologisch sortiert wren.

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1498

**Comment by laufhannes** [comment]
There is already some sorting added: New activities are always on top. That's enough as the communicator is already deprecated.
