### ISSUE TITLE
VDOT by elevation: use exact gradient from gps data

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#791]
**Reported by hugo3673 on 19 Nov 43413731 19:33 UTC**
siehe http://www.laufen-in-siegen.de/index.html?./html/laelles_3.html

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1504

**Comment by laufhannes** [comment]
Duplicate of #1573.
