### ISSUE TITLE
flot v0.9: legend in canvas to be savable

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#811]
**Reported by laufhannes on 26 Dec 43497745 15:33 UTC**
Mit flot v0.8.1 luft das Speichern zwar gut, aber die Legende ist noch nicht Teil des Canvas.

Daher, sobald flot v0.9 verfgbar ist -> updaten!

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1524

**Comment by laufhannes** [comment]
v0.8.3 is from end of April 2014 and from then on there's only one commit in May for v0.9. Don't think that there'll ever be a v0.9.
