### ISSUE TITLE
CURL: handle if 'not allowed'

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#815]
**Reported by laufhannes on 21 Jan 43500342 02:13 UTC**
Bisher wird nur geprft, ob CURL installiert ist. Es kann aber trotz der Installation verboten sein.

**Comment by mipapo** [comment]
@laufhannes Never happened again?

**Comment by laufhannes** [comment]
Nope. And I guess we won't use *raw* curl in the future but some symfony methods instead.

Closed as *wontfix*.
