### ISSUE TITLE
Optimierung: Queries optimieren

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#817]
**Reported by laufhannes on 8 Dec 43500493 15:06 UTC**
Mittels ordentlichem Profiling!

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1530

**Comment by laufhannes** [comment]
Symfony/Doctrine will care for effective queries. (And if there are special bottlenecks they have to be considered in extra tickets)
