### ISSUE TITLE
Trainings-Cache nach längerer Zeit wieder leeren

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#821]
**Reported by laufhannes on 21 Feb 43505657 09:20 UTC**
Beispiel aus der Online-Version:
- rund 93.500 Trainings = 3,0 GB
- `gps_cache_object` leeren und optimieren = 1,9 GB

Ohne das Cache-Objekt wrden wir also 1/3 Speicherplatz der DB sparen. Ich wei nicht, inwiefern sich das auf die Performance auswirkt?

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1534

**Comment by laufhannes** [comment]
`gps_cache_object` is not used anymore.
