### ISSUE TITLE
Optimization: column types

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#822]
**Please check all column types!**

| Type | Bytes | Range |
| --- | --- | --- |
| TINYINT | 1 Byte | [-128, 127] or 0 - 255 |
| SMALLINT | 2 Byte | [-32768, 32767] or 0 - 65535 |
| MEDIUMINT | 3 Byte | [...] or 0 - 16777215 |
| INT | 4 Byte | [...] or 0 - 4294967295 |
| BIGINT | 8 Byte | ~18 trillion |
| ------- | ------- | --------- |
| CHAR(X) | always X Bytes | X chars |
| VARCHAR(X) | variable (+ 1 Byte for actual size) | X chars |
| TINYTEXT | variable | 255 chars |
| TEXT | variable | 65.536 chars |
| MEDIUMTEXT | variable | 16.777.215 chars |
| LONGTEXT | variable | 4.294.967.295 chars |

**Comment by laufhannes** [comment]
`runalyze_training`
 * [ ] unsigned missing: `sportid`, `typeid`, `created`, `edited`, `use_vdot`, `jd_intensity`, `weatherid`, `accountid`
 * [ ] `elapsed_time`: from `int` to `unsigned mediumint`
 * [ ] `elevation`: from `int` to `unsigned smallint`
 * [ ] `kcal`: from `int` to `unsigned smallint`
 * [ ] `pulse_avg`: from `int` to `unsigned tinyint`
 * [ ] `pulse_max`: from `int` to `unsigned tinyint`
 * [ ] `trimp`: from `int` to `unsigned smallint`
 * [ ] `cadence`: from `int` to `unsigned tinyint`
 * [ ] `power`: from `int` to `unsigned smallint`
 * [ ] `abc`: from `smallint` to `unsigned tinyint`

`runalyze_account`
 * [ ] unsigned missing: `registerdate`, `lastaction`, `lastlogin`, `changepw_timelimit`, `allow_mails`
 * [ ] all hashes from `varchar(X) NOT NULL` to `char(X) NULL`

`runalyze_conf`
 * [ ] unsigned missing: `id`, `accountid`

`runalyze_equipment`
 * [ ] `additional_km`: from `int` to `unsigned smallint`

`runalyze_equipment_type`
 * [ ] unsigned missing: `input`, `accountid`
 * [ ] `max_km`: from `int` to `unsigned mediumint`
 * [ ] `max_time`: from `int` to `unsigned mediumint`

`runalyze_plugin`
 * [ ] unsigned missing: `active`, `accountid`
 * [ ] `order`: from `smallint` to `unsigned tinyint`

`runalyze_sport`
 * [ ] unsigned missing: `sport`, `distances`, `kcal`, `types`, `power`, `outside`, `accountid`
 * [ ] `HFavg`: from `smallint` to `unsigned tinyint`

`runalyze_type`
 * [ ] unsigned missing: `id`, `sportid`, `accountid`

`runalyze_user`
 * [ ] unsigned missing: `id`, `time`, `accountid`
 * [ ] `pulse_rest`: from `smallint` to `unsigned tinyint`
 * [ ] `pulse_max`: from `smallint` to `unsigned tinyint`

**Comment by mipapo** [comment]
runalyze_dataset
Maybe add a unique constraint for _dataset
ALTER TABLE runalyze_dataset ADD CONSTRAINT dataset UNIQUE (keyid, accountid)

**Comment by mipapo** [comment]
check upcoming commit
`runalyze_account`
 * [ ] unsigned missing: `registerdate`, `lastaction`, `lastlogin`, `changepw_timelimit`, `allow_mails`
 * [ ] all hashes from `varchar(X) NOT NULL` to `char(X) NULL`

`runalyze_conf`
 * [ ] unsigned missing: `id`, `accountid`

`runalyze_equipment`
 * [x] `additional_km`: from `int` to `unsigned smallint`

`runalyze_equipment_type`
 * [ ] unsigned missing: `input`
 * [ ] `max_km`: from `int` to `unsigned mediumint`
 * [ ] `max_time`: from `int` to `unsigned mediumint`

`runalyze_plugin`
 * [ ] unsigned missing: `active`, `accountid`
 * [ ] `order`: from `smallint` to `unsigned tinyint`

`runalyze_sport`
 * [ ] unsigned missing: `sport`, `distances`, `kcal`, `types`, `power`, `outside`, `accountid`
 * [ ] `HFavg`: from `smallint` to `unsigned tinyint`

`runalyze_type`
 * [ ] unsigned missing: `id`, `sportid`, `accountid`

`runalyze_user`
 * [ ] unsigned missing: `id`, `time`, `accountid`
 * [ ] `pulse_rest`: from `smallint` to `unsigned tinyint`
 * [ ] `pulse_max`: from `smallint` to `unsigned tinyint`
