### ISSUE TITLE
Rundenzeiten (gestoppt) mit Puls

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#829]
**Reported by cpmagin on 23 Jan 43522153 23:06 UTC**
Hallo,

erstmal ein dickes Dankeschn fr die tolle Software! 

Einen kleinen Verbesserungsvorschlag habe ich bei der Detailanzeige eines Laufs fr das Widget "Rundenzeiten".
Dort werden bei den gestoppten Runden leider keine Durchschnittspulswerte (und auch kein Maximalwert) angezeigt. Gerade beim Intervalltraining finde ich das sehr hilfreich.

Vielleicht lsst sich da ja was machen ;)

Viele Gre,
Chris

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1542

**Comment by laufhannes** [comment]
Are shown in the detailed window as long as the total distance fits.
