### ISSUE TITLE
Training bearbeiten dauert zu lange

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#832]
**Reported by laufhannes on 27 Jul 43576745 06:40 UTC**
- `tasksAfterUpdate()` berprfen
- evtl. irgendwie merken, welche Werte gendert wurden

z.B.
- `Trimp::checkForMaxValuesAt` nur, wenn sich TRIMP gendert hat
- `updateVdot()` nur bei nderung der Distanz/Dauer
- `updateShoeForUpdate()` nur bei nderung der Schuhid/Distanz/Dauer

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1545

**Comment by laufhannes** [comment]
Fixed since 595894ec642e95d1f15c739381c01de29bbc7e39.
