### ISSUE TITLE
Installation: Reihenfolge bei manueller config.php korrigieren

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#836]
**Reported by laufhannes on 4 Jul 43577587 20:26 UTC**
config.php nicht schreibbar -> Man gelangt zurck zu den Verbindungsdaten -> ...

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1549

**Comment by laufhannes** [comment]
This does already work the way it should.
