### ISSUE TITLE
DB-Backup-Import: Memory Limit

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#846]
**Reported by laufhannes on 14 May 43580782 00:00 UTC**
orbis berichtet ber Probleme beim JSON-Export/Import

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1559

**Comment by mipapo** [comment]
@laufhannes For large imports the queuing feature #1989 should be use. So I think this issue can be closed?

**Comment by laufhannes** [comment]
The original issue was about `gzencode()` / `json_encode()` hitting memory limits. This is already fixed as backups are read line by line since 9494e3bdadc1c9216f1cae8316b225d2eeed260a (released in v2.0; fixed more than two years ago, ...).
