### ISSUE TITLE
.htaccess: update-safe version

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#874]
**Reported by laufhannes on 16 Oct 43649148 01:46 UTC**
None

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1587

**Comment by laufhannes** [comment]
I suggest renaming `.htaccess` in root directory to `.htaccess.dist` (or `.htaccess.default`) such that potential changes are not overwritten by updates. (I'm not sure if there are things to adjust in the current `.htaccess` for admins, anyway, I'm a big fan of providing update-safe adjustments.)

The installer could copy the default one if we wish to enable the rewrite rules for not mounting the web directory.

**Comment by mipapo** [comment]
> The installer could copy the default one if we wish to enable the rewrite rules for not mounting the web directory.
I would say this would be the task of the users. 

The naming .`htaccess.dist` sounds good
