### ISSUE TITLE
activity data: borg scale

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#876]
**Reported by laufhannes on 29 Sep 43656081 17:20 UTC**
subjektives Empfinden von 1 bis 10

siehe http://forum.runalyze.de/viewtopic.php?f=8&t=59

**Comment by laufhannes** [comment]
+3 from #500

**Comment by mipapo** [comment]
+1

**Comment by mipapo** [comment]
@laufhannes Kann ja eigtl nicht schwer umzusetzen zu sein?

**Comment by grzeg1** [comment]
[Borg.pdf](https://www.google.pl/url?sa=t&rct=j&q=&esrc=s&source=web&cd=7&ved=0CDYQFjAGahUKEwi5rPPknPTIAhVBhiwKHTp_AnY&url=http%3A%2F%2Fwww.uni-leipzig.de%2F~isp%2Fisp%2Fconferences%2Ffd01_files%2Fgeneralinfo%2FPDFs%2FEBorg.pdf&usg=AFQjCNH4NZ19fEl_37g394H03UjUAkHeaA&sig2=mLONLyyK_HVCzLUW0f6rGw)

https://en.wikipedia.org/wiki/Borg_scale

*The seemingly odd range of 6-20 is to follow the general heart rate of a healthy adult by multiplying by 10. For instance, a perceived exertion of 12 would be expected to coincide with a heart rate of roughly 120 beats per minute.*

So it all comes down to calculating HR based on perceived effort. Could be even done as javascript calculator.

**Comment by laufhannes** [comment]
+1 via http://forum.runalyze.de/viewtopic.php?p=1132#p1132

**Comment by laufhannes** [comment]
+1 via https://forum.runalyze.com/viewtopic.php?f=8&t=394&p=1657#p1657
