### ISSUE TITLE
Mobile Ansicht: Alternative zu fineuploader

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#880]
**Reported by laufhannes on 10 Aug 43659161 13:20 UTC**
Falls fineuploader nicht untersttzt wird:
"Standard-Formular" verwenden

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1593

**Comment by laufhannes** [comment]
Duplicate of #1355.
