### ISSUE TITLE
marker gleichzeitig auf verschiedenen diagrammen

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#894]
**Reported by jecketyia on 14 Jun 43725267 21:46 UTC**
wre das mglich: wenn man den cursor z.b. im hhendiagramm bewegt, dass der in den anderen diagrammen auch zu sehen ist und sich synchron bewegt? am besten auch noch auf der karte ...

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1607

**Comment by laufhannes** [comment]
Duplicate of #714.
