### ISSUE TITLE
GPX-Importer: Pause erkennen

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#895]
**Reported by hkrull on 1 Aug 43733255 01:46 UTC**
Hi,

ist es mglich beim Import einer gpx-Datei Pausen zu erkennen?
Ich nutze diese SUUUPER-App zum Loggen meiner MTB-Touren.
Pausen produzieren dabei eine kleinere Durchschnittsgeschwindigkeit.

Gru 
H

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1608

**Comment by laufhannes** [comment]
Same problem as #624.
