### ISSUE TITLE
Repository for plugins

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#915]
**Reported by laufhannes on 20 Apr 43828789 14:40 UTC**
 - Plugins brauchen Versionsnummern
   - evtl. an die offizielle Versionsnummer gekoppelt? fr v1.3 -> v1.3.0 etc, damit die Abhngigkeit zu einer bestimmten Version klar ist
 - Hinweis ber neue Updates
 - Plugins einzeln updaten knnen

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1628

**Comment by laufhannes** [comment]
I don't see a way to realize this within the next years. So far, "plugins" are just a kind of core modules or widgets. As long as there are no non-core widgets out there, we don't need to think about a repository for them.
