### ISSUE TITLE
HRM importer: import elevation/power

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#919]
`[HRData]` contains arrays for elevation and power. The parser simply needs to add:
 - `$this->gps['altitude'][] = isset($values[3]) ? (int)trim($values[3]) : 0;`
 - `$this->gps['power'][] = isset($values[4]) ? (int)trim($values[4]) : 0;`

see http://www.polar.com/en/support/downloads/device_interface_toolkit/documentation
see http://forum.runalyze.de/viewtopic.php?f=7&t=32

**Comment by grzeg1** [comment]
alert: enhancement in 2.0.x ;)

**Comment by laufhannes** [comment]
One could call it a bug that they are not imported ;)
