### ISSUE TITLE
Bash-Script: Dateien direkt importieren

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#920]
**Reported by laufhannes on 11 Sep 43829185 16:53 UTC**
Fr Nutzer einer eigenen, lokalen Installation, ein Skript anbieten, dass automatisch die Trainings aus einem bestimmten Verzeichnis importiert.

Dabei muss irgendwie die Account-ID geregelt werden (oder nur bei einem einzigen Nutzer mglich?) und diese Datei darf nie und nimmer ber das Web aufgerufen werden.

Dazu noch die Frage: Alle Dateien aus dem Verzeichnis importieren oder irgendwie "merken", welche neu sind?

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1633

**Comment by laufhannes** [comment]
See #1478.
