### ISSUE TITLE
Forms: allow info message within fieldset

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#929]
**Reported by laufhannes on 1 Dec 43840545 19:33 UTC**
Anstelle eines normalen Input-Feldes zur direkten Integration einer Info in das Formular. Vor allem hilfreich als w50 an der rechten Seite neben einem Input-Feld.

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1642

**Comment by laufhannes** [comment]
All form classes are deprecated and will be replaced by templates (that may use macros for common elements, but there will still be a way to add custom elements everywhere).
