### ISSUE TITLE
Zwischenzeiten-Fenster: Auswertung der weiteren GPS-Daten

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#939]
**Reported by laufhannes on 5 Jun 43881799 12:53 UTC**
fr die verfgbaren GPS-Daten, z.B. Herzfrequenz/Schrittfrequenz etc.: Minimum/Maximum/Durchschnitt(/Varianz)

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1652

**Comment by laufhannes** [comment]
Duplicate of #1507.
