### ISSUE TITLE
Define official browser support

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#945]
**Reported by laufhannes on 10 Jan 43947533 05:46 UTC**
None

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1658

**Comment by laufhannes** [comment]
It's very likely that such a defined browser support is outdated quite soon. We'll try to require as little as possible, but in case something does not work in any outdated browser - it's like that.
