### ISSUE TITLE
PluginTool: csv-export

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#95]
**Reported by laufhannes on 23 Dec 41532393 15:06 UTC**
Analog zum csv-Import sollte auch der Export ermglicht werden, falls man ganz eigene Sachen mit den Daten vorhat.

Eventuell mit kml-Export #101 kombinierbar.

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/95

**Comment by laufhannes** [comment]
Duplicate of #1313.
