### ISSUE TITLE
Export von allen angezeigten Trainingseinheiten

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#950]
**Reported by mipapo on 1 May 43968837 16:00 UTC**
Mglichkeit alle derzeitig in der Tabelle angezeigten Trainingsdaten in eine Datei zu exportieren

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1663

**Comment by laufhannes** [comment]
see #1313 and #95
