### ISSUE TITLE
Zeitzonen überprüfen?

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#951]
**Reported by laufhannes on 23 Apr 43968998 23:06 UTC**
None

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1664

**Comment by mipapo** [comment]
Gehört nicht direkt dazu, aber wird benötigt werden: Zeitzone in Accountkonfiguration!

**Comment by laufhannes** [comment]
Duplicate of #1145.
