### ISSUE TITLE
Statistik-Plugin: Höhenmeter

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#971]
**Reported by laufhannes on 3 Sep 44009583 04:13 UTC**
Optional hinzufgen, siehe http://runalyze.de/allgemein/runalyze-v1-5/comment-page-1/#comment-867

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1685

**Comment by laufhannes** [comment]
Fixed since 9880f0bcbaa163cc93a870a4bb7bf0a55041d156.
