### ISSUE TITLE
Strecken-Plugin: Streckennetz nach Sportart

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#972]
**Reported by laufhannes on 12 Apr 44009585 14:23 UTC**
Siehe http://runalyze.de/allgemein/runalyze-v1-5/comment-page-1/#comment-867

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1686

**Comment by laufhannes** [comment]
Duplicate of #1181
