### ISSUE TITLE
Idea: queue for import

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#980]
Einlieferung von Trainingsdaten per Mail
Upload von vielen Dateien (Verarbeitung nach Upload im Hintergrund)

Kann grundstzlich bei Runalyze im Core integriert sein, aber muss nicht aktiviert/konfiguriert werden (Serverzugriff ntig)

**Comment by mipapo** [comment]
Adding two thoughts:
When I created the ticket i didn't mean the import via an API from other services. 
Currently the users want to upload MANY files at once. If so the import should be handled in the background and the user gets an information, when the import is ready (and if so he gets information about files which couldn't be uploaded to Runalyze)

**Comment by undertrained** [comment]
I started looking into something like this some time ago.
I would like to be able to rsync my Garmin ANT Agent's history directory onto the server and have runalyze automatically import all new trainings. I planned on calling a script regularly via cron, which scans for files in a dir structure such as <uploaddir>/<userid>/<training_files>. The respective <userid> dir only should be +w for the appropriate user.
It would be nice to have a visual hint in the calendar view showing new imports.
This would help getting rid of the (deprecated) Communicator Plugin...

**Comment by mipapo** [comment]
@undertrained Well you're talking about an own installation?
With an API a local script could send this to the API.
But without any visual hint or notification - (like github?) it wouldn't be nice.
The API should also look at the file which is imported and see if there is a activity within the same time range and should deny the new activitry.

**Comment by undertrained** [comment]
Yes, this is (mainly) for self-hosted installations. But it could also work for a larger user base if the server is set up accordingly.
I also don't like to have to call a script via cron, but this would allow me to use regular unix tools to upload my files. And the lack of a (visual) notification if an error occured would not be nice, I agree...

**Comment by mipapo** [comment]
summarized in #1989
