### ISSUE TITLE
Trainingstyp: In Kalender gruppieren

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#986]
**Reported by laufhannes on 4 Aug 44028400 02:41 UTC**
Optional, sinnvoll z.B. fr "Warm-/Auslaufen". Evtl. auch fr komplette Sportarten mglich?

Wenn aktiv, werden mehrere Trainings dieses Trainingstyps an einem Tag gruppiert. Summe/Durchschnitt etc. nach Einstellungen des Datasets.

Offen: Wie wird diese bersicht dann zu den einzelnen Trainings verlinkt?

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1700

**Comment by mipapo** [comment]
Wie wäre es einfach nur mit einer Gruppierung ohne eine Summe/Durchschnitt? 
Dachte an eine Tabelle: (id könnte theoretisch rausfallen)
id | activityid | groupid | name/description | hash zum teilen? (Sharedview mit allen drei Aktivitäten auf einer Seite)

**Comment by laufhannes** [comment]
Das wäre in meinen Augen ein anderes/eigenständiges Ticket im Sinne von 'Combined Activities' o.ä.

Dieses Ticket hatte ursprünglich die Idee, dass z.B. das Warm-/Auslaufen die Kalenderübersicht nicht überflutet. Dafür würde ich aber eher #1379 vorsehen. Meinetwegen kann das Ticket daher geschlossen werden und ein neues für 'Combined Activities' angelegt werden.
