### ISSUE TITLE
Wetterdaten auf Basis der GPS Trainingsdaten

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#997]
**Reported by mipapo on 21 Dec 44058826 06:28 UTC**
Frage ist inwiefern man Koordinaten an eine Wetterschnittstelle mitgeben kann und die Daten vom Ort, der in der Nhe liegt abgefragt werden knnte.

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1711

**Comment by laufhannes** [comment]
Does already work.
