### ISSUE TITLE
Verbesserungsvorschlag: Formverlauf - gleitendes Zeitfenster

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#999]
**Reported by markus.uhlendahl@me.com on 24 Oct 44059305 20:47 UTC**
Gerade jetzt zum Jahresanfang fllt es negativ auf:
Ich kann mir entweder den Formverlauf fr 2013 oder den fr 2014 anschauen (Alternativ den Gesamtverlauf fr alle Jahre, was aber nur eine unzureichende Detailsicht erlaubt). Sinnvoller wre es, wenn ich zustlich und als Default den Formverlauf der letzten x Monate anschauen knnte, also z.B. von Februar 2013 bis Januar 2014. Am schnsten wre es natrlich, wenn man x als User selber festlegen/konfigurieren knnte. Die letzten sechs oder zwlf Monate als feste Einstellung wren aber auch i.O.

Ich benutze die Online-Version (sollte unter Version unten auch auswhlbar sein).

Migrated-From: http://trac.runalyze.de/cgi-bin/trac.fcgi/ticket/1713

**Comment by laufhannes** [comment]
Already fixed for "Last 6 months".
